plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_investigations/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_investigations/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

- Change `LQL` to `LEQL` on advanced query on log & (log_sets)
- Take users size input in list investigations.
* …

[PLGN-383][PLGN-375] IDR fixes

---

plugins/basename/.CHECKSUM
plugins/basename/bin/komand_basename
plugins/basename/help.md
plugins/basename/plugin.spec.yaml
plugins/basename/setup.py

* Version bump, add empty init.py file and help.md additions
* Fixing helpValidator by adding links and changing capitalisation
* fixing RegenerationValidator
-Added empty `__init__.py` file into `unit_test` folder, version bump and refresh with new tooling. …

[SOAR-15498] Basename 1.1.2 Release

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/expected/monitor_users_bad_request.json.exp
plugins/salesforce/unit_test/expected/monitor_users_empty.json.exp
plugins/salesforce/unit_test/expected/monitor_users_with_state.json.exp
plugins/salesforce/unit_test/expected/monitor_users_without_state.json.exp
plugins/salesforce/unit_test/inputs/monitor_users_empty.json.inp
plugins/salesforce/unit_test/inputs/monitor_users_with_state.json.inp
plugins/salesforce/unit_test/responses/get_specific_user_empty.json.resp
plugins/salesforce/unit_test/util.py

- Task Monitor Users: updated users query improvement 
- Task Monitor Users: add extra logs on timestamp
- Task Monitor Users: add cutoff time limit for 24 hours  …

[PLGN-380] Salesforce - updated users query improvment

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_investigations/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_investigations/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

* List investigations fix
* Changes lql to leql
* Update version across files
* Update size description for list investigations
-
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use …

[PLGN-383][PLGN-375] IDR 5.1.1 - Release

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/expected/monitor_users_bad_request.json.exp
plugins/salesforce/unit_test/expected/monitor_users_empty.json.exp
plugins/salesforce/unit_test/expected/monitor_users_with_state.json.exp
plugins/salesforce/unit_test/expected/monitor_users_without_state.json.exp
plugins/salesforce/unit_test/inputs/monitor_users_empty.json.inp
plugins/salesforce/unit_test/inputs/monitor_users_with_state.json.inp
plugins/salesforce/unit_test/responses/get_specific_user_empty.json.resp
plugins/salesforce/unit_test/util.py

- Task Monitor Users: updated users query improvement
- Task Monitor Users: add extra logs on timestamp
- Task Monitor Users: add a cutoff time limit of 24 hours …

Salesforce 2.1.1 - release

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/inputs/monitor_users_with_old_format_state.json.inp
plugins/salesforce/unit_test/test_monitor_users.py

- Task Monitor Users: normalisation for date in state, handle backwards compatibility …

[PLGN-380] Salesforce Task Monitor User: date normalisation 

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/expected/monitor_logs.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_2.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_3.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_bad_request.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_server_error.json.exp
plugins/duo_admin/unit_test/inputs/monitor_logs_bad_request.json.inp
plugins/duo_admin/unit_test/inputs/monitor_logs_server_error.json.inp
plugins/duo_admin/unit_test/test_monitor_logs.py
plugins/duo_admin/unit_test/util.py

Updated the unit tests following functionality updates in previous PR (move to using three timestamps instead of a single timestamp window for log monitoring). 
Pluginvalidator failure due to manual change to schema (tooling ticket raised against this).

[PLGN-399] Update task unit tests

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/connection/schema.py
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/constants.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py

Add extra logging for C2C investigation (PLGN-425) and add missing regions. 
Regions listed here: https://integrations.mimecast.com/documentation/api-overview/global-base-urls/
- Added extra logging to help any furture debugging/investigation around the number of events mimecast c2c is working. 
- Added extra regions that are missing - customers may need in the future and needed for our mimecast credentials. 
- Tested monitor logs events and can see new logs and can use connection ok. 
```
joneill:mimecast/ (PLGN-434✗) $ docker run -p 10001:10001 --name mimecast rapid7/mimecast http        [14:02:03]
WARNING: The requested image's platform (linux/amd64) does not match the …
```

PLGN-434: Update mimecast supported regions. 

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/endpoints.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/resource_helper.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/mock.py

- Action: `Advanced Query on Log Set` - Bug fix
- Fix issue where `raise JSONDecodeError("Expecting value", s, err.value) from None` appears for customer when querying logs.
- Action: `Query` - Change use of query ID to log ID
- Action: `Get A Saved Query` - Fixed endpoint by updating typo in URI
I tested it by manually re-creating the customer data in a local Python repl.
Most data in IDR is already properly formatted in correct json so the code handles it just fine.
The issue was that the customer was trying to retrieve 'Unparsed Data' which is not properly formatted in JSON and caused the code to break when it hit `json.loads(thedata)`.
I was able to fix by simply formatting …

[PLGN-345][PLGN-253] IDR - Query Parsing

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml

- Update packagecloud url
* All …

update packagecloud url

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml
tools/release_plugin.sh

- Prod and Staging releases in Python 3.8 …

[SOAR-15650] plugin release workflow

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml
tools/release_plugin.sh

- Successfully retrieves branch names, activates only on merged pr, fixes release call pathing
* Single …

Update Plugin Release Workflow

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml

Plugin Release Escape var reference

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml

Move quote

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml

Updated permissions

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml

Updated aws resources

---

tools/release_plugin.sh

Update INF name key

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml

- Update Build Trigger and Build URL …

Update Build information

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml

- Update spacing | ensure action read …

Update format | Add actions read

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml

- build cause remove unneccessary quotation mark …

Update build causes

---

tools/release_plugin.sh

Update env naming

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/resource_helper.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

- Action: `Advanced Query on Log Set` - Bug fix
- Fix issue where `raise JSONDecodeError("Expecting value", s, err.value) from None` appears for customer when querying logs.
- Action: `Query` - Change use of query ID to log ID
[PLGN-354](https://issues.corp.rapid7.com/browse/PLGN-345)
[PLGN-253](https://issues.corp.rapid7.com/browse/PLGN-253) …

[PLGN-354][PLGN-253] IDR - Fix parsing unparsed data

---

plugins/zoom/.CHECKSUM
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

- Task Monitor Users: set cutoff time of 24 hours …

[PLGN-430] Zoom Task Monitor Users: set cutoff time of 24 hours

---

.github/workflows/plugin_release.yml
.github/workflows/plugin_release_staging.yml

…ckout (#2070)
- Update clone depth
- Update branch checkout
- Update input requirements …

Release - Plugin Release Workflow - Update Depth

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/test_advanced_query_on_log_set_unit.py

[PLGN-356] IDR - Statistical result - 6.0.0 (#2040)

---

plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/unit_test/expected/monitor_events_subsequent_run.json.exp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_subsequent_run.json.inp

Noticed during testing on staging environment that the interval could go out of range (either less than one minute or start time > than end time / time now. This PR is to address this boundary condition.
Tested locally using Postman requests.
Unit test update in progress.

[PLGN-560] Update proofpoint task subsequent run

---

plugins/zoom/.CHECKSUM
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

- Monitor Sign in and out Activity: set cutoff time of 24 hours …

Zoom 4.1.3 - release 

---

plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py

- Changed the max request time to 30 …

[PLGN-425] Mimecast - Changed max request time

---

plugins/trendmicro_visionone/.CHECKSUM
plugins/trendmicro_visionone/bin/icon_trendmicro_visionone
plugins/trendmicro_visionone/help.md
plugins/trendmicro_visionone/plugin.spec.yaml
plugins/trendmicro_visionone/requirements.txt
plugins/trendmicro_visionone/setup.py

- Update `pytmv1` package.
* All …

Trend Micro Vision One Update Package

---

plugins/trendmicro_visionone/.CHECKSUM
plugins/trendmicro_visionone/bin/icon_trendmicro_visionone
plugins/trendmicro_visionone/help.md
plugins/trendmicro_visionone/plugin.spec.yaml
plugins/trendmicro_visionone/requirements.txt
plugins/trendmicro_visionone/setup.py

* Update version to 201
* Remove tasks
* Update checksum
- …

Trend Micro Vision One Update Package (#2085)

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py

- Task Monitor Users: improve deduplication logic on user login history …

[PLGN-380] Salesforce Task Monitor Users: improve deduplication logic on user login history

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py

- Task Monitor Users: improve deduplication logic on user login history …

Salesforce 2.1.3 release 

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/help.md
plugins/sentinelone/komand_sentinelone/actions/move_between_sites/action.py
plugins/sentinelone/komand_sentinelone/actions/move_between_sites/schema.py
plugins/sentinelone/komand_sentinelone/util/api.py
plugins/sentinelone/plugin.spec.yaml

- To ensure that the type is used in the action is `string` and not `"string"`
- rewording the description of the action for `Move Agent to Another Site` 
- now allow for action to be passed into the `agents_action_move_agent_to_new_site` method 
https://issues.corp.rapid7.com/browse/PLGN-429 …

PLGN-429-Making sure type string is not in quotes, minor fix to description of action

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/schema.py
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/komand_duo_admin/util/api.py
plugins/duo_admin/komand_duo_admin/util/endpoints.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/test_add_user.py
plugins/duo_admin/unit_test/test_enroll_user.py
plugins/duo_admin/unit_test/test_get_logs.py
plugins/duo_admin/unit_test/test_get_phones_by_user_id.py
plugins/duo_admin/unit_test/test_get_user_by_id.py
plugins/duo_admin/unit_test/test_get_user_by_username.py
plugins/duo_admin/unit_test/test_get_user_status.py
plugins/duo_admin/unit_test/test_get_users.py
plugins/duo_admin/unit_test/test_modify_user.py
plugins/duo_admin/unit_test/test_monitor_logs.py

**Description:**
**Release PR for:**
* Adding in handling for task 403 errors
* Updated to allow optional collection of events and logs for task
* Updated unit tests due to change in response handling for task 403

[PLGN-611] Duo Admin Task Handle 403 errors and allow configuration of event and log gathering

---

.github/workflows/plugin_production_build.yml
.github/workflows/plugin_staging_build.yml

…tion release and staging release
- Two workflows to create builds and GitHub releases
- Trigger on merges to develop and master
- Can also be triggered manually provided the release does not already exist
- Builds a docker image in the name format 'vendor-plugin-version(-timestamp).tar.gz'
- Adds image as an asset to a new release in the name format 'vendor-plugin-version(-timestamp)'
If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product …

Plugin Auto Build and Tag

---

.github/workflows/plugin_production_build.yml
.github/workflows/plugin_staging_build.yml

- Fix retrieval of build output env var …

Update var retrieval

---

plugins/pdf_generator/.CHECKSUM
plugins/pdf_generator/Dockerfile
plugins/pdf_generator/bin/komand_pdf_generator
plugins/pdf_generator/help.md
plugins/pdf_generator/komand_pdf_generator/actions/generate_pdf/action.py
plugins/pdf_generator/plugin.spec.yaml
plugins/pdf_generator/requirements.txt
plugins/pdf_generator/setup.py

- update library to generate pdf  …

[SOAR-15967] PDF Generator Plugin - update library to generate pdf 

---

plugins/pdf_generator/.CHECKSUM
plugins/pdf_generator/Dockerfile
plugins/pdf_generator/bin/komand_pdf_generator
plugins/pdf_generator/help.md
plugins/pdf_generator/komand_pdf_generator/actions/generate_pdf/action.py
plugins/pdf_generator/plugin.spec.yaml
plugins/pdf_generator/requirements.txt
plugins/pdf_generator/setup.py

- update library to generate pdf …

[SOAR-15967] PDF Generator 1.0.3 - release

---

plugins/python_3_script/icon_python_3_script/actions/run/action.py

- Removed unnecessarry error traceback from the plugin …

[PLGN-414] Python 3 Script - Removed unnecessarry error traceback from the plugin

---

plugins/rapid7_insightvm/plugin.spec.yaml

- Remove connection version preventing requirement for new connection to be added
- Does not require release, therefore is eligible for merge to master
* All actions/triggers shortcut `insight-plugin run -T …

Rapid7 InsightVM Remove Connection Version

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

- Update to the latest plugin SDK …

[SOAR-15973] Zoom SDK update and slack message test

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/connection/connection.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/unit_test/mock.py
plugins/rapid7_insightvm_cloud/unit_test/test_asset_search.py
plugins/rapid7_insightvm_cloud/unit_test/test_get_asset.py
plugins/rapid7_insightvm_cloud/unit_test/test_get_scan.py
plugins/rapid7_insightvm_cloud/unit_test/test_start_scan.py
plugins/rapid7_insightvm_cloud/unit_test/test_stop_scan.py
plugins/rapid7_insightvm_cloud/unit_test/test_vuln_search.py
plugins/rapid7_insightvm_cloud/unit_test/utils.py

- Updated the documentation with links related to query builder and operators
- Updated the SDK
* Single …

[PLGN-273] InsightVM - Updated the documentation with links related to query builder and operators | Updated the SDK

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

- Update to the latest plugin SDK …

Zoom 4.1.4 - release 

---

plugins/abnormal_security/.CHECKSUM
plugins/abnormal_security/icon_abnormal_security/actions/get_cases/schema.py
plugins/abnormal_security/plugin.spec.yaml

after https://github.com/rapid7/insightconnect-plugins/pull/2158 adding in a default empty for enum 
* Single …

PLGN-321-Making sure that type enum has a default

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/assign_user_to_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/create_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/get_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_investigations/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/search_investigations/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/set_disposition_of_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/set_priority_of_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/set_status_of_investigation_action/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/update_investigation/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py

- Update schema for `Investigation`
- Update dependency for aiohttp …

[PLGN-618] Insight IDR update Investigation Schema, update dependency for aiohttp 

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/connection/connection.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py

Note- Validators are failing on the tasks and this is an known error for now. 
The Salesforce plugin logs "connection success" without actually attempting to authenticate to Salesforce.
- The log line has been removed.
* Single action/trigger `insight-plugin run -T tests/example.json …

[PLGN-364]- Remove unnecessary connection log line

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/connection/connection.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py

- Removed unnecessary connection log. …

[PLG-364]- Salesforce 2.1.4 Release

---

tools/update-tools.sh

- Update the install script contained within the `tools` folder to install the new `insight-plugin` tooling rather than the legacy `icon-plugin`.
* All actions/triggers shortcut `insight-plugin run -T all …

[SOAR-14960] Update Install Script

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/Dockerfile
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/get_incident_comments_worknotes/schema.py
plugins/servicenow/icon_servicenow/connection/connection.py
plugins/servicenow/icon_servicenow/connection/schema.py
plugins/servicenow/icon_servicenow/triggers/incident_created/trigger.py
plugins/servicenow/icon_servicenow/util/request_helper.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py
plugins/servicenow/unit_test/payloads/get_oauth_token.json.resp
plugins/servicenow/unit_test/test_create_change_request.py
plugins/servicenow/unit_test/test_create_security_incident.py
plugins/servicenow/unit_test/test_create_vulnerability.py
plugins/servicenow/unit_test/test_delete_security_incident.py
plugins/servicenow/unit_test/test_delete_vulnerability.py
plugins/servicenow/unit_test/test_get_attachments_for_an_incident.py
plugins/servicenow/unit_test/test_get_incident_attachment.py
plugins/servicenow/unit_test/test_get_security_incident.py
plugins/servicenow/unit_test/test_get_vulnerability.py
plugins/servicenow/unit_test/test_search_security_incident.py
plugins/servicenow/unit_test/test_update_security_incident.py
plugins/servicenow/unit_test/test_update_vulnerability.py
plugins/servicenow/unit_test/util.py

- Adds OAuth support for API authentication by way of adding two new optional fields to the connection: `oauth client ID` and `oauth client secret`
* All actions/triggers shortcut `insight-plugin run -T all …

[PLGN-621] Add OAuth to ServiceNow Plugin

---

plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_investigations/action.py

https://issues.corp.rapid7.com/browse/PLGN-613
- To add back in the index parameter to the rest_params
as part of the 5.0.0 update to IDR, how the user params were used to construct the rest_params to pass to idr was changed, as a result the index param that the user supplied was not being passed through to idr
testing before code changes we can see the index does not get reflected in what is returned from IDR
testing afterwords we can see that the index var is getting used as expected 
If …

[PLGN-613] - Insight IDR - Adding back in the index parameter into list investigations action

---

plugins/servicenow/icon_servicenow/connection/connection.py

- KeyError fixing for unhandled fields …

ServiceNow - Connection KeyError fix

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/top_remediations/schema.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/scan_completion/schema.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/scan_completion/trigger.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

- Update the `Scan Completion` trigger.
- Add new 'Category' input.
- Change output mapping from:
_before_
```
{
"asset_id": 765, 
"ip": "123.123.123.123", 
"hostname": "test_host", 
vulnerability_info": [
{
"vulnerability_id": "68883", 
"nexpose_id": "tls-untrusted-ca", 
"cvss_v3_score": "", 
"severity": "", 
"solution_id": "77017", 
"solution_summary": "Solution 1"
},
{
"vulnerability_id": "68888", 
"nexpose_id": "tls-untrust", 
"cvss_v3_score": "", 
"severity": "", 
"solution_id": "77019", 
"solution_summary": "Solution 2"
}
]
}
```
_after_
```
{
"output":
{
"assets":
[
{"asset_id": 765, "ip": "123.123.123.123", "hostname": "test_host"},
{"asset_id": 764, "ip": "123.123.123.123", "hostname": "test_host"},
{"asset_id": 763, "ip": "123.123.123.123", …
```

[PLGN-653] IVM - Scan completion update

---

plugins/abnormal_security/.CHECKSUM
plugins/abnormal_security/bin/icon_abnormal_security
plugins/abnormal_security/help.md
plugins/abnormal_security/icon_abnormal_security/util/api.py
plugins/abnormal_security/plugin.spec.yaml
plugins/abnormal_security/setup.py

- After changes made in the 2.0.0 release an issue where the wrong timeformat was getting passed to the UI, when the user entered `2023-01-01T21:11:38Z` the value of `2023-01-01T21:11:38:00:00` was being passed to the abnormal api and failing, so the plan is to just pass the users timestamp directly to the api with no parsing on our end
https://issues.corp.rapid7.com/browse/PLGN-651
all unit tests are still passing
testing using the test postmnan instance we have (note this is not fully the …

[PLGN-651] - Abnormal Security-Not parsing the timestamps provided by the user and just passing through the exact timestamp to the server

---

plugins/html/.CHECKSUM
plugins/html/Dockerfile
plugins/html/bin/icon_html
plugins/html/help.md
plugins/html/icon_html/actions/docx/schema.py
plugins/html/icon_html/actions/epub/schema.py
plugins/html/icon_html/actions/html5/schema.py
plugins/html/icon_html/actions/markdown/schema.py
plugins/html/icon_html/actions/pdf/schema.py
plugins/html/icon_html/actions/text/schema.py
plugins/html/icon_html/actions/validate/schema.py
plugins/html/plugin.spec.yaml
plugins/html/requirements.txt
plugins/html/setup.py

- Update the requirements for html to remove Snyk vulnerabilities. …

[PLGN-623 & PLGN-624] HTML - Snyk update

---

plugins/html/.CHECKSUM
plugins/html/Dockerfile
plugins/html/plugin.spec.yaml

after changes mad in https://github.com/rapid7/insightconnect-plugins/pull/2192, to now use nobody instead of root was made the plugin will no longer function due to permison issues
- To revert the use of the user to root
testing now that the user has been reverted
* Single …

[PLGN-623 & PLGN-624] HTML - Revert user

---

plugins/html/.CHECKSUM
plugins/html/Dockerfile
plugins/html/bin/icon_html
plugins/html/help.md
plugins/html/icon_html/actions/docx/schema.py
plugins/html/icon_html/actions/epub/schema.py
plugins/html/icon_html/actions/html5/schema.py
plugins/html/icon_html/actions/markdown/schema.py
plugins/html/icon_html/actions/pdf/schema.py
plugins/html/icon_html/actions/text/schema.py
plugins/html/icon_html/actions/validate/schema.py
plugins/html/plugin.spec.yaml
plugins/html/requirements.txt
plugins/html/setup.py

-  https://github.com/rapid7/insightconnect-plugins/pull/2192
-  Update the requirements for html to remove Snyk vulnerabilities.
- https://github.com/rapid7/insightconnect-plugins/pull/2200
- To revert a change in 2192 to update the user  
The following tickets are part of this release
- https://issues.corp.rapid7.com/browse/PLGN-623
- https://issues.corp.rapid7.com/browse/PLGN-624

HTML v1.2.5 release 

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/constants.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/resource_helper.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

- Extended error logging for all the actions …

[PLGN-270] Insight IDR - Extended error logging for all the actions

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

- Update SDK
- Add logs when we raise an exception error
Forced an API exception error to see the additional logging logs out-
* All actions/triggers shortcut `insight-plugin run --debug --jq` (use PR format at end)
You …

[PLGN-638]- Improve debugging and update SDK in Okta

---

plugins/cisco_firepower_management_center/.CHECKSUM
plugins/cisco_firepower_management_center/help.md
plugins/cisco_firepower_management_center/icon_cisco_firepower_management_center/connection/schema.py
plugins/cisco_firepower_management_center/plugin.spec.yaml

- Added cert format in the certificate description …

[PLGN-608] Cisco Firepower Management Center - Added cert format in the certificate description

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/actions/create_user/schema.py
plugins/okta/komand_okta/actions/get_user/schema.py
plugins/okta/komand_okta/triggers/users_added_removed_from_group/schema.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

Noticed the validations around passwords was not working correctly because of previous schema changes.
- Changed the password schema.
* All actions/triggers shortcut `insight-plugin run --debug --jq` (use PR format at end)
1. Run `insight-plugin validate` and make sure everything passes
2. Run the assessment …

[NO-TICKET]- Fix password schemas

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

- Update SDK
- Add logs when we raise an exception error
* All actions/triggers shortcut `insight-plugin run --debug --jq` (use PR format at end)
1. Run `insight-plugin validate` …

Plgn 641 improve zoom logging

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/schema.py
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml

[PLGN-639: Improve debugging/troubleshooting info in Proofpoint TAP tasks
](https://rapid7.atlassian.net/browse/PLGN-639)
- Bump SDK version to pull in new logging when an exception is instantiated and when a task begins and finishes. 
- Extensive logging was already present in the task logic, so this hasn't needed to change like in other similar PRs. 
- Unit tests are failing but they pass locally and the last release of proofpoint TAP had the same failing tests. 
- Various testing of code paths can be seen below:
```
https://usb-api.mimecast.com
rapid7/Mimecast:5.3.3. Step name: monitor_siem_logs
First run...
Plugin exception instantiated. …
```

[PLGN-639] [Proofpoint TAP] : pull latest SDK for task and exception logging

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

Zoom 4.1.5 Release
Bumped SDK version to get task improved logging and exception handling.
https://github.com/rapid7/insightconnect-plugins/pull/2230

[PLGN-641]- Zoom 4.1.5 Release

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/scan_completion/schema.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/scan_completion/trigger.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

- Rework query / output
- Remove all inputs except `site_id` …

Ivm trigger updates 2 - 8.0.0

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

- Restore version back to 7.0.0 to avoid 7 major version updates for one overall change. …

Return version back to 7.0.0

---

plugins/microsoft_intune/.CHECKSUM
plugins/microsoft_intune/Dockerfile
plugins/microsoft_intune/bin/icon_microsoft_intune
plugins/microsoft_intune/help.md
plugins/microsoft_intune/icon_microsoft_intune/connection/connection.py
plugins/microsoft_intune/icon_microsoft_intune/connection/schema.py
plugins/microsoft_intune/icon_microsoft_intune/util/api.py
plugins/microsoft_intune/icon_microsoft_intune/util/constants.py
plugins/microsoft_intune/plugin.spec.yaml
plugins/microsoft_intune/setup.py

- Connection: Added `client_credentials` authentication type …

[SOAR-428] Microsoft Intune new auth method

---

plugins/microsoft_intune/.CHECKSUM
plugins/microsoft_intune/help.md
plugins/microsoft_intune/icon_microsoft_intune/connection/schema.py
plugins/microsoft_intune/icon_microsoft_intune/util/api.py
plugins/microsoft_intune/icon_microsoft_intune/util/constants.py
plugins/microsoft_intune/plugin.spec.yaml

- Connection: Added client_credentials authentication type, changed username and password credentials as not required 
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR format …

[SOAR-428] Microsoft Intune new auth method fix

---

plugins/cisco_firepower_management_center/.CHECKSUM
plugins/cisco_firepower_management_center/bin/icon_cisco_firepower_management_center
plugins/cisco_firepower_management_center/help.md
plugins/cisco_firepower_management_center/icon_cisco_firepower_management_center/util/api.py
plugins/cisco_firepower_management_center/plugin.spec.yaml
plugins/cisco_firepower_management_center/setup.py

- Updated to latest SDK version
- Fixed issue related to pagination …

[PLGN-608] Cisco Firepower Management Center - Updated to latest SDK version | Fixed issue related to pagination

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

Release of Mimecast 5.3.4
Purpose:
- Further logger improvements around two erros being raised by customer integrations on production. 
Original PR:
- #2258 
Testing (evidence on JIRA):
- All actions passing on staging workflow
- Internal staging integration switched over to this version and happy path running <- unable to force errors.

Mimecast 5.3.4 Release

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

- Updated plugin description
* …

Python 3 Script - 648 - Updated plugin description

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/icon_python_3_script/actions/run/action.py
plugins/python_3_script/icon_python_3_script/util/constants.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

- Fix issue where input argument was too long …

Release [PLGN-648] Python 3 Script - Updated the SDK to latest version | Fix issue where input argument was too long (#2261)

---

plugins/cisco_firepower_management_center/.CHECKSUM
plugins/cisco_firepower_management_center/bin/icon_cisco_firepower_management_center
plugins/cisco_firepower_management_center/help.md
plugins/cisco_firepower_management_center/icon_cisco_firepower_management_center/util/api.py
plugins/cisco_firepower_management_center/plugin.spec.yaml
plugins/cisco_firepower_management_center/setup.py

- Updated to latest SDK version
- Fixed issue related to pagination …

Release [PLGN-608] Cisco Firepower Management Center - Updated to latest SDK version | Fixed issue related to pagination

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/scan_completion/trigger.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

* Helper method added
* Rename one variable
* Fix very easy to miss mistake
* Fix the equals
- …

IVM 7.0.2 (#2270)

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py

Temp fix to move Mimecast to 5.3.6 to extend the lifespan of the filtering to 96 hours. 
To do this I checked out Mimecast 5.3.2 commit, and pulled the files from master. Did an API call to 5.3.2 to match the SDK version to not accidentally bump this. 
Unit tests are passing locally:
Logs locally of first run on 5.3.2 showing more logs being filtered:
```
rapid7/Mimecast:5.3.2. Step name: monitor_siem_logs
First run
Number of raw logs returned from Mimecast: 45
Number of returned logs after filtering performed: 11
```
Logs locally of 5.3.5
```
https://usb-api.mimecast.com
rapid7/Mimecast:5.3.5. Step name: monitor_siem_logs
First run...
About to read file name spameventthread_tse_usb01_11_22_00_19ca0_97ce21fa-ace8-4b8f-be74-f9da3b4b1443_20240201.json …
```

PLGN-696 Mimecast: Task filter increase to 96 hours. 

---

plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py

Bump hours to 108 hours to allow for further backfill.

PLGN-696: mimecast bump cutoff hours to 108 hours

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py

Release of mimecast 5.3.4 to handle a gap in data up to 96 hours ago. 
PRs:
- #2272

Mimecast Release 5.3.5

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

- Actions: `Advanced Query On Log Set` and `Advanced Query On Log` - optimized data fetching mechanisms
* Single …

[PLGN-703] Insight IDR - Advanced Query on Log improve fetching logs mechanism 

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

- Actions: Advanced Query On Log Set and Advanced Query On Log - optimized data fetching mechanisms
* Single …

[PLGN-703] Insight IDR 8.2.0 release

---

plugins/trendmicro_visionone/.CHECKSUM
plugins/trendmicro_visionone/help.md
plugins/trendmicro_visionone/icon_trendmicro_visionone/actions/get_endpoint_activity_data_count/action.py
plugins/trendmicro_visionone/icon_trendmicro_visionone/actions/update_custom_script/action.py
plugins/trendmicro_visionone/icon_trendmicro_visionone/actions/update_custom_script/schema.py
plugins/trendmicro_visionone/plugin.spec.yaml

- Fixed validators and prospector …

Trendmicro Visionone - Fixed validators and prospector

---

plugins/rapid7_insightvm/komand_rapid7_insightvm/util/resource_helpers.py

[PLGN-741] InsightVM - Updated docstring

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

- 4.2.4 Production release does not contain commit 20ed9059001d6e2bf27060148d8ff8b1152db506
* Single …

[PLGN-730] okta fix komand props

---

.gitignore

- Add `.coverage` & `.dccache` (Snyk & Coverage) to `.gitignore`. …

GitIgnore Update - Include snyk and coverage files

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

- Update SDK
- Update Handling of plugin_config in task …

Okta 4.2.5 Release

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/test_monitor_logs.py

- Update monitor_logs with backfill logic for C2C
- Update max cutoff from 72 to 720 hours (tested, maximum allowed value is 180 days)
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` …

[PLGN-732] Duo Admin

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/plugin.spec.yaml

[PLGN-741] InsightVM - Updated SDK

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

Update Zoom plugin to include the latest SDK version (5.4.4).

[PLGN-753] Update Zoom to include SDK version 5.4.4

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

Python 3 Script - Updated the SDK to latest version

---

plugins/rest/.CHECKSUM
plugins/rest/Dockerfile
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py

Rest - Updated the SDK to latest version

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/Dockerfile
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/help.md
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/setup.py

Active Directory LDAP - Updated the SDK to latest version

---

plugins/dynamodb/.CHECKSUM
plugins/dynamodb/Dockerfile
plugins/dynamodb/help.md
plugins/dynamodb/plugin.spec.yaml

- Updated to the latest SDK to address memory usage issues
- Updated plugin packages …

[PLGN-314] DynamoDB - Updated to the latest SDK to address memory usage issues | Updated plugin packages

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/test_monitor_users.py
plugins/salesforce/unit_test/util.py

Release of Salesforce 2.1.6 - containing latest SDK 2.4.4, passing `cutom_config` parameter to allow backfills without the need for a new plugin release.
Testing is on-going which is why the `Do Not Merge` has been added.
PRs/Ticket:
- #2366
- [PLGN-729](https://rapid7.atlassian.net/browse/PLGN-729)
[PLGN-729]: https://rapid7.atlassian.net/browse/PLGN-729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Salesforce v2.1.6 Release

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

- Updated the SDK to the latest version to address memory usage issues …

[PLGN-768] Python 3 Script - Updated the SDK to the latest version to address memory usage issues

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

Zoom plugin updated to include latest SDK.

[PLGN-753] Release Zoom version 4.1.7 to include SDK version 5.4.4 (#2368)

---

plugins/rest/.CHECKSUM
plugins/rest/Dockerfile
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py

- Updated the SDK to the latest version to address memory usage issues …

[PLGN-769] Rest - Updated the SDK to the latest version to address memory usage issues

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/Dockerfile
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/help.md
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/setup.py

- Updated the SDK to the latest version to address memory usage issues …

[PLGN-770] Active Directory LDAP - Updated the SDK to the latest version to address memory usage issues

---

.gitignore

Update gitignore to include snyk and coverage files (#2355)

---

plugins/misp/.CHECKSUM
plugins/misp/bin/komand_misp
plugins/misp/help.md
plugins/misp/komand_misp/actions/download_attachment/action.py
plugins/misp/komand_misp/actions/export_attributes/action.py
plugins/misp/komand_misp/actions/export_events/action.py
plugins/misp/komand_misp/actions/export_hashes/action.py
plugins/misp/komand_misp/actions/export_rpz/action.py
plugins/misp/komand_misp/actions/export_rules/action.py
plugins/misp/komand_misp/actions/export_stix/action.py
plugins/misp/komand_misp/connection/connection.py
plugins/misp/plugin.spec.yaml
plugins/misp/setup.py

- SSL configuration for all actions …

[PLGN-736] MISP SSL configuration

---

plugins/threatminer/help.md

[PLGN-757] Threatminer - Updated help.md

---

plugins/misp/.CHECKSUM
plugins/misp/bin/komand_misp
plugins/misp/help.md
plugins/misp/komand_misp/actions/download_attachment/action.py
plugins/misp/komand_misp/actions/export_attributes/action.py
plugins/misp/komand_misp/actions/export_events/action.py
plugins/misp/komand_misp/actions/export_hashes/action.py
plugins/misp/komand_misp/actions/export_rpz/action.py
plugins/misp/komand_misp/actions/export_rules/action.py
plugins/misp/komand_misp/actions/export_stix/action.py
plugins/misp/komand_misp/connection/connection.py
plugins/misp/plugin.spec.yaml
plugins/misp/setup.py

- SSL configuration for all actions …

[PLGN-736] MISP Plugin 5.0.3 - release

---

plugins/rest/.CHECKSUM
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/komand_rest/util/util.py
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py
plugins/rest/unit_test/test_utils.py

- fix hard overriding custom header from `CUSTOM_SECRET_INPUT` …

[PLGN-789]  REST Plugin - custom headers fix

---

plugins/sonicwall/.CHECKSUM
plugins/sonicwall/Dockerfile
plugins/sonicwall/bin/icon_sonicwall
plugins/sonicwall/help.md
plugins/sonicwall/icon_sonicwall/actions/add_address_object_to_group/action.py
plugins/sonicwall/icon_sonicwall/actions/check_if_address_in_address_group/action.py
plugins/sonicwall/icon_sonicwall/actions/create_address_object/action.py
plugins/sonicwall/icon_sonicwall/actions/delete_address_object/action.py
plugins/sonicwall/icon_sonicwall/actions/remove_address_from_group/action.py
plugins/sonicwall/icon_sonicwall/util/api.py
plugins/sonicwall/icon_sonicwall/util/util.py
plugins/sonicwall/plugin.spec.yaml
plugins/sonicwall/setup.py
plugins/sonicwall/unit_test/test_add_address_object_to_group.py
plugins/sonicwall/unit_test/test_check_if_address_in_address_group.py
plugins/sonicwall/unit_test/test_create_address_object.py
plugins/sonicwall/unit_test/test_delete_address_object.py
plugins/sonicwall/unit_test/test_remove_address_from_group.py

[PLGN-378] SonicWall - Updated SDK to the latest version | Extended actions logging

---

plugins/trendmicro_visionone/help.md
plugins/trendmicro_visionone/icon_trendmicro_visionone/actions/get_endpoint_activity_data_count/action.py
plugins/trendmicro_visionone/icon_trendmicro_visionone/actions/update_api_key/action.py

trend micro 400 fixes

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/schema.py
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/test_monitor_logs.py

- Add task log type check for lookback
- Apply lookback limit of 180 days …

[PLGN-784] Duo Admin

---

plugins/pdf_generator/.CHECKSUM
plugins/pdf_generator/bin/icon_pdf_generator
plugins/pdf_generator/help.md
plugins/pdf_generator/plugin.spec.yaml
plugins/pdf_generator/requirements.txt
plugins/pdf_generator/setup.py

- Pin setuptools to 4.50.0 
- This is because the module `fpdf2` specifies `setuptools >= 4.38.0`, which means we usually install a valid version but snyk highlights a vulnerability because of the **possibility** of installing a vulnerable version. …

PDF Generator 1.0.5

---

plugins/pdf_generator/.CHECKSUM
plugins/pdf_generator/bin/icon_pdf_generator
plugins/pdf_generator/help.md
plugins/pdf_generator/plugin.spec.yaml
plugins/pdf_generator/requirements.txt
plugins/pdf_generator/setup.py

PDF Generator 1.0.5 Release

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/schema.py
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/test_monitor_logs.py

* Update task with multi-log type lookback
* Update version | Update unit test
* Update example help.md
* Update example help.md
* Update example help.md | update schema error
* Update lookback limit
* Refresh
- Add 180 day max lookback to task
- Add ability to determine lookback value for each logtype whenever custom_config is passed to task …

[PLGN-784] Duo Admin 4.0.0 Release

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/icon_python_3_script/util/constants.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

- Updated the SDK to the latest version
- Updated Python version to 3.9.19
- Fixed issue with invalid unicode character
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR format …

[PLGN-799] Python 3 Script - Updated the SDK to the latest version | Updated Python version to 3.9.19 | Fixed issue with invalid unicode character

---

plugins/broadcom_symantec_endpoint_protection/.CHECKSUM
plugins/broadcom_symantec_endpoint_protection/bin/icon_broadcom_symantec_endpoint_protection
plugins/broadcom_symantec_endpoint_protection/help.md
plugins/broadcom_symantec_endpoint_protection/icon_broadcom_symantec_endpoint_protection/connection/connection.py
plugins/broadcom_symantec_endpoint_protection/icon_broadcom_symantec_endpoint_protection/connection/schema.py
plugins/broadcom_symantec_endpoint_protection/icon_broadcom_symantec_endpoint_protection/util/api.py
plugins/broadcom_symantec_endpoint_protection/plugin.spec.yaml
plugins/broadcom_symantec_endpoint_protection/setup.py
plugins/broadcom_symantec_endpoint_protection/unit_test/util.py

[PLGN-738] symantec endpoint protection

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py

- Remove trust monitor events logging of full response …

[PLGN-809] duo admin remove logging

---

plugins/broadcom_symantec_endpoint_protection/.CHECKSUM
plugins/broadcom_symantec_endpoint_protection/bin/icon_broadcom_symantec_endpoint_protection
plugins/broadcom_symantec_endpoint_protection/help.md
plugins/broadcom_symantec_endpoint_protection/icon_broadcom_symantec_endpoint_protection/connection/connection.py
plugins/broadcom_symantec_endpoint_protection/icon_broadcom_symantec_endpoint_protection/connection/schema.py
plugins/broadcom_symantec_endpoint_protection/icon_broadcom_symantec_endpoint_protection/util/api.py
plugins/broadcom_symantec_endpoint_protection/plugin.spec.yaml
plugins/broadcom_symantec_endpoint_protection/setup.py
plugins/broadcom_symantec_endpoint_protection/unit_test/util.py

* Update SSL Verification
* Lint fix
* Remove unused ignore
* Add timeout
- Fix SSL verify
* Single …

[PLGN-738] symantec endpoint protection (#2444)

---

plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py

- Duo Admin Fix Message Trust Monitor Events …

Duo Admin Fix Message Trust Monitor Events

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py

* Remove logs
* Fix lint
- Remove extra logging of response in task monitor events …

[PLGN-809] duo admin 4.0.1

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/Dockerfile
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/get_agent_details/schema.py
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/get_all_agents_by_ip/schema.py
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py
plugins/rapid7_insight_agent/unit_test/parameters/get_all_agents_by_ip.json.resp
plugins/rapid7_insight_agent/unit_test/responses/get_all_agents_by_ip.resp
plugins/rapid7_insight_agent/unit_test/test_check_agent_status.py
plugins/rapid7_insight_agent/unit_test/test_get_agent_details.py
plugins/rapid7_insight_agent/unit_test/test_get_all_agents_by_ip.py
plugins/rapid7_insight_agent/unit_test/test_quarantine.py
plugins/rapid7_insight_agent/unit_test/test_quarantine_multiple.py

- `Get All Agents by IP Address`: Fixed issue where action failed when agent did not have a primary address
* …

[PLGN-817] Insight Agent - Get All Agents by IP Address: Fixed issue where action failed when agent did not have a primary address

---

plugins/confluence/.CHECKSUM
plugins/confluence/Dockerfile
plugins/confluence/bin/komand_confluence
plugins/confluence/help.md
plugins/confluence/komand_confluence/actions/get_page/action.py
plugins/confluence/komand_confluence/actions/get_page/schema.py
plugins/confluence/komand_confluence/actions/get_page_by_id/action.py
plugins/confluence/komand_confluence/actions/get_page_by_id/schema.py
plugins/confluence/komand_confluence/actions/get_page_content/action.py
plugins/confluence/komand_confluence/actions/get_page_content/schema.py
plugins/confluence/komand_confluence/actions/get_page_content_by_id/action.py
plugins/confluence/komand_confluence/actions/get_page_content_by_id/schema.py
plugins/confluence/komand_confluence/actions/store_page_content/action.py
plugins/confluence/komand_confluence/actions/store_page_content/schema.py
plugins/confluence/komand_confluence/connection/connection.py
plugins/confluence/komand_confluence/connection/schema.py
plugins/confluence/komand_confluence/util/api.py
plugins/confluence/plugin.spec.yaml
plugins/confluence/requirements.txt
plugins/confluence/setup.py
plugins/confluence/unit_test/test_get_page.py
plugins/confluence/unit_test/test_get_page_by_id.py
plugins/confluence/unit_test/test_get_page_content.py
plugins/confluence/unit_test/test_get_page_content_by_id.py
plugins/confluence/unit_test/test_store_page_content.py
plugins/confluence/unit_test/util.py

- Fixed issue where connection test would fail even if credentials entered were correct …

[PLGN-779] Confluence - Fixed issue where connection test would fail even if credentials entered were correct

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/connection/connection.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/new_exception_request/trigger.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/scan_completion/trigger.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/util/async_requests.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py
plugins/rapid7_insightvm/unit_test/test_async_requests.py

- Fixed issue with running the tasks with new SSL Verify parameter …

[PLGN-822] InsightVM - Fixed issue with running the tasks with new SSL Verify parameter

---

plugins/markdown/Dockerfile

- Add new package and command in the Dockerfile to remove problematic file that raises an error when running on insight connect due to inconsistencies between local environment and kubernetes.
* All …

Add new package and command to dockerfile

---

plugins/phishtank/.CHECKSUM
plugins/phishtank/bin/komand_phishtank
plugins/phishtank/help.md
plugins/phishtank/komand_phishtank/connection/connection.py
plugins/phishtank/plugin.spec.yaml
plugins/phishtank/setup.py

- https://github.com/rapid7/insightconnect-plugins/pull/2411
- Added error handling in the previous PR: https://github.com/rapid7/insightconnect-plugins/pull/2471
- This error handling raised a hidden 400 in the connection test which was not caught until testing on production.
- New URL is used to prevent this 400 and pass the connection test
Exported plugin and tested new connection:
If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product …

PLGN-761: Fixing phishtank connection test

---

plugins/sonicwall/.CHECKSUM
plugins/sonicwall/Dockerfile
plugins/sonicwall/bin/icon_sonicwall
plugins/sonicwall/help.md
plugins/sonicwall/icon_sonicwall/actions/check_if_address_in_address_group/action.py
plugins/sonicwall/icon_sonicwall/actions/remove_address_from_group/action.py
plugins/sonicwall/icon_sonicwall/util/api.py
plugins/sonicwall/icon_sonicwall/util/util.py
plugins/sonicwall/plugin.spec.yaml
plugins/sonicwall/setup.py
plugins/sonicwall/unit_test/mock.py
plugins/sonicwall/unit_test/responses/address_groups_ipv4_name_v2.json.resp
plugins/sonicwall/unit_test/responses/address_objects.json.resp
plugins/sonicwall/unit_test/test_add_address_object_to_group.py
plugins/sonicwall/unit_test/test_check_if_address_in_address_group.py
plugins/sonicwall/unit_test/test_delete_address_object.py

[PLGN-378] SonicWall - Updated SDK to the latest version | Updated objects checking

---

plugins/phishtank/.CHECKSUM
plugins/phishtank/bin/komand_phishtank
plugins/phishtank/help.md
plugins/phishtank/komand_phishtank/connection/connection.py
plugins/phishtank/plugin.spec.yaml
plugins/phishtank/setup.py

* fixing connection test
* reformatting connection test
- https://github.com/rapid7/insightconnect-plugins/pull/2476
- Fixing the failing connection test
* All actions/triggers shortcut `insight-plugin run -T …

PLGN-761: Phishtank 2.0.1 Release (#2476)

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/Dockerfile
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/triggers/incident_created/trigger.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

ServiceNow 7.4.1 Release:
- Updated to the latest SDK 5.47
- Trigger was not working properly to find new incidents. Found that there is now a limit where it pulls back 10,000 results so it was never finding the latest incident. I have changed this now so it pulls the most recent 10,000 results.
- Also fixed an issue with the polling time as it kept missing new incidents.

ServiceNow 7.4.1 Release

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/connection/connection.py
plugins/okta/komand_okta/connection/schema.py
plugins/okta/komand_okta/util/api.py
plugins/okta/komand_okta/util/helpers.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py
plugins/okta/unit_test/test_create_user.py
plugins/okta/unit_test/util.py

- Add error handling around okta.com url connection input …

Okta 4.2.6 Release

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/komand_whois/actions/address/action.py
plugins/whois/komand_whois/actions/domain/action.py
plugins/whois/plugin.spec.yaml
plugins/whois/requirements.txt
plugins/whois/setup.py
plugins/whois/unit_test/test_address.py
plugins/whois/unit_test/test_domain.py
plugins/whois/unit_test/util.py

- Added validation for input parameters …

[PLGN-831] WHOIS - Updated SDK to the latest version | Added validation for input parameters

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/komand_whois/actions/address/action.py
plugins/whois/komand_whois/actions/domain/action.py
plugins/whois/plugin.spec.yaml
plugins/whois/requirements.txt
plugins/whois/setup.py
plugins/whois/unit_test/test_address.py
plugins/whois/unit_test/test_domain.py
plugins/whois/unit_test/util.py

- Added validation for input parameters …

[PLGN-831] WHOIS - Updated SDK to the latest version | Added validation for input parameters (#2499)

---

plugins/sonicwall/.CHECKSUM
plugins/sonicwall/bin/icon_sonicwall
plugins/sonicwall/help.md
plugins/sonicwall/icon_sonicwall/actions/add_address_object_to_group/action.py
plugins/sonicwall/icon_sonicwall/util/api.py
plugins/sonicwall/plugin.spec.yaml
plugins/sonicwall/setup.py

- `Add Address Object to Group`: Fixed issue with payload syntax …

[PLGN-378] SonicWall - `Add Address Object to Group`: Fixed issue with payload syntax

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/scan_completion/trigger.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py

- `Scan Completion`: Updated the query …

[PLGN-814] InsightVM - Updated SDK to the latest version | `Scan Completion`: Updated the query

---

plugins/rapid7_intsights/.CHECKSUM
plugins/rapid7_intsights/Dockerfile
plugins/rapid7_intsights/bin/icon_rapid7_intsights
plugins/rapid7_intsights/help.md
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_indicator_by_value/action.py
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_indicator_by_value/schema.py
plugins/rapid7_intsights/icon_rapid7_intsights/triggers/new_alert/trigger.py
plugins/rapid7_intsights/icon_rapid7_intsights/util/api.py
plugins/rapid7_intsights/icon_rapid7_intsights/util/constants.py
plugins/rapid7_intsights/plugin.spec.yaml
plugins/rapid7_intsights/setup.py
plugins/rapid7_intsights/unit_test/test_close_alert.py
plugins/rapid7_intsights/unit_test/test_connection.py
plugins/rapid7_intsights/unit_test/test_get_iocs_for_cyber_term.py

* updated api and unit test exception presets
* ran black
* added new output field subType
* fixed subtype var name and refresh
* fixing validators
* Update Docker version
- …

[PLGN-261] Threat Command - 5.2.0 (#2485)

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/scan_completion/trigger.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py

- `Scan Completion`: Updated the query …

[PLGN-814] InsightVM - Updated SDK to the latest version | Scan Completion: Updated the query (#2504)

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/help.md
plugins/powershell/plugin.spec.yaml

- Update dependancies in dockerfile …

Powershell alpine dependancies fix

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/plugin.spec.yaml

The SDK had moved on before I merged the Zoom lookback update so this is a small PR to update it.

[SOAR-26854] -  zoom sdk update

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

Release PR to increase the lookback for tasks to be up to 7 days. Initial lookback is still 24 hours. 
Updated to latest SDK.

[SOAR-26854] Zoom task lookback time (#2506)

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/schema.py
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py

- Update initial lookback to 7 days
- Update SDK …

[SOAR-16852] Proofpoint Initial Lookback

---

plugins/cisco_umbrella_destinations/.CHECKSUM
plugins/cisco_umbrella_destinations/bin/icon_cisco_umbrella_destinations
plugins/cisco_umbrella_destinations/help.md
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dlCreate/action.py
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dlCreate/schema.py
plugins/cisco_umbrella_destinations/plugin.spec.yaml
plugins/cisco_umbrella_destinations/setup.py

- `dlCreate`: Add error handling and new default enum value for type …

Cisco Umbrella Destination List - 5.0.1

---

plugins/zoom/.CHECKSUM
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

- Update task to handle pagination token error in response …

[SOAR-16986] Zoom Update task to handle pagination error

---

plugins/zoom/.CHECKSUM
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

* Update task to handle pagination error
* Update lint and static code anlysis
* Update version | Update has_more_pages to False for no pagination token returned, and pagination error.
* Update timeout
* Update has_next_pages
* Remove print
* Undo has_next_page update | Undo set last_event_timestamp logic for exiting pagintation
- Update task to handle pagination token error
If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests …

[SOAR-16986] Zoom 4.1.10 Release

---

plugins/cisco_umbrella_destinations/.CHECKSUM
plugins/cisco_umbrella_destinations/bin/icon_cisco_umbrella_destinations
plugins/cisco_umbrella_destinations/help.md
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dlCreate/action.py
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dlCreate/schema.py
plugins/cisco_umbrella_destinations/plugin.spec.yaml
plugins/cisco_umbrella_destinations/setup.py

* Handle destination input
* Update hash
- …

Cisco Umbrella Destination List - 5.0.1 (#2537)

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/expected/monitor_logs_2.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_3.json.exp
plugins/duo_admin/unit_test/inputs/monitor_logs_next_page.json.inp
plugins/duo_admin/unit_test/inputs/monitor_logs_with_state.json.inp
plugins/duo_admin/unit_test/util.py

- Update SDK to 5.4.9
- Update MAX_CUTOFF_HOURS to 7 days for tasks
https://rapid7.atlassian.net/browse/SOAR-16858 
Tested by running a load test in the staging environment.

Duo Admin 4.4.2

---

plugins/microsoft_atp/.CHECKSUM
plugins/microsoft_atp/Dockerfile
plugins/microsoft_atp/bin/komand_microsoft_atp
plugins/microsoft_atp/help.md
plugins/microsoft_atp/komand_microsoft_atp/actions/blacklist/action.py
plugins/microsoft_atp/komand_microsoft_atp/actions/blacklist/schema.py
plugins/microsoft_atp/plugin.spec.yaml
plugins/microsoft_atp/requirements.txt
plugins/microsoft_atp/setup.py

the customer wanted the ability to makes sure that the generate alerts flag could be disabled when creating adding an ioc to the blacklist. Please note as stated in the Microsoft docs and I have added this to the description of this new field that it will not work will all action types
-  Adding the following as new action types to `blacklist` action ['Warn', 'Block', 'Audit']
-  Add a new flag in the `blacklist` action to toggle generateAlerts flag
- Bump SDK to version 5.4.9
- bump version of validators used for a medium snyk vuln
https://rapid7.atlassian.net/browse/SOAR-17011
Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) …

[SOAR-17011] - Microsoft ATP -Adding the following as new action types to  action ['Warn', 'Block', 'Audit']

---

plugins/microsoft_atp/.CHECKSUM
plugins/microsoft_atp/Dockerfile
plugins/microsoft_atp/bin/komand_microsoft_atp
plugins/microsoft_atp/help.md
plugins/microsoft_atp/komand_microsoft_atp/actions/blacklist/action.py
plugins/microsoft_atp/komand_microsoft_atp/actions/blacklist/schema.py
plugins/microsoft_atp/plugin.spec.yaml
plugins/microsoft_atp/requirements.txt
plugins/microsoft_atp/setup.py

Release pr for 
https://github.com/rapid7/insightconnect-plugins/pull/2547
- https://rapid7.atlassian.net/browse/SOAR-17011
- Adding the following as new action types to `blacklist` action ['Warn', 'Block', 'Audit']
- Add a new flag in the `blacklist` action to toggle generateAlerts flag
- Bump SDK to version 5.4.9
- bump version of validators used for a medium snyk vuln
testing on stging with the new flag set to false, generate alert is now set to false on defender

Microsoft ATP - 5.1.0  release

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/actions/create_user/schema.py
plugins/okta/komand_okta/actions/deactivate_user/schema.py
plugins/okta/komand_okta/actions/get_factors/schema.py
plugins/okta/komand_okta/actions/get_user_groups/schema.py
plugins/okta/komand_okta/actions/suspend_user/schema.py
plugins/okta/komand_okta/connection/connection.py
plugins/okta/komand_okta/tasks/monitor_logs/schema.py
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/komand_okta/util/helpers.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py
plugins/okta/unit_test/expected/get_logs.json.exp
plugins/okta/unit_test/expected/get_logs_filtered.json.exp
plugins/okta/unit_test/expected/get_logs_next_page.json.exp
plugins/okta/unit_test/inputs/monitor_logs_next_page.json.inp
plugins/okta/unit_test/responses/send_push_verify_challenge1.json.resp
plugins/okta/unit_test/responses/send_push_verify_challenge2.json.resp
plugins/okta/unit_test/responses/send_push_verify_challenge3.json.resp
plugins/okta/unit_test/responses/send_push_verify_poll_status_waiting.json.resp
plugins/okta/unit_test/test_monitor_logs.py
plugins/okta/unit_test/util.py

Changes for:
- https://rapid7.atlassian.net/browse/SOAR-16857
- https://rapid7.atlassian.net/browse/SOAR-16861
- Increase cutoff for Okta to 7 days. Initial lookback remains 24 hours.
- Additional validation for oktaUrl connection input, so that the oktaUrl must endWith one of the allowed okta hosts in [pd_k8s/variables.tf](https://github.com/rapid7/tf-komand/blob/master/integration_alliance/production/cloud/pd_k8s/variables.tf#L469-L476)
If you are an InsightConnect customer or have access …

[SOAR-16857] - Update task lookback cutoff to 7 days

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/actions/create_user/schema.py
plugins/okta/komand_okta/actions/deactivate_user/schema.py
plugins/okta/komand_okta/actions/get_factors/schema.py
plugins/okta/komand_okta/actions/get_user_groups/schema.py
plugins/okta/komand_okta/actions/suspend_user/schema.py
plugins/okta/komand_okta/connection/connection.py
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/komand_okta/util/helpers.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py
plugins/okta/unit_test/expected/get_logs.json.exp
plugins/okta/unit_test/expected/get_logs_filtered.json.exp
plugins/okta/unit_test/expected/get_logs_next_page.json.exp
plugins/okta/unit_test/inputs/monitor_logs_next_page.json.inp
plugins/okta/unit_test/responses/send_push_verify_challenge1.json.resp
plugins/okta/unit_test/responses/send_push_verify_challenge2.json.resp
plugins/okta/unit_test/responses/send_push_verify_challenge3.json.resp
plugins/okta/unit_test/responses/send_push_verify_poll_status_waiting.json.resp
plugins/okta/unit_test/test_monitor_logs.py
plugins/okta/unit_test/util.py

- Increase cutoff for Okta to 7 days. Initial lookback remains 24 hours.
- Additional validation for oktaUrl connection input
- Tickets:
- https://rapid7.atlassian.net/browse/SOAR-16857
- https://rapid7.atlassian.net/browse/SOAR-16861
Original PR:
- https://github.com/rapid7/insightconnect-plugins/pull/2546
Testing: 
- On staging confirmed that initial lookback was 24 hours on first run
- Modified state to be >7 days ago, and confirmed the cutoff is 168 hours (7 days)
- Confirmed no errors in pod logs
- Tested new validation around oktaUrl connection input
- Expected invalid domain error is raised when the input url does not match `example.okta-domain.com`

[SOAR-16857] - Okta v4.2.7 Release

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py

- Update SDK.
- Bump aiohttp to fix dependency issue.
- Fix issue where message can be received as an object or a string.
https://rapid7.atlassian.net/browse/SOAR-17022

Soar 17022 InsightIDR Fix Schema

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py

- Update SDK.
- Bump aiohttp to fix dependency issue.
- Fix issue where message can be received as an object or a string.

[SOAR-17022] InsightIDR 10.1.1 Release

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/event.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

https://rapid7.atlassian.net/browse/SOAR-17038
- https://github.com/rapid7/insightconnect-plugins/pull/2569
- If there is no datetime timestamp in the response from Mimecast then we will not check to see if the that field is within teh filter time
- https://github.com/rapid7/insightconnect-plugins/pull/2509
- to bump the werkzeug package version

MImecast 5.3.12 Release

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/connection/connection.py
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/komand_okta/util/api.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

Ticket - https://rapid7.atlassian.net/browse/SOAR-17031
- Raise an exception with a `401` status_code in the api.py make_request function if the Okta domain is invalid
- This will be caught in the task.py code and the 401 will be set in the body so that the task executor handles it correctly, and puts the integration in to an error state
e.g. 
```
{
"body": {
"exception": {
"assistance": "Please include a valid subdomain, e.g. 'example.okta.com', if using 'okta.com'.",
"cause": "Invalid domain entered for input 'Okta Domain'.",
"data": "Provided Okta Domain: dev-12345"
},
"has_more_pages": false,
"log": "Connect: Connecting...\nrapid7/Okta:4.2.8. Step name: monitor_logs\nTask execution will be applying filter period of 24 hours...\nFirst run\nCalling Okta …
```

[SOAR-17031] - Set 401 status_code if Okta domain is invalid

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/schema.py
plugins/proofpoint_tap/komand_proofpoint_tap/connection/schema.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py

- [[Proofpoint TAP] Update connection schema to correct fields as required](https://rapid7.atlassian.net/browse/SOAR-17028)
We need to change the fields for the connection to be required as it is allowing customers to create connection objects with no associated credentials which then causes the actions/tasks to fail when they are triggered. 
- Ran refresh which has re-ordered the help.md and required some fields populated into the plugin spec.
- Updated connection schema so that the user is required to enter values. One action: parse alerts does not require a connection but due to how we run the action the plugin sidecar still tries to decrypt the connection associated with the plugin and fails on decrypting empty values. 
Developers, verify you have …

[SOAR-17028] [Proofpoint TAP] Update connection schema to required:true

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/actions/create_user/action.py
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/icon_zoom/util/api.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/mock.py
plugins/zoom/unit_test/test_api.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

- Check if exception.data exists before accessing
- Update api.py to use insightconnect-plugin-runtime helper methods for requests
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use …

[SOAR-17043] Zoom fix error handling in task

---

plugins/azure_ad_admin/.CHECKSUM
plugins/azure_ad_admin/Dockerfile
plugins/azure_ad_admin/help.md
plugins/azure_ad_admin/icon_azure_ad_admin/triggers/risk_detection/trigger.py
plugins/azure_ad_admin/plugin.spec.yaml
plugins/azure_ad_admin/requirements.txt

- Refactored code in risk detection trigger …

[SOAR-17046] Azure AD Admin - Refactored code in risk detection trigger

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/actions/create_user/action.py
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/icon_zoom/util/api.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/mock.py
plugins/zoom/unit_test/test_api.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

* Update attribute access clause
* Initial update
* Initial update
* Update SDK to 5.5.1
* Update SDK to 5.5.2
- Update 401 handling in task
- Refactor API code to use insightconnect-plugin-runtime helper methods
* Single action/trigger `insight-plugin run -T …

Zoom 4-1-2 Release

---

plugins/azure_ad_admin/.CHECKSUM
plugins/azure_ad_admin/Dockerfile
plugins/azure_ad_admin/plugin.spec.yaml

[SOAR-17046] Azure AD Admin - Updated SDK to the latest version

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/asset_search/schema.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_asset/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_asset/schema.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/vuln_search/action.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py

- Change type of output `new` from `[]string` to `[]object` …

Change type of 'new' output | Update version to 6.0.0

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/util/event.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

[[C2C Zoom] Zoom API change has removed required field](https://rapid7.atlassian.net/browse/SOAR-17144)
- Zoom occasionally returning log entries with the client type  missing and resulting in an error:
```
unable to parse events: __init__() missing 1 required positional argument: 'client_type'
```
- small code change to bypass this by setting default values to each Event - allowing the rest of the task code to still access attributes for comparison.
- wildcards have states they don't parse this field/wouldn't fail on missing this field - details in slack channel: #cloud-event-source-datacollection
- Sanity run of task and no errors. 
Review our documentation on …

[SOAR-17144] [Zoom] Set event attributes to be optional

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/util/event.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

Release of Zoom 4.1.13
Changes:
- Allow event object to be created with missing attributes from their API response. 
- This will unblock any integrations that are being returned data from Zoom with the missing `client_type` key.
- SDK version bump.
Testing:
- Limited tested on staging as can't reproduce bug on our account. 
- Evidence of logs on happy path on jira ticket: https://rapid7.atlassian.net/browse/SOAR-17144
Original PR: #2596

Zoom Release 4.1.13

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/update_alert/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml

-New Action: Update Alert
* All …

NOTICKET-InsightIDR-New Action: Update Alert

---

plugins/jenkins/komand_jenkins/util/util.py

- Updated extract build number logic …

[SOAR-17160] Jenkins - Updated extract build number logic

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/Dockerfile
plugins/carbon_black_cloud/plugin.spec.yaml

[SOAR-17212] Update SDK to 5.6.0

---

plugins/microsoft_defender_incidents/.CHECKSUM
plugins/microsoft_defender_incidents/Dockerfile
plugins/microsoft_defender_incidents/plugin.spec.yaml

MS Defender | Update sdk to latest

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/connection/connection.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py

- bump SDK to 5.6.1 to pull in improved task connection test status codes
- improve the logging around task tests 
https://rapid7.atlassian.net/browse/SOAR-17237
an invalid test will now return as a 400 
a valid test will now show better logging  …

SOAR-17237-Bump Mimecast SDK version

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/Dockerfile
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/plugin.spec.yaml

As the SDK was bumped as I was about to merge to production I had to bump it to 5.6.1.
[Original Ticket](https://rapid7.atlassian.net/browse/SOAR-17168)
- SDK Bump to 5.6.1
- Plugin Refresh
- Fixing Unit Tests
**Postman Local Test:**
Get Content Test:
Search DB Test:
Output: …

[SOAR-17168] Vulndb Bumping SDK to 5.6.1

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/asset_search/schema.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_asset/schema.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py

- Update asset schema to fully reflect API response
- [
API Docs](https://help.rapid7.com/insightvm/en-us/api/integrations.html#operation/getIntegrationAsset)
* All actions/triggers shortcut `insight-plugin …

[SOAR-17243] InsightVM Cloud - Update Asset Schema

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/Dockerfile
plugins/sentinelone/komand_sentinelone/tasks/monitor_logs/schema.py
plugins/sentinelone/plugin.spec.yaml

SentinelOne 10.0.0 SDK Update

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/asset_search/schema.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_asset/schema.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py

* Update schema for asset type
* Update SDK
- Update custom type Asset to match API specification
* Single …

InsightVM Cloud 7.0.0 Release

---

plugins/domaintools/.CHECKSUM
plugins/domaintools/Dockerfile
plugins/domaintools/bin/komand_domaintools
plugins/domaintools/help.md
plugins/domaintools/plugin.spec.yaml
plugins/domaintools/requirements.txt
plugins/domaintools/setup.py
plugins/domaintools/unit_test/test_brand_monitor.py
plugins/domaintools/unit_test/test_domain_profile.py

Release of DomainTools 2.0.1
Changes:
- API has been bumped to 2.0.0
- Anyio was added in requirements.txt (to fix Snyk vulnerability)
- SDK bumped to 5.6.1
- Plugin Refresh
- Unit Tests fixed 
- Unit Tests carried out (via Terminal and PyCharm)
- Sending POST requests on Postman
- Thorough testing done in the staging environment
Original PR: #2620 
[Ticket](https://rapid7.atlassian.net/browse/SOAR-17225)

[SOAR-17225] Domaintools 2.0.1 release

---

plugins/trendmicro_visionone/.CHECKSUM
plugins/trendmicro_visionone/icon_trendmicro_visionone/actions/get_endpoint_activity_data/action.py
plugins/trendmicro_visionone/plugin.spec.yaml
plugins/trendmicro_visionone/unit_test/test_a_poll_alert_list.py
plugins/trendmicro_visionone/unit_test/test_a_poll_oat_list.py
plugins/trendmicro_visionone/unit_test/test_add_custom_script.py
plugins/trendmicro_visionone/unit_test/test_delete_custom_script.py
plugins/trendmicro_visionone/unit_test/test_get_alert_list.py
plugins/trendmicro_visionone/unit_test/test_get_custom_script_list.py
plugins/trendmicro_visionone/unit_test/test_get_exception_list.py
plugins/trendmicro_visionone/unit_test/test_get_suspicious_list.py
plugins/trendmicro_visionone/unit_test/test_run_custom_script.py
plugins/trendmicro_visionone/unit_test/test_update_custom_script.py

Fix sca, unit tests

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

- Update SDK
- Update version to `8.0.3`
- Update `Dockerfile` user to `root` …

IVM Console | 8.0.3 | Permission Issues

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

- Update Dockerfile permissions
- Update SDK …

IVM | 8.0.3 | Release

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/Dockerfile
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/triggers/vulnerability_updated/schema.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/requirements.txt
plugins/servicenow/setup.py

- Remediate SNYK vulnerabilities
- Update SDK …

[SOAR-17271] Servicenow

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/plugin.spec.yaml
plugins/whois/requirements.txt
plugins/whois/setup.py

- Bump to use latest SDK version and setuptools version. 
- Validator failing due to installing whois in dockerfile, this has failed on previous version as well - 
- Ran integration tests and passing. 
- Small change on status code for bad requests now returning 400 instead of previously 500. Opening a second PR for this integration test.  …

[SOAR-17285] [WHOIS]: Bump setuptools and SDK version

---

plugins/servicenow/help.md

- Add in values from help.md removed in refresh …

[SOAR-17271]  servicenow help.md

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

- Update SDK
- Update Setuptools …

[SOAR-17287] InsightVM

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/Dockerfile
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/triggers/vulnerability_updated/schema.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/requirements.txt
plugins/servicenow/setup.py

* Update dependancies
* Update dependancies
- Update SDK
- Update setuptools dependency …

ServiceNow 8.0.1 Release

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/connection/connection.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py

https://rapid7.atlassian.net/browse/SOAR-17270
- Update setuptools to `70.0.0`
- Update version to `5.3.15`
https://rapid7.atlassian.net/browse/SOAR-17272
After new changes to the SDK, we now support passing back a message to the SDK as part of the task connection test, this will allow for the use of the custom message to be shown in the UI for a task connection test, rather than have the end user see all of the available logs 
This has been tested locally using docker and postman, using the mew version of the SDK
on a successful test, task route 
on a successful test, connection test route 
on a failure we will now try and return the data section of the error raised to the end …

[SOAR-17270,SOAR-17272 ] Mimecast | Snyk fix | Improve task connection test logic

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/Dockerfile
plugins/rapid7_vulndb/bin/komand_rapid7_vulndb
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/plugin.spec.yaml
plugins/rapid7_vulndb/requirements.txt
plugins/rapid7_vulndb/setup.py

- Update SDK
- Pin setuptools == 70.0.0 …

[SOAR-17289] Vuln DB | Snyk fix

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/help.md
plugins/mimecast/plugin.spec.yaml

- Bump the sdk used in Mimecast that was part of  https://github.com/rapid7/insightconnect-plugins/pull/2639

SOAR-17270-Update the version of the SDK used for Mimecast

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/Dockerfile
plugins/rapid7_vulndb/bin/komand_rapid7_vulndb
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/plugin.spec.yaml
plugins/rapid7_vulndb/requirements.txt
plugins/rapid7_vulndb/setup.py

Rapid7 VulnDb 2.1.3 Release

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

* Update SDK and setuptools
* Update SDK and setuptools
* Fix apk add removed by refresh
- Update SDK and SetupTools
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR format at …

InsightVM 8.0.4 Release

---

plugins/palo_alto_pan_os/.CHECKSUM
plugins/palo_alto_pan_os/Dockerfile
plugins/palo_alto_pan_os/bin/komand_palo_alto_pan_os
plugins/palo_alto_pan_os/help.md
plugins/palo_alto_pan_os/plugin.spec.yaml
plugins/palo_alto_pan_os/requirements.txt
plugins/palo_alto_pan_os/setup.py

Palo Alto Pan OS 6.1.6 Release

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/requirements.txt
plugins/python_3_script/setup.py

Original PR: #2644 
Updated PR: #2661 
[Ticket](https://rapid7.atlassian.net/browse/SOAR-17284)
- SDK Bump to 6.0.1
- Removing 'records' & bumping 'setuptools'
- Updating Plugin Spec and help.md
- Replaced '[maya](https://github.com/kennethreitz/maya)' with '[arrow](https://github.com/arrow-py/arrow)' (maya has not been maintained for a large duration of time)
Unit test carried out:

[SOAR-17284] Python 3 Script 5.0.0 release

---

plugins/freshdesk/.CHECKSUM
plugins/freshdesk/bin/icon_freshdesk
plugins/freshdesk/help.md
plugins/freshdesk/icon_freshdesk/actions/updateTicket/schema.py
plugins/freshdesk/plugin.spec.yaml
plugins/freshdesk/setup.py

- Update Ticket action include responder id …

[SOAR-17269] freshdesk

---

plugins/freshdesk/.CHECKSUM
plugins/freshdesk/bin/icon_freshdesk
plugins/freshdesk/help.md
plugins/freshdesk/icon_freshdesk/actions/updateTicket/schema.py
plugins/freshdesk/plugin.spec.yaml
plugins/freshdesk/setup.py

- Update update ticket with responder id …

Freshdesk 1.2.0 release

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/triggers/get_new_investigations/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

* Fix query on log bug | Update SDK | Update version
* Black formatting
* Update sdk
* Restore schemas
* Restore other schema
* Restore schemas properly
* Restore the query schema too
- …

[SOAR-17283] IDR | 10.3.1 Release

---

plugins/base64/.CHECKSUM
plugins/base64/help.md
plugins/base64/plugin.spec.yaml

Base64 - Updated supported versions

---

plugins/domaintools/.CHECKSUM
plugins/domaintools/Dockerfile
plugins/domaintools/bin/komand_domaintools
plugins/domaintools/help.md
plugins/domaintools/plugin.spec.yaml
plugins/domaintools/requirements.txt
plugins/domaintools/setup.py

- Updated SDK and packages to the latest version …

[SOAR-17377] Domaintools - Updated SDK and packages to the latest version

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/help.md
plugins/powershell/plugin.spec.yaml

https://rapid7.atlassian.net/browse/SI-24367
- Change the SDK base image back from Alpine to Bullseye as the realm package was not available for Alpine
- bumping to latest sdk  …

SOAR-17026 - Powershell - moving powershell back to slim SDK version

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/connection/connection.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

- SDK Bump to 6.0.1 & Plugin Refresh
[Ticket](https://rapid7.atlassian.net/browse/SOAR-17318)
The following exceptions were hit in order to ensure the correct message was outputted:
- PluginException Error: 
- Successful Connection:
- Authentication Error:
- Retry Limit Error:

[SOAR-17318] Zoom Task Connection Test & SDK Bump

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/Dockerfile
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py

- Insight Agent Search Agents is failing in cloud due to a timeout
- Initial step, reduce logging of results to increase performance
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` …

[SOAR-17259] Rapid7 Insight Agent

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/Dockerfile
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py

Rapid7 Insight Agent 2.1.2 Release

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/Dockerfile
plugins/sentinelone/bin/komand_sentinelone
plugins/sentinelone/help.md
plugins/sentinelone/komand_sentinelone/tasks/monitor_logs/schema.py
plugins/sentinelone/komand_sentinelone/tasks/monitor_logs/task.py
plugins/sentinelone/plugin.spec.yaml
plugins/sentinelone/setup.py
plugins/sentinelone/unit_test/test_monitor_logs.py
plugins/sentinelone/unit_test/util.py

* Remove task inputs
* Fix unit tests
* Run black
- Remove task inputs …

SentinelOne 11.0.0 Release

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/connection/connection.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

- SDK Bump and Plugin Refresh
- Task Connection Test created
[Original PR](https://github.com/rapid7/insightconnect-plugins/pull/2688)
[Ticket](https://rapid7.atlassian.net/browse/SOAR-17318)
Thoroughly tested in Postman to ensure the correct exceptions are handled (Evidence added in Original PR)
Logs checked in Staging to ensure rollover is as expected

[SOAR-17318] Zoom 4.1.14 Release

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/help.md
plugins/okta/plugin.spec.yaml

Plugin was about to be deployed to production but due to the SDK changes, I need to bump to the newest version
- SDK Bump to 6.1.0
Previous PR's: #2692 #2694

[SOAR-17320] Okta Bumping SDK to 6.1.0

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/help.md
plugins/powershell/plugin.spec.yaml

Powershell | Update SDK

---

plugins/bitwarden/.CHECKSUM
plugins/bitwarden/Dockerfile
plugins/bitwarden/bin/icon_bitwarden
plugins/bitwarden/help.md
plugins/bitwarden/plugin.spec.yaml
plugins/bitwarden/setup.py

[[Bitwarden] Refresh SDK and update plugin spec with correct vendor API version](https://rapid7.atlassian.net/browse/SOAR-17462)
- Use the latest SDK version.
- Correct the specified supported product version in help docs. 
- Will run workflow on staging to ensure all actions still pass using latest SDK. 
-  …

[SOAR-17462] Bump SDK version and correct specified product version in help docs. 

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/Dockerfile
plugins/sentinelone/bin/komand_sentinelone
plugins/sentinelone/help.md
plugins/sentinelone/komand_sentinelone/connection/connection.py
plugins/sentinelone/plugin.spec.yaml
plugins/sentinelone/setup.py

- Add connection test for task | update SDK
{
"body": {
"log": "Connect: Connecting...\nrapid7/SentinelOne:11.1.0. Step name: create_query\nRunning a connection test to Sentinelone...\nThe connection test to Sentinelone for activities_logs was successful.\nThe connection test to Sentinelone for events_logs has failed.\nThis failure was caused by: 'Invalid API Key'\nCheck your API Key\nThe connection test to Sentinelone for threats_logs was successful.\nThe connection test was successful for 2/3 event types.\n",
"meta": {},
"output": [
{
"success": true
},
"The connection test was successful for 2/3 event types.\nThe connection test to Sentinelone for activities_logs was successful.\nThe connection test to Sentinelone for events_logs has failed.\nThis failure …

[SOAR-17523] Sentinelone - Task Connection Test

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/actions/parse_tap_alert/action.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/requirements.txt

- Update dependancies for Snyk vulnerability …

[SOAR-17239] proofpoint tap

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/connection/connection.py
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py

Task connection test added for Salesforce, alongside bumping the SDK and performing a plugin refresh
- SDK Bump to 6.1.0 & Plugin Refresh
[Ticket](https://rapid7.atlassian.net/browse/SOAR-17319)
Tested valid and invalid inputs for each field on Postman to ensure the correct exception handling is in place:
- Successful Test
- Invalid Login URL
-Invalid Client ID
- Invalid Secret Key
- Invalid Username & or Password
- Invalid Security Token

[SOAR-17319] Salesforce Task Connection test & SDK Bump

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/Dockerfile
plugins/sentinelone/bin/komand_sentinelone
plugins/sentinelone/help.md
plugins/sentinelone/komand_sentinelone/connection/connection.py
plugins/sentinelone/plugin.spec.yaml
plugins/sentinelone/setup.py

* Add connection test for task
* Update test logs and version log
* Fix checksum
- Add connection test for task …

Sentinelone 11.1.0 Release

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/Dockerfile
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/connection/connection.py
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/icon_carbon_black_cloud/util/constants.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py

* First draft:
* Save point
* Successful connection test
* Fix unit test and add more error handling
* Try to patch get current time method
* Restore get current time & loop over each api call
* Restore unit test imports
* Add in cause assist for final exception
* Nvm, remove cause and assist
* Update error messaging
* Updates
* Suggested fixes
* Loggers everywhere
- …

Carbon Black Cloud 2.2.4 Release

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/util/api.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

Integration tests were failing due to the status code being returned as 500 and not 400. This was due to the output not being handled correctly (as it expected JSON but now returns an xml output) which is why a 500 status code is being returned. By changing the `data_location` to `RESPONSE.TEXT` it allows for other formats like xml to be handled (which is what was being returned in this case instead of JSON) 
[Ticket](https://rapid7.atlassian.net/browse/SOAR-17461)
- Updated Zoom API to handle exceptions better
- SDK Bump and Plugin Refresh
Tested the integration tests against debug mode and the test now works:
- ![image](https://github.com/user-attachments/assets/592155ba-7edd-4e73-8180-5c65ce684f9e)
- …

[SOAR-17461] Zoom Error Handling

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/util/api.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

Integration tests were failing due to the status code being returned as 500 and not 400. This was due to the output not being handled correctly (as it expected JSON but now returns an xml output) which is why a 500 status code is being returned. By changing the `data_location` to `RESPONSE.TEXT` it allows for other formats like xml to be handled (which is what was being returned in this case instead of JSON) 
[Ticket](https://rapid7.atlassian.net/browse/SOAR-17461)
- #2720 
- Updated Zoom API to handle exceptions better
- SDK Bump and Plugin Refresh
Tested via Postman and Debugger to ensure the changes in place will return the correct error code and message and the outcome matches those in the integration test (seen in #2720)
Tested in staging and the …

[SOAR-17461] Zoom 4.1.15 Release

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/connection/connection.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

Release of Okta 4.2.9
- SDK Bump to 6.0.1 & Plugin refresh
Original PR's: #2692 #2694 
[Ticket](https://rapid7.atlassian.net/browse/SOAR-17320)
Tested on staging to ensure each exception is his and the correct logs are returned.

[SOAR-17320] Okta 4.2.9 release

---

plugins/base64/.CHECKSUM
plugins/base64/Dockerfile
plugins/base64/plugin.spec.yaml

Base64 - Updated SDK to the latest version

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/schema.py
plugins/proofpoint_tap/komand_proofpoint_tap/actions/parse_tap_alert/action.py
plugins/proofpoint_tap/komand_proofpoint_tap/actions/parse_tap_alert/schema.py
plugins/proofpoint_tap/komand_proofpoint_tap/connection/connection.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/requirements.txt
plugins/proofpoint_tap/setup.py

- #2710 
- SDK Bump to 6.1.0
- #2709 
- Dependancies updated to address Snyk vulnerability
All tests have been tested (and can be seen in this [PR](https://github.com/rapid7/insightconnect-plugins/pull/2710))
Logs have also been checked to ensure there is no conflicts/issues

Proofpoint tap 4.1.10 release

---

plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py

- agent var referenced before initialise …

InsightAgent Quick Fix

---

plugins/base64/.CHECKSUM
plugins/base64/help.md
plugins/base64/plugin.spec.yaml

[SOAR-16977] Base64 - Initial updates for fedramp compliance | Updated SDK to the latest version

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/Dockerfile
plugins/rapid7_vulndb/bin/komand_rapid7_vulndb
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/komand_rapid7_vulndb/actions/get_content/action.py
plugins/rapid7_vulndb/komand_rapid7_vulndb/actions/search_db/action.py
plugins/rapid7_vulndb/komand_rapid7_vulndb/connection/connection.py
plugins/rapid7_vulndb/plugin.spec.yaml
plugins/rapid7_vulndb/requirements.txt
plugins/rapid7_vulndb/setup.py
plugins/rapid7_vulndb/unit_test/mock.py
plugins/rapid7_vulndb/unit_test/payloads/get_content.json.resp
plugins/rapid7_vulndb/unit_test/payloads/get_content_bad.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_metasploit.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_metasploit_page_0.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_nexpose.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_nexpose_page_0.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_no_results.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_page_0.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_page_1.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_result.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_3.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_4.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_5.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_6.json.resp
plugins/rapid7_vulndb/unit_test/test_get_content.py
plugins/rapid7_vulndb/unit_test/test_search_db.py
plugins/rapid7_vulndb/unit_test/util.py

[SOAR-16970] Rapid7 Vulndb - Initial updates for fedramp compliance | Updated SDK to the latest version

---

plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/komand_okta/util/api.py

Okta change error handling

---

plugins/okta/komand_okta/util/api.py

Okta | Change PluginException to APIException

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/komand_okta/util/api.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

Okta 4.2.10 (#2728)

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/connection/connection.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py
plugins/rapid7_insightvm/unit_test/test_asset_vulnerability_solution.py
plugins/rapid7_insightvm/unit_test/test_async_requests.py
plugins/rapid7_insightvm/unit_test/test_convert_date_to_iso8601.py
plugins/rapid7_insightvm/unit_test/test_create_exception.py
plugins/rapid7_insightvm/unit_test/test_delete_asset.py
plugins/rapid7_insightvm/unit_test/test_generate_adhoc_sql_report.py
plugins/rapid7_insightvm/unit_test/test_get_asset.py
plugins/rapid7_insightvm/unit_test/test_get_asset_software.py
plugins/rapid7_insightvm/unit_test/test_get_asset_vulnerabilities.py
plugins/rapid7_insightvm/unit_test/test_get_expiring_vulnerability_exceptions.py
plugins/rapid7_insightvm/unit_test/test_list_inactive_assets.py
plugins/rapid7_insightvm/unit_test/test_list_reports.py
plugins/rapid7_insightvm/unit_test/test_new_scans.py
plugins/rapid7_insightvm/unit_test/test_resource_requests.py
plugins/rapid7_insightvm/unit_test/test_scan.py
plugins/rapid7_insightvm/unit_test/test_tag_assets.py
plugins/rapid7_insightvm/unit_test/test_update_shared_credential.py
plugins/rapid7_insightvm/unit_test/test_update_site_excluded_targets.py
plugins/rapid7_insightvm/unit_test/test_update_site_included_targets.py
plugins/rapid7_insightvm/unit_test/test_update_vulnerability_exception_expiration_date.py
plugins/rapid7_insightvm/unit_test/test_validate_user.py
plugins/rapid7_insightvm/unit_test/util.py

[SOAR-16969] InsightVM - Initial updates for fedramp compliance | Updated SDK to the latest version

---

plugins/jira/.CHECKSUM
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/connection/connection.py
plugins/jira/plugin.spec.yaml
plugins/jira/setup.py

- To raise an error if the user is trying to connect to a jira on prem instance from icon cloud 
testing using postam 
setting env var to cloud and using an non jira url 
setting env var to cloud and using  a  jira url 
when not using the env var both jira and none jira links work 
note (we dont have an on prem instance to test with, so just testing that we pass that check is the best we can test)
running an action will also fail, if trying to use an on-prem instance from cloud 
If you are an …

[SOAR-17400] - Jira - Adding an error if trying to use Jira on-prem on ICON cloud

---

plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/new_exception_request/trigger.py

- `New Exception Request`: Refactored the trigger …

[SOAR-16969] InsightVM - New Exception Request: Refactored the trigger

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/Dockerfile
plugins/rapid7_vulndb/bin/komand_rapid7_vulndb
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/komand_rapid7_vulndb/actions/get_content/action.py
plugins/rapid7_vulndb/komand_rapid7_vulndb/actions/search_db/action.py
plugins/rapid7_vulndb/komand_rapid7_vulndb/connection/connection.py
plugins/rapid7_vulndb/plugin.spec.yaml
plugins/rapid7_vulndb/requirements.txt
plugins/rapid7_vulndb/setup.py
plugins/rapid7_vulndb/unit_test/mock.py
plugins/rapid7_vulndb/unit_test/payloads/get_content.json.resp
plugins/rapid7_vulndb/unit_test/payloads/get_content_bad.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_metasploit.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_metasploit_page_0.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_nexpose.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_nexpose_page_0.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_no_results.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_page_0.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_page_1.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_result.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_3.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_4.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_5.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_6.json.resp
plugins/rapid7_vulndb/unit_test/test_get_content.py
plugins/rapid7_vulndb/unit_test/test_search_db.py
plugins/rapid7_vulndb/unit_test/util.py

[SOAR-16970] Rapid7 Vulndb - Initial updates for fedramp compliance | Updated SDK to the latest version (#2734)

---

plugins/rapid7_vulndb/requirements.txt

- Removed core packages from requirements …

[SOAR-16970] Rapid7 Vulndb - Removed core packages from requirements

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/new_exception_request/trigger.py
plugins/rapid7_insightvm/plugin.spec.yaml

[SOAR-16969] InsightVM - Updated the changelog

---

plugins/ssh/.CHECKSUM
plugins/ssh/Dockerfile
plugins/ssh/bin/komand_ssh
plugins/ssh/help.md
plugins/ssh/komand_ssh/actions/run/action.py
plugins/ssh/komand_ssh/connection/connection.py
plugins/ssh/plugin.spec.yaml
plugins/ssh/requirements.txt
plugins/ssh/setup.py
plugins/ssh/unit_test/test_run.py

[SOAR-16976] SSH - Initial updates for fedramp compliance | Updated SDK to the latest version

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/connection/connection.py
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py

- https://rapid7.atlassian.net/browse/SOAR-17662
- Fix for leading/trailing whitespace in connection issue
- https://rapid7.atlassian.net/browse/SOAR-17657
- Explicitly set the query options request header to 2000
- This is already enforced by Salesforce API: `The default is 2,000; the minimum is 200, and the maximum is 2,000` - https://developer.salesforce.com/docs/atlas.en-us.250.0.api_rest.meta/api_rest/headers_queryoptions.htm
- However we want to explicitly set it incase the API limit changes in future, and we inadvertently exceed the max limit (7,500) that can be returned in a run, as 3 queries are run per task execution
Review our documentation on …

[SOAR-17657][SOAR-17662] - Salesforce query limit and strip whitespace from inputs

---

plugins/ssh/.CHECKSUM
plugins/ssh/plugin.spec.yaml

- Added fedramp flag set to true …

[SOAR-16976] SSH - Added fedramp flag set to true

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/komand_whois/connection/connection.py
plugins/whois/plugin.spec.yaml
plugins/whois/requirements.txt
plugins/whois/setup.py
plugins/whois/unit_test/inputs/address.json.inp
plugins/whois/unit_test/inputs/address_error.json.inp
plugins/whois/unit_test/inputs/domain.json.inp
plugins/whois/unit_test/inputs/domain_error.json.inp

[SOAR-16964] WHOIS - Initial updates for fedramp compliance | Updated SDK to the latest version

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/connection/connection.py
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py

- Merging PR https://github.com/rapid7/insightconnect-plugins/pull/2767
- Fix for leading/trailing whitespace in connection input
- Explicitly set query options request header to `2000`

[SOAR-17657][SOAR-17662] - Salesforce query limit and strip whitespace

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/bin/komand_sentinelone
plugins/sentinelone/help.md
plugins/sentinelone/komand_sentinelone/tasks/monitor_logs/task.py
plugins/sentinelone/plugin.spec.yaml
plugins/sentinelone/setup.py
plugins/sentinelone/unit_test/expected/monitor_logs_unexpected_timestamp.json.exp
plugins/sentinelone/unit_test/responses/monitor_logs_events_unexpected_timestamp.json.resp
plugins/sentinelone/unit_test/test_monitor_logs.py
plugins/sentinelone/unit_test/util.py

- Update to handle unexpected timestamps: https://rapid7.atlassian.net/jira/software/c/projects/SOAR/boards/1492?selectedIssue=SOAR-17697
* All actions/triggers shortcut `insight-plugin run -T all --debug …

[SOAR-17529] Sentinelone

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/komand_whois/connection/connection.py
plugins/whois/plugin.spec.yaml
plugins/whois/requirements.txt
plugins/whois/setup.py
plugins/whois/unit_test/inputs/address.json.inp
plugins/whois/unit_test/inputs/address_error.json.inp
plugins/whois/unit_test/inputs/domain.json.inp
plugins/whois/unit_test/inputs/domain_error.json.inp

[SOAR-16964] WHOIS - Initial updates for fedramp compliance | Updated SDK to the latest version (#2775)

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

- Add the fedramp true flag to the plugin spec
- bump the SDK to the latest version
https://rapid7.atlassian.net/browse/SOAR-16967
testing using the build packs locally the plugin builds correctly and the actions run as expected  
* Single action/trigger `insight-plugin run -T …

SOAR-16967-Adding fedramp ready flag to plugin

---

plugins/microsoft_atp/.CHECKSUM
plugins/microsoft_atp/Dockerfile
plugins/microsoft_atp/bin/komand_microsoft_atp
plugins/microsoft_atp/help.md
plugins/microsoft_atp/komand_microsoft_atp/connection/connection.py
plugins/microsoft_atp/komand_microsoft_atp/connection/schema.py
plugins/microsoft_atp/komand_microsoft_atp/util/api.py
plugins/microsoft_atp/plugin.spec.yaml
plugins/microsoft_atp/setup.py
plugins/microsoft_atp/unit_test/util.py

- Bumping the SDK version
-  adding the fedramp true flag to the plugin spec 
testing locally the image can be built with build packs and actions run as expected  …

SOAR-17414-Adding fedramp ready flag to plugin

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py

- Update for FedRAMP compliance
- Update SDK …

[SOAR-17411] Duo Admin

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/connection/connection.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py

- Fix for task connection test 
- Remove trailing/leading whitespace from connection input values
Tested locally with trailing/leading whitespace in the task body resulted in a successful test
```
{
"body": {
"log": "The connection test to Mimecast was successful",
"meta": {},
"output": {
"success": true
},
"status": "ok"
},
"type": "task_event",
"version": "v1"
}
```

[SOAR-17732] - Fix task connection test

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py

* Update Fedramp | Update SDK
* Update SDK
- FedRAMP toggle on …

Duo Admin 5.0.1 Release

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/connection/connection.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py

- Merging PR to master - https://github.com/rapid7/insightconnect-plugins/pull/2799
- Fix for broken task connection test & trim whitespace from connection inputs
- https://rapid7.atlassian.net/browse/SOAR-17732
- Mimecast integration rolled over to new version successfully (on staging)
- Connection tests pass locally (will be tested again in Prod EA)

Mimecast 5.3.18 Release

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/asset_search/schema.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_asset/schema.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py

- Update schema to modify required fields that are not always present in results for `Asset Search` and `Get Asset`
https://rapid7.atlassian.net/browse/SOAR-17728 …

[SOAR-17729] Rapid7 InsightVM Cloud

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

- Update task error handling to resolve permissions issues with version subscription to Zoom and runtime errors …

[SOAR-17735] Zoom - error handling

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/asset_search/schema.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_asset/schema.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py

* Update SDK | Update output schema for asset and asset_vulnerability
- Update SDK | Update required output fields
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` …

Rapid7 InsightVM Cloud 8.0.0 Release

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

* Init
* Unit tests | Update error raised
* Lint | Update SDK
* Version update
- Update error handling to collect all exceptions and return in the task.error | Update SDK …

Zoom 4.1.16 Release

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/Dockerfile
plugins/microsoft_teams/bin/icon_microsoft_teams
plugins/microsoft_teams/help.md
plugins/microsoft_teams/icon_microsoft_teams/connection/connection.py
plugins/microsoft_teams/icon_microsoft_teams/connection/schema.py
plugins/microsoft_teams/icon_microsoft_teams/triggers/new_message_received/trigger.py
plugins/microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
plugins/microsoft_teams/icon_microsoft_teams/util/teams_utils.py
plugins/microsoft_teams/plugin.spec.yaml
plugins/microsoft_teams/requirements.txt
plugins/microsoft_teams/setup.py
plugins/microsoft_teams/unit_test/test_new_message_received.py
plugins/microsoft_teams/unit_test/util.py

https://rapid7.atlassian.net/browse/SOAR-17409
- Adding the fedramp true flag
- Adding in a option for the user to select what endpoints they want to connect to, normal, gcc, gcc high and MoD
- Bumping the SDK to version 6.1.2
- Bumping the version of zipp used to address a snyk issue 
The unit tests have been updated to now include the resource url
Testing has been done locally with both actions and triggers and all works as expected
If you are an InsightConnect customer or have access to an …

[Soar 17409] - Microsoft Teams - Adding fedramp true flag

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/Dockerfile
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

[SOAR-16975] ServiceNow - Initial updates for fedramp compliance | Updated SDK to the latest version

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/plugin.spec.yaml

Update cloud enabled

---

plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/monitor_alerts/task.py

Reset offsets when changing lookback

---

plugins/domaintools/.CHECKSUM
plugins/domaintools/Dockerfile
plugins/domaintools/bin/komand_domaintools
plugins/domaintools/help.md
plugins/domaintools/plugin.spec.yaml
plugins/domaintools/requirements.txt
plugins/domaintools/setup.py

Addressing the High and Moderate Synk vulnerabilities within the Domain Tools Plugin. I checked to see what is the most recent version of the outdated packages which are causing the problem and bumped and tested them.
Snyk Issue: https://app.snyk.io/org/soar-insightconnect-new/project/0669246a-5a1c-4f3a-9ce3-5bd4848f9fba
Ticket: https://rapid7.atlassian.net/browse/SOAR-17752
- SDK Bump to 6.1.2 & Plugin Refresh
- Bump `anyio` and `zipp` in requirements.txt to resolve snyk issues.
I ran snyk internally and the vulnerabilities have been addressed. To ensure there was no issues with the bumped requirements I ran a few actions via Postman and they pass as expected.
Snyk:

[SOAR-17752] Domain Tools -  Addressing Snyk Vulnerabilities

---

plugins/domaintools/.CHECKSUM
plugins/domaintools/Dockerfile
plugins/domaintools/bin/komand_domaintools
plugins/domaintools/help.md
plugins/domaintools/plugin.spec.yaml
plugins/domaintools/requirements.txt
plugins/domaintools/setup.py

Bumping Packages to resolve Snyk vulnerability and SDK Bump
Original PR: 
- #2813 
- SDK Bump to 6.1.2 and Plugin Refresh
- Bumping anyio and zipp to resolve Snyk Vulnerabilities
Tested on staging (and locally prior to merging to develop) and all actions pass.

[SOAR-17752] Domain Tools 2.0.3 Release

---

plugins/cisco_firepower_management_center/.CHECKSUM
plugins/cisco_firepower_management_center/Dockerfile
plugins/cisco_firepower_management_center/bin/icon_cisco_firepower_management_center
plugins/cisco_firepower_management_center/help.md
plugins/cisco_firepower_management_center/plugin.spec.yaml
plugins/cisco_firepower_management_center/requirements.txt
plugins/cisco_firepower_management_center/setup.py

Bumped `cryptography` package in order to resolve the snyk vulnerabilities. Bumped the SDK to 6.1.2 and performed a plugin refresh.
- #2816 
- SDK Bump to 6.1.2 & Plugin Refresh
- Bumped `cryptography`
Tested it locally via Postman and the test pass as expected (In [Original PR](https://github.com/rapid7/insightconnect-plugins/pull/2816))

[SOAR-17751] Cisco Firepower Management Center 2.1.3 Release

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/Dockerfile
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

[SOAR-16975] ServiceNow - Initial updates for fedramp compliance | Updated SDK to the latest version (#2807)

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/connection/connection.py
plugins/okta/plugin.spec.yaml
plugins/okta/requirements.txt
plugins/okta/setup.py
plugins/okta/unit_test/test_add_user_to_group.py
plugins/okta/unit_test/test_assign_user_to_app_sso.py
plugins/okta/unit_test/test_create_user.py
plugins/okta/unit_test/test_deactivate_user.py
plugins/okta/unit_test/test_delete_user.py
plugins/okta/unit_test/test_get_factors.py
plugins/okta/unit_test/test_get_user.py
plugins/okta/unit_test/test_get_user_groups.py
plugins/okta/unit_test/test_list_groups.py
plugins/okta/unit_test/test_monitor_logs.py
plugins/okta/unit_test/test_remove_user_from_group.py
plugins/okta/unit_test/test_reset_factors.py
plugins/okta/unit_test/test_reset_password.py
plugins/okta/unit_test/test_send_push.py
plugins/okta/unit_test/test_suspend_user.py
plugins/okta/unit_test/test_unsuspend_user.py
plugins/okta/unit_test/test_update_blacklist_zones.py
plugins/okta/unit_test/test_users_added_removed_from_group.py
plugins/okta/unit_test/util.py

[SOAR-17410] Okta - Initial updates for fedramp compliance | Updated SDK to the latest version

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/Dockerfile
plugins/microsoft_teams/plugin.spec.yaml

- bumping SDK used to 6.13
* All …

[SOAR-17409] - Microsoft teams - Bumping SDK to latest

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/icon_python_3_script/connection/connection.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

Release Python 3 Script - Initial updates for fedramp compliance | Updated SDK to the latest version

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/Dockerfile
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/monitor_alerts/task.py
plugins/palo_alto_cortex_xdr/plugin.spec.yaml

- Add more logging when on final page of pagination
- Fix bug where start time was moving along before finishing paginating
- Refactor deduping logic
* All actions/triggers shortcut `insight-plugin run -T all …

Palo Alto | Fix start time moving bug, Refactor dedupe logic

---

plugins/rapid7_insightappsec/.CHECKSUM
plugins/rapid7_insightappsec/Dockerfile
plugins/rapid7_insightappsec/bin/komand_rapid7_insightappsec
plugins/rapid7_insightappsec/help.md
plugins/rapid7_insightappsec/komand_rapid7_insightappsec/util/endpoints.py
plugins/rapid7_insightappsec/plugin.spec.yaml
plugins/rapid7_insightappsec/setup.py

* Init
* help.md
- Update SDK
- Update Create Scan Config to remove 404 bug …

rapid7_insightappsec 1.2.2 Release

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
plugins/palo_alto_cortex_xdr/help.md
plugins/palo_alto_cortex_xdr/plugin.spec.yaml
plugins/palo_alto_cortex_xdr/setup.py

- Update version to 4.0.1
* All …

Palo Alto | Update version to 4.0.1

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
plugins/palo_alto_cortex_xdr/help.md
plugins/palo_alto_cortex_xdr/plugin.spec.yaml
plugins/palo_alto_cortex_xdr/setup.py

Palo Alto Cortex XDR 4.0.1 | Release

---

plugins/abnormal_security/.CHECKSUM
plugins/abnormal_security/Dockerfile
plugins/abnormal_security/bin/icon_abnormal_security
plugins/abnormal_security/help.md
plugins/abnormal_security/icon_abnormal_security/actions/get_case_details/action.py
plugins/abnormal_security/icon_abnormal_security/actions/get_cases/action.py
plugins/abnormal_security/plugin.spec.yaml
plugins/abnormal_security/setup.py

Release of Abnormal Security 2.0.3
This will address the customer issue regarding the CaseID being returned and set as an integer despite it meaning to be a string.
- #2751 
- [SI Ticket](https://rapid7.atlassian.net/browse/SI-25434)
Changes:
- Converted CaseID to string before receiving and sending
- SDK Bump to 6.1.3 & Plugin refresh
Provided the customer a custom plugin of the changes within this PR and it resolved their issue.

[SOAR-17793] Abnormal Security 2.0.3 Release

---

plugins/subnet/plugin.spec.yaml

Subnet - 17807 - Added fedramp flag

---

plugins/extractit/.CHECKSUM
plugins/extractit/Dockerfile
plugins/extractit/bin/icon_extractit
plugins/extractit/help.md
plugins/extractit/plugin.spec.yaml
plugins/extractit/requirements.txt
plugins/extractit/setup.py

[SOAR-17802] ExtractIt - Initial updates for fedramp compliance | Updated SDK to the latest version

---

plugins/subnet/.CHECKSUM

[SOAR-17807] Subnet - Updated checksum

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/Dockerfile
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py

Bumps SDK for carbonblackcloud
- …

Noticket bump sdk carbonblackcloud

---

plugins/pdf_generator/.CHECKSUM
plugins/pdf_generator/Dockerfile
plugins/pdf_generator/bin/icon_pdf_generator
plugins/pdf_generator/help.md
plugins/pdf_generator/plugin.spec.yaml
plugins/pdf_generator/requirements.txt
plugins/pdf_generator/setup.py

[Addressing Snyk vulnerabilities in pdf_generator plugin:](https://app.snyk.io/org/soar-insightconnect-new/project/5cd470bf-4f90-4842-ba9e-0e095a0f6a6a), and bumping the SDK and performing a plugin refresh.
Ticket: https://rapid7.atlassian.net/browse/SOAR-17935
- Bumping `Pillow` to 10.3.0 (Snyk Vulnerability patch)
Ran snyk internally and the prior vulnerabiltiies are no longer showing:
Ran the action to ensure the SDK bump did not conflict and the action ran successfully:

[SOAR-17935] Snyk Vulnerabilities in pdf_generator

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/Dockerfile
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py

Bump SDK Carbonblackcloud (#2869)

---

plugins/pdf_generator/.CHECKSUM
plugins/pdf_generator/Dockerfile
plugins/pdf_generator/bin/icon_pdf_generator
plugins/pdf_generator/help.md
plugins/pdf_generator/plugin.spec.yaml
plugins/pdf_generator/requirements.txt
plugins/pdf_generator/setup.py

[Addressing Snyk vulnerabilities in pdf_generator plugin:](https://app.snyk.io/org/soar-insightconnect-new/project/5cd470bf-4f90-4842-ba9e-0e095a0f6a6a), and bumping the SDK and performing a plugin refresh.
Ticket: https://rapid7.atlassian.net/browse/SOAR-17935
- #2867 
- Bumping `Pillow` in requirements.txt
Alongside the testing carried out in the original PR, I tested on staging and the action passes.

[SOAR-17935] pdf_generator 1.0.6 Release

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/plugin.spec.yaml

[SOAR-17899] Python 3 Script - Bumped SDK version

---

plugins/extractit/.CHECKSUM
plugins/extractit/Dockerfile
plugins/extractit/bin/icon_extractit
plugins/extractit/help.md
plugins/extractit/plugin.spec.yaml
plugins/extractit/requirements.txt
plugins/extractit/setup.py

Release [SOAR-17802] ExtractIt - Initial updates for fedramp compliance | Updated SDK to the latest version (#2846)

---

plugins/python_3_script/icon_python_3_script/actions/run/action.py

- Updated timeout error message …

[SOAR-17899] Python 3 Script - Updated timeout error message

---

.github/workflows/black.yml
.github/workflows/main.yml
.github/workflows/plugin_production_build.yml
.github/workflows/plugin_staging_build.yml
.github/workflows/prospector.yml
.github/workflows/unit_test.yml

bump gha python version (#2880)

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/inputs/connection_retry_request.json.inp
plugins/salesforce/unit_test/responses/retry_request.json.resp
plugins/salesforce/unit_test/test_connection.py
plugins/salesforce/unit_test/util.py

[SOAR-17915] Salesforce 2.1.11 Release

---

plugins/rdap/.CHECKSUM
plugins/rdap/Dockerfile
plugins/rdap/bin/icon_rdap
plugins/rdap/help.md
plugins/rdap/plugin.spec.yaml
plugins/rdap/requirements.txt
plugins/rdap/setup.py

Addressing snyk vuln and bumping SDK
- #2886 
- SDK to 6.1.4
- Bumping requirements to resolve snyk vuln

[SOAR-17996] rdap 2.0.3 Release

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/asset_search/schema.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml

- Updated size parameter description …

[PLGN-840] InsightVM Cloud - Updated size parameter description

---

plugins/cylance_protect/.CHECKSUM
plugins/cylance_protect/Dockerfile
plugins/cylance_protect/help.md
plugins/cylance_protect/plugin.spec.yaml
plugins/cylance_protect/requirements.txt

Ticket: https://rapid7.atlassian.net/browse/SOAR-18032
PR to address [snyk vulnerabilities](https://app.snyk.io/org/soar-insightconnect-new/project/9323440b-99c2-4671-8d49-6f50e1a25c95) and SDK bump
- Bumping requirements.txt (snyk vulns)
Ran snyk locally after resolving the vulnerability and it now passes:

[SOAR-18032] Cylance Protect - Snyk and SDK bump

---

plugins/cylance_protect/.CHECKSUM
plugins/cylance_protect/Dockerfile
plugins/cylance_protect/help.md
plugins/cylance_protect/plugin.spec.yaml
plugins/cylance_protect/requirements.txt

Ticket: https://rapid7.atlassian.net/browse/SOAR-18032
Snyk: https://app.snyk.io/org/soar-insightconnect-new/project/9323440b-99c2-4671-8d49-6f50e1a25c95
- #2912 
- Bumped requirements.txt

[SOAR-18032] Cylance Protect 1.5.3 Release

---

plugins/cylance_protect/.CHECKSUM
plugins/cylance_protect/bin/icon_cylance_protect
plugins/cylance_protect/help.md
plugins/cylance_protect/plugin.spec.yaml
plugins/cylance_protect/setup.py

Changing API Docs referenced in help.md 
- #2913
- Changing API Doc linked in reference

[NO-TICKET] Cylance Protect - Change reference

---

plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/unit_test/responses/first_observations_within_window.json.resp
plugins/carbon_black_cloud/unit_test/responses/task_test_data.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py

Updates the task to ensure that in cases where the observations are provided before the start of the query window, we will successfully move forward rather than get stuck in a loop

[Carbon Black Cloud] Additional Edgecase Fix

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/new_exception_request/trigger.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/util/util.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py

- Trigger: `New Exception Request` - Added retry mechanism …

[SOAR-17939] InsightVM - Trigger: New Exception Request - Added retry mechanism

---

plugins/broadcom_symantec_endpoint_protection/.CHECKSUM
plugins/broadcom_symantec_endpoint_protection/Dockerfile
plugins/broadcom_symantec_endpoint_protection/bin/icon_broadcom_symantec_endpoint_protection
plugins/broadcom_symantec_endpoint_protection/help.md
plugins/broadcom_symantec_endpoint_protection/plugin.spec.yaml
plugins/broadcom_symantec_endpoint_protection/requirements.txt
plugins/broadcom_symantec_endpoint_protection/setup.py

Ticket: https://rapid7.atlassian.net/browse/SOAR-17936
Addressing [snyk vulnerabilities](https://app.snyk.io/org/soar-insightconnect-new/project/3cf527aa-3c43-47db-9461-322185e08804) in Broadcom, as well as bumping the SDK and plugin refresh
Tested all unit tests and they pass as expected:
Ran snyk locally after resolving the vulnerabilities and it now passes:

[SOAR-17936] Broadcom Symantec Endpoint Protection - Snyk vulnerabilities and SDK Bump

---

plugins/broadcom_symantec_endpoint_protection/.CHECKSUM
plugins/broadcom_symantec_endpoint_protection/Dockerfile
plugins/broadcom_symantec_endpoint_protection/bin/icon_broadcom_symantec_endpoint_protection
plugins/broadcom_symantec_endpoint_protection/help.md
plugins/broadcom_symantec_endpoint_protection/plugin.spec.yaml
plugins/broadcom_symantec_endpoint_protection/requirements.txt
plugins/broadcom_symantec_endpoint_protection/setup.py

Ticket: https://rapid7.atlassian.net/browse/SOAR-17936
Snyk: https://app.snyk.io/org/soar-insightconnect-new/project/3cf527aa-3c43-47db-9461-322185e08804
- #2919 
- Bumped requirements.txt

[SOAR-17936] Broadcom Symantec Endpoint Protection 2.0.1 Release

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/bin/icon_powershell
plugins/powershell/help.md
plugins/powershell/plugin.spec.yaml
plugins/powershell/requirements.txt
plugins/powershell/setup.py

Ticket: https://rapid7.atlassian.net/browse/SOAR-17954
Snyk: https://app.snyk.io/org/soar-insightconnect-new/project/e914542e-fa84-4dcf-a00e-1cf638b8846e
Snyk validator is an ongoing issue (trouble installing github package on python 3.9) although this PR will cover the vulns but currently it won't pick up the snyk changes: https://rapid7.atlassian.net/browse/SOAR-17972
- #2879 
- Bumped requirements.txt

[SOAR-17954] Powershell 3.0.5 Release

---

plugins/crowdstrike_falcon_intelligence/.CHECKSUM
plugins/crowdstrike_falcon_intelligence/Dockerfile
plugins/crowdstrike_falcon_intelligence/help.md
plugins/crowdstrike_falcon_intelligence/icon_crowdstrike_falcon_intelligence/actions/uploadMalwareSample/action.py
plugins/crowdstrike_falcon_intelligence/icon_crowdstrike_falcon_intelligence/actions/uploadMalwareSample/schema.py
plugins/crowdstrike_falcon_intelligence/icon_crowdstrike_falcon_intelligence/util/api.py
plugins/crowdstrike_falcon_intelligence/plugin.spec.yaml

[SOAR-16877] Crowdstrike Falcon Intelligence - Updated action schema

---

plugins/gitlab/.CHECKSUM
plugins/gitlab/Dockerfile
plugins/gitlab/bin/icon_gitlab
plugins/gitlab/help.md
plugins/gitlab/plugin.spec.yaml
plugins/gitlab/requirements.txt
plugins/gitlab/setup.py

Ticket: https://rapid7.atlassian.net/browse/SOAR-18169
Addressing [snyk vulnerability](https://app.snyk.io/org/soar-insightconnect-new/project/422c86cb-2591-4e5a-b41d-ef5cdec69330) in gitlab, as well as bumping the SDK and plugin refresh
- Removing `requests` from requirements.txt (included in SDK and caused Snyk vuln)
- SDK Bump to 6.2.0
Snyk locally passes:

[SOAR-18169] Gitlab - Snyk Vulnerability and SDK Bump

---

plugins/gitlab/.CHECKSUM
plugins/gitlab/Dockerfile
plugins/gitlab/bin/icon_gitlab
plugins/gitlab/help.md
plugins/gitlab/plugin.spec.yaml
plugins/gitlab/requirements.txt
plugins/gitlab/setup.py

Ticket: https://rapid7.atlassian.net/browse/SOAR-18169
Snyk: https://app.snyk.io/org/soar-insightconnect-new/project/cb0a7eee-6799-4d30-bfe2-3d9527260086
- #2946 
- SDK Bump to 6.2.0
- Removing `requests` from requirements.txt (included in SDK, caused Snyk vuln)

[SOAR-18169] Gitlab 2.0.1 Release

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/komand_mimecast/util/constants.py
plugins/mimecast/komand_mimecast/util/exceptions.py
plugins/mimecast/komand_mimecast/util/util.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

Update 429 error handling
---------
- …

Mimecast 5.3.19 Release

---

plugins/broadcom_symantec_endpoint_protection/.CHECKSUM
plugins/broadcom_symantec_endpoint_protection/Dockerfile
plugins/broadcom_symantec_endpoint_protection/bin/icon_broadcom_symantec_endpoint_protection
plugins/broadcom_symantec_endpoint_protection/help.md
plugins/broadcom_symantec_endpoint_protection/plugin.spec.yaml
plugins/broadcom_symantec_endpoint_protection/requirements.txt
plugins/broadcom_symantec_endpoint_protection/setup.py

Addressing [Snyk Vulnerabilities](https://app.snyk.io/org/soar-insightconnect-new/project/3cf527aa-3c43-47db-9461-322185e08804)
- Bumping requirements.txt (Snyk)
- SDK Bump to 6.2.0
No vulnerabilities after bumping `aiohttp`:
Ran locally and they all pass:

[SOAR-18245] Broadcom Symantec Endpoint Protection - Snyk vulnerabilities and SDK Bump

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py

Addressing [Snyk Vulnerabilities](https://app.snyk.io/org/soar-insightconnect-new/project/39425795-4986-4da1-85c8-ed8be28cd78b)
- SDK Bump to 6.2.0
No vulnerabilities show after bumping requirements.txt
Tested locally and they all pass:

[SOAR-18246] Rapid7 InsightVM - Snyk Vulnerabilities and SDK Bump

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py

Addressing [Snyk Vulnerabilities](https://app.snyk.io/org/soar-insightconnect-new/project/39425795-4986-4da1-85c8-ed8be28cd78b)
- #2968 
- SDK bump 6.2.0

Rapid7 InsightIVM 8.0.7 Release

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/responses/task_test_data.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py

https://rapid7.atlassian.net/browse/SOAR-18272
- To add an check to ensure that if the link times out and we have not collected any data then we will keep the timestamp the same and not move it forward
* All …

Carbon black hotfix

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/responses/task_test_data.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py

Release PR for 
https://rapid7.atlassian.net/browse/SOAR-18272
- https://github.com/rapid7/insightconnect-plugins/pull/2975
- To add an check to ensure that if the link times out and we have not collected any data then we will keep the timestamp the same and not move it forward

Carbon Black cloud 2.2.9 release

---

plugins/greynoise/.CHECKSUM
plugins/greynoise/Dockerfile
plugins/greynoise/plugin.spec.yaml
plugins/greynoise/unit_test/payloads/similar_ip.json
plugins/greynoise/unit_test/payloads/timeline_ip.json
plugins/greynoise/unit_test/test_community_lookup.py
plugins/greynoise/unit_test/test_context_lookup.py
plugins/greynoise/unit_test/test_get_tag_details.py
plugins/greynoise/unit_test/test_gnql_query.py
plugins/greynoise/unit_test/test_quick_lookup.py
plugins/greynoise/unit_test/test_riot_lookup.py
plugins/greynoise/unit_test/test_similar_lookup.py
plugins/greynoise/unit_test/test_timeline_lookup.py
plugins/greynoise/unit_test/test_vulnerability_lookup.py

- Fix broken unit tests
- Update SDK …

Greynoise unit test fix

---

plugins/greynoise/.CHECKSUM
plugins/greynoise/plugin.spec.yaml

- Make greynoise cloud enabled
* …

Cloud eenable greynoise

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_investigations/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py

Addressing [Snyk Vulnerability](https://app.snyk.io/org/soar-insightconnect-new/project/6af2af72-6825-4014-90d0-83cfa8ae699e) within `aiohttp` package.
- Bumping requirements.txt (Snyk Vulnerability)

[SOAR-18442] Rapid7 InsightIDR Snyk Vulnerability and SDK Bump

---

plugins/broadcom_symantec_endpoint_protection/.CHECKSUM
plugins/broadcom_symantec_endpoint_protection/Dockerfile
plugins/broadcom_symantec_endpoint_protection/bin/icon_broadcom_symantec_endpoint_protection
plugins/broadcom_symantec_endpoint_protection/help.md
plugins/broadcom_symantec_endpoint_protection/plugin.spec.yaml
plugins/broadcom_symantec_endpoint_protection/requirements.txt
plugins/broadcom_symantec_endpoint_protection/setup.py

Addressing [Snyk Vulnerability](https://app.snyk.io/org/soar-insightconnect-new/project/3cf527aa-3c43-47db-9461-322185e08804) within `aiohttp` package
- Bumping requirements.txt (Snyk Vulnerability)

[SOAR-18441] Broadcom Symantec Endpoint Protection Snyk Vulnerability and SDK Bump

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_investigations/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py

Resolving Snyk vuln whilst updating SDK and plugin spec
- #2989 
- Bumping requirements.txt (snyk vuln)
- Updating `list_investigations` descriptions in `help.md`/`plugin.spec`

[SOAR-18442] Rapid7 InsightIDR 10.3.4 Release

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py

Bumping requirements.txt to address snyk vuln
- #2988 
- Bumping requirements.txt (snyk vuln)

[SOAR-18441] Rapid7 InsightVM 8.0.8 Release

---

plugins/broadcom_symantec_endpoint_protection/.CHECKSUM
plugins/broadcom_symantec_endpoint_protection/Dockerfile
plugins/broadcom_symantec_endpoint_protection/bin/icon_broadcom_symantec_endpoint_protection
plugins/broadcom_symantec_endpoint_protection/help.md
plugins/broadcom_symantec_endpoint_protection/plugin.spec.yaml
plugins/broadcom_symantec_endpoint_protection/requirements.txt
plugins/broadcom_symantec_endpoint_protection/setup.py

Bumping package in requirements.txt to resolve snyk vuln
- #2987 
- Bumping requirements.txt (snyk vuln)

[SOAR-18441] Broadcom Symantec Endpoint Protection 2.0.3 Release

---

plugins/base64/.CHECKSUM
plugins/base64/Dockerfile
plugins/base64/bin/komand_base64
plugins/base64/help.md
plugins/base64/plugin.spec.yaml
plugins/base64/setup.py

Changes: Bump to latest SDK. 
Original PR: #2996

Base64 Release v1.1.8

---

plugins/string/.CHECKSUM
plugins/string/Dockerfile
plugins/string/bin/komand_string
plugins/string/help.md
plugins/string/plugin.spec.yaml
plugins/string/setup.py

Part of a long list of plugins being bumped to latest SDK.

[string] SOAR-18473: bump SDK and address vulnerabilities

---

plugins/rdap/.CHECKSUM
plugins/rdap/Dockerfile
plugins/rdap/bin/icon_rdap
plugins/rdap/help.md
plugins/rdap/plugin.spec.yaml
plugins/rdap/setup.py

[SOAR-18473] RDAP 2.0.4 Release (fedRAMP)

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

[SOAR-18473] Okta fedRAMP, SDK bump and vuln

---

plugins/math/.CHECKSUM
plugins/math/Dockerfile
plugins/math/bin/komand_math
plugins/math/help.md
plugins/math/plugin.spec.yaml
plugins/math/setup.py

[SOAR-18473] Math 1.2.3 Release (fedRAMP)

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py

Change to 3.0.2 for buildpacks to pick up latest changes

[SOAR-18473] Rapid7 Insight Agent -  fedRAMP

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/Dockerfile
plugins/rapid7_vulndb/bin/komand_rapid7_vulndb
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/plugin.spec.yaml
plugins/rapid7_vulndb/setup.py

[SOAR-18473] Rapid7 VulnDB - fedRAMP, SDK bump and vuln

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

Regarding [SI ticket](https://rapid7.atlassian.net/browse/SI-26849) on schema being formatted incorrectly (missing keys and keys being unaccessible from ICON via additional workflow actions)
-  #2995 
-   - Update schema for `advanced_query_on_log`, `advanced_query_on_log_set` & `query` to account for missing keys and invalid mapping
Trivy scan:

[SOAR-18495] Rapid7_InsightIDR 11.0.0 Release (Schema Fix)

---

plugins/microsoft_atp/.CHECKSUM
plugins/microsoft_atp/Dockerfile
plugins/microsoft_atp/bin/komand_microsoft_atp
plugins/microsoft_atp/help.md
plugins/microsoft_atp/plugin.spec.yaml
plugins/microsoft_atp/setup.py

Changes to bump to use the latest SDK and buildpack image.

[SOAR-18473] MS ATP

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py

[SOAR-18529] Insight IVM Cloud (fedRAMP), SDK Bump and vuln

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

Bump version for iVM to get the latest and greatest in build pipeline.

[SOAR-18525] bump to latest buildpack for IVM

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/plugin.spec.yaml

Update the plugin.spec to reflect the help.md
will be merged alongside #3015 
- Updating plugin.spec to be in sync with help.md

[SOAR-18529] Vuln DB (Plugin.spec to reflect help.md)

---

.github/workflows/unit_test.yml

- Updated `libssl` package from `1.1` to `3` due to latest ubuntu runner …

Updated libssl in unittests workflow

---

.github/workflows/unit_test.yml

- UPdated `libssl` package in unittests workflow from `1.1` to `3` …

Updated libssl in unittests workflow (#3038)

---

.github/CODEOWNERS

Add Codeowner File

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/schema.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

[SOAR-18473] Okta 4.1.12 Release (fedRAMP)

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/bin/icon_powershell
plugins/powershell/help.md
plugins/powershell/icon_powershell/connection/connection.py
plugins/powershell/plugin.spec.yaml
plugins/powershell/requirements.txt
plugins/powershell/setup.py

[SOAR-18586] Powershell - Updated dependencies | Updated SDK to the latest version

---

plugins/whois/.CHECKSUM
plugins/whois/help.md
plugins/whois/plugin.spec.yaml

- Update `plugin.spec` to be in sync with `help.md`
PR that has already been merged into develop:
- https://github.com/rapid7/insightconnect-plugins/pull/2997
**Validator is expected to fail due to Dockerfile having packages and the plugin being CloudReady**

[SOAR-18528] Whois plugin.spec (fedRAMP)

---

plugins/microsoft_atp/.CHECKSUM
plugins/microsoft_atp/Dockerfile
plugins/microsoft_atp/help.md
plugins/microsoft_atp/plugin.spec.yaml

Changes include:
- few missed references in the help.md that should be updated to point to the correct place.
- updated to latest SDK

SOAR-18525 - missed links in rename

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/help.md
plugins/powershell/plugin.spec.yaml

- Updated Dockerfile refresh in spec file
- Updated powershell version to 7.4.6 …

Powershell - 18586 - Updated Dockerfile refresh in spec file | Updated powershell version to 7.4.6

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/plugin.spec.yaml

- Removing -y flag in Plugin.spec due to Dockerfile template updates in tooling
PR to be merged into: https://github.com/rapid7/insightconnect-plugins/pull/3053

Whois removing -y

---

plugins/rapid7_insightcloudsec/.CHECKSUM
plugins/rapid7_insightcloudsec/Dockerfile
plugins/rapid7_insightcloudsec/help.md
plugins/rapid7_insightcloudsec/plugin.spec.yaml

Bumping SDK to the latest version.
This will be merged alongside the following PR: https://github.com/rapid7/insightconnect-plugins/pull/3019
- SDK Bump to 6.2.3

[SOAR-18570] Rapid7 InsightCloudSec SDK bump (6.2.3)

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/plugin.spec.yaml

Bumping SDK to latest version.
This will be cherry picked within the following release PR: https://github.com/rapid7/insightconnect-plugins/pull/3023
- SDK bump to 6.2.3

[SOAR-18570] Rapid7 Insight VM Cloud (SDK bump to 6.2.3)

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py

Bumping SDK to latest versions
Previous PR's:
- #3022 
- #3057 
- SDK bump to 6.2.3

[SOAR-18570] Insight VM Cloud 8.1.1 release

---

plugins/rapid7_insightcloudsec/.CHECKSUM
plugins/rapid7_insightcloudsec/Dockerfile
plugins/rapid7_insightcloudsec/bin/icon_rapid7_insightcloudsec
plugins/rapid7_insightcloudsec/help.md
plugins/rapid7_insightcloudsec/plugin.spec.yaml
plugins/rapid7_insightcloudsec/setup.py

SDK bump to the latest version
Previous PR's:
- #3019 
- #3056 
- SDK bump to 6.2.3

[SOAR-18570] Insight CloudSec 2.1.1 Release

---

plugins/mimecast_v2/icon_mimecast_v2/connection/connection.py
plugins/mimecast_v2/icon_mimecast_v2/tasks/monitor_siem_logs/task.py

- Fix connection test
- Fix custom config retrieving with no state …

Mimecast V2 - Fix connection test | Fix custom config

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/schema.py
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/inputs/connection_unsupported_grant.json.inp
plugins/salesforce/unit_test/responses/unsupported_grant_type.json.resp
plugins/salesforce/unit_test/test_connection.py
plugins/salesforce/unit_test/test_monitor_users.py
plugins/salesforce/unit_test/util.py

Release pr for 
https://github.com/rapid7/insightconnect-plugins/pull/3065
- https://rapid7.atlassian.net/browse/SOAR-18579
- If the user enters a URL that we cannot reach this info should be raised back to the end user in UI
- https://rapid7.atlassian.net/browse/SOAR-18230
- Adding a mapping for the unsupported_grant_type error

salesforce 2.1.13 release

---

plugins/joe_sandbox/.CHECKSUM
plugins/joe_sandbox/Dockerfile
plugins/joe_sandbox/bin/icon_joe_sandbox
plugins/joe_sandbox/help.md
plugins/joe_sandbox/icon_joe_sandbox/actions/get_submitted_info/action.py
plugins/joe_sandbox/icon_joe_sandbox/actions/submit_cookbook/action.py
plugins/joe_sandbox/icon_joe_sandbox/actions/submit_sample/action.py
plugins/joe_sandbox/icon_joe_sandbox/actions/submit_sample/schema.py
plugins/joe_sandbox/plugin.spec.yaml
plugins/joe_sandbox/setup.py
plugins/joe_sandbox/unit_test/mock.py
plugins/joe_sandbox/unit_test/responses/chunked_sample.json.resp
plugins/joe_sandbox/unit_test/responses/get_submitted_info.json.resp
plugins/joe_sandbox/unit_test/responses/submit_sample.json.resp
plugins/joe_sandbox/unit_test/test_get_submitted_info.py
plugins/joe_sandbox/unit_test/test_submit_cookbook.py
plugins/joe_sandbox/unit_test/test_submit_sample.py

https://rapid7.atlassian.net/browse/SOAR-18821
- Updated input parameters handling
- Bumped SDK

[SOAR-18821] Joe Sandbox issue with passing a sample

---

plugins/joe_sandbox/.CHECKSUM
plugins/joe_sandbox/Dockerfile
plugins/joe_sandbox/bin/icon_joe_sandbox
plugins/joe_sandbox/help.md
plugins/joe_sandbox/icon_joe_sandbox/actions/get_submitted_info/action.py
plugins/joe_sandbox/icon_joe_sandbox/actions/submit_cookbook/action.py
plugins/joe_sandbox/icon_joe_sandbox/actions/submit_sample/action.py
plugins/joe_sandbox/icon_joe_sandbox/actions/submit_sample/schema.py
plugins/joe_sandbox/plugin.spec.yaml
plugins/joe_sandbox/setup.py
plugins/joe_sandbox/unit_test/mock.py
plugins/joe_sandbox/unit_test/responses/chunked_sample.json.resp
plugins/joe_sandbox/unit_test/responses/get_submitted_info.json.resp
plugins/joe_sandbox/unit_test/responses/submit_sample.json.resp
plugins/joe_sandbox/unit_test/test_get_submitted_info.py
plugins/joe_sandbox/unit_test/test_submit_cookbook.py
plugins/joe_sandbox/unit_test/test_submit_sample.py

https://rapid7.atlassian.net/browse/SOAR-18821
- Updated input parameters handling
- Bumped SDK
PR of changes https://github.com/rapid7/insightconnect-plugins/pull/3077

Joe sandbox Plugin 3.0.0

---

plugins/cisco_firepower_management_center/.CHECKSUM
plugins/cisco_firepower_management_center/Dockerfile
plugins/cisco_firepower_management_center/bin/icon_cisco_firepower_management_center
plugins/cisco_firepower_management_center/help.md
plugins/cisco_firepower_management_center/plugin.spec.yaml
plugins/cisco_firepower_management_center/requirements.txt
plugins/cisco_firepower_management_center/setup.py

A  snyk vulnerability has came in regarding the `cryptography` package. This will bump it to resolve the vuln and to also update the SDK to the latest version.
This will resolve the following PR:
- https://github.com/rapid7/insightconnect-plugins/pull/3127
- Bumping `cryptography` package to latest version
- SDK bump to 6.2.4

[SOAR-18892] Cisco Firepower - Bump 'cryptography' package

---

plugins/cisco_firepower_management_center/.CHECKSUM
plugins/cisco_firepower_management_center/Dockerfile
plugins/cisco_firepower_management_center/bin/icon_cisco_firepower_management_center
plugins/cisco_firepower_management_center/help.md
plugins/cisco_firepower_management_center/plugin.spec.yaml
plugins/cisco_firepower_management_center/requirements.txt
plugins/cisco_firepower_management_center/setup.py

Resolving Snyk vuln within `cryptography` package
Prior PR:
- #3128 
- Bumping `cryptography` to latest version
- SDK Bump to 6.2.4

[SOAR-18892] Cisco Firepower 2.1.4 Release ('cryptography' package bump)

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/set_disposition_of_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/set_priority_of_investigation/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

Update RNN to RRN in action descriptions
Original ticket: 
- #3130 
- Update RNN to RNN for `set_priority_of_investigation` & `set_disposition_of_investigation` descriptions

[SOAR-18897] Insight IDR 11.0.2 Release

---

plugins/jira/.CHECKSUM
plugins/jira/Dockerfile
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/actions/get_comments/action.py
plugins/jira/komand_jira/connection/connection.py
plugins/jira/komand_jira/util/util.py
plugins/jira/plugin.spec.yaml
plugins/jira/requirements.txt
plugins/jira/setup.py
plugins/jira/unit_test/test_connection.py
plugins/jira/unit_test/test_create_issue.py
plugins/jira/unit_test/test_create_user.py
plugins/jira/unit_test/test_delete_user.py
plugins/jira/unit_test/test_find_users.py
plugins/jira/unit_test/test_monitor_issues.py
plugins/jira/unit_test/test_new_issue.py
plugins/jira/unit_test/test_transition_issue.py
plugins/jira/unit_test/test_util.py
plugins/jira/unit_test/util.py

- Updated normalizing user object …

[SOAR-18914] Jira - Updated normalizing user object | Updated SDK to the latest version

---

plugins/mimecast_v2/.CHECKSUM
plugins/mimecast_v2/Dockerfile
plugins/mimecast_v2/bin/icon_mimecast_v2
plugins/mimecast_v2/help.md
plugins/mimecast_v2/icon_mimecast_v2/connection/connection.py
plugins/mimecast_v2/plugin.spec.yaml
plugins/mimecast_v2/setup.py

- Update the connection test return message. Output expects return message which is not included.
* Single …

Mimecast v2 Connection Test Fix

---

plugins/mimecast_v2/.CHECKSUM
plugins/mimecast_v2/Dockerfile
plugins/mimecast_v2/bin/icon_mimecast_v2
plugins/mimecast_v2/help.md
plugins/mimecast_v2/icon_mimecast_v2/connection/connection.py
plugins/mimecast_v2/plugin.spec.yaml
plugins/mimecast_v2/setup.py

* Update SDK | Update connection test for task
- Update connection test | Bump SDK
* Single …

Mimecast V2 1.0.1 Release

---

plugins/splunk/.CHECKSUM
plugins/splunk/Dockerfile
plugins/splunk/bin/icon_splunk
plugins/splunk/help.md
plugins/splunk/plugin.spec.yaml
plugins/splunk/setup.py

Due to splunk app being deprecated, this will remove all references too it whilst also refreshing the plugin.spec and bumping the SDK to the latest version.
- Removing references to `Splunk App`

[SOAR-18941] Splunk - SDK Bump & Reference Update

---

plugins/splunk/.CHECKSUM
plugins/splunk/Dockerfile
plugins/splunk/bin/icon_splunk
plugins/splunk/help.md
plugins/splunk/plugin.spec.yaml
plugins/splunk/setup.py

Remove references to Splunk app and SDK bump to 6.2.5
Original PR:
- #3151

[SOAR-18941] Splunk 3.0.5 Release (update references)

---

plugins/jira/.CHECKSUM
plugins/jira/Dockerfile
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/actions/get_comments/action.py
plugins/jira/komand_jira/connection/connection.py
plugins/jira/komand_jira/util/util.py
plugins/jira/plugin.spec.yaml
plugins/jira/requirements.txt
plugins/jira/setup.py
plugins/jira/unit_test/test_connection.py
plugins/jira/unit_test/test_create_issue.py
plugins/jira/unit_test/test_create_user.py
plugins/jira/unit_test/test_delete_user.py
plugins/jira/unit_test/test_find_users.py
plugins/jira/unit_test/test_monitor_issues.py
plugins/jira/unit_test/test_new_issue.py
plugins/jira/unit_test/test_transition_issue.py
plugins/jira/unit_test/test_util.py
plugins/jira/unit_test/util.py

- Updated normalising user object …

[SOAR-18914] Jira - Updated normalising user object | Updated SDK to the latest version

---

plugins/jira/.CHECKSUM
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/plugin.spec.yaml
plugins/jira/setup.py

- Updated plugin description
* …

Updated plugin description

---

plugins/jira/.CHECKSUM
plugins/jira/Dockerfile
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/actions/get_comments/action.py
plugins/jira/komand_jira/connection/connection.py
plugins/jira/komand_jira/util/util.py
plugins/jira/plugin.spec.yaml
plugins/jira/requirements.txt
plugins/jira/setup.py
plugins/jira/unit_test/test_connection.py
plugins/jira/unit_test/test_create_issue.py
plugins/jira/unit_test/test_create_user.py
plugins/jira/unit_test/test_delete_user.py
plugins/jira/unit_test/test_find_users.py
plugins/jira/unit_test/test_monitor_issues.py
plugins/jira/unit_test/test_new_issue.py
plugins/jira/unit_test/test_transition_issue.py
plugins/jira/unit_test/test_util.py
plugins/jira/unit_test/util.py

- Updated normalising user object
- Updated plugin description
* Single …

[SOAR-18914] Jira - Updated normalising user object | Updated SDK to the latest version | Updated plugin description

---

plugins/extractit/.CHECKSUM
plugins/extractit/Dockerfile
plugins/extractit/bin/icon_extractit
plugins/extractit/help.md
plugins/extractit/icon_extractit/actions/extract_all/action.py
plugins/extractit/plugin.spec.yaml
plugins/extractit/setup.py

Automated pull request to bump the SDK version to 6.2.5

Extractit 3.0.10 Release (FedRAMP Automation)

---

plugins/math/.CHECKSUM
plugins/math/Dockerfile
plugins/math/bin/komand_math
plugins/math/help.md
plugins/math/plugin.spec.yaml
plugins/math/setup.py

Automated pull request to bump the SDK version to 6.2.5

Math 1.2.4 Release (FedRAMP Automation)

---

plugins/rdap/.CHECKSUM
plugins/rdap/Dockerfile
plugins/rdap/bin/icon_rdap
plugins/rdap/help.md
plugins/rdap/icon_rdap/util/helpers.py
plugins/rdap/plugin.spec.yaml
plugins/rdap/setup.py

Automated pull request to bump the SDK version to 6.2.5

Rdap 2.0.5 Release (FedRAMP Automation)

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py

Updating spec file so no data is lost during automation
- Refactoring plugin.spec

Duo Admin- SDK automation prep

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/plugin.spec.yaml

Release of MS Teams v7.0.1 now with a shortened description to allow for DB limits on the field.
Previous release PR failed to build: 
https://github.com/rapid7/insightconnect-plugins/pull/3146

MS Release v7.0.1

---

plugins/csv/.CHECKSUM
plugins/csv/Dockerfile
plugins/csv/bin/komand_csv
plugins/csv/help.md
plugins/csv/plugin.spec.yaml
plugins/csv/setup.py

Updating the spec file so no data is lost when the SDK automation takes place
Unit test check on GH is current not working. Tests pass locally:

CSV - SDK Automaton prep

---

plugins/rapid7_insightidr/plugin.spec.yaml

- Removed `fedramp_ready` flag from IDR …

Removed fedramp flag from IDR

---

plugins/mimecast_v2/icon_mimecast_v2/util/api.py

- Error if starting position is None (next day and if file continue exited on last run) …

Miemcast V2 Add default value 0

---

plugins/extractit/.CHECKSUM
plugins/extractit/bin/icon_extractit
plugins/extractit/help.md
plugins/extractit/icon_extractit/util/extractor.py
plugins/extractit/plugin.spec.yaml
plugins/extractit/requirements.txt
plugins/extractit/setup.py

Release of Extract v3.0.11
Changes:
- Bump to latest version of tldextract lib
Original PR:
- #3229

ExtractIT v3.0.11 Release

---

plugins/rest/.CHECKSUM
plugins/rest/Dockerfile
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py

REST - SDK Automation prep

---

plugins/mimecast_v2/icon_mimecast_v2/util/api.py
plugins/mimecast_v2/unit_test/test_monitor_siem_logs.py

- Reset starting position which increments to infinity …

Add in starting position reset

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/Dockerfile
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/help.md
plugins/active_directory_ldap/komand_active_directory_ldap/actions/add_user/schema.py
plugins/active_directory_ldap/komand_active_directory_ldap/actions/delete/schema.py
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/requirements.txt
plugins/active_directory_ldap/setup.py

As the SDK automation runs refresh on the plugin, this will ensure no data is lost (data not included in plugin.spec but added in help.md)
- Refactoring plugin.spec 
Issue with unit test on GH. Passes locally:

[SOAR-18918] Microsoft Active Directory LDAP (Prepping for SDK automation)

---

plugins/datetime/.CHECKSUM
plugins/datetime/Dockerfile
plugins/datetime/bin/komand_datetime
plugins/datetime/help.md
plugins/datetime/plugin.spec.yaml
plugins/datetime/setup.py

Updating for spec to be inline so when the automation is ran no data is lost
- Refactoring plugin.spec
Issue on GH for unit test check. Test pass locally:

Datetime- SDK automation prep

---

plugins/hashit/.CHECKSUM
plugins/hashit/Dockerfile
plugins/hashit/bin/icon_hashit
plugins/hashit/help.md
plugins/hashit/plugin.spec.yaml
plugins/hashit/setup.py

Refactoring plugin.spec to not loose data with the automation
- Refactor plugin.spec

Hashit- SDK Automation prep

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/Dockerfile
plugins/rapid7_vulndb/bin/komand_rapid7_vulndb
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/plugin.spec.yaml
plugins/rapid7_vulndb/setup.py

Refctoring plugin.spec for SDK automation to take place
- Refactor plugin.spec

Rapid7 Vuln DB - SDK Automation prep

---

plugins/mimecast_v2/.CHECKSUM
plugins/mimecast_v2/bin/icon_mimecast_v2
plugins/mimecast_v2/help.md
plugins/mimecast_v2/icon_mimecast_v2/tasks/monitor_siem_logs/task.py
plugins/mimecast_v2/icon_mimecast_v2/util/api.py
plugins/mimecast_v2/plugin.spec.yaml
plugins/mimecast_v2/setup.py
plugins/mimecast_v2/unit_test/test_monitor_siem_logs.py

- Remove streaming of content for logs
- Improve error handling around requests and content loading
* Single …

[SOAR-18956] Mimecast V2 1.0.3

---

plugins/hashit/.CHECKSUM
plugins/hashit/Dockerfile
plugins/hashit/bin/icon_hashit
plugins/hashit/help.md
plugins/hashit/plugin.spec.yaml
plugins/hashit/setup.py

- #3219
- Plugin.spec refactored for sdk automation

Hashit 2.0.6 Release (SDK Automation prep)

---

plugins/rest/.CHECKSUM
plugins/rest/Dockerfile
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py

REST 6.0.9 Release (SDK Automation prep)

---

plugins/csv/.CHECKSUM
plugins/csv/Dockerfile
plugins/csv/bin/komand_csv
plugins/csv/help.md
plugins/csv/plugin.spec.yaml
plugins/csv/setup.py

CSV 2.0.3 Release (SDK prep)

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py

Duo Admin 5.0.4 Release (Automation prep)

---

plugins/mimecast_v2/.CHECKSUM
plugins/mimecast_v2/bin/icon_mimecast_v2
plugins/mimecast_v2/help.md
plugins/mimecast_v2/icon_mimecast_v2/tasks/monitor_siem_logs/task.py
plugins/mimecast_v2/icon_mimecast_v2/util/api.py
plugins/mimecast_v2/plugin.spec.yaml
plugins/mimecast_v2/setup.py
plugins/mimecast_v2/unit_test/test_monitor_siem_logs.py

- Remove streaming
- Update dedupe
- Add additional error handling …

Mimecast V2 1.0.3 Release

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/Dockerfile
plugins/rapid7_vulndb/bin/komand_rapid7_vulndb
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/plugin.spec.yaml
plugins/rapid7_vulndb/setup.py

- #3237
- Refactor plugin.spec for SDK automation

Rapid7 VulnDB 2.1.6 Release (SDK Automation prep)

---

plugins/sleep/.CHECKSUM
plugins/sleep/Dockerfile
plugins/sleep/bin/komand_sleep
plugins/sleep/help.md
plugins/sleep/plugin.spec.yaml
plugins/sleep/setup.py

Refactoring plugin.spec so no data is lost during SDK automation
- Plugin spec refactor

Sleep (SDK Automation prep)

---

plugins/type_converter/.CHECKSUM
plugins/type_converter/Dockerfile
plugins/type_converter/bin/icon_type_converter
plugins/type_converter/help.md
plugins/type_converter/plugin.spec.yaml
plugins/type_converter/requirements.txt
plugins/type_converter/setup.py

Refactoring spec file so no data is lost during SDK automation
- Refactoring plugin.spec

Type Converter - (SDK Automation prep)

---

plugins/string/.CHECKSUM
plugins/string/Dockerfile
plugins/string/bin/komand_string
plugins/string/help.md
plugins/string/plugin.spec.yaml
plugins/string/setup.py

Refactoring plugin.spec so no data is lost during SDK automation
- plugin.spec refactored
- Removing `parameterized` from params (included in SDK)
Unit test:

String (SDK Automation prep)

---

plugins/ssh/.CHECKSUM
plugins/ssh/Dockerfile
plugins/ssh/bin/komand_ssh
plugins/ssh/help.md
plugins/ssh/plugin.spec.yaml
plugins/ssh/setup.py

Refactoring plugin.spec so no data is lost during SDK automation
- plugin.spec refactored

SSH (SDK Automation prep)

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/Dockerfile
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/help.md
plugins/active_directory_ldap/komand_active_directory_ldap/actions/add_user/schema.py
plugins/active_directory_ldap/komand_active_directory_ldap/actions/delete/schema.py
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/requirements.txt
plugins/active_directory_ldap/setup.py

- #3213
- plugin.spec refactor for sdk automation

[SOAR-18918] Microsoft Active Directory LDAP 9.0.3 Release

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/Dockerfile
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py

Refactoring spec file so no data is lost during SDK automation

Rapid7 Insight Agent - SDK Automation prep

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

Refactoring spec file so no data is lost for SDK automation
- Refactor spec file

Python 3 Script -  SDK Automation prep

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

- #3232
- plugin.spec refactor

Python 3 Script 5.1.1 Release  (SDK Automation prep)

---

plugins/microsoft_atp/.CHECKSUM
plugins/microsoft_atp/Dockerfile
plugins/microsoft_atp/bin/komand_microsoft_atp
plugins/microsoft_atp/help.md
plugins/microsoft_atp/plugin.spec.yaml
plugins/microsoft_atp/setup.py

Updating spec file to be inline with help.md so no data is lost during SDK automation
- Refactor plugin.spec

Microsoft ATP -  SDK Automation prep

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

Updating spec file so no data is lost during automation
- Refactor spec file

Okta -  SDK Automation prep

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

Refactoring spec file for SDK automation

Rapid7 Insight IVM - SDK Automation prep

---

plugins/datetime/.CHECKSUM
plugins/datetime/Dockerfile
plugins/datetime/bin/komand_datetime
plugins/datetime/help.md
plugins/datetime/plugin.spec.yaml
plugins/datetime/setup.py

- #3216
- plugin.spec refactor for sdk automation

Datetime 3.0.2 Release (SDK automation prep)

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/plugin.spec.yaml
plugins/whois/requirements.txt
plugins/whois/setup.py

Refactoring plugin.spec to be inline with help.md so no data is lost during SDK automation
***Validator is expected to pass as seen in previous Whois releases: https://github.com/rapid7/insightconnect-plugins/actions/runs/12826357809/job/35766117994***

Whois - (SDK Automation prep)

---

plugins/sleep/.CHECKSUM
plugins/sleep/Dockerfile
plugins/sleep/bin/komand_sleep
plugins/sleep/help.md
plugins/sleep/plugin.spec.yaml
plugins/sleep/setup.py

Refactoring plugin.spec for SDK automation
- #3249
- Refactor plugin.spec

Sleep 1.0.4 Release (SDK Automation)

---

plugins/html/.CHECKSUM
plugins/html/Dockerfile
plugins/html/bin/icon_html
plugins/html/help.md
plugins/html/plugin.spec.yaml
plugins/html/setup.py

Updating plugin so no data is lost during SDK automation
**Validator is expecting to fail as USER permissions needs to be ROOT for plugin to work**

HTML - SDK automation prep 

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/bin/icon_powershell
plugins/powershell/help.md
plugins/powershell/icon_powershell/util/util.py
plugins/powershell/plugin.spec.yaml
plugins/powershell/requirements.txt
plugins/powershell/setup.py

- (#3242)
- Bumping `cryptography` package to resolve Snyk
- Update clean messages (SI issue)

[SOAR-19013] Powershell 3.0.8 Release

---

plugins/type_converter/.CHECKSUM
plugins/type_converter/Dockerfile
plugins/type_converter/bin/icon_type_converter
plugins/type_converter/help.md
plugins/type_converter/plugin.spec.yaml
plugins/type_converter/setup.py

- #3252
- Plugin.spec refactor

Type Converter 1.8.4 Release - (SDK Automation prep)

---

plugins/ssh/.CHECKSUM
plugins/ssh/Dockerfile
plugins/ssh/bin/komand_ssh
plugins/ssh/help.md
plugins/ssh/plugin.spec.yaml
plugins/ssh/setup.py

- #3250
- Plugin.spec refactor

SSH 4.0.4 Release (SDK Automation) 

---

plugins/microsoft_atp/.CHECKSUM
plugins/microsoft_atp/Dockerfile
plugins/microsoft_atp/bin/komand_microsoft_atp
plugins/microsoft_atp/help.md
plugins/microsoft_atp/plugin.spec.yaml
plugins/microsoft_atp/setup.py

Microsoft ATP 6.0.2 Release (SDK Automation)

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/Dockerfile
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py

- #3233
- plugin.spec refactor

Rapid7 Insight Agent 3.0.3 Release (SDK Automation)

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

Rapid7 Insight IVM 8.0.10 Release - (SDK Automation) 

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/plugin.spec.yaml
plugins/whois/setup.py

- (#3253)
- plugin.spec refactor
VALIDATOR IS EXPECTED TO **FAIL!**

Whois 3.1.8 Release - (SDK Automation)

---

plugins/html/.CHECKSUM
plugins/html/Dockerfile
plugins/html/bin/icon_html
plugins/html/help.md
plugins/html/plugin.spec.yaml
plugins/html/setup.py

- (#3222)
**VALIDATOR IS EXPECTED TO FAIL**

HTML 1.2.8 Release (SDK automation) 

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

Okta 4.2.13 Release - (SDK Automation)

---

plugins/subnet/.CHECKSUM
plugins/subnet/Dockerfile
plugins/subnet/bin/komand_subnet
plugins/subnet/help.md
plugins/subnet/komand_subnet/actions/calculate/schema.py
plugins/subnet/komand_subnet/actions/check_address_in_subnet/schema.py
plugins/subnet/plugin.spec.yaml
plugins/subnet/setup.py

Refactoring plugin for SDK Automation

Subnet - (SDK Automation prep)

---

plugins/basename/.CHECKSUM
plugins/basename/Dockerfile
plugins/basename/bin/komand_basename
plugins/basename/help.md
plugins/basename/komand_basename/actions/basename/schema.py
plugins/basename/plugin.spec.yaml
plugins/basename/setup.py

Refactoring plugin for SDK automation

Basename - (SDK Automation prep)

---

plugins/subnet/.CHECKSUM
plugins/subnet/Dockerfile
plugins/subnet/bin/komand_subnet
plugins/subnet/help.md
plugins/subnet/komand_subnet/actions/calculate/schema.py
plugins/subnet/komand_subnet/actions/check_address_in_subnet/schema.py
plugins/subnet/plugin.spec.yaml
plugins/subnet/setup.py

Subnet 2.0.2 Release - (SDK Automation) 

---

plugins/basename/.CHECKSUM
plugins/basename/Dockerfile
plugins/basename/bin/komand_basename
plugins/basename/help.md
plugins/basename/komand_basename/actions/basename/schema.py
plugins/basename/plugin.spec.yaml
plugins/basename/setup.py

Basename 1.1.4 Release - (SDK Automation)

---

plugins/dig/.CHECKSUM
plugins/dig/Dockerfile
plugins/dig/bin/komand_dig
plugins/dig/help.md
plugins/dig/plugin.spec.yaml
plugins/dig/setup.py

Dig 2.0.5 Release - (SDK Automation)

---

plugins/advanced_regex/.CHECKSUM
plugins/advanced_regex/Dockerfile
plugins/advanced_regex/bin/icon_advanced_regex
plugins/advanced_regex/help.md
plugins/advanced_regex/plugin.spec.yaml
plugins/advanced_regex/setup.py

Advanced Regex 1.0.5 Release - (SDK Automation) 

---

plugins/mimecast_v2/.CHECKSUM
plugins/mimecast_v2/Dockerfile
plugins/mimecast_v2/bin/icon_mimecast_v2
plugins/mimecast_v2/help.md
plugins/mimecast_v2/icon_mimecast_v2/tasks/monitor_siem_logs/task.py
plugins/mimecast_v2/icon_mimecast_v2/util/api.py
plugins/mimecast_v2/plugin.spec.yaml
plugins/mimecast_v2/setup.py
plugins/mimecast_v2/unit_test/responses/monitor_siem_logs_batch_duplicates.json.resp
plugins/mimecast_v2/unit_test/test_monitor_siem_logs.py
plugins/mimecast_v2/unit_test/util.py

- Deduplicate log batches
- If log batch cannot be found, do not resume from beginning but attempt to carry on from last known position
- Add additionally logging for log batch position in total log batches, and next page token
* Single action/trigger `insight-plugin run -T …

[DNR-8579] Mimecast V2 1.0.4

---

plugins/mimecast_v2/.CHECKSUM
plugins/mimecast_v2/Dockerfile
plugins/mimecast_v2/bin/icon_mimecast_v2
plugins/mimecast_v2/help.md
plugins/mimecast_v2/icon_mimecast_v2/tasks/monitor_siem_logs/task.py
plugins/mimecast_v2/icon_mimecast_v2/util/api.py
plugins/mimecast_v2/plugin.spec.yaml
plugins/mimecast_v2/setup.py
plugins/mimecast_v2/unit_test/responses/monitor_siem_logs_batch_duplicates.json.resp
plugins/mimecast_v2/unit_test/test_monitor_siem_logs.py
plugins/mimecast_v2/unit_test/util.py

- Add additional logging
- Add deduplication of batch URLS for task
- Add debug log level to custom config
- Update SDK
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR format …

Mimecast V2 1.0.4 Release

---

plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py

- Updated pagination time calculation …

Updated pagination time calculation

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/unit_test/test_monitor_events.py

- Made `split_size` configurable …

Updated split_size to be configurable

---

plugins/microsoft_defender_incidents/.CHECKSUM
plugins/microsoft_defender_incidents/Dockerfile
plugins/microsoft_defender_incidents/bin/icon_microsoft_defender_incidents
plugins/microsoft_defender_incidents/help.md
plugins/microsoft_defender_incidents/icon_microsoft_defender_incidents/actions/get_incident/schema.py
plugins/microsoft_defender_incidents/icon_microsoft_defender_incidents/actions/list_incidents/schema.py
plugins/microsoft_defender_incidents/icon_microsoft_defender_incidents/actions/update_incident/schema.py
plugins/microsoft_defender_incidents/icon_microsoft_defender_incidents/triggers/get_new_incidents/schema.py
plugins/microsoft_defender_incidents/plugin.spec.yaml
plugins/microsoft_defender_incidents/setup.py

The documentation for the update_incident action does not match what is in our spec file. This will update them to be inline. There is also an warning that values will be removed, these will also be removed from all actions:
- Update input/output values to correlate with docs
Tried to set value as expired and doesn't work:
`"error": "('action input JSON was invalid', <ValidationError: \"'Unknown' is not one of ['', 'TruePositive', 'FalsePositive', 'InformationalExpectedActivity']\">)",`

[SOAR-19189] Microsoft Defender Incidents - Updating update action values to align with documentation

---

.github/workflows/main.yml
.github/workflows/prospector.yml
.github/workflows/unit_test.yml
.github/workflows/unit_test_coverage.yml

The prospector is failing:
This will update the ubuntu version to latest and update the Python version. This version was also used in Black and works: 
- #3281

[SOAR-19228] Prospector Fix - Ubuntu Version

---

plugins/smb/.CHECKSUM
plugins/smb/Dockerfile
plugins/smb/help.md
plugins/smb/plugin.spec.yaml

SMB 3.0.0 -  (SDK 6.3.3)

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/resource_helper.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

https://rapid7.atlassian.net/browse/SOAR-19348
- Improved parsing method

[SOAR-19348] Improved parsing method

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/resource_helper.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

https://rapid7.atlassian.net/browse/SOAR-19348
- Improved parsing method
From PR: https://github.com/rapid7/insightconnect-plugins/pull/3396

Rapid7 InsightIDR 11.0.4 Release

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/icon_python_3_script/actions/run/action.py
plugins/python_3_script/icon_python_3_script/connection/connection.py
plugins/python_3_script/icon_python_3_script/connection/schema.py
plugins/python_3_script/icon_python_3_script/util/constants.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py
plugins/python_3_script/unit_test/inputs/connection_with_credentials.json.inp

- #3409 
- Adding 3 more optional connection fields (`secret_credential_1`, `secret_credential_2`, `secret_credential_3`)
- Change description as it's >500 (with addition of new fields)
- Updated Unit Test

[SOAR-19381] Python 3 Script 5.2.0 Release (Addition 3 extra connection fields)

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/requirements.txt
plugins/python_3_script/setup.py

`setuptools` is causing a medium snyk vulnerability but can be removed as it is included in the SDK. 
- Removing `setuptools`
- SDK bump to 6.3.4

[SOAR-19419] Python 3 Script - Addressing Snyk Vulnerability

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py

Removing `setuptools` as it is included in SDK (and is being flagged on Snyk)
- Removing `setuptools` from requirements.txt
- SDK bump to 6.3.4

[SOAR-19419] Rapid7 InsightVM Resolving Snyk Vulnerability 

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/requirements.txt
plugins/python_3_script/setup.py

Snyk fix and SDK Bump
-  (#3416)

[SOAR-19419] Python 3 Script - 5.2.1 Release

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py

SDK bump and fixing Snyk Vulnerability within `setuptools`
- (#3417)

[SOAR-19419] Rapid7 InsightVM 8.0.12 Release 

---

plugins/html/.CHECKSUM
plugins/html/Dockerfile
plugins/html/bin/icon_html
plugins/html/help.md
plugins/html/icon_html/actions/text/action.py
plugins/html/icon_html/actions/validate/action.py
plugins/html/icon_html/actions/validate/schema.py
plugins/html/icon_html/util/api.py
plugins/html/icon_html/util/constants.py
plugins/html/icon_html/util/strategies.py
plugins/html/plugin.spec.yaml
plugins/html/requirements.txt
plugins/html/setup.py
plugins/html/unit_test/test_markdown.py

Removing `setuptools` as it is included in SDK (and is being flagged on Snyk)
- Removing `setuptools` from requirements.txt
- SDK bump to 6.3.4

[SOAR-19419] HTML - Snyk Vulnerability

---

plugins/html/.CHECKSUM
plugins/html/Dockerfile
plugins/html/bin/icon_html
plugins/html/help.md
plugins/html/icon_html/actions/text/action.py
plugins/html/icon_html/actions/validate/action.py
plugins/html/icon_html/actions/validate/schema.py
plugins/html/icon_html/util/api.py
plugins/html/icon_html/util/constants.py
plugins/html/icon_html/util/strategies.py
plugins/html/plugin.spec.yaml
plugins/html/requirements.txt
plugins/html/setup.py
plugins/html/unit_test/test_markdown.py

Addressing Snyk Vulnerability
-  (#3418)

[SOAR-19419] HTML 2.0.1 Release (Snyk fix)

---

plugins/palo_alto_pan_os/.CHECKSUM
plugins/palo_alto_pan_os/Dockerfile
plugins/palo_alto_pan_os/bin/komand_palo_alto_pan_os
plugins/palo_alto_pan_os/help.md
plugins/palo_alto_pan_os/plugin.spec.yaml
plugins/palo_alto_pan_os/requirements.txt
plugins/palo_alto_pan_os/setup.py

Resolving Snyk Vulnerability 
- (#3422)

[SOAR-19419] Palo Alto Pan OS 6.1.9 Release (Snyk Vulnerability)

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py

Addressing Snyk Vulnerability (`setuptools`) by removing package from requirements.txt as it is included within SDK. Bumped SDK version to latest
- Removed `setuptools` from requirements.txt
- SDK bump to 6.3.4

[SOAR-19419] Mimecast - Resolving Snyk Vulnerability

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py

Resolving snyk vulnerability
- (#3424)

Mimecast 6.0.1 Release (Snyk Vulnerability)

---

.github/workflows/prospector.yml

- Updated GHA workflow for prospector …

[SOAR-19427] Prospector - Updated GHA workflow

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/help.md
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/monitor_alerts/schema.py

Fix p a c xdr 4.0.7

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/plugin.spec.yaml

[SOAR-19518] InsightIDR - SDK bump 6.3.6

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/Dockerfile
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/help.md
plugins/active_directory_ldap/komand_active_directory_ldap/util/api.py
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/requirements.txt
plugins/active_directory_ldap/setup.py

https://rapid7.atlassian.net/browse/SOAR-19429
- Fixed issues with channel binding support
- Updated SDK to the latest version (6.3.4)
From PR: https://github.com/rapid7/insightconnect-plugins/pull/3429

Active Directory LDAP 10.0.1 Release 

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py
plugins/proofpoint_tap/unit_test/test_monitor_events.py

- Add headroom of 1 hour to cutoff
- Add logging for lagging …

Proofpoint Tap 4.1.13 Release

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py

- Fix time set for next run when deduping to prevent large retrieval window. …

Carbon Black Cloud 2.2.11 Release

---

plugins/carbon_black_response/.CHECKSUM
plugins/carbon_black_response/Dockerfile
plugins/carbon_black_response/bin/icon_carbon_black_response
plugins/carbon_black_response/help.md
plugins/carbon_black_response/plugin.spec.yaml
plugins/carbon_black_response/requirements.txt
plugins/carbon_black_response/setup.py

Snyk vulnerability in `urllib3` package. This is derived from `boto3` and `botocore` which are in the SDK so the package can be removed
- Removed `urllib3`
- SDK Bump to 6.3.7

[SOAR-19631] Carbon Black Response - Resolving Snyk Vulnerabilities

---

plugins/carbon_black_response/.CHECKSUM
plugins/carbon_black_response/Dockerfile
plugins/carbon_black_response/bin/icon_carbon_black_response
plugins/carbon_black_response/help.md
plugins/carbon_black_response/plugin.spec.yaml
plugins/carbon_black_response/requirements.txt
plugins/carbon_black_response/setup.py

Resolving Snyk vulnerability caused within `urllib3` package. Removed as it is included in SDK. Bumped other packages.
- SDK Bump to 6.3.7
- Removed `urllib3` package 
- (#3485)

[SOAR-19631] Carbon Black Response 3.3.2 Release - Resolving Snyk Vulnerabilities

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py
plugins/okta/unit_test/expected/get_logs_empty_resp.json.exp
plugins/okta/unit_test/expected/get_logs_next_empty.json.exp
plugins/okta/unit_test/test_monitor_logs.py

- Add decorator
- Bump SDK
- Change start time set …

[SOAR-19663] Okta Lagging Decorator

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py
plugins/okta/unit_test/expected/get_logs_empty_resp.json.exp
plugins/okta/unit_test/expected/get_logs_next_empty.json.exp
plugins/okta/unit_test/test_monitor_logs.py

Okta 4.2.15 Release

---

plugins/matrix42/icon_matrix42/actions/create_ticket/action.py
plugins/matrix42/icon_matrix42/connection/connection.py
plugins/matrix42/requirements.txt
plugins/matrix42/unit_test/test_create_ticket.py

Fixing static code check errors and unit tests

Matrix42 1.0.0 final pre-release fixes

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py

Snyk and Dependabot vulnerability in `aiohttp` package
- (#3519)
- #3515

[SOAR-19837] Rapid7 InsightIDR 12.0.1 Release - Resolving Snyk Vulnerability and dependabot issue 

---

plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py

Remove invalid logger:
```
{"message": "An Exception has been raised. Error: 'MonitorLogs' object has no attribute 'log_level'", "taskName": null, "int_id": "6adc320d-9b55-4ad7-80cf-d1c5c6bbea5f", "org_id": "3697e7df-6f52-4891-8ade-929fc845c01e", "request_id": "819ea152-ed25-9fe8-80a6-0f2da83020a1", "request_path": "/api/v1/tasks/monitor_logs", "level": "info", "timestamp": "2025-07-30 17:55.48"}
```

remove log level

---

plugins/jira/.CHECKSUM
plugins/jira/Dockerfile
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/plugin.spec.yaml
plugins/jira/requirements.txt
plugins/jira/setup.py

- Updated SDK to the latest version (6.3.9) …

[SOAR-19984] Jira - Updated SDK to the latest version (6.3.9)

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml

PR will be merged into:
- #3542
- Bumping SDK to 6.3.10

[SOAR-20017] Rapid7 InsightVM - SDK Bump to 6.3.10

---

plugins/basename/.CHECKSUM
plugins/basename/Dockerfile
plugins/basename/help.md
plugins/basename/plugin.spec.yaml

[SOAR-19984] Basename - Updated SDK to the latest version (6.3.10)

---

plugins/jira/.CHECKSUM
plugins/jira/Dockerfile
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/plugin.spec.yaml
plugins/jira/requirements.txt
plugins/jira/setup.py

- Updated SDK to the latest version (6.3.9) …

[SOAR-19984] Jira - Updated SDK to the latest version (6.3.9) (#3535)

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py
plugins/okta/unit_test/expected/get_logs.json.exp
plugins/okta/unit_test/expected/get_logs_empty_resp.json.exp
plugins/okta/unit_test/expected/get_logs_filtered.json.exp
plugins/okta/unit_test/expected/get_logs_next_empty.json.exp
plugins/okta/unit_test/expected/get_logs_next_page.json.exp
plugins/okta/unit_test/inputs/monitor_logs_next_page.json.inp
plugins/okta/unit_test/inputs/monitor_logs_with_state.json.inp
plugins/okta/unit_test/test_monitor_logs.py

…uns to the last run end time
- Add events limit to custom config
- Add new value to track start time that is separate from last log collection time which is now used for information and deduping only. Resetting the new value 'last_search_end_timestamp' only on subsequent or first runs to allow the next run after pagination to pick up where it left off
- Update SDK …

[SOAR-20047] Okta (Query Start Time Adjustment)

---

plugins/mimecast_v2/icon_mimecast_v2/tasks/monitor_siem_logs/task.py
plugins/mimecast_v2/unit_test/test_monitor_siem_logs.py

- Updated caught up flag for TTP to move run state …

[SOAR-20032] Mimecast v2 - Updated caught up flag for TTP to move run state

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/Dockerfile
plugins/microsoft_teams/bin/icon_microsoft_teams
plugins/microsoft_teams/help.md
plugins/microsoft_teams/plugin.spec.yaml
plugins/microsoft_teams/requirements.txt
plugins/microsoft_teams/setup.py

[SOAR-20096] Microsoft Teams - Updated SDK to the latest version (6.3.10)

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/Dockerfile
plugins/rapid7_vulndb/bin/komand_rapid7_vulndb
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/plugin.spec.yaml
plugins/rapid7_vulndb/setup.py

[SOAR-20096] Rapid7 Vulndb - Updated SDK to the latest version (6.3.10)

---

plugins/hashit/.CHECKSUM
plugins/hashit/Dockerfile
plugins/hashit/bin/icon_hashit
plugins/hashit/help.md
plugins/hashit/plugin.spec.yaml
plugins/hashit/requirements.txt
plugins/hashit/setup.py

[SOAR-20096] Hashit - Updated SDK to the latest version (6.3.10)

---

plugins/base64/.CHECKSUM
plugins/base64/Dockerfile
plugins/base64/bin/komand_base64
plugins/base64/help.md
plugins/base64/plugin.spec.yaml
plugins/base64/setup.py

[SOAR-20096] Base64 - Updated SDK to the latest version (6.3.10)

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/Dockerfile
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/requirements.txt
plugins/rapid7_insight_agent/setup.py

[SOAR-20096] Rapid7 Insight Agent - Updated SDK to the latest version (6.3.10)

---

plugins/type_converter/.CHECKSUM
plugins/type_converter/Dockerfile
plugins/type_converter/bin/icon_type_converter
plugins/type_converter/help.md
plugins/type_converter/plugin.spec.yaml
plugins/type_converter/requirements.txt
plugins/type_converter/setup.py

- Updated SDK to the latest version (6.3.10) (#3570) …

Type Converter - 20096 - Updated SDK to the latest version (6.3.10) (#3570)

---

plugins/csv/.CHECKSUM
plugins/csv/Dockerfile
plugins/csv/bin/komand_csv
plugins/csv/help.md
plugins/csv/plugin.spec.yaml
plugins/csv/setup.py

- Updated SDK to the latest version (6.3.10) (#3571) …

CSV - 20096 - Updated SDK to the latest version (6.3.10) (#3571)

---

plugins/hashit/.CHECKSUM
plugins/hashit/Dockerfile
plugins/hashit/bin/icon_hashit
plugins/hashit/help.md
plugins/hashit/plugin.spec.yaml
plugins/hashit/requirements.txt
plugins/hashit/setup.py

- Updated SDK to the latest version (6.3.10) (#3572) …

Hashit - 20096 - Updated SDK to the latest version (6.3.10) (#3572)

---

plugins/datetime/.CHECKSUM
plugins/datetime/Dockerfile
plugins/datetime/bin/komand_datetime
plugins/datetime/help.md
plugins/datetime/plugin.spec.yaml
plugins/datetime/requirements.txt
plugins/datetime/setup.py

- Updated SDK to the latest version (6.3.10) (#3574) …

Datetime - 20096 - Updated SDK to the latest version (6.3.10) (#3574)

---

plugins/microsoft_atp/.CHECKSUM
plugins/microsoft_atp/Dockerfile
plugins/microsoft_atp/bin/komand_microsoft_atp
plugins/microsoft_atp/help.md
plugins/microsoft_atp/plugin.spec.yaml
plugins/microsoft_atp/requirements.txt
plugins/microsoft_atp/setup.py

- Updated SDK to the latest version (6.3.10) (#3577) …

Microsoft ATP - 20096 - Updated SDK to the latest version (6.3.10) (#3577)

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_asset/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_scan/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/start_scan/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/stop_scan/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/vuln_search/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/connection/connection.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/util/api.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py
plugins/rapid7_insightvm_cloud/unit_test/test_asset_search.py
plugins/rapid7_insightvm_cloud/unit_test/test_get_asset.py
plugins/rapid7_insightvm_cloud/unit_test/test_get_scan.py
plugins/rapid7_insightvm_cloud/unit_test/test_start_scan.py
plugins/rapid7_insightvm_cloud/unit_test/test_stop_scan.py
plugins/rapid7_insightvm_cloud/unit_test/test_vuln_search.py

- Added user-agent and correlation ID headers to all requests
```
2025-09-25 07:27:51 [info     ] Connect: Connecting...
2025-09-25 07:27:51 [info     ] rapid7/Rapid7 InsightVM Cloud:9.0.1. Step name: asset_search
2025-09-25 07:27:51 [info     ] Receiving 0 page of results...
2025-09-25 07:27:51 [info     ] Making request to https://us.api.insight.rapid7.com/vm/v4/integration/assets with request ID: 925027c3-792f-40fd-913d-99ec590a3d5d
2025-09-25 07:27:53 [info     ] Found 1 assets. Returning results...
{"body": {"log": "", "status": "ok", "meta": {}, "output": {"assets": [{"assessed_for_policies": false, "assessed_fo...
```
``` …
```

[SOAR-20107] InsightVM Cloud - Added user-agent and correlation ID headers to all requests | Updated SDK to the latest version (6.3.10)

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/Dockerfile
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

- Updated SDK to the latest version (6.3.10) (#3579) …

[SOAR-20096] Servicenow - Updated SDK to the latest version (6.3.10) (#3579)

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/Dockerfile
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_asset/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_scan/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/start_scan/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/stop_scan/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/vuln_search/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/connection/connection.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/util/api.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py
plugins/rapid7_insightvm_cloud/unit_test/test_asset_search.py
plugins/rapid7_insightvm_cloud/unit_test/test_get_asset.py
plugins/rapid7_insightvm_cloud/unit_test/test_get_scan.py
plugins/rapid7_insightvm_cloud/unit_test/test_start_scan.py
plugins/rapid7_insightvm_cloud/unit_test/test_stop_scan.py
plugins/rapid7_insightvm_cloud/unit_test/test_vuln_search.py

- Added user-agent and correlation ID headers to all requests
- Updated SDK to the latest version (6.3.10) (#3596)
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR format at …

[SOAR-20107] InsightVM Cloud - Added user-agent and correlation ID headers to all requests | Updated SDK to the latest version (6.3.10) (#3596)
