README.md

- Fix the Plugin Support link in the menu. It didn't match the heading.
4. Add UI screenshot …

README: Fix link in menu

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

- Add a contributing guide based on Metasploit's excellent guide
```
$ mdl CONTRIBUTING.md | grep -v 'MD013 Line length' && printf "We're good"
A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
We're good
```
Thank you for your interest in improving InsightConnect! Please review our [Code of Conduct] before making contributions.
There are multiple ways to contribute beyond writing code. These include:
- [Submit bugs and feature requests] with detailed information about your issue or idea.
- [Help fellow users with open issues] or [help fellow committers test recent pull requests].
- [Report a security vulnerability in InsightConnect's plugins] to Rapid7.
- Submit an updated or brand new …

CONTRIBUTING: Add a more fleshed out contributing guide

---

zeus_tracker/plugin.spec.yaml

- marked ZeuSTracker as obsolete, same change as in komand-plugins
4. Add UI screenshot of the …

[DF-2840] marked ZeuSTracker as obsolete

---

github/komand_github/actions/add_issue_label/schema.py
github/komand_github/actions/close_issue/schema.py
github/plugin.spec.yaml

- Output variable `success` needs to be capitalized for title
3. Copy (`./run ... | pbcopy`) and paste the …

Github: Github title fix to pass Title validator

---

freegeoip/help.md
freegeoip/plugin.spec.yaml

Freegeoip test

---

tools/Makefiles/Helpers.mk

- Remove `runner` targets from Helpers Makefile, `icon-plugin` should be used instead
- Remove `help` target from Helpers Makefile, it's outdated and `icon-plugin generate help` should be used instead
- Add `update-tools` target to menu
- Keep scripts around in `tools/` directory for now in case they become necessary for use in edge cases or bugs in the main tool.
`make` validation:
```
$ make -n -f tools/Makefiles/Helpers.mk
echo ""
echo "Plugin main targets:"
echo " default    - Builds the plugin and creates a tarball (image + tarball targets)"
echo " image      - Build a Docker image of the current plugin directory"
echo " tarball    - Create a plugin tarball of the current directory"
echo " regenerate - Regenerate the plugin schema from plugin.spec.yaml" …
```

Makefiles: Remove outdated Makefile helpers

---

mimecast/help.md
tools/mdl.sh

- Enforce markdown linting when `icon-validate` is used by returning `mdl` status code
- Update any specs to pass linting rules
```
$ for i in */help.md; do plugin=$(dirname $i); pushd $plugin 1>/dev/null; ../tools/mdl.sh &>/dev/null || printf "$plugin\n"; popd 1>/dev/null; done && printf "Done"
Done
```

Enforce markdown linting in validation

---

proofpoint_tap/.CHECKSUM
proofpoint_tap/bin/komand_proofpoint_tap
proofpoint_tap/help.md
proofpoint_tap/komand_proofpoint_tap/actions/parse_tap_alert/action.py
proofpoint_tap/komand_proofpoint_tap/actions/parse_tap_alert/schema.py
proofpoint_tap/komand_proofpoint_tap/util/tap_formatter.py
proofpoint_tap/plugin.spec.yaml
proofpoint_tap/requirements.txt
proofpoint_tap/setup.py
proofpoint_tap/tests/parse_tap_alert.json

- Add a new return key and value to the Proofpoint TAP action.  The Threat Details URL is a link to Proofpoint documentation on the threat in element "threat_details_url"
Some fields obfuscated with <removed>
```
run -R tests/parse_tap_alert_attachment.json 
INFO[0000] Running command:  docker run --rm -i rapid7/proofpoint_tap:1.0.5 run < tests/parse_tap_alert_attachment.json 
{"body": {"log": "rapid7/Proofpoint TAP:1.0.5. Step name: parse_tap_alert", "status": "ok", "meta": {}, "output": {"results": {"threat": {"attachment_sha256": "", "category": "phish", "condemnation_time": "2019-08-12T22:03:36Z", "url": "<removed>", "threat_details_url": "https://threatinsight.proofpoint.com/<removed>/threat/email/<removed>"}, "message": {"time_delivered": "2019-08-10T05:18:51Z", "recipients": …
```

Added new value to return output of proofpoint TAP plugin

---

domaintools/plugin.spec.yaml

* Fix syntax bug in `plugin.spec.yaml` causing error in CI
```
17:13:17 ruamel.yaml.parser.ParserError: while parsing a flow node
17:13:17 expected the node content, but found ','
17:13:17   in "<unicode string>", line 23, column 46:
17:13:17      ... [threat_detection_and_response, , offensive_security]
17:13:17                                          ^ (line: 23)
17:13:17 Build step 'Execute shell' marked build as failure
```

Fix spec error in use case elements

---

ifconfig_co/help.md
ipify/help.md
jq/help.md
json_edit/help.md
markdown/help.md
math/help.md
matplotlib/help.md
pushover/help.md

- Added missing punctuation on the following lines:
```
_This plugin does not contain any triggers_
_This plugin does not contain any requirements_
```

Missing punctuation in help.md files

---

rapid7_vulndb/.CHECKSUM
rapid7_vulndb/bin/komand_rapid7_vulndb
rapid7_vulndb/help.md
rapid7_vulndb/komand_rapid7_vulndb/actions/search_db/schema.py
rapid7_vulndb/komand_rapid7_vulndb/util/transform.py
rapid7_vulndb/plugin.spec.yaml
rapid7_vulndb/setup.py

Add module or vulnerability identifier to the search result
Currently, search vuln_db action doesn't return identifier of the module or vulnerability , instead it returns the URL,  which makes using the `get_content` action inconvenient as  URL should be parsed and identifier should be extracted manually from the URL.  This PR adds the field so no parsing is required to get the content results for the search_db results. 
- Update schema to include the result
- Don't pop the identifier from the original API result
- checked that search action returns identifier `"identifier": "mozilla-thunderbird-cve-2015-7189"`
```
icon-plugin run -R tests/search_db.json
INFO[0000] Running command:  docker run --rm -i rapid7/rapid7_vulndb:2.0.1 run < tests/search_db.json …
```

Add the identifier field for the vuln_db search result.

---

dig/.CHECKSUM
dig/bin/komand_dig
dig/help.md
dig/komand_dig/connection/connection.py
dig/plugin.spec.yaml
dig/setup.py

- Add example inputs raw JSON section to help.md
- Add example inputs to input markdown table
- Add example keys for inputs in spec
Tested in product via custom plugin. PR assessment below.
<details>
```
{
"body": {
"log": "rapid7/Dig:1.0.4. Step name: forward\nExecuting command /usr/bin/dig google.com A\n",
"meta": {},
"output": {
"all_answers": [
"172.217.6.14"
],
"answer": "172.217.6.14",
"fulloutput": "\n; \u003c\u003c\u003e\u003e DiG 9.12.4-P2 \u003c\u003c\u003e\u003e google.com A\n;; global options: +cmd\n;; Got answer:\n;; -\u003e\u003eHEADER\u003c\u003c- opcode: QUERY, status: NOERROR, id: 47921\n;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;google.com.\t\t\tIN\tA\n\n;; ANSWER …
```

Dig: Example Input Reference

---

proofpoint_url_defense/.CHECKSUM
proofpoint_url_defense/bin/komand_proofpoint_url_defense
proofpoint_url_defense/help.md
proofpoint_url_defense/komand_proofpoint_url_defense/actions/url_decode/action.py
proofpoint_url_defense/komand_proofpoint_url_defense/connection/connection.py
proofpoint_url_defense/komand_proofpoint_url_defense/util/proofpoint_decoder.py
proofpoint_url_defense/plugin.spec.yaml
proofpoint_url_defense/setup.py
proofpoint_url_defense/unit_test/test_url_decode.py

This PR adds v3 link support to the Proofpoint URL Defense plugin 
```
rmt-mbp-5357:proofpoint_url_defense jmcadams$ icon-validate .
[*] Executing …
```

Proofpoint URL Defense - added support for v3 links

---

proofpoint_url_defense/.CHECKSUM
proofpoint_url_defense/bin/komand_proofpoint_url_defense
proofpoint_url_defense/help.md
proofpoint_url_defense/komand_proofpoint_url_defense/actions/url_decode/action.py
proofpoint_url_defense/komand_proofpoint_url_defense/actions/url_decode/schema.py
proofpoint_url_defense/plugin.spec.yaml
proofpoint_url_defense/setup.py
proofpoint_url_defense/unit_test/test_url_decode.py

This PR adds 'decode_success' to Proof Point URL Defense. This will allow the user to know if a URL was successfully decoded, but not break a workflow if a non-encoded URL is passed in. 
```
rmt-mbp-5357:proofpoint_url_defense jmcadams$ icon-validate .
[*] Executing …
```

Proof Point Decode Success

---

microsoft_teams/.CHECKSUM
microsoft_teams/bin/icon_microsoft_teams
microsoft_teams/help.md
microsoft_teams/icon_microsoft_teams/util/teams_utils.py
microsoft_teams/plugin.spec.yaml
microsoft_teams/setup.py
microsoft_teams/tests/send_message_by_guid.json
microsoft_teams/unit_test/test_get_channels.py
microsoft_teams/unit_test/test_teams_utils.py

This PR adds pagination support to the Microsoft Teams "Get Teams" action. This adds support for more than 20 teams when looking for a team. 
``` …
```

[WIP] - Microsoft Teams add support for more than 20 teams in Get Teams

---

mcafee_epo/.CHECKSUM
mcafee_epo/bin/komand_mcafee_epo
mcafee_epo/help.md
mcafee_epo/komand_mcafee_epo/actions/system_info/schema.py
mcafee_epo/komand_mcafee_epo/connection/schema.py
mcafee_epo/plugin.spec.yaml
mcafee_epo/setup.py

-
<details>
```
{
"body": {
"status": "ok",
"output": {
"properties": [
{
"EPOComputerProperties.CPUSpeed": 1608,
"EPOComputerProperties.OSPlatform": "Workstation",
"EPOComputerProperties.ComputerName": "DESKTOP-C27R09E", …
```

Mcafee EPO - Fix issue with wrong type in action System Information

---

palo_alto_pan_os/.CHECKSUM
palo_alto_pan_os/bin/komand_palo_alto_pan_os
palo_alto_pan_os/help.md
palo_alto_pan_os/komand_palo_alto_pan_os/actions/set_address_object/action.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/set_address_object/schema.py
palo_alto_pan_os/plugin.spec.yaml
palo_alto_pan_os/setup.py

This change updates the PAN OS Create Address Object names to match other actions. 
NOTE: Validation errors are known validation bugs. 
```
rmt-mbp-5357:palo_alto_pan_os jmcadams$ icon-validate .
Validator "TitleValidator" failed!
Cause: ("actions key 'check_if_address_object_in_group''s title ends with period …
```

[SOAR-1308] PAN OS - fixed names

---

palo_alto_pan_os/.CHECKSUM
palo_alto_pan_os/bin/komand_palo_alto_pan_os
palo_alto_pan_os/help.md
palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_external_dynamic_list/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_to_policy/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/commit/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/delete/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/edit/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/get/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/op/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/remove_from_policy/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/retrieve_logs/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/set/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/set_address_object/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/set_security_policy_rule/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/actions/show/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/connection/schema.py
palo_alto_pan_os/plugin.spec.yaml
palo_alto_pan_os/setup.py

This PR rebrands the Palo Alto Pan-OS plugin to Palo Alto Firewall
Note: Verification errors are the result of verification bugs
```
rmt-mbp-5357:palo_alto_pan_os jmcadams$ icon-validate .
Validator "TitleValidator" failed!
Cause: ("actions key 'check_if_address_object_in_group''s title ends with period when it …
```

[SOAR-1024] - Palo Alto update PAN-OS to Firewall

---

palo_alto_pan_os/help.md

This PR fixes missing input example in Palo Alto Firewall help
None - Doc only change.

Palo Alto - fixed help

---

cylance_protect/.CHECKSUM
cylance_protect/bin/icon_cylance_protect
cylance_protect/help.md
cylance_protect/icon_cylance_protect/actions/blacklist/action.py
cylance_protect/plugin.spec.yaml
cylance_protect/setup.py

Add SHA256 input validation in Blacklist action
-
<details>
```
{
"body": {
"log": "Connect: Connecting...\nrapid7/Blackberry CylancePROTECT:1.0.0. Step name: blacklist\n",
"meta": {},
"output": {
"success": true
},
"status": "ok"
},
"type": …
```

Cylance Protect - Add SHA256 input validation in Blacklist action

---

carbon_black_cloud/.CHECKSUM
carbon_black_cloud/bin/icon_carbon_black_cloud
carbon_black_cloud/help.md
carbon_black_cloud/icon_carbon_black_cloud/connection/connection.py
carbon_black_cloud/plugin.spec.yaml
carbon_black_cloud/setup.py

This PR fixes an issue where if a retry was needed on 503, the connection would call "get" instead of "post" 
```
rmt-mbp-5357:carbon_black_cloud jmcadams$ icon-validate .
[*] Executing …
```

Carbon Black Cloud - Fixed get in retry call

---

sql/.CHECKSUM
sql/bin/komand_sql
sql/help.md
sql/komand_sql/connection/connection.py
sql/komand_sql/connection/schema.py
sql/plugin.spec.yaml
sql/setup.py

Fix issue where connection test always success
-
<details>
```
{
"body": {
"log": "Using postgres connection string...\nConnect: Connecting...\nrapid7/SQL:2.0.5. Step name: query\n{'Node Type': 'Result', 'Parallel Aware': False, 'Startup Cost': …
```

Fix issue where connection test always success

---

tools/spec_to_manifest.py

- Added more details to fields to allow initial plugin conversion of spec to manifest
```
ncramer@BOS-MBP-8176 tools % python3 ./spec_to_manifest.py /Users/ncramer/Desktop/Scripts/SpecToManifest/Plugins/basename/plugin.spec.yaml /Users/ncramer/Desktop/Scripts/SpecToManifest/Plugins/basename/
Read spec file at /Users/ncramer/Desktop/Scripts/SpecToManifest/Plugins/basename/plugin.spec.yaml
Converted fields
Wrote manifest at /Users/ncramer/Desktop/Scripts/SpecToManifest/Plugins/basename/
ncramer@BOS-MBP-8176 tools % python3 ./spec_to_manifest.py /Users/ncramer/Desktop/Scripts/SpecToManifest/Plugins/google_docs/plugin.spec.yaml /Users/ncramer/Desktop/Scripts/SpecToManifest/Plugins/google_docs/
Read spec file at …
```

Plugin spec to manifest

---

palo_alto_pan_os/.CHECKSUM
palo_alto_pan_os/bin/komand_palo_alto_pan_os
palo_alto_pan_os/help.md
palo_alto_pan_os/komand_palo_alto_pan_os/actions/set_address_object/action.py
palo_alto_pan_os/plugin.spec.yaml
palo_alto_pan_os/setup.py
palo_alto_pan_os/unit_test/test_set_address_object.py

Fix issue with IPv6 in palo alto pan os
```
RMT-X270-4700:palo_alto_pan_os jmcadams$ icon-validate .
[*] Executing validator VersionValidator
[*] …
```

[SOAR-2758] - Fix issue with IPv6 in palo alto pan os

---

whois/.CHECKSUM
whois/bin/komand_whois
whois/help.md
whois/komand_whois/actions/address/action.py
whois/komand_whois/actions/address/schema.py
whois/plugin.spec.yaml
whois/setup.py

Whois - Add input `Registrar` to `Address Lookup` action
-
<details>
```
{
"body": {
"log": "rapid7/WHOIS:3.0.0. Step name: address\nInfo: Using registry: arin\n",
"meta": {},
"output": {
"address": "1538 S Fern Dr.",
"cidr": "149.112.3.0/24", …
```

Whois - Add input Registrar to Address Lookup action

---

dig/.CHECKSUM
dig/bin/komand_dig
dig/help.md
dig/komand_dig/util/util.py
dig/plugin.spec.yaml
dig/setup.py

Dig plugin - fix bug when `answers` in function `execute_command` is str
-
<details>
```
{
"body": {
"log": "rapid7/Dig:1.0.8. Step name: forward\nExecuting command /usr/bin/dig sdf ANY\n",
"meta": {},
"output": {
"all_answers": [
"Not found" …
```

Dig plugin - fix bug when `answers` in function `execute_command` is str

---

active_directory_ldap/.CHECKSUM
active_directory_ldap/bin/komand_active_directory_ldap
active_directory_ldap/help.md
active_directory_ldap/komand_active_directory_ldap/connection/schema.py
active_directory_ldap/plugin.spec.yaml
active_directory_ldap/setup.py

This PR corrects the connection example for host in the active directory LDAP plugin. 
```
LAX-X260-3213:active_directory_ldap jmcadams$ icon-validate . …
```

SOAR-3402 - Fix AD/LDAP plugin connection documentation

---

recorded_future/.CHECKSUM
recorded_future/bin/komand_recorded_future
recorded_future/help.md
recorded_future/komand_recorded_future/actions/lookup_domain/schema.py
recorded_future/plugin.spec.yaml
recorded_future/setup.py

-
<details>
```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../tools/Makefiles/Helpers.mk ../tools/Makefiles/Colors.mk
--
[*] Running validators …
```

[MC-198] Recorded Future output bug in Lookup Domain action

---

okta/.CHECKSUM
okta/bin/komand_okta
okta/help.md
okta/komand_okta/triggers/users_added_removed_from_group/trigger.py
okta/plugin.spec.yaml
okta/setup.py

This PR adds logging to the Okta plugin to show when it has sent messages to the orchestrator
```
RMT-MBP-5357:okta jmcadams$ ./run.sh -R tests/users_added_removed_from_group.json
Running: cat tests/users_added_removed_from_group.json | docker run --rm   -i rapid7/okta:3.5.1 --debug run
This is a trigger ^C to continue
Connect: Connecting...
rapid7/Okta:3.5.1. Step name: users_added_removed_from_group
Loop complete, sleeping for 10 seconds...
Loop complete, sleeping for 10 seconds...
```

[SOAR-3716] - Add debug logging to Okta

---

proofpoint_url_defense/.CHECKSUM
proofpoint_url_defense/bin/komand_proofpoint_url_defense
proofpoint_url_defense/help.md
proofpoint_url_defense/komand_proofpoint_url_defense/actions/url_decode/action.py
proofpoint_url_defense/plugin.spec.yaml
proofpoint_url_defense/setup.py
proofpoint_url_defense/unit_test/test_url_decode.py

-
<details>
```
{
"decoded": true,
"decoded_url": "http://example.com"
}
```
<summary>
docker run --rm -i rapid7/proofpoint_url_defense:1.2.3 --debug run < tests/url_decode_http_with_one_slash.json
</summary>
</details>
<details>
```
{ …
```

Proofpoint - fix url scheme

---

active_directory_ldap/.CHECKSUM
active_directory_ldap/bin/komand_active_directory_ldap
active_directory_ldap/help.md
active_directory_ldap/komand_active_directory_ldap/actions/query/action.py
active_directory_ldap/komand_active_directory_ldap/actions/query/schema.py
active_directory_ldap/plugin.spec.yaml
active_directory_ldap/setup.py

Improve Query action in Active Directory LDAP
-
<details>
```
{
"body": {
"log": "Connecting to 10.0.2.15:10389\nConnected!\nrapid7/Active Directory LDAP:4.1.0. Step name: query\nEscaped query: (ou=people)\n",
"meta": {},
"output": { …
```

Improve Query action in Active Directory LDAP

---

datetime/.CHECKSUM
datetime/bin/komand_datetime
datetime/help.md
datetime/komand_datetime/actions/date_from_epoch/action.py
datetime/komand_datetime/actions/date_from_epoch/schema.py
datetime/plugin.spec.yaml
datetime/setup.py

Add support for epochs in milliseconds, microseconds and nanoseconds in Date from Epoch action
-
<details>
```
{
"body": {
"log": "rapid7/Datetime:3.0.0. Step name: date_from_epoch\n",
"meta": {},
"output": {
"date": …
```

Support epochs in ms, μs and ns in Date from Epoch action in Datetime plugin

---

active_directory_ldap/.CHECKSUM
active_directory_ldap/help.md
active_directory_ldap/komand_active_directory_ldap/actions/disable_user/action.py
active_directory_ldap/komand_active_directory_ldap/actions/enable_user/action.py
active_directory_ldap/komand_active_directory_ldap/actions/modify_groups/action.py
active_directory_ldap/komand_active_directory_ldap/actions/modify_object/action.py
active_directory_ldap/komand_active_directory_ldap/actions/query/action.py
active_directory_ldap/komand_active_directory_ldap/connection/connection.py
active_directory_ldap/komand_active_directory_ldap/util/utils.py
active_directory_ldap/plugin.spec.yaml
active_directory_ldap/unit_test/test_host_formatter.py
active_directory_ldap/unit_test/test_query.py

Removed trailing spaces
Move duplicate code to library
-
<details>
```
{
"body": {
"log": "Connecting to example.com:389\nConnected!\nrapid7/Active Directory LDAP:5.0.0. Step name: disable_user\nEscaped DN …
```

Number of bug fixes

---

tools/generate_custom_dictionary.py

- This change adds a script to `/tools` to generate a custom dictionary for a plugin by running `tools/generate_custom_dictionary.py -p {PLUGIN_PATH}`. Custom dictionaries are used to exempt plugin-specific words from the spellcheck validator in `insightconnect-integrations-validators`. Generated dictionaries are saved as `custom_dict.json` in the plugin directory.
Tested locally. …

SOAR-3688: Add script to generate a custom dictionary for a plugin

---

recorded_future/.CHECKSUM
recorded_future/bin/komand_recorded_future
recorded_future/help.md
recorded_future/komand_recorded_future/actions/lookup_domain/action.py
recorded_future/plugin.spec.yaml
recorded_future/setup.py

- strip `http://` and `https://` prefixes from the domain input
Assessment test details are attached in the comments below, as they were too long to be in the initial PR comment.
<details>
```
[*] Validating plugin with all validators …
```

MC-330 - Recorded Future - Lookup Domain - Improve Input Handling

---

recorded_future/.CHECKSUM
recorded_future/bin/komand_recorded_future
recorded_future/help.md
recorded_future/komand_recorded_future/actions/lookup_domain/action.py
recorded_future/plugin.spec.yaml
recorded_future/setup.py
recorded_future/unit_test/test_lookup_domain.py

This PR fixes a problem in Recorded Future Lookup Domain where if the domain ended in an s, it would strip the s...
"bob.us" would become "bob.u" 
This caused the action to fail
Note: Validator seems to be broken
```
RMT-MBP-5357:recorded_future jmcadams$ icon-validate . …
```

[SOAR-4588] Rf fix lookup domain

---

whois/.CHECKSUM
whois/bin/komand_whois
whois/help.md
whois/komand_whois/actions/address/action.py
whois/komand_whois/actions/domain/action.py
whois/plugin.spec.yaml
whois/setup.py

Add PluginException when response is empty in Domain and Address action in Whois plugin
-
<details>
```
{
"body": {
"log": "rapid7/WHOIS:3.0.3. Step name: address\nInfo: Using registry: ripe\n",
"meta": {},
"output": {
"address": "DE", …
```

Add PluginException when response is empty in Domain and Address action in Whois plugin

---

servicenow/.CHECKSUM
servicenow/bin/icon_servicenow
servicenow/help.md
servicenow/icon_servicenow/actions/create_incident/action.py
servicenow/icon_servicenow/actions/create_incident/schema.py
servicenow/icon_servicenow/connection/connection.py
servicenow/plugin.spec.yaml
servicenow/setup.py

Added `incident_url` output to Create Incident action, that will return a URL pointing to the newly created ticket.
-
<details>
```
{
"body": {
"log": "Connect: Connecting...\nrapid7/ServiceNow:5.1.0. Step name: create_incident\n", …
```

MC-348 - Service Now - Add Incident URL output to Create Incident Action

---

palo_alto_pan_os/.CHECKSUM
palo_alto_pan_os/bin/komand_palo_alto_pan_os
palo_alto_pan_os/help.md
palo_alto_pan_os/plugin.spec.yaml
palo_alto_pan_os/setup.py

Remove extra Troubleshooting section from help.md in Palo Alto PanOS plugin
-
<details>
```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../tools/Makefiles/Helpers.mk ../tools/Makefiles/Colors.mk
-- …
```

Remove extra Troubleshooting section from help.md in Palo Alto PanOS plugin

---

microsoft_teams/.CHECKSUM
microsoft_teams/bin/icon_microsoft_teams
microsoft_teams/help.md
microsoft_teams/icon_microsoft_teams/util/teams_utils.py
microsoft_teams/plugin.spec.yaml
microsoft_teams/setup.py
microsoft_teams/unit_test/test_teams_utils.py

This PR fixes an issue in Microsoft Teams where the trigger would fail if the team name had a bracket in it. 
```
RMT-MBP-5357:microsoft_teams jmcadams$ icon-validate .
[*] Executing validator CloudReadyConnectionCredentialTokenValidator …
```

[No ticket] - Fix microsoft teams for team name with bracket

---

jira/.CHECKSUM
jira/bin/komand_jira
jira/help.md
jira/komand_jira/actions/assign_issue/action.py
jira/komand_jira/actions/attach_issue/action.py
jira/komand_jira/actions/comment_issue/action.py
jira/komand_jira/actions/create_issue/action.py
jira/komand_jira/actions/create_user/action.py
jira/komand_jira/actions/delete_user/action.py
jira/komand_jira/actions/edit_issue/action.py
jira/komand_jira/actions/find_issues/action.py
jira/komand_jira/actions/find_users/action.py
jira/komand_jira/actions/get_comments/action.py
jira/komand_jira/actions/get_issue/action.py
jira/komand_jira/actions/label_issue/action.py
jira/komand_jira/actions/transition_issue/action.py
jira/komand_jira/util/api.py
jira/komand_jira/util/util.py
jira/plugin.spec.yaml
jira/setup.py

Fixed the issue, where attaching a file or creating an issue with a new file would fail.
-
<details>
```
{
"body": {
"log": "rapid7/Jira:6.0.7. Step name: attach_issue\n",
"meta": {},
"output": {
"id": "10022"
},
"status": "ok"
}, …
```

MC-394 - Jira - Adding Attachments Bug Fix

---

rest/Dockerfile
rest/komand_rest/util/util.py

Remove unused SSL code from the Rest plugin
``` 
Tested locally, had mike watch me, it works
```
NOTE: Correcting for accidental change to master.

[SOAR-5251] - Remove unused SSL code from the Rest plugin

---

rest/.CHECKSUM
rest/bin/komand_rest
rest/help.md
rest/komand_rest/util/util.py
rest/plugin.spec.yaml
rest/setup.py
rest/unit_test/test_get.py
rest/unit_test/test_utils.py

This PR fixes an issue where the Rest plugin would fail if a list was returned by a successful API call 
```
RMT-MBP-5357:rest jmcadams$ icon-validate .
[*] Executing validator CloudReadyConnectionCredentialTokenValidator
[*] …
```

[SOAR-5270] - Rest Plugin Fix non object return

---

plugins/recorded_future/.CHECKSUM
plugins/recorded_future/bin/komand_recorded_future
plugins/recorded_future/help.md
plugins/recorded_future/komand_recorded_future/actions/lookup_domain/action.py
plugins/recorded_future/komand_recorded_future/util/api.py
plugins/recorded_future/plugin.spec.yaml
plugins/recorded_future/setup.py
plugins/recorded_future/unit_test/test_get_new_alerts.py
plugins/recorded_future/unit_test/test_lookup_alert.py
plugins/recorded_future/unit_test/test_lookup_domain.py
plugins/recorded_future/unit_test/test_lookup_vulnerability.py
plugins/recorded_future/unit_test/test_search_vulnerabilities.py

Recorded Future error handling on Lookup Domain when a domain does not exist
```
Plugin Version: 5.0.1
rapid7/Recorded Future:5.0.1. Step name: lookup_domain
Looking up domain: this.is.not.a.valid.domain
Starting new HTTPS connection (1): api.recordedfuture.com:443
https://api.recordedfuture.com:443 "GET /v2/domain/this.is.not.a.valid.domain?fields=analystNotes%2Ccounts%2CenterpriseLists%2Centity%2CintelCard%2Cmetrics%2CrelatedEntities%2Crisk%2Csightings%2CthreatLists%2Ctimestamps HTTP/1.1" 404 None
An error occurred during plugin execution!
No results found.
Please provide valid inputs or verify the endpoint/URL/hostname configured in your plugin.
Response was: {"error":{"message":"Not found","status":404},"traceId":"6f107b04-e329-4aae-a03e-e0a7058efda6"}
url: …
```

[SOAR-6054] - Recorded Future error handling

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/get_incident_attachment/action.py
plugins/servicenow/icon_servicenow/actions/get_incident_attachment/schema.py
plugins/servicenow/icon_servicenow/util/request_helper.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

- This PR fixes a reported issue that the Get Incident Attachment action incorrectly parses a returned attachment type (as raw bytes) as a string.
- JIRA: https://issues.corp.rapid7.com/browse/SOAR-6617
Successfully decoded file attachment from ServiceNow by passing the attachment contents to the base64 plugin for decoding.
This proves that actions whose response content is in fact JSON gets parsed correctly.
If you are an InsightConnect customer or have access to an InsightConnect instance, …

[SOAR-6617] Fix Get Incident Attachment response type bug

---

plugins/sql/.CHECKSUM
plugins/sql/bin/komand_sql
plugins/sql/help.md
plugins/sql/komand_sql/connection/connection.py
plugins/sql/plugin.spec.yaml
plugins/sql/setup.py
plugins/sql/unit_test/test_connection.py

Add default PORT for MySQL and MSSQL connection
Add unit test for Query action
Tickets: [MC-566][MC-705] 
* Single …

Add default PORT in SQL plugin and add unit test

---

prospector.yaml

Updates prospector rules to ignore the 'inconsistent-return-statements' rule. It flags on the following code which is perfectly fine as far as I can tell (as all logic branches are exhausted/defaulted):
```
if response.status_code == 401:
raise PluginException(preset=PluginException.Preset.USERNAME_PASSWORD, data=response.text)
if response.status_code == 403:
raise PluginException(preset=PluginException.Preset.API_KEY, data=response.text)
if response.status_code == 404:
raise PluginException(preset=PluginException.Preset.NOT_FOUND, data=response.text)
if 400 <= response.status_code < 500:
raise PluginException(
preset=PluginException.Preset.UNKNOWN,
data=response.text,
)
if response.status_code >= 500:
raise PluginException(preset=PluginException.Preset.SERVER_ERROR, data=response.text) …
```

Update Prospector to Ignore 'inconsistent-return-statements'

---

plugins/palo_alto_cortex_xdr/help.md

As per Slack:
Jon Schipp:  18 hours ago
This is great. Nice work guys! One thought about this is customers can’t use tasks yet so we should create standard note in plugins docs that this is for a future feature, or hide that section until we launch Cloud Events (edited) 
Spencer Engleson  15 hours ago
@jdevlin @sdevlin @jprice could we put a very low-lift notice on "Tasks" documentation in the library? We just want users to know this is a new plugin capability that is not yet available in-product. Something along the lines of, "Plugin Tasks are currently in development! This new plugin capability will collect and deliver events to Insight products for search and use in automation workflows."

Update Palo Alto Cortex XDR help.md

---

plugins/trendmicro_deepsecurity/.CHECKSUM
plugins/trendmicro_deepsecurity/bin/icon_trendmicro_deepsecurity
plugins/trendmicro_deepsecurity/help.md
plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/deploy_rules/action.py
plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/get_rule_details/action.py
plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/list_rules/action.py
plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/search_computers/action.py
plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/search_computers/schema.py
plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/search_rules/action.py
plugins/trendmicro_deepsecurity/icon_trendmicro_deepsecurity/connection/connection.py
plugins/trendmicro_deepsecurity/plugin.spec.yaml
plugins/trendmicro_deepsecurity/requirements.txt
plugins/trendmicro_deepsecurity/setup.py

Remove the requests library 'session' as it can cause memory leaks, per 
https://github.com/psf/requests/issues/4601
Could use the .close() method on the session, but that removes the only valuable functionality that request sessions provide, so changed to using normal get and post requests. 
- …

SOAR-6425 Trendmicro Deepsecurity Fix Memory Leak- Request Session

---

plugins/cybereason/.CHECKSUM
plugins/cybereason/bin/icon_cybereason
plugins/cybereason/help.md
plugins/cybereason/plugin.spec.yaml
plugins/cybereason/setup.py

- Removes the `ISOLATE_MACHINE` remediate option for the Remediate Items action from the Cybereason documentation.
* …

Remove ISOLATE_MACHINE remediate option from Cybereason documentation

---

.github/workflows/main.yml

- Installs/upgrades `wheel` as part of the GitHub Action for plugin validation where it could fail with certain package dependencies. 
- Fixes issues like this one: https://github.com/rapid7/insightconnect-plugins/runs/4599365700?check_suite_focus=true

Fix Workflow Validator GitHub Action

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/get_attachments_for_an_incident/action.py
plugins/servicenow/icon_servicenow/actions/get_attachments_for_an_incident/schema.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py
plugins/servicenow/unit_test/test_get_attachments_for_an_incident.py

https://issues.corp.rapid7.com/browse/MC-751
- The `Get Attachments for an Incident` action will now return a list of attachments that includes the content, file name and the content type. …

[MC-751] - ServiceNow Get Attachments for an Incident

---

.github/workflows/prospector.yml

- Replace the `-r` flag in the `git diff` command with `--no-renames`. The flag `-r` is not a valid argument. The flag `--no-renames` prevents git from attempting to detect renames, which would list the old, non-existent path of a renamed file, and exclude the newly named path.
- Filter results of the `git diff` command by verifying that each path exists on disk, instead of simply checking that the path is not to a directory, which may or may not exist on the filesystem.
If you are an …

[NO-TICKET] Patch Prospector diff filter

---

.github/workflows/unit_test.yml

- Removes the `komand` module from the GitHub Actions unit test runner. This will fix dependency conflicts, fixing the unit test runner and ensuring all plugins get updated to runtime v4 in the process.

Remove komand module from unit test runner GHA

---

plugins/rest/.CHECKSUM
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/komand_rest/actions/patch/action.py
plugins/rest/komand_rest/util/util.py
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py
plugins/rest/unit_test/mockconnection.py
plugins/rest/unit_test/test_delete.py
plugins/rest/unit_test/test_get.py
plugins/rest/unit_test/test_patch.py
plugins/rest/unit_test/test_post.py
plugins/rest/unit_test/test_put.py
plugins/rest/unit_test/test_utils.py

- Fix the issue with PATCH method in REST/HTTP plugin …

SOAR [8441] - Fix issue with REST/HTTP patch method

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/put_incident_attachment/action.py
plugins/servicenow/icon_servicenow/util/request_helper.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

- Fix b64 decoding in put_incident_attachment action …

[MC-954] ServiceNow - Fix b64 decoding in put_incident_attachment action

---

plugins/fireeye_hx/icon_fireeye_hx/actions/quarantine_host/action.py
plugins/fireeye_hx/unit_test/payloads/get_containment_state.json.resp
plugins/fireeye_hx/unit_test/test_quarantine_host.py

- Add Quarantine Host action
* All …

[MC-650] Add Quarantine Host action in FireEye HX plugin

---

plugins/fireeye_hx/icon_fireeye_hx/actions/unquarantine_host/action.py
plugins/fireeye_hx/unit_test/test_unquarantine_host.py

- Add Unquarantine Host action
* All …

[MC-652] Add Unquarantine Host action in FireEye HX plugin

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
plugins/palo_alto_cortex_xdr/help.md
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_incidents/trigger.py
plugins/palo_alto_cortex_xdr/plugin.spec.yaml
plugins/palo_alto_cortex_xdr/requirements.txt
plugins/palo_alto_cortex_xdr/setup.py
plugins/palo_alto_cortex_xdr/unit_test/responses/get_incidents.json.resp
plugins/palo_alto_cortex_xdr/unit_test/test_get_incidents.py
plugins/palo_alto_cortex_xdr/unit_test/test_get_xql_query_results.py
plugins/palo_alto_cortex_xdr/unit_test/util.py

- Fix issue in Get Incidents trigger where fields with null values were causing trigger to fail
- Add unit tests for Get Incidents trigger
* All actions/triggers shortcut `icon-plugin run -T all --debug --jq` …

[MC-917] Fix Get Incidents trigger in Palo Alto Cortex XDR plugin

---

plugins/netskope/.CHECKSUM
plugins/netskope/bin/icon_netskope
plugins/netskope/help.md
plugins/netskope/icon_netskope/actions/patch_url_list_by_id/action.py
plugins/netskope/icon_netskope/actions/patch_url_list_by_id/schema.py
plugins/netskope/plugin.spec.yaml
plugins/netskope/setup.py

- Update the Update URL List By ID action to handle non-required field 'name' being empty. Previously, if left empty, the action would fail.
- Update the Update URL List By ID action to successfully update URL list by setting 'type' input to required. If 'type' input was not provided previously, the passed URLs would not be appended to or replace the original URL list. …

[SOAR-9079] Fix Update URL List By ID Non-Required Fields

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/connection/connection.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/resource_helper.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/payloads/label_006.json.resp
plugins/rapid7_insightidr/unit_test/payloads/label_007.json.resp
plugins/rapid7_insightidr/unit_test/payloads/label_404.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id2.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id3.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id4.json.resp
plugins/rapid7_insightidr/unit_test/payloads/logs.json.resp
plugins/rapid7_insightidr/unit_test/payloads/logsets.json.resp
plugins/rapid7_insightidr/unit_test/test_advanced_query_on_log_set_unit.py
plugins/rapid7_insightidr/unit_test/test_advanced_query_on_log_unit.py
plugins/rapid7_insightidr/unit_test/util.py

Change object `labels` to `[]string` in Advanced Query on Log and Advanced Query on Log Set actions and add unit tests for this case
Tickets: MC-525 and MC-595 …

Update labels in output in InsightIDR plugin

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/connection/connection.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/resource_helper.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/payloads/label_006.json.resp
plugins/rapid7_insightidr/unit_test/payloads/label_007.json.resp
plugins/rapid7_insightidr/unit_test/payloads/label_404.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id2.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id3.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id4.json.resp
plugins/rapid7_insightidr/unit_test/payloads/logs.json.resp
plugins/rapid7_insightidr/unit_test/payloads/logsets.json.resp
plugins/rapid7_insightidr/unit_test/test_advanced_query_on_log_set_unit.py
plugins/rapid7_insightidr/unit_test/test_advanced_query_on_log_unit.py
plugins/rapid7_insightidr/unit_test/util.py

- Change object `labels` to `[]string` in Advanced Query on Log and Advanced Query on Log Set actions in InsightIDR plugin
- This is a **patch fix** that solves almost all errors relating to labels, but may still cause errors in rare edge cases. A full fix to the underlying issues will be released in the next major release. End users should update the InsightIDR plugin to version 4.0.0 when it becomes available.
JIRA:
- https://issues.corp.rapid7.com/browse/MC-525
- https://issues.corp.rapid7.com/browse/MC-595
- https://issues.corp.rapid7.com/browse/SOAR-7544 …

InsightIDR patch update (#965)

---

plugins/automox/.CHECKSUM
plugins/automox/bin/icon_automox
plugins/automox/help.md
plugins/automox/icon_automox/actions/list_devices/action.py
plugins/automox/icon_automox/connection/connection.py
plugins/automox/icon_automox/util/api_client.py
plugins/automox/plugin.spec.yaml
plugins/automox/setup.py

- No longer send org ID with requests when it is not defined for actions; currently sends org ID 0
- Update user-agent version
- Add connection outcome recording for adoption visibility …

Fix issue where undefined org ID is sent as zero value instead of non

---

plugins/automox/.CHECKSUM
plugins/automox/bin/icon_automox
plugins/automox/help.md
plugins/automox/icon_automox/actions/list_devices/action.py
plugins/automox/icon_automox/connection/connection.py
plugins/automox/icon_automox/util/api_client.py
plugins/automox/plugin.spec.yaml
plugins/automox/setup.py

- Release https://github.com/rapid7/insightconnect-plugins/pull/1305 same as https://github.com/rapid7/insightconnect-plugins/pull/1226
- No longer send org ID with requests when it is not defined for actions; currently sends org ID 0
- Update user-agent version
- Add connection outcome recording for adoption visibility …

Automox plugin patch update (#1305)

---

plugins/rest/.CHECKSUM
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/komand_rest/actions/patch/action.py
plugins/rest/komand_rest/actions/patch/schema.py
plugins/rest/komand_rest/actions/post/action.py
plugins/rest/komand_rest/util/util.py
plugins/rest/plugin.spec.yaml
plugins/rest/requirements.txt
plugins/rest/setup.py
plugins/rest/unit_test/test_patch.py
plugins/rest/unit_test/test_post.py
plugins/rest/unit_test/test_utils.py

* Update help.md
* Add new input body of array to support array objects in the patch request
* Add support for x-www-form-urlencoded in the POST action
-
* All actions/triggers shortcut `icon-plugin run -T all …

SOAR-8722 HTTPRest - New Branch (#1333)

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/bin/icon_microsoft_teams
plugins/microsoft_teams/help.md
plugins/microsoft_teams/icon_microsoft_teams/actions/create_teams_enabled_group/schema.py
plugins/microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
plugins/microsoft_teams/plugin.spec.yaml
plugins/microsoft_teams/setup.py
plugins/microsoft_teams/unit_test/payloads/get_group_id_from_name.json.resp
plugins/microsoft_teams/unit_test/payloads/get_members.json.resp
plugins/microsoft_teams/unit_test/payloads/get_user_info.json.resp
plugins/microsoft_teams/unit_test/test_add_group_owner.py
plugins/microsoft_teams/unit_test/test_add_member_to_channel.py
plugins/microsoft_teams/unit_test/util.py

- Fix issue with Create Teams Enabled Group action input types …

[SOAR-8968] Microsoft Teams - Fix issue with Create Teams Enabled Group action input types

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/endpoints.py
plugins/rapid7_insightidr/plugin.spec.yaml

- Cloud_ready flag set to true
- Fix issue with NoneType object in Advanced query on log action
* Single …

Insight IDR - 10421 - Enabled could_ready flag, fix issue with NoneType object in advanced query on log action

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/help.md
plugins/active_directory_ldap/komand_active_directory_ldap/actions/modify_object/action.py
plugins/active_directory_ldap/komand_active_directory_ldap/util/api.py
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/setup.py

- Fix issue with modify object action
- Enhanced LDAP logging (Extended for Query action, and for docker container logs)
- Fix issue with variable error when connection fails …

[SOAR-10021] Active Directory LDAP - Fix issue with modify object action, enhanced LDAP logging, fix issue with variable error when connection fails

---

plugins/any_run/.CHECKSUM
plugins/any_run/bin/icon_any_run
plugins/any_run/help.md
plugins/any_run/icon_any_run/util/api.py
plugins/any_run/plugin.spec.yaml
plugins/any_run/setup.py
plugins/any_run/unit_test/util.py

- Fix for run analysis on file defaulting to windows 7 32-bit on any.run platform …

[SOAR-10246] - Any.Run OS params fix

---

plugins/powershell/help.md
plugins/powershell/komand_powershell/util/util.py

This PR removes the mismatch between the default behavior of port 5985 and the plugin.  The plugin now checks if it's working on port 5985
- check if port is 5985 and if it is, don't require ssl
* All …

remove requirement that SSL be used on default http port

---

plugins/darktrace/.CHECKSUM
plugins/darktrace/bin/icon_darktrace
plugins/darktrace/help.md
plugins/darktrace/icon_darktrace/connection/connection.py
plugins/darktrace/icon_darktrace/connection/schema.py
plugins/darktrace/icon_darktrace/triggers/pull_alerts/schema.py
plugins/darktrace/icon_darktrace/triggers/pull_alerts/trigger.py
plugins/darktrace/icon_darktrace/util/api.py
plugins/darktrace/plugin.spec.yaml
plugins/darktrace/requirements.txt
plugins/darktrace/setup.py
plugins/darktrace/unit_test/__init__.py
plugins/darktrace/unit_test/mock.py
plugins/darktrace/unit_test/responses/get_status.json.resp
plugins/darktrace/unit_test/responses/invalid_json.json.resp
plugins/darktrace/unit_test/responses/pull_alerts.json.resp
plugins/darktrace/unit_test/responses/update_watched_domains.json.resp
plugins/darktrace/unit_test/test_connection.py
plugins/darktrace/unit_test/test_pull_alerts.py
plugins/darktrace/unit_test/test_update_watched_domains.py

- Added verify SSL certificate boolean field to the plugin connection …

[SOAR-10434] - Darktrace SSL verification field

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/connection/connection.py
plugins/servicenow/icon_servicenow/connection/schema.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py
plugins/servicenow/unit_test/util.py

- Cloud enabled | Changed connection input `URL` to `instance` …

[SOAR-8054] Servicenow - Cloud enabled | Changed connection input

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/get_all_saved_queries/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/connection/connection.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/endpoints.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/mock.py
plugins/rapid7_insightidr/unit_test/util.py

- Fix issue with Get Query Logs and Get All Saved Queries actions …

[SOAR-10641] Insight IDR - Fix issue with Get Query Results and Get All Saved Queries actions

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/bin/komand_sentinelone
plugins/sentinelone/help.md
plugins/sentinelone/komand_sentinelone/actions/blacklist/action.py
plugins/sentinelone/komand_sentinelone/actions/blacklist/schema.py
plugins/sentinelone/komand_sentinelone/actions/quarantine/action.py
plugins/sentinelone/komand_sentinelone/actions/update_analyst_verdict/action.py
plugins/sentinelone/komand_sentinelone/actions/update_analyst_verdict/schema.py
plugins/sentinelone/komand_sentinelone/actions/update_incident_status/action.py
plugins/sentinelone/komand_sentinelone/actions/update_incident_status/schema.py
plugins/sentinelone/komand_sentinelone/connection/connection.py
plugins/sentinelone/komand_sentinelone/util/helper.py
plugins/sentinelone/plugin.spec.yaml
plugins/sentinelone/requirements.txt
plugins/sentinelone/setup.py
plugins/sentinelone/unit_test/payloads/alerts_non_existing.json.resp
plugins/sentinelone/unit_test/test_blacklist.py
plugins/sentinelone/unit_test/test_update_analyst_verdict.py
plugins/sentinelone/unit_test/test_update_incident_status.py
plugins/sentinelone/unit_test/util.py

- Blacklist action: Fix for unblocked action
- Update Analyst Verdict action: Accepting only single thread ID in order to standardize inputs 
- Update Incident Status action: Accepting only single thread ID in order to standardize inputs
- Quarantine action: unification of the output data when action fails …

[PLGN-29][PLGN-30][PLGN-33] Sentinelone Plugin actions update

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/icon_python_3_script/actions/run/action.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py
plugins/python_3_script/unit_test/test_run.py

- Run: Updated indentation fix for input function when user has non-empty credentials …

Python 3 Script - Updated indentation fix

---

plugins/threatcrowd/.CHECKSUM
plugins/threatcrowd/bin/icon_threatcrowd
plugins/threatcrowd/help.md
plugins/threatcrowd/icon_threatcrowd/connection/connection.py
plugins/threatcrowd/icon_threatcrowd/connection/schema.py
plugins/threatcrowd/icon_threatcrowd/util/api.py
plugins/threatcrowd/plugin.spec.yaml
plugins/threatcrowd/requirements.txt
plugins/threatcrowd/setup.py
plugins/threatcrowd/unit_test/mock.py
plugins/threatcrowd/unit_test/responses/address.json.resp
plugins/threatcrowd/unit_test/responses/av.json.resp
plugins/threatcrowd/unit_test/responses/domain.json.resp
plugins/threatcrowd/unit_test/responses/email.json.resp
plugins/threatcrowd/unit_test/responses/empty_response.json.resp
plugins/threatcrowd/unit_test/responses/hash.json.resp
plugins/threatcrowd/unit_test/responses/invalid_json.json.resp
plugins/threatcrowd/unit_test/test_address.py
plugins/threatcrowd/unit_test/test_av.py
plugins/threatcrowd/unit_test/test_connection.py
plugins/threatcrowd/unit_test/test_domain.py
plugins/threatcrowd/unit_test/test_email.py
plugins/threatcrowd/unit_test/test_hash.py
plugins/threatcrowd/unit_test/test_votes.py

- Added SSL verification field to the connection part of the plugin
- Added unittests …

[PLGN-16] Threatcrowd -  Added SSL verification field to the connection part of the plugin

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/bin/icon_microsoft_teams
plugins/microsoft_teams/help.md
plugins/microsoft_teams/icon_microsoft_teams/triggers/new_message_received/trigger.py
plugins/microsoft_teams/plugin.spec.yaml
plugins/microsoft_teams/setup.py
plugins/microsoft_teams/unit_test/payloads/get_messages.json
plugins/microsoft_teams/unit_test/test_add_channel_to_team.py
plugins/microsoft_teams/unit_test/test_add_group_owner.py
plugins/microsoft_teams/unit_test/test_add_member_to_channel.py
plugins/microsoft_teams/unit_test/test_new_message_received.py
plugins/microsoft_teams/unit_test/test_send_message.py
plugins/microsoft_teams/unit_test/test_strip_html.py
plugins/microsoft_teams/unit_test/util.py

- Fixed issue where `font-size` value appeared in the urls, and domains output fields  …

[PLGN-57] Microsoft Teams - Fixed issue where `font-size` value appeared in the urls, and domains output fields

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/plugin.spec.yaml
plugins/whois/setup.py
plugins/whois/whois.conf

-  monster and nl tlds
*Regarding failed validator:*
https://rapid7.slack.com/archives/G0121JRRYF9/p1669209556869009
Apparently the os dependency was added before and now we have to live with it.
*Regarding failed unit-test:*
Github action does not have python-whois package installed so it cant perform unit-tests.

[PLGN-31] whois - Add .monster and .nl tld (#1496)

---

plugins/cisco_firepower_management_center/.CHECKSUM
plugins/cisco_firepower_management_center/bin/icon_cisco_firepower_management_center
plugins/cisco_firepower_management_center/help.md
plugins/cisco_firepower_management_center/icon_cisco_firepower_management_center/actions/add_address_to_group/action.py
plugins/cisco_firepower_management_center/plugin.spec.yaml
plugins/cisco_firepower_management_center/requirements.txt
plugins/cisco_firepower_management_center/setup.py
plugins/cisco_firepower_management_center/unit_test/parameters/add_address_to_group.json.resp
plugins/cisco_firepower_management_center/unit_test/responses/add_address_to_group_empty_objects.json.resp
plugins/cisco_firepower_management_center/unit_test/responses/get_address_groups.json.resp
plugins/cisco_firepower_management_center/unit_test/util.py

- Fix 'Key Error' in Add Address to Group action causing action failure …

[PLGN-109] Cisco Firepower Management Center - Add Address to Group (Key Error)

---

plugins/cisco_firepower_management_center/.CHECKSUM
plugins/cisco_firepower_management_center/bin/icon_cisco_firepower_management_center
plugins/cisco_firepower_management_center/help.md
plugins/cisco_firepower_management_center/icon_cisco_firepower_management_center/actions/add_address_to_group/action.py
plugins/cisco_firepower_management_center/plugin.spec.yaml
plugins/cisco_firepower_management_center/requirements.txt
plugins/cisco_firepower_management_center/setup.py
plugins/cisco_firepower_management_center/unit_test/parameters/add_address_to_group.json.resp
plugins/cisco_firepower_management_center/unit_test/responses/add_address_to_group_empty_objects.json.resp
plugins/cisco_firepower_management_center/unit_test/responses/get_address_groups.json.resp
plugins/cisco_firepower_management_center/unit_test/util.py

…Key Error) (#1564)
* Set default "objects" in address_group in action AddAddressToGroup
* Update help.md version
* Update pyOpenSSL version
* Update Unit Test
- Prevent Key Error in Group with no Address Objects when adding Address Object to Group …

[PLGN-109] Cisco Firepower Management Center - Release

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py

- Fix incorrect behavior for unquarantine when the agent ID is wrong …

Release Insight Agent - Fix incorrect behavior for unquarantine when the agent ID is wrong

---

plugins/jira/.CHECKSUM
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/actions/create_issue/action.py
plugins/jira/komand_jira/util/util.py
plugins/jira/plugin.spec.yaml
plugins/jira/setup.py
plugins/jira/unit_test/test_create_issue.py

- Create Issue fails when Issue Types that hold the same name in Jira exist. Update to change Issue Type Validation.
* …

[PLGN-123] Jira - Create Issue Failure on Multiple Existing Issue Type

---

plugins/powershell/.CHECKSUM
plugins/powershell/bin/icon_powershell
plugins/powershell/bin/komand_powershell
plugins/powershell/help.md
plugins/powershell/icon_powershell/util/util.py
plugins/powershell/plugin.spec.yaml
plugins/powershell/requirements.txt
plugins/powershell/setup.py
plugins/powershell/unit_test/test_util.py

- Fix issue where single quotes in script password causes parsing error …

[PLGN-58] - PowerShell password bug fix

---

plugins/cisco_umbrella_reporting/.CHECKSUM
plugins/cisco_umbrella_reporting/bin/icon_cisco_umbrella_reporting
plugins/cisco_umbrella_reporting/help.md
plugins/cisco_umbrella_reporting/plugin.spec.yaml
plugins/cisco_umbrella_reporting/requirements.txt
plugins/cisco_umbrella_reporting/setup.py
plugins/cisco_umbrella_reporting/unit_test/mock.py
plugins/cisco_umbrella_reporting/unit_test/responses/get_domain_visits.json.resp
plugins/cisco_umbrella_reporting/unit_test/test_get_domain_visits.py

- Update docs to let user know to use legacy API key since reporting is currently using v1 api.
- Added unit tests
* …

[PLGN-164] Cisco Umbrella Reporting - Updated docs with links

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/help.md
plugins/sentinelone/komand_sentinelone/triggers/get_threats/schema.py
plugins/sentinelone/plugin.spec.yaml

**Background:**
The description for the 'Resolved' field in the Trigger was causing confusion - 'Include resolved threats' gave the impression that both resolved and unresolved would be included if True was set however setting this to True causes the underlying API to only return resolved threats. 
**Solution:**
Updated the description and added a note to the troubleshooting guide. 
**Note:**
No update to the version history as this will be wrapped up with an existing SentinelOne update (version 8.1.0).

[PLGN-175] Update Sentinelone trigger info

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_alerts_for_investigation/action.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/mock.py
plugins/rapid7_insightidr/unit_test/payloads/list_alerts_for_investigation_rrn_as_object.json.resp
plugins/rapid7_insightidr/unit_test/test_list_alerts_for_investigation.py

- The API of InsightIDR is very inconsistent, for detection rule sometimes we retrieve `detection_rule_rrn` as string, but sometimes as object. The change is about, in scenario when API retrieve object we fetch only `rule_rrn` filed as string. …

[PLGN-195] InsightIDR List Alerts for Investigation fix issue

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_alerts_for_investigation/action.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/mock.py
plugins/rapid7_insightidr/unit_test/payloads/list_alerts_for_investigation_rrn_as_object.json.resp
plugins/rapid7_insightidr/unit_test/test_list_alerts_for_investigation.py

- The API of InsightIDR is very inconsistent, for detection rule sometimes we retrieve `detection_rule_rrn` as string, but sometimes as object. The change is about, in scenario when API retrieve object we fetch only `rule_rrn` filed as string. …

[PLGN-195] InsightIDR Plugin 4.4.1 - Release

---

plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/icon_zoom/util/api.py
plugins/zoom/unit_test/mock.py
plugins/zoom/unit_test/test_api.py
plugins/zoom/unit_test/test_create_user.py
plugins/zoom/unit_test/test_delete_user.py
plugins/zoom/unit_test/test_get_user.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

- Updates Zoom authentication logic to re-authenticate only when needed
- Updates datetime calls to use a timezone to improve time accuracy
* All actions/triggers shortcut `icon-plugin run -T all --debug --jq` …

SOAR-13594: Zoom auth update

---

plugins/zoom/.CHECKSUM
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/connection/connection.py
plugins/zoom/icon_zoom/connection/schema.py
plugins/zoom/icon_zoom/util/api.py
plugins/zoom/icon_zoom/util/util.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/requirements.txt
plugins/zoom/setup.py
plugins/zoom/unit_test/mock.py
plugins/zoom/unit_test/test_api.py
plugins/zoom/unit_test/test_create_user.py
plugins/zoom/unit_test/test_delete_user.py
plugins/zoom/unit_test/test_get_user.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

- Improves OAuth authentication logic to help mitigate infinite looping
- Adds back JWT authentication to possible connection configurations until OAuth token invalidation is fully solved. Please note: JWT auth will become unavailable in June 2023.
Task with JWT Authentication
Task with OAuth Authentication …

SOAR-13594,13667: Update Zoom Auth and Add JWT

---

plugins/thehive/.CHECKSUM
plugins/thehive/help.md
plugins/thehive/komand_thehive/actions/create_case/schema.py
plugins/thehive/komand_thehive/actions/create_case_observable/schema.py
plugins/thehive/komand_thehive/actions/create_case_task/schema.py
plugins/thehive/komand_thehive/connection/connection.py
plugins/thehive/komand_thehive/connection/schema.py
plugins/thehive/komand_thehive/util/api.py
plugins/thehive/plugin.spec.yaml

- Fixes for theHive to patch issues that only occurred during testing on IC.
- Fix API key usage
- Fixes to descriptions 
* All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at …

More theHive fixes

---

plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py

- reduced the maximum number of results returned per run in Monitor Events task …

[MC-1454]  Reduced number of results returned in Monitor Events task in Proofpoint plugin

---

plugins/mimecast/komand_mimecast/util/api.py

- handled error messaging in cause field …

[PLGN-294] Mimecast handle messaging in cause field

---

plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/unit_test/test_response_status_code_handling.py

- update message when status code are 401 and 403  …

[PLGN-294] Mimecast update message for 401 and 403

---

plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/komand_okta/util/api.py
plugins/okta/unit_test/test_add_user_to_group.py
plugins/okta/unit_test/test_assign_user_to_app_sso.py
plugins/okta/unit_test/test_deactivate_user.py
plugins/okta/unit_test/test_delete_user.py
plugins/okta/unit_test/test_get_factors.py
plugins/okta/unit_test/test_get_user.py
plugins/okta/unit_test/test_get_user_groups.py
plugins/okta/unit_test/test_remove_user_from_group.py
plugins/okta/unit_test/test_reset_factors.py
plugins/okta/unit_test/test_reset_password.py
plugins/okta/unit_test/test_send_push.py
plugins/okta/unit_test/test_suspend_user.py
plugins/okta/unit_test/test_unsuspend_user.py

- turn off rate limiting function for task …

[PLGN-308] Okta plugin - remove rate liming for tasks

---

plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/komand_proofpoint_tap/util/api.py
plugins/proofpoint_tap/unit_test/test_fetch_forensics.py

- remove rate limiting function in task …

[PLGN-310] Proofpoint - remove rate limiting

---

plugins/trendmicro_visionone/unit_test/test_add_alert_note.py
plugins/trendmicro_visionone/unit_test/test_add_to_block_list.py
plugins/trendmicro_visionone/unit_test/test_add_to_exception_list.py
plugins/trendmicro_visionone/unit_test/test_add_to_suspicious_list.py
plugins/trendmicro_visionone/unit_test/test_collect_file.py
plugins/trendmicro_visionone/unit_test/test_delete_email_message.py
plugins/trendmicro_visionone/unit_test/test_disable_account.py
plugins/trendmicro_visionone/unit_test/test_download_sandbox_analysis_result.py
plugins/trendmicro_visionone/unit_test/test_download_sandbox_investigation_package.py
plugins/trendmicro_visionone/unit_test/test_edit_alert_status.py
plugins/trendmicro_visionone/unit_test/test_enable_account.py
plugins/trendmicro_visionone/unit_test/test_get_alert_details.py
plugins/trendmicro_visionone/unit_test/test_get_sandbox_analysis_result.py
plugins/trendmicro_visionone/unit_test/test_get_sandbox_submission_status.py
plugins/trendmicro_visionone/unit_test/test_get_sandbox_suspicious_list.py
plugins/trendmicro_visionone/unit_test/test_get_task_result.py
plugins/trendmicro_visionone/unit_test/test_isolate_endpoint.py
plugins/trendmicro_visionone/unit_test/test_poll_sandbox_suspicious_list.py
plugins/trendmicro_visionone/unit_test/test_quarantine_email_message.py
plugins/trendmicro_visionone/unit_test/test_remove_from_block_list.py
plugins/trendmicro_visionone/unit_test/test_remove_from_exception_list.py
plugins/trendmicro_visionone/unit_test/test_remove_from_suspicious_list.py
plugins/trendmicro_visionone/unit_test/test_reset_password_account.py
plugins/trendmicro_visionone/unit_test/test_restore_email_message.py
plugins/trendmicro_visionone/unit_test/test_restore_endpoint.py
plugins/trendmicro_visionone/unit_test/test_sign_out_account.py
plugins/trendmicro_visionone/unit_test/test_submit_file_to_sandbox.py
plugins/trendmicro_visionone/unit_test/test_submit_urls_to_sandbox.py
plugins/trendmicro_visionone/unit_test/test_terminate_process.py

Adding the @skip flag to unit tests that are actually reaching out as we don't want this to happen, and they also are hitting an endpoint that is now returning a 502 error which is causing the unit tests to fail. 
Allow all github actions to now pass so that we can release the plugin. Once the release happens and we ask trend micro to verify we can then mention that these tests should be removed or updated for the next release. 
Github actions now [passing](https://github.com/rapid7/insightconnect-plugins/actions/runs/5865671886/job/15903022167) where previously they were failing. 
Passing on github action and locally:
Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-gen …

PLGN-342: disable integration tests for trend micro vision one

---

plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/komand_salesforce/util/event.py

PLGN-380 Salesforce - add de-duping

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py

Update handling of timestamp functionality with tasks:
- Ensure that the auth logs are ordered ascending in timestamp
- Change now time to 2 mins ago instead of 1 minute as suggested should be the case in the Duo docs 
- Split into maintaining three timestamps - one per log type
- Change the timestamp used to the latest log time instead of the max window time
- Backwards compatibility with the older one last collection timestamp method
- Add additional logging for debug purposes. 
NoteL To minimise risk, have tried to keep changes to a minimum. Also updated unit tests will come after in a subsequent PR.  Schema manually updated with ticket already raised around tooling fix required.

[PLGN-423]Updated timestamp handling

---

plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py

Updated backward compatibility with state with last collection timestamp already available.
Updated trust event monitor to look for surfaced_timestamp
Added cutoff time in case of event collection pause. 
Note: Unit tests to be addressed separately. Plugvalidator failing due to manual change of task schema file.

[PLGN-423] Duo admin timestamp original timestamp compatibility

---

plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/unit_test/test_monitor_logs.py

Collector code when querying Okta will never query beyond 24 hours. Update plugin logic to match this. 
- If a customer has paused the task from running and resumes days/weeks/months later we don't want to resume the polling logic from when it was paused. In this case we want to drop that saved timestamp and only query from the last 24 hours - in essence following the workflow of a first iteration. 
- For pagination customers can't pause when there is next pages as in the [flowchart](https://miro.com/app/board/uXjVOCDYIyA=/?moveToWidget=3458764526762399018&cot=14&share_link_id=387182528433) when the task returns `has_more_pages`, it queues the next iteration/page.
- in the collector code this differs slightly in that we run one large execution of the task, …

PLGN-398: add logic to prevent searching beyond 24 hours

---

plugins/basename/.CHECKSUM
plugins/basename/bin/komand_basename
plugins/basename/help.md
plugins/basename/plugin.spec.yaml
plugins/basename/setup.py

- Added empty `__inti__.py` file into `unit_test` folder, version bump and refresh with new tooling.
* Single …

[SOAR-15498] Basename Version Bump

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py
plugins/okta/unit_test/expected/get_logs_next_page.json.exp
plugins/okta/unit_test/test_monitor_logs.py
plugins/okta/unit_test/util.py

Release PR - Okta 4.2.2
PRs:
- #2030 
Changes:
- Only apply filtering logic if the request to Okta has not been carried out using the `next_page` value. 
Testing:
- Deployed to staging and logs are looking as expected. 
- Unable to hit new logger on staging: `next_page value used to poll from Okta. Returning x event(s) from response.` as dev instance only seems to create 8 log events per log in action and pagination is triggered at +1000 events. (verified in unit tests). 
- Unable to test edge case of two events on separate pages at the exact time.

Okta 4.2.2. Release - PLGN-431 - improved monitor log task. 

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/schema.py
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/komand_mimecast/util/constants.py
plugins/mimecast/plugin.spec.yaml

- Removed `token` input parameter
- Updated pagination handler
Snyk found a problem related to the unzipping file mechanism, which pulls the content from the response and unzips the attachment. Snyk thinks that there is a possibility that its allowed to do path traversal in this code, but its not. We pull the response content into the `BytesIO` to load the attachment into RAM, and then unzip that memory. In this case there is no access to the file system etc.
If you are an InsightConnect …

[PLGN-425] Mimecast - Updated pagination handler | Removed token input parameter

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/connection/schema.py
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/schema.py
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/komand_mimecast/util/constants.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py

Release of Mimecast 5.3.2. 
Changes:
- Add all regions of Mimecast: USB, and USBCOM was previously not supported. 
- Add extra logs around monitor logs task to help in future with any C2C investigation. 
- Updated pagination handler
- Removed `token` input
- Changed max request time to 30s
Notes:
- This is cloud enabled. 
Original PR:
- #2039
- #2068
- #2078

Mimecast 5.3.2 Release (PLGN-434)

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/schema.py
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/komand_duo_admin/util/api.py
plugins/duo_admin/komand_duo_admin/util/endpoints.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/test_add_user.py
plugins/duo_admin/unit_test/test_enroll_user.py
plugins/duo_admin/unit_test/test_get_logs.py
plugins/duo_admin/unit_test/test_get_phones_by_user_id.py
plugins/duo_admin/unit_test/test_get_user_by_id.py
plugins/duo_admin/unit_test/test_get_user_by_username.py
plugins/duo_admin/unit_test/test_get_user_status.py
plugins/duo_admin/unit_test/test_get_users.py
plugins/duo_admin/unit_test/test_modify_user.py
plugins/duo_admin/unit_test/test_monitor_logs.py

**Background and Solution**
Currently the Duo Admin task assume that the user has access to admin logs and trust monitor events. However this will depend on the level of licensing. If a 403 error is received from either of these endpoints, an error should be logged and then continue on to gather data which they have access to e.g. auth logs. 
Also add in boolean task inputs so that the UI can be updated to allow the collection of trust monitor events and admin logs to be configurable. This has been coded so that these default to True currently so that the code will function as normal until the UI is updated. 
**Testing**
Tested locally using Postman calls against the task with and without task inputs for the collect logs and events. Mocked the 403 failures by changing out error code …

[PLGN-611] Duo Admin Task Handle 403 errors and allow configuration of event and log gathering

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

- To increase the max per page size from the default of 50 to 500
- To add this behaviour into the documentation
- To add in a logger message to reflect when there are more results that were not returned
https://issues.corp.rapid7.com/browse/PLGN-252
all unit tests passed
```
Ran 80 tests in 0.034s
OK
```
testing in local docker container using postman to make the …

PLGN-251-Increasing the maximum results per call from 50 to 500 and adding in log if there is more than 500

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

Plugin release for  - https://github.com/rapid7/insightconnect-plugins/pull/2104
- To increase the max per page size from the default of 50 to 500
- To add this behaviour into the documentation
- To add in a logger message to reflect when there are more results that were not returned
https://issues.corp.rapid7.com/browse/PLGN-252
all unit tests passed
```
Ran 80 tests in 0.034s
OK
```
If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product …

[PLGN-252] IDR 6.0.1 release

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/payloads/log_id5.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id6.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id7.json.resp
plugins/rapid7_insightidr/unit_test/payloads/log_id8.json.resp
plugins/rapid7_insightidr/unit_test/payloads/logsets.json.resp
plugins/rapid7_insightidr/unit_test/test_advanced_query_on_log_set_unit.py
plugins/rapid7_insightidr/unit_test/util.py

- to take the id that comes back from calling the `/query/logs` endpoint, then this ID can be used to the `/query/` endpoint to get back the correct values for the statistics, as the will not return the results we need
new unit test have been added and all of the old tests are passing 
```
Ran 82 tests in 0.038s
OK
```
testing via postman using a local docker …

[SOAR-15940] InsightIDR - advanced_query_on_log_set statistical result bug fix

---

.github/workflows/plugin_production_build.yml
.github/workflows/plugin_staging_build.yml

- Add workflow to build and tag plugin images for production and staging …

Plugin build workflow release

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/payloads/logs.json.resp
plugins/rapid7_insightidr/unit_test/test_advanced_query_on_log_unit.py
plugins/rapid7_insightidr/unit_test/util.py

making sure that there is feature parity between `advanced_query_on_log_set` and `advanced_query_on_log` action 
- add in params["per_page"] = 500 to `advanced_query_on_log_set` and added to documentation 
- fix issue with `advanced_query_on_log_set` where if a call back url was used, incorrect results were returned 
- added example for `results_statistical`  to help md 
- add in statistical results to `advanced_query_on_log`
- added unit tests for new functional
- fix issue with advanced_query_on_log where if a call back url was used, incorrect results were returned 
Note this be released at the same time as https://github.com/rapid7/insightconnect-plugins/pull/2108, as a result the versoin number for the other pr has been overwritten to 7.0.0, rather than …

[PLGN-614] InsightIDR - Adding parity between advanced_query_on_log_set and advanced_query_on_log

---

plugins/rest/.CHECKSUM
plugins/rest/Dockerfile
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/komand_rest/util/util.py
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py
plugins/rest/unit_test/test_utils.py

Essentially what is happening is that we cannot pass the API Key from the input into the Authentication header if the header value includes a prefix ie 
"Authorization": "ApiKey CUSTOM_SECRET_INPUT"
- The current code checks to see if the header equals CUSTOM_SECRET_INPUT but if you enter a prefix then it does not. I have changed this so the code checks if the head contains CUSTOM_SECRET_INPUT instead.
If you are an InsightConnect customer or have access to an InsightConnect instance, the …

[PLGN-45] Custom Auth prefix bug

---

plugins/rest/.CHECKSUM
plugins/rest/Dockerfile
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/komand_rest/util/util.py
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py
plugins/rest/unit_test/test_utils.py

- Fixes bug where Custom Auth does not work if a prefix is added. …

[PLGN-45]- Rest 6.4 Release

---

tools/update-tools.sh

* Initial commit
* Added comments on next steps
* Update script
* Move pip install and remove comments
* update loggers
-
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR …

[SOAR-14960] Update Install Script (#1924)

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py

- add logs when we raise an exception so we can trace this back if needed. 
- bump SDK version so that we log when the task has started/finished. 
- fixed md5sum for schema as was failing validation. 
Logging evidence of exception raised from plugin (AnAPI Exception has been raised) and SDK (plugin exception instantiated):
```
Connect: Connecting...
rapid7/Duo Admin API:4.3.1. Step name: monitor_logs
Previous timestamps retrieved. Auth None. Admin: None. Trust monitor None.
First run for Trust monitor events
Retrieve …
```

PLGN-633: add exception logging and bump SDK.

---

plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/asset_search/action.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/util/resource_requests.py

- Investigate and fix a customer issue regarding a json decode error returned when using the `Asset Search` action.
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR format at …

[PLGN-634] InsightVM - Asset Search | JsonDecode Error

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/Dockerfile
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/get_incident_comments_worknotes/schema.py
plugins/servicenow/icon_servicenow/connection/connection.py
plugins/servicenow/icon_servicenow/connection/schema.py
plugins/servicenow/icon_servicenow/triggers/incident_created/trigger.py
plugins/servicenow/icon_servicenow/util/request_helper.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py
plugins/servicenow/unit_test/payloads/get_oauth_token.json.resp
plugins/servicenow/unit_test/test_create_change_request.py
plugins/servicenow/unit_test/test_create_security_incident.py
plugins/servicenow/unit_test/test_create_vulnerability.py
plugins/servicenow/unit_test/test_delete_security_incident.py
plugins/servicenow/unit_test/test_delete_vulnerability.py
plugins/servicenow/unit_test/test_get_attachments_for_an_incident.py
plugins/servicenow/unit_test/test_get_incident_attachment.py
plugins/servicenow/unit_test/test_get_security_incident.py
plugins/servicenow/unit_test/test_get_vulnerability.py
plugins/servicenow/unit_test/test_search_security_incident.py
plugins/servicenow/unit_test/test_update_security_incident.py
plugins/servicenow/unit_test/test_update_vulnerability.py
plugins/servicenow/unit_test/util.py

- Added `OAuth` authentication to the plugin …

[PLGN-621] Add OAuth to ServiceNow Plugin (#2157)

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py

Release of Duo Admin v4.3.1
Changes:
- Bump SDK version to get latest image: containing new logging around tasks. 
-  Add logging in both exceptions of the task. 
Original PR:
- #2814
Testing:
- C2C task running as expected, any exceptions (429 from testing) is now logged. 
- PLugin actions verified as passing on new workflow.

Duo Admin 4.3.1 Release

---

plugins/abnormal_security/.CHECKSUM
plugins/abnormal_security/bin/icon_abnormal_security
plugins/abnormal_security/help.md
plugins/abnormal_security/icon_abnormal_security/util/api.py
plugins/abnormal_security/plugin.spec.yaml
plugins/abnormal_security/setup.py

- https://github.com/rapid7/insightconnect-plugins/pull/2196 
- user entered 2023-01-01T21:11:38Z the value of 2023-01-01T21:11:38:00:00 was being passed to the abnormal api and failing, so the plan is to just pass the users timestamp directly to the api with no parsing on our end

Abnormal Security v2.0.1 release

---

plugins/thehive/.CHECKSUM
plugins/thehive/Dockerfile
plugins/thehive/bin/komand_thehive
plugins/thehive/help.md
plugins/thehive/plugin.spec.yaml
plugins/thehive/requirements.txt
plugins/thehive/setup.py

---------
- Update requests module …

TheHive 5.0.0 Release

---

plugins/abnormal_security/.CHECKSUM
plugins/abnormal_security/bin/icon_abnormal_security
plugins/abnormal_security/help.md
plugins/abnormal_security/icon_abnormal_security/util/api.py
plugins/abnormal_security/plugin.spec.yaml
plugins/abnormal_security/setup.py

After a change made in https://github.com/rapid7/insightconnect-plugins/pull/2196 toTime had went is gte, but should be lte
- Update gte to lte
https://issues.corp.rapid7.com/browse/PLGN-651
testing on docker with the following input 
`
"input": {
"from_date": "2023-12-01T00:00:00Z",
"to_date": "2023-12-31T00:00:00Z"
}
`
`rapid7/Abnormal Security:2.0.2. Step name: get_threats 
Paramters used for the api call - {'filter': 'receivedTime gte 2023-12-01T00:00:00Z lte 2023-12-31T00:00:00Z'}`
If …

[PLGN-651] Abnormal Security-Fixing issue where toTime should be lte

---

plugins/abnormal_security/.CHECKSUM
plugins/abnormal_security/bin/icon_abnormal_security
plugins/abnormal_security/help.md
plugins/abnormal_security/icon_abnormal_security/util/api.py
plugins/abnormal_security/plugin.spec.yaml
plugins/abnormal_security/setup.py

- https://github.com/rapid7/insightconnect-plugins/pull/2196
- Update gte to lte for the fromTime used to query the abnormal security endpoint 
https://issues.corp.rapid7.com/browse/PLGN-651
testing on stging using the following input 
`{
"from_date": "2023-12-01T00:00:00Z",
"to_date": "2023-12-31T00:00:00Z"
}
`
the time string will now be correct

Abnormal Security v2.0.2 release

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

- Bump SDK version so that we pull in exception and task started/finished logging. 
- Add direct logging when we catch an exception.
- Small changes to `_is_last_token` to check this value is `True`. noticed when testing 401 code path this gets returned as `False` and was masking the error by going into the condition and trying to parse zip content and resulting in returning `[]` as output instead of the following through to the exception being raised. 
- Update help.md to include all supported regions (PLGN-415). 
Lint failing because of automox. 
```
https://usb-api.mimecast.com
rapid7/Mimecast:5.3.3. Step name: monitor_siem_logs
Subsequent …
```

PLGN- 642: sdk bump and logger improvements.

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/actions/find_groups/schema.py

Small change to fix the schema for `find_groups`. When I began testing all actions for my last PR I was getting validation errors. 
Last PR:
- #2220
Updated to fix the schema and action now passing on local docker image. Checked schema for other actions and couldn't see any other schemas with a similar invalid schema. 
Test:

[PLGN-642] [Mimecast] - Fix schema for find_groups action. 

---

plugins/okta/.CHECKSUM
plugins/okta/Dockerfile
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/actions/create_user/schema.py
plugins/okta/komand_okta/actions/get_user/schema.py
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/komand_okta/triggers/users_added_removed_from_group/schema.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

Release the following changes:
- Updated SDK 
- Improved logging for debugging
- Fixed broken schemas

Okta 4.2.3 Release

---

plugins/automox/.CHECKSUM
plugins/automox/help.md
plugins/automox/icon_automox/actions/execute_vulnerability_sync_actions/action.py
plugins/automox/icon_automox/actions/list_vulnerability_sync_action_set_solutions/action.py
plugins/automox/icon_automox/actions/update_group/action.py
plugins/automox/icon_automox/util/api_client.py
plugins/automox/plugin.spec.yaml
plugins/automox/unit_test/test_create_group.py
plugins/automox/unit_test/test_delete_vulnerability_sync_action_set.py
plugins/automox/unit_test/test_execute_vulnerability_sync_actions.py
plugins/automox/unit_test/test_get_device_by_hostname.py
plugins/automox/unit_test/test_get_device_by_ip.py
plugins/automox/unit_test/test_get_device_software.py
plugins/automox/unit_test/test_get_vulnerability_sync_action_set.py
plugins/automox/unit_test/test_list_devices.py
plugins/automox/unit_test/test_list_groups.py
plugins/automox/unit_test/test_list_organization_users.py
plugins/automox/unit_test/test_list_organizations.py
plugins/automox/unit_test/test_list_policies.py
plugins/automox/unit_test/test_list_vulnerability_sync_action_set_issues.py
plugins/automox/unit_test/test_list_vulnerability_sync_action_set_solutions.py
plugins/automox/unit_test/test_list_vulnerability_sync_action_sets.py
plugins/automox/unit_test/test_run_command.py
plugins/automox/unit_test/test_update_device.py
plugins/automox/unit_test/test_update_group.py
plugins/automox/unit_test/test_upload_vulnerability_sync_file.py
plugins/automox/unit_test/util.py

Correct a couple of automated check failures on Automox e.g. linter failures and help.md examples.
Note there is one failing plugin validator check - this is a known validator issue (with a ticket raised to fix) around a failure when no connection version previously exists - it shows up as the error:
```
INFO:root:Found the following directories for validation: {'automox'}
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
This can be ignored for now.

[PLGN-646] Correct Automox check failures

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/actions/get_audit_events/schema.py
plugins/mimecast/requirements.txt
plugins/mimecast/unit_test/test_add_group_member.py
plugins/mimecast/unit_test/test_create_blocked_sender_policy.py
plugins/mimecast/unit_test/test_create_managed_url.py
plugins/mimecast/unit_test/test_decode_url.py
plugins/mimecast/unit_test/test_delete_blocked_sender_policy.py
plugins/mimecast/unit_test/test_delete_group_member.py
plugins/mimecast/unit_test/test_delete_managed_url.py
plugins/mimecast/unit_test/test_find_groups.py
plugins/mimecast/unit_test/test_get_audit_event.py
plugins/mimecast/unit_test/test_get_managed_url.py
plugins/mimecast/unit_test/test_get_ttp_url_logs.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/test_permit_or_block_sender.py
plugins/mimecast/unit_test/test_track_messages.py

- Hit schema validation error when testing get_audit_events action on staging, fixed broken schema from an old refresh. 
- Added `validate(..)` into all unit tests to catch this happening again. 
- Noticed snyk vulnerability so bumped package.
- Tested get_audit_events locally and passing. 
- following failing on staging but passing locally: get_ttp_url_logs and track_messages, will confirm after deploy all working ok. 
- `delete_group_member` failing on local image, staging and python shell: mimecast throwing 500 even when copy sample python code from their docs.  …

[PLGN-642] [Mimecast] Schema changes/unit testing and bump validators version.

---

plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

[SOAR-16345: Mimecast: rapid7/insightconnect-plugins(master) - Path Traversal](https://rapid7.atlassian.net/browse/SOAR-16345)
- sanitise the file names retrieved from response content before attempting to open these. 
- Tested by adding a unit test that will include the `../` in file names and can see by doing this it will then hit then BadZipFile
after the .replace has occurred. 
-- by using .replace it now passes the snyk test.
- Testing against mimecast with valid values:
-- returned filenames/zip files: `.replace()` has no action and parses content as expected
-- empty response: hit BadZipFile as no zip file is in the content, and we return `[]` as before but don't log an …

[SOAR-16345] [Mimecast] : sanitise filenames from zip content

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/top_remediations/action.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/top_remediations/schema.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/scan_completion/schema.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/scan_completion/trigger.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

InsightVM 7.0.0 release

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/schema.py
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml

Release of v4.1.2 which bumps the SDK version to pull task logging and exception handling. 
Original PR: 
- https://github.com/rapid7/insightconnect-plugins/pull/2229)
Testing:
- All actions passing on ICON 
- Dashboard on datadog showing swap over to new version and no alarming exceptions in platform logs. 
- unit test failing is expected on GH actions - unable to find a cache file, however pass locally.

[PLGN-639] Proofpoint TAP Release v4.1.2

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/actions/find_groups/schema.py
plugins/mimecast/komand_mimecast/actions/get_audit_events/schema.py
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_add_group_member.py
plugins/mimecast/unit_test/test_create_blocked_sender_policy.py
plugins/mimecast/unit_test/test_create_managed_url.py
plugins/mimecast/unit_test/test_decode_url.py
plugins/mimecast/unit_test/test_delete_blocked_sender_policy.py
plugins/mimecast/unit_test/test_delete_group_member.py
plugins/mimecast/unit_test/test_delete_managed_url.py
plugins/mimecast/unit_test/test_find_groups.py
plugins/mimecast/unit_test/test_get_audit_event.py
plugins/mimecast/unit_test/test_get_managed_url.py
plugins/mimecast/unit_test/test_get_ttp_url_logs.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/test_permit_or_block_sender.py
plugins/mimecast/unit_test/test_track_messages.py
plugins/mimecast/unit_test/util.py

Release of Mimecast 5.3.3
PRs pulled in this release:
- #2220 
- #2223 
- #2224 
- #2233
Overview:
- Bump SDK version to get task improved logging and exception handling. 
- Unit tests now validate input/output schemas. 
- Schema fixes for broken actions. 
- Validators lib bumped to remove vulnerability. 
- Sanitise filenames in request content to prevent path traversal.

[PLGN-642] Mimecast 5.3.3 release

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/icon_python_3_script/actions/run/action.py
plugins/python_3_script/icon_python_3_script/util/constants.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

- Fix issue where input argument was too long …

[PLGN-648] Python 3 Script - Updated the SDK to latest version | Fix issue where input argument was too long

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

[[C2C Mimecast] Bad JSON decode error](https://rapid7.atlassian.net/browse/PLGN-696)
Snyk code analysis is failing on a different plugin for 'hardcoded' secrets in a unit test and can be ignored.
After marking Mimecast v5.3.3 as GA:
- noticed that a customer is in a bad retry loop, as the state contains a next_token value, and on trying to access `request.content` we're raising a JSON decode error. On the next try for this integration we make the same request returning the same content and so on..
- mimecast is occasionally returning bad data which is throwing `bad seek value - 3`
- Fix validator issues around quotes in plugin.spec and help.md
- Added a catch for this type of error which builds up an error string containing the as much detail as possible to see which response is being …

[PLGN-696] [Mimecast] : handle JSONDecodeError / negative seek

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py

Tickets:
- [[C2C Proofpoint] Update polling logic to get missing data from outage](https://rapid7.atlassian.net/browse/PLGN-701)
- [[C2C Proofpoint] Handle comparison of nonetype of str error](https://rapid7.atlassian.net/browse/PLGN-693)
- Allow env var to override the date that we perform the first integration run. 
- Resolve a bug that if proofpoint returns `{'md5': ""}` we use the value `""` and not `None`
- when retrieving the value from the response because they supply md5 as "", this gets saved as None.
- added an additional try/catch around this logic so that if we hit this we will drop a single log event in this time frame rather than the entire time frame. This is also needed because due to the `if not SPECIFIC_DATE:` we will not be able to jump …

[PLGN-701] [PLGN-693] Proofpoint Tap: allow backfill date to be specified by env var / fix sorting on missing md5

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py

- Previously we used to filter by a timeframe of 24 hours. this was bumped in the following PRs:
- #2275 I bumped the cut off period to 108 hours to allow a backfill of data after coming close to the date we needed. 
- #2272 Original PR that I bumped to 96 hours. 
- We now want to put this back to the originally timeframe of 24 hours to get everyone on production inline on one version. 
- I also added a lot of logging to log each file name, which is excessive and ca now be removed. This is possibly causing of memory issue as well when the pods on production.  …

PLGN-696: adjust filter back to 24 hours and pin SDK version

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py

Release of Mimecast v5.1.6:
- Remove logging of every filename being parsed during the iteration. 
- Filter event logs on first run to 24 hours. 
Testing evidence found on JIRA:  [PLGN-714](https://rapid7.atlassian.net/browse/PLGN-714)
- Soak over night on staging and not errors. 
- Unit tests passing. 
- All actions passing - except for remove group member which is known issue. 
Original PR:
- #2287 
[PLGN-714]: https://rapid7.atlassian.net/browse/PLGN-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PLGN-714 Mimecast 5.3.6 Release

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/Dockerfile
plugins/microsoft_teams/bin/icon_microsoft_teams
plugins/microsoft_teams/help.md
plugins/microsoft_teams/icon_microsoft_teams/util/teams_utils.py
plugins/microsoft_teams/plugin.spec.yaml
plugins/microsoft_teams/setup.py

The users had notided when using a channel name such `alerts` as in input paramater, the messages were sometimes instead getting posted to a differenert channel `high severity alerts`. This was due to us getting all channel names, then using that list to find out the id of the chanel to post the message to. As we were using regex serach to determine a match, if the list of channels came back with `high severity alerts` first in the list the message would be posted there rather than to `alerts`. 
- I have updated this form `search` to `match` to ensure that we are always selecting the correct channel 
- Added in missing example to help.md
https://rapid7.atlassian.net/browse/PLGN-699
Developers, verify you have completed the following items by checking them …

[PLGN-699] - Microsoft Teams- Using regex match rather than regex search when getting the channel ids based on the channel names supplied by users

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py
plugins/proofpoint_tap/unit_test/expected/monitor_events_bad_request.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_first_run.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_server_error.json.exp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_bad_request.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_server_error.json.inp
plugins/proofpoint_tap/unit_test/test_monitor_events.py
plugins/proofpoint_tap/unit_test/test_parse_tap_alert.py
plugins/proofpoint_tap/unit_test/test_util.py

Release of Proofpoint TAP v4.1.4
Original PR:
- #2295
Changes:
- Increase look back/cutoff times to 24 hours.
- Remove env var but keep logic to allow injection of env var to the plugin if a backfill is needed.

Proofpoint TAP Release 4.1.4

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/Dockerfile
plugins/microsoft_teams/bin/icon_microsoft_teams
plugins/microsoft_teams/help.md
plugins/microsoft_teams/icon_microsoft_teams/util/teams_utils.py
plugins/microsoft_teams/plugin.spec.yaml
plugins/microsoft_teams/setup.py
plugins/microsoft_teams/unit_test/util.py

release pr for the following 
- https://github.com/rapid7/insightconnect-plugins/pull/2298 (https://rapid7.atlassian.net/browse/PLGN-699)
- To use regex match so channel names are exact matches than search where there may be ambiguity 
- updated help.md to include more examples for all actions
- https://github.com/rapid7/insightconnect-plugins/pull/2299 (https://rapid7.atlassian.net/browse/PLGN-697)
- Using urllib parse to encode channel teams to avoid symbols breaking any api calls to ms teams 
- updated unit tests to reflect the new encoding 
testing using match over serach we can see that the correct channel is now found, and `High Severity Alerts` channel is now longer selected
```
{
"channel_name": "Alerts",
"message_content": "this is a test message to test from stging", …
```

Microsoft teams 6.0.1 release

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/Dockerfile
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/connection/connection.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/responses/get_agent_details.json.resp
plugins/carbon_black_cloud/unit_test/test_agent_type.py
plugins/carbon_black_cloud/unit_test/test_get_agent_details.py

Release pr for 
https://github.com/rapid7/insightconnect-plugins/pull/2307
https://rapid7.atlassian.net/browse/PLGN-712
- To return {} rather than None in the case the search returns results, but none match the hostname provided
- To esacpe any special chars that are in the agent names to avoid broken searches 
- To add new unit tests to cover these cases
https://rapid7.atlassian.net/browse/PLGN-723
-  To allow for case insensitive hostname search
-  To add in new unit test case to ensure that the search works
testing on stging 
for fetching an endpoint with `\` in the name  input - `TEST\windowsapp`
testing case insensitive hostname, using input of `CARBONBLACK`

Carbon Black Cloud -  2.0.1 - Release

---

plugins/google_drive/.CHECKSUM
plugins/google_drive/bin/komand_google_drive
plugins/google_drive/help.md
plugins/google_drive/komand_google_drive/actions/copy_file/action.py
plugins/google_drive/komand_google_drive/actions/create_file_in_folder/action.py
plugins/google_drive/komand_google_drive/actions/create_folder/action.py
plugins/google_drive/komand_google_drive/actions/find_file_by_name/action.py
plugins/google_drive/komand_google_drive/actions/move_file/action.py
plugins/google_drive/komand_google_drive/actions/overwrite_file/action.py
plugins/google_drive/plugin.spec.yaml
plugins/google_drive/setup.py
plugins/google_drive/unit_test/test_copy_file.py
plugins/google_drive/unit_test/test_create_file_in_folder.py
plugins/google_drive/unit_test/test_create_folder.py
plugins/google_drive/unit_test/test_find_file_by_name.py
plugins/google_drive/unit_test/test_get_file_contents.py
plugins/google_drive/unit_test/test_move_file.py
plugins/google_drive/unit_test/test_overwrite_file.py
plugins/google_drive/unit_test/test_upload_file.py
plugins/google_drive/unit_test/util.py

after vendor submitted code in https://github.com/rapid7/insightconnect-plugins/pull/2292  Updating the code to comply with all of our code checks 
- running black formater  
- bumping from 2.2.0 to 3.0.0 rather than to 2.3.0 (Cause: Type folder_id removed from move_file_result without a major version increment. Please change the plugin version to 3.0.0)
- add in import for `from  insightconnect_plugin_runtime.helper import clean` that was missed
- Fix import paths in the unit tests
- Update the unit tests util class to now correctly take the new parameters added in the new plugin updates 
https://rapid7.atlassian.net/browse/PLGN-724
Review our documentation on …

[PLGN-724] - Google Drive - Updating the code to comply with all of our code checks 

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/test_advanced_query_on_log_unit.py
plugins/rapid7_insightidr/unit_test/util.py

- to allow for the use of either a log name or log id to be passed in from the ned user 
- to bump the version of Aiohhtp used (https://github.com/rapid7/insightconnect-plugins/pull/2279)
https://rapid7.atlassian.net/browse/PLGN-717
new unit tests have been added to test the addition of the new paramater 
testing using local image and docker 
examples of logs from idr
fetched logs when using log name
fetched logs when using the log id
test for an invalid log
If you are an InsightConnect …

[PLGN-717] - Rapid7 InsightIDR-Allowing for a log id to be used instead of a log name in AdvancedQueryOnLog action

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/test_advanced_query_on_log_unit.py
plugins/rapid7_insightidr/unit_test/util.py

Release pr for the following 
https://github.com/rapid7/insightconnect-plugins/pull/2313
- to allow for the use of either a log name or log id to be passed in from the ned user 
- to bump the version of Aiohhtp used (https://github.com/rapid7/insightconnect-plugins/pull/2279)
https://rapid7.atlassian.net/browse/PLGN-717
Testing on stging 
testing using just log id 
```
{
"log": "",
"log_id": "ac5d962a-bb9f-43df-b0d1-6ac96762f837",
"query": "where(CROND)",
"relative_time": "Use Time From Value",
"time_from": "2024-01-29T23:00:00+00:00",
"time_to": "2024-01-30T00:00:00+00:00",
"timeout": 60
}
```
testing using just log name
```
{
"log": "Raw Data",
"log_id": "",
"query": "where(CROND)",
"relative_time": "Use Time From Value",
"time_from": "2024-01-29T23:00:00+00:00",
"time_to": …
```

Rapid7 InsightIDR release 9.0.0

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py

After changes were made in https://rapid7.atlassian.net/browse/SOAR-16345 to try and sanitise the file path names `data='negative seek value -3'` errors were being raised. This was caused as the way the way the zip file is being read in, is from a buffer an not from a file path  as a result the replace that was called on `../` and .`.\\` could cause the file to get corrupted as it read in as they were not part of the file path, but just general data 
This change will try to sanitise the filenames before the individual files are loaded to ensure only the correct files get red in, however for this approach the snyk vuln still appears in the list 
updated the old unit test to ensure …

[PLGN-700] - Mimecast - Adding in file sanitation from zip files

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/schema.py
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/icon_zoom/triggers/user_activity_event/schema.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_create_user.py
plugins/zoom/unit_test/test_delete_user.py
plugins/zoom/unit_test/test_get_user.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

- Adding better handling to `monitor_sign_in_out_activity` if the users account does not have all of the required permsions
- updated the unit  tests to add json schema validation 
- ran refresh to fix a broken schema 
https://rapid7.atlassian.net/browse/PLGN-734
testing locally when the app has correct permissions, but the user account does not have the correct permissions 
If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests …

[PLGN-734] - Zoom -Adding better handling to  if the users account does not have all of the required permsions

---

plugins/mimecast/Dockerfile
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/requirements.txt

Ticket: [[C2C Mimecast] Implement new configurable backfill and initial params from SDK](https://rapid7.atlassian.net/browse/PLGN-728)
- Implement new SDK image which will pass custom_config allowing us to carry out backfills with no new plugin release. 
- To help traceability of when we have caught up, we now log the last event time at the end of the run. 
- Included in with @rbowden-r7 's changes for sanitising file names which have yet been released to production. 
- Bump setuptools to non vulnerable version. 
- Tested locally with forcing fake custom_configs and works as expected:
- passing lookback the plugin applies this filter.
- passing default the plugin applies this …

[PLGN-728] [Mimecast] - implement new SDK for custom_config backfilling.

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml

- bumped the version of the sdk used 
- added in logic, that if there is a custom config, that it can be used to create a custom start time
https://rapid7.atlassian.net/browse/PLGN-731 …

[PLGN-731] - Zoom -Adding in support for a custom start to be used based on the custom config

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py

Release of Mimecast 5.3.7
- Improved file name sanitation to remove path traversal
- Package bumps to remove vulnerabiltiies
- Latest SDK to allow backfilling and ease of updating our filter time. 
Original PRs:
- #2290
- #2325 
Logs of a backfill run:
```
Found config options; adding this to the request parameters...
Custom config being sent to plugin: {'default': 108, 'lookback': 108}
rapid7/Mimecast:5.3.7. Step name: monitor_siem_logs
Task execution will be applying filter period of 108 hours...
First run...
Number of raw logs returned from Mimecast: 66
Number of returned logs after filtering performed: 38
Latest event time returned from Mimecast logs: 2024-02-22 02:49:56
Plugin task finished execution...
```
Logs of a normal run using next_header and …

Mimecast 5.3.7 Release

---

plugins/okta/Dockerfile
plugins/okta/komand_okta/tasks/monitor_logs/schema.py
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/unit_test/test_monitor_logs.py

- Update to use datetime type as well as hours (int, str) in backfill logic …

[PLGN-730] okta backfill datetime

---

plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

- swapping the start and end times round if there is no state as the were the wrong way round 
- adding in logic so when doing a backfill and the while run doesn't complete we will not enforce the 24 cut off an miss data 
https://rapid7.atlassian.net/browse/PLGN-731
* Single …

PLGN-731-Allowing for a custom cutoff time to be passed in from the custom config

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py
plugins/proofpoint_tap/unit_test/test_monitor_events.py

Ticket: [[C2C Proofpoint] Implement new configurable backfill and initial params from SDK](https://rapid7.atlassian.net/browse/PLGN-727)
- Update to the latest SDK so that we now accept the custom_config parameter.
- I built on the existing logic that was accepting an environment variable to accept this new config parameter. 
- I did not remove the environment variable but added unit tests to cover if this was supplied (for any reason) that the new custom_config parameter takes precedence. 
- customer config can specify either options `lookback` or `cutoff`:
- lookback will follow the env var logic and will epxect the year/month/day etc to specified and will do this lookback value if no state is passed.
- `cutoff` can have either `date` to follow the same as …

PLGN-727: implement SDK 5.4 for custom_config task parameter.

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/schema.py
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/icon_zoom/triggers/user_activity_event/schema.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_create_user.py
plugins/zoom/unit_test/test_delete_user.py
plugins/zoom/unit_test/test_get_user.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

releasing for the following
https://rapid7.atlassian.net/browse/PLGN-734
- https://github.com/rapid7/insightconnect-plugins/pull/2322/
- Adding better handling to `monitor_sign_in_out_activity` if the users account does not have all of the required permsions
- updated the unit  tests to add json schema validation 
- ran refresh to fix a broken schema 
https://rapid7.atlassian.net/browse/PLGN-731
- https://github.com/rapid7/insightconnect-plugins/pull/2326
- bumped the version of the sdk used 
- added in logic, that if there is a custom config, that it can be used to create a custom start time
- https://github.com/rapid7/insightconnect-plugins/pull/2336
- swapping the start and end times round if there is no state as the were the wrong way round 
- adding in logic so when doing a backfill …

Zoom 4.1.6 release

---

plugins/okta/Dockerfile
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/unit_test/test_monitor_logs.py

* Update cutoff logic for datetime type
* Black and Refresh
* Fix schema type error
* Update task to use komand properties cutoff value, improve logging, refactor date type check
- …

Okta  4.2.4 Release - 2

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/test_monitor_users.py
plugins/salesforce/unit_test/util.py

[Implement new configurable backfill and initial params from SDK](https://rapid7.atlassian.net/browse/PLGN-729)
- Allow task to accept custom config that will enable a configurable backfill and cut off date to be applied. 
- This involved small refactoring of variable assignments to simplify how the code reads and flows
- Added extra comments as I found this difficult to understand why certain conditions and timedeltas were being calculated.
- Similar to other plugins:
- the cut off values can be supplied in either hours or a date. 
- the lookback can be supplied as a date. 
- Testing locally performing a normal execution with no lookback values.
- Testing locally with lage …

[PLGN-729] [Salesforce] : implement custom_config for backfilling. 

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py
plugins/proofpoint_tap/unit_test/expected/monitor_events_first_run.json.exp

[PLGN-764](https://rapid7.atlassian.net/browse/PLGN-764)
- Bump to the latest SDK version. 
- I noticed during testing that during a first run for a user we were looking back 24 hours and this didn't seem right... I checked and I changed this logic during one of my previous releases when I shouldn't have. I've changed this back to only lookback 1 hour for first run.
- Still showing now - 1 hour: [#2281](https://github.com/rapid7/insightconnect-plugins/pull/2281/files#diff-96569c90f581170f3a472609d19e792b6bedd2d4cbc62de9408cd6c100500f91R59)
-  Where I changed this logic - [#2297](https://github.com/rapid7/insightconnect-plugins/pull/2297/files#diff-96569c90f581170f3a472609d19e792b6bedd2d4cbc62de9408cd6c100500f91R59)
Developers, verify you have completed the …

PLGN-764: bump SDK version in Proofpoint TAP

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py
plugins/proofpoint_tap/unit_test/expected/monitor_events_first_run.json.exp

Release of Proofpoint TAP v4.1.6.
Changes:
- Make use of the latest SDK.
- Revert back that the first poll for an org will look back 1 hour. 
Original PR: 
- #2373

Release Proofpoint TAP v4.1.6

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

Release of Mimecast v5.3.8. 
Changes:
- Bump SDK to v5.4.4
- Add additional logger to indicate when no logs returned in a run. 
- Handle incorrect app ID correctly and raise this to the user.
Original PRs:
- #2370 
- #2386

Mimecast v5.3.8 Release

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/connection/connection.py
plugins/salesforce/komand_salesforce/connection/schema.py
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/inputs/connection_invalid_client_id.json.inp
plugins/salesforce/unit_test/inputs/connection_server_error.json.inp
plugins/salesforce/unit_test/responses/invalid_client_id.json.resp
plugins/salesforce/unit_test/responses/invalid_grant.json.resp
plugins/salesforce/unit_test/test_connection.py
plugins/salesforce/unit_test/test_monitor_users.py
plugins/salesforce/unit_test/util.py

Release of Salesforce 2.1.7
Changes in this version:
- Allow customer to specify their own Salesforce URL; implemented to let the user hit sandbox instances. 
- Force a reset on the token held within the connection object at the end of each task execution; this will bubble to the customer as soon as their password and security token has expired. 
- Update the retry logic so that on getting invalid_grant (typically expired password), we don't retry 10 times to avoid an account lockout. 
- New helper method `get_error` to try and surface as much information to the customer when an error is returned from Salesforce. 
Original PRs:
- #2396 
- #2402 
Jiras:
- [PLGN-771 Salesforce connection update](https://rapid7.atlassian.net/browse/PLGN-771)
- [PLGN-775 Salesforce token …

Salesforce 2.1.7 Release

---

plugins/cuckoo/.CHECKSUM
plugins/cuckoo/help.md
plugins/cuckoo/komand_cuckoo/actions/reschedule_task/action.py
plugins/cuckoo/komand_cuckoo/actions/reschedule_task/schema.py
plugins/cuckoo/plugin.spec.yaml
plugins/cuckoo/unit_test/expected/reschedule_task_success.json.exp
plugins/cuckoo/unit_test/responses/reschedule_task_success.json.resp

- Reschedule Task - Output: Success -> Status …

Update reschdule task output

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

releasing for the following
* https://rapid7.atlassian.net/browse/PLGN-797
*  https://github.com/rapid7/insightconnect-plugins/pull/2434
* Added in logic that will allow for the c2c tasks to be in state of pagination until caught up when running backfills
* updated to the newest SDK version
Initial running of the task on staging looks successful but some more error checking will need to be done after the zoom task has been running over the weekend before this will be merged

Zoom 4.1.8 release

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py

- To always set the value of `header_next_token` as even when there is no chance the Mimecast should always return the value for itself if the item fetch is the last in the list 
- bump the sdk to the latest 
https://rapid7.atlassian.net/browse/PLGN-824 …

PLGN-824-Always setting the header_next_token value

---

plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

- Add unit test single failing json response in monitor siem logs …

Mimecast no new logs unit test

---

plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py

- to increase the default cuttoff time from 24hrs to 7 days 
testing locally we can see that the new cuttoff time is honoured on the first run 
```
rapid7/Mimecast:5.3.10. Step name: monitor_siem_logs
Task execution will be applying filter period of 168 hours...
First run...
Number of raw logs returned from Mimecast: 15
Number of returned logs after filtering performed: 14
Latest event time returned from Mimecast logs: 2024-04-15 03:54:48
The token will be set to 'eNo9js1Og0AYAN_lu0pil4WykHgA2iWKxtJWsIkXsn7o1v0xLKu2je9u9eB9ZjIncCj8iPIZMpjrMVrt-MWtrobVXbJu17l67aQOa3a9r7kT4itXlntLkbPSN8fDptfHPOz2Bo1YqGXR0JvdolFvlfVVW8fWkHsuny6ZtX77WXTlY9_WxC9NEl1BAHYYHE6QzQJwErWyL78bMYvTKGUBiBH7CbdSI2QkIZQkaRjO6Yz-49PhHf_0DxydtObMBdALYb05Z6F82BQkzQmD7x-Zmkmu' in the state. …
```

PLGN-824-increase the default cuttoff time to 7 days

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

- https://github.com/rapid7/insightconnect-plugins/pull/2477
- To always set the value of header_next_token as even when there is no chance the Mimecast should always return the value for itself if the item fetch is the last in the list
- bump the sdk to the latest
- https://github.com/rapid7/insightconnect-plugins/pull/2478  
- Add unit test single failing json response in monitor siem logs
- https://github.com/rapid7/insightconnect-plugins/pull/2480
- to increase the default cuttoff time from 24hrs to 7 days
- https://github.com/rapid7/insightconnect-plugins/pull/2481
- revert of 2480

Mimecast 5.3.10 release

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/Dockerfile
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/triggers/incident_created/trigger.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

- Updated to the latest SDK 5.47
- Trigger was not working properly to find new incidents. Found that there is now a limit where it pulls back 10,000 results so it was never finding the latest incident. I have changed this now so it pulls the most recent 10,000 results.
- Also fixed an issue with the polling time as it kept missing new incidents.
Ran the trigger locally and created new incidents on ServiceNow to watch them flow through.

[PLGN-823]- ServiceNow- Fix Incident Created Trigger

---

plugins/rapid7_intsights/.CHECKSUM
plugins/rapid7_intsights/Dockerfile
plugins/rapid7_intsights/bin/icon_rapid7_intsights
plugins/rapid7_intsights/help.md
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_indicator_by_value/action.py
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_indicator_by_value/schema.py
plugins/rapid7_intsights/icon_rapid7_intsights/triggers/new_alert/trigger.py
plugins/rapid7_intsights/icon_rapid7_intsights/util/api.py
plugins/rapid7_intsights/icon_rapid7_intsights/util/constants.py
plugins/rapid7_intsights/plugin.spec.yaml
plugins/rapid7_intsights/setup.py
plugins/rapid7_intsights/unit_test/test_close_alert.py
plugins/rapid7_intsights/unit_test/test_connection.py
plugins/rapid7_intsights/unit_test/test_get_iocs_for_cyber_term.py

- Exception presets may be hard coded into unit tests or code which may cause issues if the preset text in the SDK changes in any upgrade.
- Updating unit tests to directly refer to the causes and assistance in the SDK instead of hard coding text.
- Specify SDK version
- Added new `subType` output field to action `get_indicator_by_value`
New output field:
Review …

[PLGN-261] Threat Command - 5.2.0

---

plugins/zoom/.CHECKSUM
plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

Increase the max lookback cutoff time from 24 hours to 7 days for the task.
Update to latest SDK version. 
Testing
Tested locally against docker container by setting a time previous to the cutoff time. 
Prior to change:
```
rapid7/Zoom:4.1.8. Step name: monitor_sign_in_out_activity
Saved state 2023-05-02T15:47:47Z exceeds the cut off. Reverting to use time: 2024-05-01T15:50:44Z
Current runstate is: continuing
Getting events for timeframe 2024-05-01T15:50:44Z to 2024-05-02T15:50:44Z. Currently paginating: false
```
Following change:
No state:
```
rapid7/Zoom:4.1.9. Step name: monitor_sign_in_out_activity
Setting min start time: No manual cutoff applied and no last request timestamp. Use default initial lookback cutoff: …
```

[SOAR-26854] Zoom task lookback time

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/connection/connection.py
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/icon_carbon_black_cloud/util/constants.py
plugins/carbon_black_cloud/icon_carbon_black_cloud/util/exceptions.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/responses/task_test_data.py
plugins/carbon_black_cloud/unit_test/test_get_agent_details.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py
plugins/carbon_black_cloud/unit_test/test_quarantine.py

Noticed when testing the task that we will raise 500 from the task call when invalid credentials are sent. 
- Implement new exception type to catch and raise this status from the task call. 
- Implementing that we will delete the observation job details from the state if we get a 404 when trying to poll this results. 
- Updated unit test to no longer expect a generic 500 error. 
- Tested manually and can see a 401 returned when invalid credentials are sent. (screenshot attached to JIRA)
- Tested manually with a made up observation ID returns 404. (screenshot attached to JIRA) …

[SOAR-16699][Carbon Black] Improved error handling to raise CB status code in task. 

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/connection/connection.py
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/icon_carbon_black_cloud/util/constants.py
plugins/carbon_black_cloud/icon_carbon_black_cloud/util/exceptions.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/responses/task_test_data.py
plugins/carbon_black_cloud/unit_test/test_get_agent_details.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py
plugins/carbon_black_cloud/unit_test/test_quarantine.py

Release of Carbon Black v2.2.1.
Includes the following PRs:
- #2515 
Changes:
- Improved task code to return the status code returned from CB in the case of an exception.
- Improved if we get a 404 from CB when polling an observation job ID that we delete this to stop a bad retry loop. 
Testing:
- Added example of testing on staging vs prod cloud integration: [SOAR-16699](https://rapid7.atlassian.net/browse/SOAR-16699?focusedCommentId=1481418)
[SOAR-16699]: https://rapid7.atlassian.net/browse/SOAR-16699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Carbon Black v.2.2.1 Release

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py

Due to the way we fetch data from Mimecast, where we get all of the data on the initial run, use the next header token to fetch the next page of data but then we carry out the time filtering on the task end 
As a result for this plugin we may need to take a different approach to the other plugins and save some extra information into the state, as unlike the other plugins Mimecast will need to have use the 24hrs as a cut off, then catch up to current time, then after that switch over to 7 days as the cut off time 
We will achieve this, by starting with a cutoff time of 24 hrs and running with this until IS_LAST_TOKEN_FIELD header is returned from MImecast as this will show that we have finished parsing all of the current data, then we can switch over to a cut …

SOAR-16851-Improving the lookback of Mimecast

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/expected/monitor_logs_2.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_3.json.exp
plugins/duo_admin/unit_test/inputs/monitor_logs_next_page.json.inp
plugins/duo_admin/unit_test/inputs/monitor_logs_with_state.json.inp
plugins/duo_admin/unit_test/util.py

- Update SDK to 5.4.9
- Update MAX_CUTOFF_HOURS to 7 days for tasks
https://rapid7.atlassian.net/browse/SOAR-16858 
First run (no state) then 24 look back is still used:
```
rapid7/Duo Admin API:4.4.2. Step name: monitor_logs
Previous timestamps retrieved. Auth None. Admin: None. Trust monitor None.
First run for Trust monitor events
Task execution for Trust monitor events will be applying a lookback to 2024-05-13 14:29:16.331290+00:00 UTC...
Retrieve data from 1715610556331 to 1715696836331. Get next page is set to False
Parameters for get trust monitor events set to {'mintime': '1715610556331', 'maxtime': '1715696836331', 'limit': '200'}
Request to path: /admin/v1/trust_monitor/events
Parameters to return from trust monitor events set to {'mintime': …
```

[SOAR-16858]- Duo Admin- update max lookback to 7 days

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py

Release pr for 
https://github.com/rapid7/insightconnect-plugins/pull/2525
- https://rapid7.atlassian.net/browse/SOAR-16851
- Bump SDK to 5.4.9
- allowing for a date to be supplied as a custom config
- to now use 24hrs as initial lookback, then 7 days for normal running
- https://rapid7.atlassian.net/browse/SOAR-16874
- to now log the request id of failed request to Mimecast
Testing on staging 
on the first run that the we have finished paginating the new token is correctly set and we should switch over to using the longer timeout

Mimecast 5.3.11 release

---

plugins/recorded_future/help.md
plugins/recorded_future/komand_recorded_future/util/api.py

- Add file size logging in case of memory error or timeout when parsing gzip for download x risk list actions.
* …

[SOAR-16911] Recorded future file size logging

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/test_connection.py
plugins/salesforce/unit_test/test_monitor_users.py
plugins/salesforce/unit_test/util.py

Release of Salesforce v2.1.8
Tickets:
- [[C2C Salesforce] Plugin returning 500/400 when customer uses invalid creds](https://rapid7.atlassian.net/browse/SOAR-16983)
- [[C2C] Salesforce: Update max lookback time](https://rapid7.atlassian.net/browse/SOAR-16856)
Changes:
- On an execution when a specific look back value is not supplied we should look back 24 hours.
- On subsequent runs we should apply the DEFAULT_CUTOFF_HOURS value against the held timestamp in the state.
- Improved error handling to raise a 401 when Salesforce returns 400 but with an error message related to their credentials being invalid.
- These error messages update the plugin cause to be more indicative other than 'Invalid Credentials' from our preset causes that would have got applied and not raise which part of the …

[ SOAR-16856] [SOAR-16983] Salesforce v2.1.8 Release

---

plugins/sonicwall/icon_sonicwall/util/api.py
plugins/sonicwall/unit_test/test_add_address_object_to_group.py
plugins/sonicwall/unit_test/test_check_if_address_in_address_group.py
plugins/sonicwall/unit_test/test_create_address_object.py
plugins/sonicwall/unit_test/test_delete_address_object.py
plugins/sonicwall/unit_test/test_remove_address_from_group.py

- Added retry login logic to handle multiple sessions
The thing is that when working with SonicWall API only once `logged` user can be at time. When using the same creds in multiple workflows, running at the same time - the session can be dropped to one another. In order to fix so the retry login logic is implemented to `_make_request` method.
```
2024-05-29 13:22:50 [info     ] Retrying to login... (1/15)
2024-05-29 13:22:55 [error    ] Plugin exception instantiated. cause='Something unexpected occurred.', assistance='Check the....
2024-05-29 13:22:55 [info     ] Retrying to login... (2/15)
2024-05-29 13:23:00 [error    ] Plugin exception instantiated. cause='Something unexpected occurred.', assistance='Check the logs and if the issue persists please …
```

[PLGN-378] SonicWall - Added retry login logic to handle multiple sessions

---

plugins/zoom/.CHECKSUM
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/icon_zoom/util/api.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

- Refactor Task
- Update de-duping logic in task to dedupe in subsequent runs during pagination (new state added)
- Keep last_event_timestamp in the event of an error incase of recovery to re-enable deduping
- Remove has_next_page in case of failure to catch up (we always query to current date (yyyy/mm/dd) …

[SOAR-16999] Zoom: Update De-duplication in Task

---

plugins/powershell/requirements.txt

After changes made in - https://github.com/rapid7/insightconnect-plugins/pull/2552 there was a snyk vulnerability that was missed (https://app.snyk.io/org/soar-insightconnect-new/project/e914542e-fa84-4dcf-a00e-1cf638b8846e) so it's being updated in this pr and will go into the 3.0.4 release as well 
Note there is 2 other snyk vulns that currently have not fix available yet

SOAR-17026-Bumping requirements of requests

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/event.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

We observed that mimecast had a response where an event did not have datetime field, this meant that we tried to do the filtertime to comparison to see if we should ingest the event it was erroring as it was trying to fetch a field that didn't exist. 
A fix has been added that will add in a default time of now to event object if the datetime field does not exist. This means thats we will ingest the data
- If there is no datetime timestamp in the response from Mimecast then we will not check to see if the that field is within teh filter time 
- to bump the werkzeug package version 
https://rapid7.atlassian.net/browse/SOAR-17038
https://github.com/rapid7/insightconnect-plugins/pull/2509
Developers, verify you have completed the following items by checking them …

SOAR-17038-If there is no datetime field in the mimecast response then don't check the timestamp

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/schema.py
plugins/proofpoint_tap/komand_proofpoint_tap/connection/schema.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py

Release of Proofpoint TAP 4.1.9
Changes -
- Ran refresh which has re-ordered the help.md and required some fields populated into the plugin spec.
- Updated connection schema so that the user is required to enter values. One action: parse alerts does not require a connection but due to how we run the action the plugin sidecar still tries to decrypt the connection associated with the plugin and fails on decrypting empty values.
PRs - 
- #2563 
- 
Testing evidence on ticket - 
- [[Proofpoint TAP] Update connection schema to correct fields as required](https://rapid7.atlassian.net/browse/SOAR-17028)

Proofpoint TAP v4.1.9 Release

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/connection/connection.py
plugins/okta/komand_okta/util/api.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

Release of Okta 4.2.8
Ticket - https://rapid7.atlassian.net/browse/SOAR-17031
- https://github.com/rapid7/insightconnect-plugins/pull/2571
- Raise an exception with a 401 status code if the Okta domain is invalid, so that integrations will enter an error state instead of continually retrying (i.e. when a 500 is returned)
- Evidence in ticket https://github.com/rapid7/insightconnect-plugins/pull/2571
- Confirmed test integration on staging continues to run successfully in new version
- Setup a new connection on ICON staging to test that the connection test still works as expected
- Successful [job run to test action / new connection …

[SOAR-17031] - Set 401 status_code if Okta domain is invalid

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/connection/connection.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py

- bump SDK used to 5.5.1
- Added in a connection test for tasks …

SOAR-17021-Adding in a connection test for task

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/connection/connection.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py

release pr for the following 
https://rapid7.atlassian.net/browse/SOAR-17021
- https://github.com/rapid7/insightconnect-plugins/pull/2581
- bump SDK used to 5.5.1
- Added in a connection test for tasks
- https://github.com/rapid7/insightconnect-plugins/pull/2588
- fixed issue where the commas at the end of the end of the string was causing the string to be treated as seperate args not as one string, as a result the error was not being logger correctly

Mimecast 5.3.13 release

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/connection/connection.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py

release pr for the following
https://rapid7.atlassian.net/browse/SOAR-17021
- https://github.com/rapid7/insightconnect-plugins/pull/2619
- bump SDK used to 5.6.1 to improve returned status code under an error 
- Improve the logging around connection tests to make it clearer to the user what is running
an invalid test will now return as a 400 
a valid test will now show better logging

MImecast 5.3.14 Release

---

plugins/domaintools/.CHECKSUM
plugins/domaintools/help.md
plugins/domaintools/plugin.spec.yaml
plugins/domaintools/requirements.txt

The SDK has already been bumped, Plugin refreshed and Unit tests fixed in the previous commit https://github.com/rapid7/insightconnect-plugins/pull/2620
**Minor update to the plugin to bump the API.** 
- Bumping Domain Tooling [API](https://github.com/DomainTools/python_api/blob/main/CHANGELOG.md) to 2.0.0
* All actions/triggers shortcut `insight-plugin run --debug --jq` (use PR format at end)

[SOAR-17225] Bumping DomainTooling API to 2.0.0

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/plugin.spec.yaml
plugins/whois/requirements.txt
plugins/whois/setup.py

Release of WHOIS v3.1.3 - [SOAR-17285](https://rapid7.atlassian.net/browse/SOAR-17285)
Changes:
- bump of SDK to latest version - v6.0.0
- bump of setuptools to version 70.0.0
Tests:
- integration tests passing
- ran workflow on staging with both cloud and orch version, happy and non-happy paths working as expected. Screenshots attached to ticket. 
[SOAR-17285]: https://rapid7.atlassian.net/browse/SOAR-17285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SOAR-17285] [WHOIS] Release v3.1.3

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/connection/connection.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py

Release pr for the following 
* https://github.com/rapid7/insightconnect-plugins/pull/2639 
*  https://rapid7.atlassian.net/browse/SOAR-17270
* Update setuptools to 70.0.0
* Update version to 5.3.15
* https://rapid7.atlassian.net/browse/SOAR-17272
After new changes to the SDK, we now support passing back a message to the SDK as part of the task connection test, this will allow for the use of the custom message to be shown in the UI for a task connection test, rather than have the end user see all of the available logs   
* https://github.com/rapid7/insightconnect-plugins/pull/2656
* Bump the sdk used in Mimecast that was used

Mimecast 5.3.15 release

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/requirements.txt

[Original PR](https://github.com/rapid7/insightconnect-plugins/pull/2644)
After testing the [records](https://pypi.org/project/records/) package it is concluded that it is no longer maintained and will not work. 
As the [records](https://pypi.org/project/records/) package caused the Snyk vulnerability, I took the zipp package out (as it was the solution to fix the snyk vulnerability) and the snyk tests pass.
- SDK Bump to 6.0.1
- Removing 'records' and 'zipp'
- Updating Plugin Spec and help.md
Unit test carried out:

[SOAR-17284] python3_script Removing 'records' and 'zipp' & SDK Bump

---

plugins/carbon_black_response/.CHECKSUM
plugins/carbon_black_response/Dockerfile
plugins/carbon_black_response/plugin.spec.yaml

Was about to merge into Master and the validator failed as the SDK has been updated to 6.0.1
[RELEASE PR](https://github.com/rapid7/insightconnect-plugins/pull/2663)
[ORIGINAL PR](https://github.com/rapid7/insightconnect-plugins/pull/2642)
- SDK bump to 6.0.1

[SOAR-17165] Carbon Black Response SDK Bump

---

plugins/html/.CHECKSUM
plugins/html/Dockerfile
plugins/html/help.md
plugins/html/plugin.spec.yaml

Convert actions were failing due to the USER permissions set to nobody. ([previous PR experienced same issue](https://github.com/rapid7/insightconnect-plugins/pull/2200))
****The validator will fail due to the change in USER permission but is required for the plugin to work****
- USER privileges changed to root
Each action has been tested on postman to ensure the conversion occurs successfully:
- Dockx
- pdf
- epub
- html5
- markdown
- text
- validate
All unit tests have been tested and pass successfully

[SOAR-17274] html updating USER permissions 

---

plugins/html/icon_html/actions/pdf/action.py

When testing the pdf action on Postman and against the Orchestrator in staging it passed but when I tested it against the cloud in staging it failed (but every other action passed).
Looking at the logs (`Error converting doc file.  Check stack trace log. Response was: Pandoc died with exitcode "-9" during conversion: b''`) this seems to be the only solution at the moment as the test works on postman and against the orchestrator 😕 
This change was also carried out on the other actions within the html plugin in the [previous pr](https://github.com/rapid7/insightconnect-plugins/pull/2653/files#diff-a141193a576d54dd9e613a220a4172372281b7d98af40c4236a29c98ac297c6f)
**The validator is expected to fail due to the USER privilege changing from nobody to root (for the pandoc package to work)** …

[SOAR-17274] html changing convert action for PDF

---

plugins/html/requirements.txt

When testing the pdf action again (against the cloud) with the [convert action changes](https://github.com/rapid7/insightconnect-plugins/pull/2668), the error still occurs. The API bump is the only potential fix at the moment.
Looking at the logs (`Error converting doc file.  Check stack trace log. Response was: Pandoc died with exitcode "-9" during conversion: b''`) this seems to be the final solution at the moment as the test works on postman and against the orchestrator 😕 
**The validator is expected to fail due to the USER privilege changing from nobody to root (for the pandoc package to work)**
- Bumping pypandoc
Testing this via Postman and the tests pass as expected

[SOAR-17274] Bumping pypandoc for html plugin

---

plugins/okta/komand_okta/connection/connection.py

When testing the connection task in staging, the 104 exception (invalid URL but correct structure) was being caught in the `ConnectionError` exception and not in the `ConnectionResetError`, meaning the exception is no longer needed (as the `ConnectionResetError` exception was only implemented to catch it).
[Original PR](https://github.com/rapid7/insightconnect-plugins/pull/2692) 
- Removing the ConnectionResetError exception
The 104 error is being caught in the ConnectionError exception and not ConnectionResetError:
Tested on Postman that by sending a invalid URL (but correct structure) is caught in the ConnectionError exception:

[SOAR-17320] Okta Removing ConnectionResetError exception

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/Dockerfile
plugins/sentinelone/bin/komand_sentinelone
plugins/sentinelone/help.md
plugins/sentinelone/komand_sentinelone/tasks/monitor_logs/schema.py
plugins/sentinelone/komand_sentinelone/tasks/monitor_logs/task.py
plugins/sentinelone/plugin.spec.yaml
plugins/sentinelone/setup.py
plugins/sentinelone/unit_test/test_monitor_logs.py
plugins/sentinelone/unit_test/util.py

- Remove task inputs due to passing of string value instead of boolean from Bridge PCA causing validator failure …

Sentinelone remove task inputs

---

plugins/jira/.CHECKSUM
plugins/jira/Dockerfile
plugins/jira/help.md
plugins/jira/plugin.spec.yaml

after changes made in https://github.com/rapid7/insightconnect-plugins/pull/2687 to add fedramp ready flag we were seeing the following error
```
07 Aug 2024 10:54:30.356{ "log": "[2024-08-07 10:53:24,259] ERROR in app: Exception on /api/v1/info [GET]Traceback (most recent call last): File \"/layers/paketo-buildpacks_pip-install/packages/lib/python3.9/site-packages/flask/app.py\", line 1463, in wsgi_app response = self.full_dispatch_request() File \"/layers/paketo-buildpacks_pip-install/packages/lib/python3.9/site-packages/flask/app.py\", line 872, in full_dispatch_request rv = self.handle_user_exception(e) File \"/layers/paketo-buildpacks_pip-install/packages/lib/python3.9/site-packages/flask/app.py\", line 870, in full_dispatch_request rv = self.dispatch_request() File …
```

[SOAR-17400] - Jira - bump the SDK to 6.1.0

---

plugins/bitwarden/.CHECKSUM
plugins/bitwarden/Dockerfile
plugins/bitwarden/bin/icon_bitwarden
plugins/bitwarden/help.md
plugins/bitwarden/plugin.spec.yaml
plugins/bitwarden/setup.py

Release of Bitwarden 2.0.1
Changes:
- bump to latest SDK: 6.1.0
- update `supported product version` to latest Bitwarden version. 
Ticket:
- [SOAR-17462](https://rapid7.atlassian.net/browse/SOAR-17462)
Original PR:
- #2702 
Testing:
- Evidence on ticket; all actions passing on both cloud and orch.
[SOAR-17462]: https://rapid7.atlassian.net/browse/SOAR-17462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bitwarden 2.0.1 Release

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/actions/fetch_forensics/schema.py
plugins/proofpoint_tap/komand_proofpoint_tap/actions/parse_tap_alert/schema.py
plugins/proofpoint_tap/komand_proofpoint_tap/connection/connection.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py

Task connection test added for Proofpoint, alongside bumping the SDK and plugin refresh
- SDK Bump to 6.1.0 & Plugin Refresh
[Ticket](https://rapid7.atlassian.net/browse/SOAR-17322)
Tested valid and invalid inputs for each field on Postman to ensure the correct exception handling is in place:
- Successful Test
- Invalid Principal Key & or Secret Key

[SOAR-17322] Proofpoint Connection Test added & SDK Bump

---

plugins/jira/.CHECKSUM
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/actions/create_user/action.py
plugins/jira/komand_jira/actions/create_user/schema.py
plugins/jira/komand_jira/connection/connection.py
plugins/jira/komand_jira/util/api.py
plugins/jira/plugin.spec.yaml
plugins/jira/setup.py
plugins/jira/unit_test/test_create_user.py

- when trying to add a new cloud connection to jira we are seeing the following error 
`"error": "json: cannot unmarshal bool into Go struct field PluginActionResponseBody.body.output of type map[string]interface {}"`
this is due to the status of the connection test being returned incorrectly 
- Adding a timeout to the connection
- Moving create user to a rest api call due to a new required field that is not avaliable in the jira python package
https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-users/#api-rest-api-3-user-post …

[SOAR-17400] - Jira - update the connection test to return as a dictionary

---

plugins/pagerduty/.CHECKSUM
plugins/pagerduty/Dockerfile
plugins/pagerduty/bin/komand_pagerduty
plugins/pagerduty/help.md
plugins/pagerduty/komand_pagerduty/actions/__init__.py
plugins/pagerduty/komand_pagerduty/actions/send_resolve_event/schema.py
plugins/pagerduty/komand_pagerduty/actions/send_trigger_event/schema.py
plugins/pagerduty/komand_pagerduty/util/api.py
plugins/pagerduty/plugin.spec.yaml
plugins/pagerduty/setup.py
plugins/pagerduty/unit_test/expected/trigger_event_additional_fields_assignments.json.exp
plugins/pagerduty/unit_test/inputs/trigger_event_additional_fields_assignments.json.inp
plugins/pagerduty/unit_test/inputs/trigger_event_additional_fields_escalation.json.inp
plugins/pagerduty/unit_test/responses/trigger_event_additional_fields_assignments.json.resp

https://rapid7.atlassian.net/browse/SOAR-17531
- Fix `send_trigger_event` action so that empty optional nested fields are not sent in payload
- https://github.com/rapid7/insightconnect-plugins/pull/2711
- Tested on ICON staging. Screenshot shows action passing (with pagerduty events triggered), when optional fields are left empty and when they are populated.

[SOAR-17531] - PagerDuty fix send_trigger_event optional field

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

- `Monitor Logs`: Update task to break if subdomain doesn't match egress rules. …

Okta 4.2.10

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

- limit the number of events thats processed in a single run to 7500 events 
- bumping sdk to version 6.1.0
- added new unit test for new logic
https://rapid7.atlassian.net/browse/SOAR-17646
when using a mocked start time and limit of 100 (due to what data we have available in our instance)
1st run 
2nd run (using state from 1st run)
3rd run (using state from 2nd run)
4th run (using state from 3rd run)
If you are an InsightConnect customer or have access to an InsightConnect instance, the …

SOAR-17646-Only processing 7500 events per run

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/Dockerfile
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/requirements.txt
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

Release pr for the following 
https://rapid7.atlassian.net/browse/SOAR-17646
-  https://github.com/rapid7/insightconnect-plugins/pull/2759
- limit the number of events thats processed in a single run to 7500 events
- bumping sdk to version 6.1.0
- added new unit test for new logic
testing on staging
we can see that the code looks to paginate as expected

Mimecast 5.3.16 release

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py

- to out the page size limits for alert_page_size and obervation_page_size so that they can be individually adjusted
- updated the unit test to test the new vars 
The unit tests have been updated to reflect the new changes
when using a limit (10 in our case for testing) we can see the limits are correctly applied 
```
rapid7/VMware Carbon Black Cloud:2.2.5. Step name: monitor_alerts
No last_alert_time within state. No last_observation_time within state. Applying the following start times: …
```

[SOAR-17658] - Carbon Black Cloud - Splitting out the page size limits for alert_page_size and obervation_page_size

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py

Release pr for the following
https://rapid7.atlassian.net/browse/SOAR-17658
- https://github.com/rapid7/insightconnect-plugins/pull/2770
- to out the page size limits for alert_page_size and obervation_page_size so that they can be individually adjusted
- updated the unit test to test the new vars

carbon_black_cloud 2.2.5 release

---

plugins/get_url/.CHECKSUM
plugins/get_url/Dockerfile
plugins/get_url/plugin.spec.yaml

- After testing `get_url` fix on staging, hit issue with permissions:
```
rapid7/Get URL:2.1.0. Step name: get_file
[Errno 13] Permission denied: '/var/cache/7c774392df25c0990a337dc8b862b783cd881b51.meta'
```
- Small fix to update user to `root` to resolve permissions issue when creating `/var/cache` directory
- Tested locally after rebuilding image

[SOAR-17746] - Need root user to create cache

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/icon_python_3_script/connection/connection.py
plugins/python_3_script/plugin.spec.yaml

- Updated package installation
* …

[SOAR-16967] Python 3 Script - Updated package installation

---

plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/monitor_alerts/task.py

- Change `return error` -> `return error.data` …

Palo Alto | Update error to return error.data

---

plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/monitor_alerts/task.py
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/api.py

- If `401`, rerun authentication for creds …

Palo alto retry creds 401

---

plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/api.py

- Take away use of `self.headers` so original creds dont get used …

Palo Alto | Dont use `self.headers` (caching)

---

plugins/abnormal_security/.CHECKSUM
plugins/abnormal_security/Dockerfile
plugins/abnormal_security/bin/icon_abnormal_security
plugins/abnormal_security/help.md
plugins/abnormal_security/icon_abnormal_security/actions/get_case_details/action.py
plugins/abnormal_security/icon_abnormal_security/actions/get_cases/action.py
plugins/abnormal_security/plugin.spec.yaml
plugins/abnormal_security/setup.py

A customer is currently experiencing an issue with the `caseId` being returned as an int and not a string, as well as an issue arising when inputting the `caseId`, as it recognises the input as a integer and not string (which is what it is meant to be : https://app.swaggerhub.com/apis/abnormal-security/abx/1.4.3#/Cases/get_cases). 
Proposed change, converts the `caseId` to a string before being inputted and before being returned, to ensure the issue doesn't appear. Provided a custom plugin to the customer and this solution solved their problem.
SI Ticket: https://rapid7.atlassian.net/browse/SI-25434
- Format the `caseId` to a string when inputted and outputted from both actions
- SDK Bump to 6.1.3 & Plugin Refresh

[SOAR-17793] Abnormal Security - Case ID issue

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/responses/task_test_data.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py

Restrains the Observability window to a customizable window
* …

[Carbon Black Cloud] Observability Window Restraint

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
plugins/palo_alto_cortex_xdr/help.md
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_incidents/trigger.py
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/api.py
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/util.py
plugins/palo_alto_cortex_xdr/plugin.spec.yaml
plugins/palo_alto_cortex_xdr/setup.py
plugins/palo_alto_cortex_xdr/unit_test/test_get_incidents.py
plugins/palo_alto_cortex_xdr/unit_test/test_monitor_alerts.py

- Add custom config exception handling to match the error handling found in the regular API calls for actions and triggers
- Update the Get Incidents trigger to separate hostname and incident ID and properly map them in their own object
**Hosts Output from `Get Incidents` Trigger**
```
In [14]: split_list_values(x)
Out[14]:
[{'hostname': 'htc-smr-2194',
'endpoint_id': '3d421251f17348469031227eea15ad5d'}]
```
If you are an InsightConnect customer or have access to an InsightConnect instance, …

Palo Alto Cortex XDR | Updates

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/help.md
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/util.py
plugins/palo_alto_cortex_xdr/plugin.spec.yaml
plugins/palo_alto_cortex_xdr/unit_test/test_get_incidents.py
plugins/palo_alto_cortex_xdr/unit_test/test_monitor_alerts.py

- Undo change from previous PR regarding `Get Incidents` trigger fix …

Palo Alto Cortex XDR | Undo change to list split for get incidents trigger

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
plugins/palo_alto_cortex_xdr/help.md
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_incidents/trigger.py
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/api.py
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/util/util.py
plugins/palo_alto_cortex_xdr/plugin.spec.yaml
plugins/palo_alto_cortex_xdr/setup.py
plugins/palo_alto_cortex_xdr/unit_test/test_get_incidents.py
plugins/palo_alto_cortex_xdr/unit_test/test_monitor_alerts.py

Palo alto cortex xdr 4.0.3 release

---

plugins/cylance_protect/.CHECKSUM
plugins/cylance_protect/bin/icon_cylance_protect
plugins/cylance_protect/help.md
plugins/cylance_protect/plugin.spec.yaml
plugins/cylance_protect/setup.py

Changing the API referenced in the help.md
The original release was not kicked off by Jenkins (1.5.3) but this will kick it off as the version has been changed in each file now
- #2914 (Original PR)
- #2913 (First PR already merged)
- Changing reference in help.md

[SOAR-18032] Cylance Protect Release - Reference changed

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/responses/first_observations_within_window.json.resp
plugins/carbon_black_cloud/unit_test/responses/task_test_data.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py

* Restrain observability Window
* Additionals bug fixes

[Carbon Black Cloud] Observability Window Restraint (#2877)

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/Dockerfile
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/new_exception_request/trigger.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/util/util.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py

- Trigger: `New Exception Request` - Added retry mechanism (#2917) …

[SOAR-17939] InsightVM - Trigger: New Exception Request - Added retry mechanism (#2917)

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/bin/icon_powershell
plugins/powershell/help.md
plugins/powershell/plugin.spec.yaml
plugins/powershell/requirements.txt
plugins/powershell/setup.py

Bump SDK version being used in the plugin and update that the requirements.txt doesn't contain inline comment causing snyk to fail.
Part of ticket: https://rapid7.atlassian.net/browse/SOAR-17972
Testing:
- Image builds locally
- `snyk test` now passes:

SOAR-17972: bump SDK and remove inline comment from requirements.txt

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/bin/icon_powershell
plugins/powershell/help.md
plugins/powershell/plugin.spec.yaml
plugins/powershell/requirements.txt
plugins/powershell/setup.py

Release of Powershell v3.0.6
Changes:
- Bump SDK version
- Update requirements.txt to not have inline comment to allow snyk scans to run
Tests:
- Basic testing running a few simple commands: `GET-ITEM`, `NEW-ITEM`, `REMOVE-ITEM`
PRs:
- https://github.com/rapid7/insightconnect-plugins/pull/2952

Powershell Release v3.0.6

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/util.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

- Add further exception handling around calculating new rate limted time as we can't hit this ourselves. 
- Original exception noticed was that the response header is a string so not convert this to an int before carrying out the calculations. 
- On adding unit tests realised that we don't check the response from `check_rate_limit`, so I have updated this and added a unit test to cover.
- Unit tests passing. 
- Mimecast happy path locally works as expected. 

[SOAR-17874] [Mimecast] - rate limiting improvements. 

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/util.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

Release of Mimecast 5.3.20
Changes:
- Handle response heade combing back as string format.
- Add broader except to catch other errors when rate limiting being enforced.
- Bump back off period for rate limits to be 10 minutes from 5 minutes.
- Check rate limit value stored in the state correctly.
Original PR:
- #2958 
Testing:
- Unit test added and all passing.
- Integration tests passing.
- C2C rolled over internally with no issues.

Mimecast Release v5.3.20

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/expected/monitor_users_bad_request.json.exp

There is a quirk in the datetime library that if you run `now()` at a time that has the time microseconds being exactly `000000` later when we run `.isoformat()` this drops the microseconds from the string value. This PR addresses this to ensure we always have the microseconds to query the API and store this in the state as expected.
Some background changes on times in this plugin 😮‍💨  :
- We store the time values in the state **without** the `T` for .isoformat() -> `2024-11-14 10:06:00.663541+00:00`
- It looks like **previously** we used to store it with the `T` meaning it would be -> `2024-11-14T10:06:00.663541+00:00`
- The Salesforce API requires that we have the `T` delimiter otherwise the query fails on parsing the spaces.
Because of this there's a few strange mixture of string state …

[SOAR-18202] [Salesforce] Ensure date.now includes microseconds

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/Dockerfile
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/expected/monitor_users_bad_request.json.exp

Release of Salesforce v2.1.12
Changes:
- Bump SDK
- Allow for .now() to be executed with microseconds value of zero and account for this in state held values and querying Salesforce API. 
Testing -
- Unit tests passing
- Manual testing
- Reactivated integration on staging with a broken state value and plugin passed without errors. [Logs search](https://us.ops.insight.rapid7.com/op/73D74FD3120207F7E98B#/search?from=1731599598000&logs=%5B%22a9fe3bda-0c32-41ce-b347-a2fcbec2b49b%22%5D&query=where(0d5f69e4-1c7c-41a0-a0ac-a5ac9a4b41fb%20and%20%22Get%20updated%20users%20-%20start%22)&to=1731600078000)
- broken state value is: `2024-11-08 19:10:38+00:00`
PRs:
- #2960

Salesforce Release 2.1.13

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/Dockerfile
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py

Fix error handling for 404 responses from carbon_black_cloud

[Carbon Black Cloud] Fix 404 job id response

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/Dockerfile
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py
plugins/carbon_black_cloud/unit_test/test_monitor_alerts.py

[Carbon Black Cloud] Fix Handling 404 JOB ID responses (#2962)

---

plugins/broadcom_symantec_endpoint_protection/.CHECKSUM
plugins/broadcom_symantec_endpoint_protection/Dockerfile
plugins/broadcom_symantec_endpoint_protection/bin/icon_broadcom_symantec_endpoint_protection
plugins/broadcom_symantec_endpoint_protection/help.md
plugins/broadcom_symantec_endpoint_protection/plugin.spec.yaml
plugins/broadcom_symantec_endpoint_protection/requirements.txt
plugins/broadcom_symantec_endpoint_protection/setup.py

Addressing [Snyk Vulnerabilities](https://app.snyk.io/org/soar-insightconnect-new/project/3cf527aa-3c43-47db-9461-322185e08804)
- #2967 
- SDK bump 6.2.0

[SOAR-18245] Broadcom Symantec Endpoint Protection 2.0.2 Release

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/komand_whois/actions/address/action.py
plugins/whois/plugin.spec.yaml
plugins/whois/setup.py

A customer was experiencing an issue when proving an RIPE IP, the `orgname` would not return when using ICON, but it would return when using WhoIs website. This is cause the orgname pointed to the description.
As the description did not have an existing field, as the orgname pointed to it, I added a description field too.
[SI TICKET](https://rapid7.atlassian.net/browse/SI-26530)
- Update Address action (add `description` output field. Correct mapping for `orgname` field)
- SDK bump to 6.2.0
When using the same IP the user used, it now returns the `orgname`:
As the above IP does not have a description, when using another RIPE IP, it returns the description too:
When specifiying …

[SOAR-18258] Whois - Update address action

---

plugins/palo_alto_pan_os/.CHECKSUM
plugins/palo_alto_pan_os/Dockerfile
plugins/palo_alto_pan_os/bin/komand_palo_alto_pan_os
plugins/palo_alto_pan_os/help.md
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_address_object_to_group/action.py
plugins/palo_alto_pan_os/plugin.spec.yaml
plugins/palo_alto_pan_os/requirements.txt
plugins/palo_alto_pan_os/setup.py

[TICKET](https://rapid7.atlassian.net/browse/SOAR-18265)
Investigating an [SI issue](https://rapid7.atlassian.net/browse/SI-26543), when debugging it seems the `.join() `operator should not be used due to it adding significantly large amount of duplicate data which leads to the following error:
`insightconnect_plugin_runtime.exceptions.LoggedException: ('Connection aborted.', BadStatusLine('<html>\r\n'))
`
The current plugin, reads the existing IP's in a list then appends the new one onto it, but the `.join()` operator does this:
This is due to joining all of the previous IP's along with the new one in each iteration (eg if the list has abc and next element is def the input will be abcdef and not def)
Changing the `.join()` to just add the string via `+=` resolves this:
**This does not …

[SOAR-18265] Palo Alto Pan OS - Fix add_address_object_to_group action

---

plugins/palo_alto_pan_os/.CHECKSUM
plugins/palo_alto_pan_os/Dockerfile
plugins/palo_alto_pan_os/bin/komand_palo_alto_pan_os
plugins/palo_alto_pan_os/help.md
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_address_object_to_group/action.py
plugins/palo_alto_pan_os/plugin.spec.yaml
plugins/palo_alto_pan_os/requirements.txt
plugins/palo_alto_pan_os/setup.py

[TICKET](https://rapid7.atlassian.net/browse/SOAR-18265)
The `.join()` operator should not be used due to it adding significantly large amount of duplicate data which leads to this error: `('Connection aborted.', BadStatusLine('<html>\r\n'))`. This is due to joining all of the previous IP's along with the new one in each iteration (eg if the list has abc and next element is def the input will be abcdef and not def)
Changing the `.join()` to just add the string via `+=` resolves this.
- #2976 
- Fix `add_address_object_to_group` action (duplicate appending)
- SDK bump to 6.2.0

[SOAR-18265] Palo Alto Pan OS 6.1.7 Release

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/Dockerfile
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py
plugins/rapid7_insight_agent/unit_test/test_get_agent_details.py

Regarding an [issue the customer has experienced](https://rapid7.atlassian.net/browse/SI-26673), when executing the action (`get_agent_details`) and no data is returned, a Plugin Exception is raised (when it shouldn't be as the action technically ran successfully) instead of returning an empty dictionary.  This failure interrupts customers workflows (and returning an empty dictionary is also used in the majority of other actions).
- Update `get_agent_details` action to allow for an empty result to be returned
Update the unit test to reflect action change:

[SOAR-18367] Updating Get Agent Details action (SI)

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/Dockerfile
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py
plugins/rapid7_insight_agent/unit_test/test_get_agent_details.py

Updating `get_agent_details` action to allow no results to be returned as it was returning a `400` previously if no results were returned (even though the action ran successfully)
- #2984
- Update `get_agent_details` action to allow for an empty result to be returned

[SOAR-18367] Rapid7 Insight Agent 3.0.1 Release

---

plugins/base64/.CHECKSUM
plugins/base64/Dockerfile
plugins/base64/bin/komand_base64
plugins/base64/help.md
plugins/base64/plugin.spec.yaml
plugins/base64/setup.py

Part of a long list of plugins being bumped to latest SDK.

[SOAR-18473] [Base64] Bump SDK Version

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/plugin.spec.yaml
plugins/whois/setup.py

Part of a long list of plugins being bumped to latest SDK.
note all tests pass locally, but fail on here due to needing to install whois via the docker file
```
❯ python3 -m unittest *
....
----------------------------------------------------------------------
Ran 4 tests in 0.016s
OK
```

SOAR-18473: bump SDK and address vulnerabilities

---

plugins/math/.CHECKSUM
plugins/math/Dockerfile
plugins/math/bin/komand_math
plugins/math/help.md
plugins/math/plugin.spec.yaml
plugins/math/setup.py

Bumping SDK and no vulnerability

[SOAR-18473] Math - fedRAMP, SDK bump and vulnerability

---

plugins/rdap/.CHECKSUM
plugins/rdap/Dockerfile
plugins/rdap/bin/icon_rdap
plugins/rdap/help.md
plugins/rdap/plugin.spec.yaml
plugins/rdap/setup.py

[SOAR-18473] RDAP fedRAMP, SDK bump and vuln

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

An [SI ticket](https://rapid7.atlassian.net/browse/SI-26849) was made in accordance to the schema being incorrect. The customer cannot access some of the keys due to the formatting in the pluginspec and other fields such as `statement` were missing altogether.
- Update schema for `advanced_query_on_log`, `advanced_query_on_log_set` & `query` to account for missing keys and invalid mapping
Fields now show in the schema output:

[SOAR-18495] Rapid7_InsightIDR Fix Schema (advanced_query_on_log)

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/Dockerfile
plugins/palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
plugins/palo_alto_cortex_xdr/help.md
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/monitor_alerts/task.py
plugins/palo_alto_cortex_xdr/plugin.spec.yaml
plugins/palo_alto_cortex_xdr/setup.py
plugins/palo_alto_cortex_xdr/unit_test/test_monitor_alerts.py

- Update pagination decision logic to check alert limit …

[SOAR-18536] palo alto cortex xdr

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/Dockerfile
plugins/palo_alto_cortex_xdr/bin/icon_palo_alto_cortex_xdr
plugins/palo_alto_cortex_xdr/help.md
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/tasks/monitor_alerts/task.py
plugins/palo_alto_cortex_xdr/plugin.spec.yaml
plugins/palo_alto_cortex_xdr/setup.py
plugins/palo_alto_cortex_xdr/unit_test/test_monitor_alerts.py

* Update pagination decision in task
- Update pagination decision …

Palo Alto Cortex XDR 4.0.5 Release

---

plugins/dig/.CHECKSUM
plugins/dig/Dockerfile
plugins/dig/bin/komand_dig
plugins/dig/help.md
plugins/dig/plugin.spec.yaml
plugins/dig/setup.py

Release of Dig v2.0.4 to bump to latest SDK and fix any vulnerabilities.
Original PR: #3001 
Validator failing due to installs in Dockerfile which is expected.

Dig Release v2.0.4

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/unit_test/test_get_agent_details.py

Regarding an [SI ticket](https://rapid7.atlassian.net/browse/SI-26673), a suggestion was made to clean up the output for the `get_agent_details` action to include the `agent` field but not populate it if there is no assets found (as it currently only returns `{}`). This will make it easier for the customers to understand when reading and will allow them to build workflows around the action easier as there is a field to check in the output.
- Update `get_agent_details` action to include `agent` in the output when no assets found
- Unit test updated to reflect above
Tested it locally and the agents field is now returned:

[SOAR-18559] insightagent

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/get_all_agents_by_ip/schema.py
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py
plugins/rapid7_insight_agent/unit_test/test_get_agent_details.py

- #3007 
- #3034 (Update action output for `get_agent_detail` to include `agent` field when no assets are found)

[SOAR-18473] Rapid7 Insight Agent 3.0.2 Release (fedRAMP)

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py

Release of InsightVM Console v8.0.8
Original PR: #3020 
Note: verifying we want this release as it's not marked as cloud ready. 
Update: Chatted to Igor around this and we still want to include these changes.

Release Rapid7 InsightVM Console v8.0.8

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/Dockerfile
plugins/rapid7_vulndb/bin/komand_rapid7_vulndb
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/plugin.spec.yaml
plugins/rapid7_vulndb/setup.py

[SOAR-18473] Rapid7 vulnDB 2.1.5 Release (fedRAMP) 

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/actions/get_logs/schema.py
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/schema.py
plugins/duo_admin/plugin.spec.yaml

Updating the plugin.spec to be in sync with the help.md. Due to the large description for the get_logs action, I am unable to add it in the plugin.spec although I found the docs where all inputs parameters are linked and added that in the spec.
PR will be bundled alongside:
- https://github.com/rapid7/insightconnect-plugins/pull/3021
- Update `plugin.spec` to be in sync

Duo Admin plugin.spec sync

---

plugins/okta/.CHECKSUM
plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/schema.py
plugins/okta/plugin.spec.yaml

Updating the `plugin.spec` to be in sync with the `help.md`. There is no way to add the extra details in the plugin.spec so the user knows the action output when there is no users/groups, but I think it can be removed as it's common sense 😅 
This will get bundled alongside #3012 
- Updating `plugin.spec`

Okta plugin.spec sync

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/actions/get_logs/schema.py
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/schema.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py

- #3017     
- #3037 
- SDK Bump to 6.2.2

[SOAR-18529] Duo Admin 5.0.2 Release (fedRAMP)

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/Dockerfile
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

Part of a long list of plugins being bumped to latest SDK.

[ServiceNow] SOAR-18473: bump SDK and address vulnerabilities

---

plugins/string/.CHECKSUM
plugins/string/Dockerfile
plugins/string/bin/komand_string
plugins/string/help.md
plugins/string/komand_string/actions/split_to_object/schema.py
plugins/string/plugin.spec.yaml
plugins/string/setup.py

Release PR for 
https://github.com/rapid7/insightconnect-plugins/pull/3000/
- Update the SDK version

String 1.4.2 Release (fedRAMP)

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/plugin.spec.yaml
plugins/whois/requirements.txt
plugins/whois/setup.py

Wiki Page detailing the decency changes and why: https://rapid7.atlassian.net/wiki/spaces/KOMAND/pages/1337360485/Whois+fedRAMP
- SDK bump to 6.2.3
- Whois dependency updated
- Plugin.spec sync
Original PR's:
- https://github.com/rapid7/insightconnect-plugins/pull/3047
- https://github.com/rapid7/insightconnect-plugins/pull/2997
- https://github.com/rapid7/insightconnect-plugins/pull/3052
- https://github.com/rapid7/insightconnect-plugins/pull/3054
Validator is expected to fail due to **CloudReady**

[SOAR-18528] Whois 3.1.7 Release (fedRAMP)

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/Dockerfile
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/schema.py
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py
plugins/proofpoint_tap/unit_test/expected/monitor_events_bad_request.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_server_error.json.exp
plugins/proofpoint_tap/unit_test/test_monitor_events.py
plugins/proofpoint_tap/unit_test/test_util.py

- Refactor task
- Update task handling of API limitations for all integration run types (first, subsequent, paginating)
- Remove system env variable used in backfill
- Limit supplied cutoff to the API limit
- Update error handling for API limits …

[SOAR-18584] Proofpoint TAP

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/bin/icon_powershell
plugins/powershell/help.md
plugins/powershell/icon_powershell/connection/connection.py
plugins/powershell/plugin.spec.yaml
plugins/powershell/requirements.txt
plugins/powershell/setup.py

Powershell - 18586 - Updated dependencies | Updated SDK to the latest version (#3041)

---

plugins/microsoft_atp/.CHECKSUM
plugins/microsoft_atp/Dockerfile
plugins/microsoft_atp/bin/komand_microsoft_atp
plugins/microsoft_atp/help.md
plugins/microsoft_atp/plugin.spec.yaml
plugins/microsoft_atp/setup.py

Release of MS ATP v6.0.1 to address vulnerabilities and pull latest SDK image, alongside updating the plugin name due to third party rebranding. 
Original PRs:
- #3016  : latest buildpack 
- #3043 : plugin rename
- #3049 : help.md missed references

Release MS ATP 6.0.2

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/komand_duo_admin/util/constants.py
plugins/duo_admin/komand_duo_admin/util/util.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/expected/monitor_logs_rate_limit.json.exp
plugins/duo_admin/unit_test/inputs/monitor_logs_with_rate_limit.json.inp
plugins/duo_admin/unit_test/test_monitor_logs.py

* Updating plugin.spec (#3047)
* Duo admin Improve handling of 429s in task code
* Linting the code
* Version bump
* Adjusting styling
* Resolving static code analysis
* Resolving plugin's validation
* CR fixes
* Additional test case
* Bumping the SDK and linting the code
---------
-
* …

[SOAR-17745] Duo admin Improve handling of 429s in task code (#3048)

---

plugins/mimecast_v2/.CHECKSUM
plugins/mimecast_v2/help.md
plugins/mimecast_v2/icon_mimecast_v2/connection/schema.py
plugins/mimecast_v2/plugin.spec.yaml

[SOAR-18657] Mimecast v2 tooltip

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

The advance query on log action requires either a `log name` or `log ID` to be provided for the action to run. As we allow either or, both are set to required:false as we can't specify a certain one as required in the event the other user wants to use the other input. 
This updates the description to specify that one of the fields are required for the action to run, to avoid confusion for the customer.
- Update description for 'Advanced Query on Log' action
- SDK bump to 6.2.4

[SOAR-18533] Insight IDR Update Advanced Query on Log action description

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/Dockerfile
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

As the log name or log id is required for the action to run but are both set to `required:false`, this specified that one or the other is needed.
Original PR:
- #3089 
- Update description for 'Advanced Query on Log' action
- SDK bump to 6.2.4

[SOAR-18533] Insight IDR 11.0.1 Release - Update Action description

---

plugins/mimecast_v2/icon_mimecast_v2/tasks/monitor_siem_logs/task.py
plugins/mimecast_v2/icon_mimecast_v2/util/api.py

- If a file is saved to be read again in the next run, we store the position in that file as the number of logs read in that file. If we have to use the file in three or more runs, we start the file at the same position as the second run. By adding the previous position to the number of logs returned in this run, we can properly finish the file.. …

Mimecast V2 continue file reading bug

---

plugins/extractit/.CHECKSUM
plugins/extractit/bin/icon_extractit
plugins/extractit/help.md
plugins/extractit/icon_extractit/util/extractor.py
plugins/extractit/plugin.spec.yaml
plugins/extractit/requirements.txt
plugins/extractit/setup.py

Bumping to latest package of tldextract so that we are FIPs compliant. 
- Package bump
- Latest package does allow direct access of the domain / suffix attributes like we previously did so accessing these using the attribute name
- Tested comparing the output on 3.0.9 vs 3.0.11 and action works as expected for subdomain true/false.
- Tested deploying debug image to govcloud and it spins up without FIPs warning. 
- Unit tests passing.
Coverage is a breaking change in icon-ci tooling that needs fixed
Debug window of how the values were accessed before:

[SOAR-18906] Bump `tldextract` to latest version for FIPs compliance

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/bin/icon_powershell
plugins/powershell/help.md
plugins/powershell/icon_powershell/util/util.py
plugins/powershell/plugin.spec.yaml
plugins/powershell/requirements.txt
plugins/powershell/setup.py

The `cryptography` package has introduced a snyk vulnerability, this will bump it to the latest version. 
The following text was originally mentioned in the setup section within the help.md but there is no way to alter this in the plugin.spec so not be deleted when running `refresh` so I have reworded it and added it under troubleshooting:
SSL is `configured for all ports except 5985`-> `SSL is not configured for port 5985`
- Bumping `cryptography` package
Snyk test after bumping cryptography:

[SOAR-19013] Powershell Snyk vuln & SDK bump

---

plugins/advanced_regex/.CHECKSUM
plugins/advanced_regex/Dockerfile
plugins/advanced_regex/bin/icon_advanced_regex
plugins/advanced_regex/help.md
plugins/advanced_regex/plugin.spec.yaml
plugins/advanced_regex/setup.py

At the moment, when we run refresh it will change the schema file for the `data_extraction` action to remove the need for `[][]`. When testing locally, I seen that it does need to support [][] as the output for groups are in their own array within an array:
```
"output": {
"matches": [
[
"startTime:1739447174230\n",
"1739447174230"
],
[
"startTime:9999999999999",
"9999999999999"
]
]
}
```
This will require the tooling to be updated to allow for the support of `[][]` but at the moment this needs to be manually reverted back and MD5 ran on it to ensure the CHECKSUM is up to date.

Advanced Regex - (SDK Automation prep)

---

.github/workflows/black.yml
pyproject.toml

At the moment, the linter check runs different on **insightconnect-plugins** vs **komand-plugins**. This repo currently runs the check via `black . --check` whereas **komand-plugins** runs it on `CHANGED_FILES=()`. 
From testing it is clear that **insightconnect-plugins** does not detect files which require black changes due to this check whereas **komand-plugins** does. This PR will have the 2 checks in sync. I am currently making an update to the tooling which will add functionality into the refresh function to allow us to ensure we are always passing the linter without manually needing to run black and MD5.
PR for komand-plugins: https://github.com/rapid7/komand-plugins/pull/2138
- Update Linter check

[SOAR-19079] Update Linter check

---

.github/workflows/black.yml

Linter check defaults to 88 char which is not is inline with the 120 character length we have changed to. This will enforce this.
- Change to 120 char check

Fixing Linter check for 120 char

---

.github/workflows/main.yml
.github/workflows/unit_test.yml
.github/workflows/unit_test_coverage.yml

When bumping the ubuntu and python version in our workflows, there were a few with no fetch depth added, causing them to fail:
```
subprocess.CalledProcessError: Command '['git', 'diff', '--name-only', 'origin/master..origin/BRANCH']' returned non-zero exit status 128.
161
```
This will add it in for the broken workflows.

[SOAR-19228] Adding Fetch Depth - Workflows

---

plugins/microsoft_defender_incidents/.CHECKSUM
plugins/microsoft_defender_incidents/bin/icon_microsoft_defender_incidents
plugins/microsoft_defender_incidents/help.md
plugins/microsoft_defender_incidents/icon_microsoft_defender_incidents/actions/update_incident/schema.py
plugins/microsoft_defender_incidents/icon_microsoft_defender_incidents/connection/schema.py
plugins/microsoft_defender_incidents/plugin.spec.yaml
plugins/microsoft_defender_incidents/setup.py

The `Clean` value was [previously removed](https://github.com/rapid7/insightconnect-plugins/pull/3302) due to it not working, and it seems Microsoft have changed it's value to NotMalicious (even though the documentation does not state this, the customer found the renaming when using the UI). This will add the value in. 
- Adding `NotMalicious` value
Locally I am able to update an incident with the field:

[NO-TICKET] Adding NotMalicious value within determination field - update_incidents

---

plugins/jq/.CHECKSUM
plugins/jq/help.md
plugins/jq/icon_jq/actions/run_jq/action.py
plugins/jq/icon_jq/actions/run_jq/schema.py
plugins/jq/plugin.spec.yaml
plugins/jq/unit_test/test_run_jq.py

Another possible POC to ensure jq is secure whilst cloud enabling is to heavily limit the flags that can be used. We originally were going to disable the field completely although after talking we think it is best not to reduce functionality but to heavily sanitise it via limited options. We still need to find a way to select multiple flags (string input? multiple enums?)
This also updates the unit test to test a flag not allowed cannot be used and correct exception raised
Some filters also blocked to prevent importing and other possible leaks.
- Heavily limit flag input fields
- Unit test updated

POC - Limited flag inputs | Unit Test updated

---

.github/workflows/prospector.yml
.github/workflows/unit_test_coverage.yml

V3 of upload-artifact is being deprecated. This is preventing the unit test coverage being generated. This will update to v4
Snowballstemmer 3.0.0 is causing issues. Specifying an older version works.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
- Update upload-artifact to v4 
- Install prior version of `snowballstemmer`

[NO-TICKET] Unit Test Coverage- Resolve deprecation of v3

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/assign_user_to_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/create_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/get_alert_information/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/get_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/list_investigations/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/search_alerts/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/search_investigations/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/set_disposition_of_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/set_priority_of_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/set_status_of_investigation_action/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/update_alert/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/update_investigation/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/triggers/get_new_alerts/schema.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/triggers/get_new_investigations/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

IDR have since updated the possible disposition values when creating/updating an investigation. A field or two will now return 400 if it is not removed as IDR no longer support is as a disposition field (`UNMAPPED`) and additional fields have been added. 
- Link to IDR code to specify the possible fields: https://github.com/rapid7/razor-properties/blob/master/CPS/globals/globals.yml#L1282
- Adding additional `disposition` values
Tested each new disposition value and it creates/updates with the new value.

[SOAR-19518] Rapid7 InsightIDR - Additional disposition values

---

plugins/carbon_black_cloud/.CHECKSUM
plugins/carbon_black_cloud/bin/icon_carbon_black_cloud
plugins/carbon_black_cloud/help.md
plugins/carbon_black_cloud/icon_carbon_black_cloud/tasks/monitor_alerts/task.py
plugins/carbon_black_cloud/plugin.spec.yaml
plugins/carbon_black_cloud/setup.py

- Update start time to end time if no logs after dedupe …

[SOAR-19634] Carbon Black Cloud - Fix set time on dedupe

---

plugins/anomali_threatstream/.CHECKSUM
plugins/anomali_threatstream/Dockerfile
plugins/anomali_threatstream/help.md
plugins/anomali_threatstream/komand_anomali_threatstream/actions/import_observable/action.py
plugins/anomali_threatstream/komand_anomali_threatstream/actions/import_observable/schema.py
plugins/anomali_threatstream/plugin.spec.yaml

SDK Bump to 6.3.7
After testing on staging I spotted a few bugs:
- If no date value provided action will fail as "" is not of type date. This will set it to None and exclude it from the body. Anomali will then default it to 90 days on their end
- Various enum values did not have an option to select null (in the case they selected a value and changed their mind)
- Validation added to ensure confidence is between 0-100
Original PR: #3469

[SOAR-19462] Anomali - Minor Refinements after staging test

---

.snyk

Various snyk vulnerabilities have come in which are patchable in `3.11` but not in `3.9`. In addition to this, our repo uses `3.11` so it's best to align this with snyk. This will update the python version snyk uses for this repo to be `3.11`
- Update Snyk version to `3.11`

[NO-TICKET] InsightConnect - Bumping snyk version to 3.11

---

plugins/duo_admin/.CHECKSUM
plugins/duo_admin/Dockerfile
plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/komand_duo_admin/util/helpers.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/test_monitor_logs.py

This release rolls back 5.0.7 release to remove the corrupted state values bug being tracked under: https://rapid7.atlassian.net/browse/SOAR-19900
Noticed as part of a low alert triggering that task failures in us-west-2 but was impacted spread across all regions. 
PR changes:
- Revert the changes applied in 5.0.6 that added the lagging decorator and bumping the time forward causing the corrupted timestamp value when no data is returned. 
- The reason behind bumping the time forward was to prevent the alerts of the integration being 'stuck' if no data was returned within the lagging period. 
- A new conversion method added to the start of the integration run to revert corrupted data values in the state and let the task resume as expected. 
Testing:
- Locally testing on the the task …

Duo Admin v5.0.7 Release

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/tag_assets/action.py
plugins/rapid7_insightvm/plugin.spec.yaml

Resolving high Snyk vulnerability: https://app.snyk.io/org/soar-insightconnect-new/project/ca817260-aa88-429e-aabe-517065276b1b
I was going to make an update to IVM a few weeks ago in regards to an SI but it closed out as it is not a plugin issue. This PR will remove them changes. 
- Revert changes in #3530
- SDK bump to 6.3.9
- Bumping `aiohttp` (snyk)

[SOAR-20017] Rapid7 InsightVM - Snyk Vulnerability

---

plugins/hybrid_analysis/.CHECKSUM
plugins/hybrid_analysis/bin/icon_hybrid_analysis
plugins/hybrid_analysis/help.md
plugins/hybrid_analysis/icon_hybrid_analysis/connection/schema.py
plugins/hybrid_analysis/icon_hybrid_analysis/util/api.py
plugins/hybrid_analysis/icon_hybrid_analysis/util/constants.py
plugins/hybrid_analysis/plugin.spec.yaml
plugins/hybrid_analysis/setup.py
plugins/hybrid_analysis/unit_test/util.py

https://rapid7.atlassian.net/browse/SOAR-20185
For the following actions, now we use the specified URLs: 
- Lookup by Hash – https://www.hybrid-analysis.com 
- Search Database – https://hybrid-analysis.com 
- Submit File – https://hybrid-analysis.com 
- Retrieve Report – https://www.hybrid-analysis.com 
It seems that two separate connections, with and without “www,” are needed for the plugin to function correctly.

[SOAR-20185] Hybrid analysis connection URL
