rapid7/insightconnect-plugins

README.md
haveibeenpwned/plugin.spec.yaml

- Update support status for haveibeenpwned plugin
4. Add UI screenshot of the workflow used …

Haveibeenpwned: Update support status

---

.github/pull_request_template.md
README.md

- PR template updates for style
4. Add UI screenshot of the workflow used for testing
5. Add …

PR Template: Add style highlights to PR template

---

README.md

- Add pyyaml dependency to README.md for tooling
3. Copy (`./run ... | pbcopy`) and paste the output in **a …

README: Add pyyaml dependency

---

tools/Makefiles/Helpers.mk

- Removes the old CI tooling bundled with the plugins repo in favor of the new all-Python, pip-installable tooling.
2. Run the assessment tool: `./run -A -R all -T all`. For single action validation: `./run -A -R tests/my_action.json -T …

Update Makefile validate target

---

CONTRIBUTING.md
README.md

- Add mailing list link for developers
3. Copy (`./run ... | pbcopy`) and paste the output in **a new …

Add developer mailing list to README and CONTRIBUTING docs

---

README.md
tools/check_spec.py

- Add dependency check in `check_spec.py` script.
-  Mention dependency in `README.md`
3. Copy (`./run ... …

Add js-yaml dependency check for check_spec.py

---

duo_auth/Makefile

- Updates Duo Auth plugin w/ the latest Makefile
3. Copy (`./run ... | pbcopy`) and paste the output in **a …

Duo Auth: Update Makefile with latest version

---

tools/Makefiles/Helpers.mk

- Removes unnecessary icon Makefile target
3. Copy (`./run ... | pbcopy`) and paste the output in **a new …

Remove icon target

---

README.md

- Mentions `update-tools.sh`
3. Copy (`./run ... | pbcopy`) and paste the output in **a new post** on this …

Update Readme with update-tools.sh

---

CONTRIBUTING.md
README.md

- We can't make it public according to IT
- List has been removed
3. Copy (`./run ... | pbcopy`) and paste …

Remove mailing list references

---

.gitignore

- Gitignores new files that may show in the repo: `.tar`, `.output`, and `.plg`.
3. Copy (`./run ... | …

Gitignore: Add new packages and .output to .gitignore

---

.github/workflows/main.yml

- Adds a GitHub Action workflow to run plugin validation against changed plugins
3. Copy (`./run ... | …

Repository CI

---

freegeoip/help.md

FreeGeoIP Test

---

freegeoip/komand_freegeoip/connection/connection.py

Update FreeGeoIP Test

---

freegeoip/komand_freegeoip/connection/connection.py
freegeoip/plugin.spec.yaml

Freegeoip connection

---

freegeoip/Dockerfile
google_safe_browsing/Dockerfile

Test multiple plugins for autorelease

---

jira/Makefile
jira/bin/komand_jira
jira/help.md
jira/komand_jira/actions/assign_issue/action.py
jira/komand_jira/actions/attach_issue/action.py
jira/komand_jira/actions/comment_issue/action.py
jira/komand_jira/actions/create_issue/action.py
jira/komand_jira/actions/create_issue/schema.py
jira/komand_jira/actions/edit_issue/action.py
jira/komand_jira/actions/get_comments/action.py
jira/komand_jira/actions/get_issue/action.py
jira/komand_jira/actions/label_issue/action.py
jira/komand_jira/actions/transition_issue/action.py
jira/komand_jira/connection/connection.py
jira/komand_jira/connection/schema.py
jira/komand_jira/triggers/new_issue/schema.py
jira/komand_jira/triggers/new_issue/trigger.py
jira/komand_jira/util.py
jira/plugin.spec.yaml
jira/setup.py

- Sync private & FOSS repos
3. Copy (`./run ... | pbcopy`) and paste the output in **a new post** on this …

Sync repos 11/4/19

---

microsoft_teams/.CHECKSUM
microsoft_teams/bin/icon_microsoft_teams
microsoft_teams/help.md
microsoft_teams/icon_microsoft_teams/triggers/new_message_received/trigger.py
microsoft_teams/icon_microsoft_teams/util/teams_utils.py
microsoft_teams/plugin.spec.yaml
microsoft_teams/setup.py
microsoft_teams/tests/new_message_received.json
microsoft_teams/unit_test/test_get_teams.py
microsoft_teams/unit_test/test_new_message_received.py

This PR changes regex in Microsoft Teams to use search instead of match. Match only finds matches at the beginning of a string, search will find matches anywhere in a string. 
NOTE: 3 failures - 2 are due to being unable to remove a channel and re-add a channel with the same name. The 3rd failure is due to the tests running out of order. Was retested in order and worked properly (It tried to create a group that already exists)
```
rmt-mbp-5357:microsoft_teams jmcadams$ ./run.sh -R tests/new_message_received.json
Running: cat tests/new_message_received.json | docker run --rm   -i rapid7/microsoft_teams:1.2.1 --debug run
This is a trigger ^C to continue
Refreshing auth token
Updating Auth Token...
Getting token from: https://login.microsoftonline.com/5c824599-dc8c-4d31-96fb-3b886d4f8f10/oaut …
```

Microsoft teams switch match to search

---

freegeoip/Dockerfile

DEMO Auto-release

---

abuseipdb/help.md
abuseipdb/plugin.spec.yaml

AbuseIPDB hub update

---

statsd/help.md
statsd/plugin.spec.yaml
storage/help.md
storage/plugin.spec.yaml
string/help.md
string/plugin.spec.yaml
subnet/help.md
subnet/plugin.spec.yaml

Hub udpate plugins joey 5

---

sumologic/help.md
sumologic/plugin.spec.yaml
symantec_bcs/help.md
symantec_bcs/plugin.spec.yaml
syslog_forwarder/help.md
syslog_forwarder/plugin.spec.yaml
tcpdump/help.md
tcpdump/plugin.spec.yaml
tcpxtract/help.md
tcpxtract/plugin.spec.yaml
tenable_io/help.md
tenable_io/plugin.spec.yaml
tenable_nessus/help.md
tenable_nessus/plugin.spec.yaml

This PR updates a bunch of plugins for the Hub Launch

Hub update plugins joey Vol. 4

---

threatq/help.md
threatq/plugin.spec.yaml
threatstack/help.md
threatstack/plugin.spec.yaml
tr/help.md
tr/plugin.spec.yaml
traceroute/help.md
traceroute/plugin.spec.yaml
trello/help.md
trello/plugin.spec.yaml
trufflehog/help.md
trufflehog/plugin.spec.yaml

This PR updates a bunch of plugins for the Hub launch

Hub udpate plugins joey 3

---

url_expander/help.md
url_expander/plugin.spec.yaml
urlscan/help.md
urlscan/plugin.spec.yaml
viper/help.md
viper/plugin.spec.yaml
virustotal_yara/help.md
virustotal_yara/plugin.spec.yaml
vmray/help.md
vmray/plugin.spec.yaml

This PR updates a bunch of plugins for the hub launch.

Hub Update Plugins vol.2 by joey

---

google_admin/help.md
google_admin/plugin.spec.yaml
google_cloud_compute/help.md
google_cloud_compute/plugin.spec.yaml
google_cloud_pub_sub/help.md
google_cloud_pub_sub/plugin.spec.yaml
google_directory/help.md
google_directory/plugin.spec.yaml
google_docs/help.md
google_docs/plugin.spec.yaml
google_drive/help.md
google_drive/plugin.spec.yaml
google_safe_browsing/help.md
google_safe_browsing/plugin.spec.yaml
google_search/help.md
google_search/plugin.spec.yaml
google_sheets/help.md
google_sheets/plugin.spec.yaml
google_web_risk/help.md
google_web_risk/plugin.spec.yaml

- Update help and yaml on google plugins
3. Copy (`./run ... | pbcopy`) and paste the output in **a new …

Google: hub update

---

bhr/help.md
bhr/plugin.spec.yaml
bitbucket/help.md
bitbucket/plugin.spec.yaml
blockade/help.md
blockade/plugin.spec.yaml
bluecoat_labs/help.md
bluecoat_labs/plugin.spec.yaml

[Hub Convert] - BHR, Bitbucket, Blockade, Bluecoat Labs

---

vxstream_sandbox/help.md
vxstream_sandbox/plugin.spec.yaml
wazuh_ossec/help.md
wazuh_ossec/plugin.spec.yaml
whois/help.md
whois/plugin.spec.yaml
wigle/help.md
wigle/plugin.spec.yaml
wordpress/help.md
wordpress/plugin.spec.yaml
zendesk/help.md
zendesk/plugin.spec.yaml
zenhub/help.md
zenhub/plugin.spec.yaml
zeus_tracker/help.md
zeus_tracker/plugin.spec.yaml

This PR updates the help and spec files on several plugins for the Hub launch.

Hub udpate for plugins FOSS Vol. 1 by Joey

---

active_directory_ldap/help.md
active_directory_ldap/plugin.spec.yaml
advanced_regex/help.md
advanced_regex/plugin.spec.yaml
awk/help.md
awk/plugin.spec.yaml
aws_workspaces/help.md
aws_workspaces/plugin.spec.yaml
base64/help.md
base64/plugin.spec.yaml
basename/help.md
basename/plugin.spec.yaml
datetime/help.md
datetime/plugin.spec.yaml
diff/help.md
diff/plugin.spec.yaml
dirname/help.md
dirname/plugin.spec.yaml
freegeoip/help.md
freegeoip/plugin.spec.yaml
freeipa/help.md
freeipa/plugin.spec.yaml
ftp/help.md
ftp/plugin.spec.yaml
grep/help.md
grep/plugin.spec.yaml

- Awk, AWS workspaces, AD/LDAP hub update
3. Copy (`./run ... | pbcopy`) and paste the output in **a new …

InsightConnect plugin hub updates by Gursimran

---

cef/help.md
cef/plugin.spec.yaml
chaosreader/help.md
chaosreader/plugin.spec.yaml
chardet/help.md
chardet/plugin.spec.yaml
checkdmarc/help.md
checkdmarc/plugin.spec.yaml
checkmarx_cxsast/help.md
checkmarx_cxsast/plugin.spec.yaml
checkpoint_sand_blast/help.md
checkpoint_sand_blast/plugin.spec.yaml
cherwell/help.md
cherwell/plugin.spec.yaml
cif/help.md
cif/plugin.spec.yaml

[Hub Convert] Cef, Chaosreader, Chardet, checkdmarc, checkmarx CxSAST, checkpoint sand blast, Cherwell, Cif

---

opendxl/help.md
opendxl/plugin.spec.yaml
openphish/help.md
openphish/plugin.spec.yaml
openvas/help.md
openvas/plugin.spec.yaml
ossec/help.md
ossec/plugin.spec.yaml
otrs/help.md
otrs/plugin.spec.yaml
p0f/help.md
p0f/plugin.spec.yaml
pagerduty/help.md
pagerduty/plugin.spec.yaml
palo_alto_pan_os/help.md
palo_alto_pan_os/plugin.spec.yaml
paloalto_wildfire/help.md
paloalto_wildfire/plugin.spec.yaml
passivetotal/help.md
passivetotal/plugin.spec.yaml

hub updates for the following:
opendxl 
openphish 
openvas
ossec
otrs
p0f
pagerduty
palo_alto_pan_os
paloalto_wildfire
Passivetotal

Hub Prep - jakob

---

grafana/help.md
grafana/plugin.spec.yaml
graphite/help.md
graphite/plugin.spec.yaml
grr/help.md
grr/plugin.spec.yaml
hashit/help.md
hashit/plugin.spec.yaml
haveibeenpwned/help.md
haveibeenpwned/plugin.spec.yaml
hipchat/help.md
hipchat/plugin.spec.yaml
hippocampe/help.md
hippocampe/plugin.spec.yaml
html/help.md
html/plugin.spec.yaml
hybrid_analysis/help.md
hybrid_analysis/plugin.spec.yaml

Joey Hub Updates Vol. 7

---

netmiko/help.md
netmiko/plugin.spec.yaml
networktotal/help.md
networktotal/plugin.spec.yaml
newrelic/help.md
newrelic/plugin.spec.yaml
nmap/help.md
nmap/plugin.spec.yaml

[Hub Convert] Netmiko, Networktotal, New Relic, Nmap

---

elasticsearch/help.md
elasticsearch/plugin.spec.yaml
eml/help.md
eml/plugin.spec.yaml
facebook_threat_exchange/help.md
facebook_threat_exchange/plugin.spec.yaml
finger/help.md
finger/plugin.spec.yaml
fireeye_hx/help.md
fireeye_hx/plugin.spec.yaml
foremost/help.md
foremost/plugin.spec.yaml

Hub Update Vol. 8

---

kolide/plugin.spec.yaml
malwareconfig/plugin.spec.yaml
math/plugin.spec.yaml
mcafee_epo/plugin.spec.yaml
microsoft_atp/plugin.spec.yaml
newrelic/plugin.spec.yaml
office365_admin/help.md
openphish/plugin.spec.yaml

- Fixes that allow passing of the new 2.0.1 validator updates
No validator output is executed :)
```
$ for i in [k-o]*/plugin.spec.yaml; do printf "$i\n"; .validator/bin/icon-validate $(dirname $i) 2>/dev/null | egrep '(SpecPropertiesValidator|HelpValidator|RequiredValidator|DescriptionValidator|TagValidator|UseCaseValidator) failed'; done
kintone/plugin.spec.yaml
kolide/plugin.spec.yaml
komand/plugin.spec.yaml
lastpass_enterprise/plugin.spec.yaml
logstash/plugin.spec.yaml
malwareconfig/plugin.spec.yaml
markdown/plugin.spec.yaml
math/plugin.spec.yaml
matplotlib/plugin.spec.yaml
mcafee_epo/plugin.spec.yaml
mcafee_esm/plugin.spec.yaml
microsoft_atp/plugin.spec.yaml
microsoft_atp_safe_links/plugin.spec.yaml
microsoft_teams/plugin.spec.yaml …
```

DF-3532: Hub: Validation K-O

---

p0f/plugin.spec.yaml
powershell/help.md
powershell/plugin.spec.yaml
python_2_script/help.md
python_3_script/help.md
redis/help.md
request_tracker/help.md
salesforce/plugin.spec.yaml
samanage/plugin.spec.yaml
screenshot_machine/plugin.spec.yaml
smtp/help.md
sophos_xg_firewall/plugin.spec.yaml
splunk/help.md
sqlmap/help.md
sqlmap/plugin.spec.yaml
ssh/plugin.spec.yaml
statsd/help.md
string/help.md
tenable_io/plugin.spec.yaml
tr/help.md
tshark/help.md
viper/plugin.spec.yaml
vxstream_sandbox/plugin.spec.yaml
whois/help.md

Hub: Validation 3

---

ssh/.CHECKSUM
ssh/bin/komand_ssh
ssh/help.md
ssh/komand_ssh/actions/run/action.py
ssh/komand_ssh/actions/run/schema.py
ssh/plugin.spec.yaml
ssh/setup.py

- Update action's output to include 3 fields i.e. STDERR, STDOUT, STDERR_STDOUT
3. Copy (`./run ... | …

Update action's output to include 3 fields.

---

microsoft_teams/.CHECKSUM
microsoft_teams/bin/icon_microsoft_teams
microsoft_teams/plugin.spec.yaml
microsoft_teams/setup.py

Updating Teams description and help file. 

---

google_cloud_pub_sub/plugin.spec.yaml

- Fix use_case name which should be plural

Hub: Use Case: Reported plural s in use_case

---

rapid7_metasploit/plugin.spec.yaml
redhat_advisory/plugin.spec.yaml

- These are listed in use_cases and do not need to be keywords

Hub: Keywords: Remove use_cases from keywords

---

.github/pull_request_template.md

- Update PR assessment with use of `icon-plugin` tooling
Below is the newly generated PR checklist
-----
-
2. Run …

Update PR assessment

---

.gitignore

- add *.json to the .gitignore file so we do not track new jsons
created new jsons to test
2. Run the assessment tool: `icon-plugin run -A -R all …

DF-3630: Add .json to gitignore

---

rapid7_insightvm/bin/komand_rapid7_insightvm
rapid7_insightvm/help.md
rapid7_insightvm/komand_rapid7_insightvm/triggers/new_exception_request/schema.py
rapid7_insightvm/komand_rapid7_insightvm/triggers/new_exception_request/trigger.py
rapid7_insightvm/plugin.spec.yaml
rapid7_insightvm/setup.py
rapid7_insightvm/tests/new_exception_request.json

Very minor bug fix - exception activity schema didn't quite match the api.  Initial tests were done prior to implementing enumeration in the spec file and the enumeration was specified with capitalization instead of all lower case.

Ivm exception fix1

---

microsoft_atp/plugin.spec.yaml

Set support status to community due to issues obtaining a license from Microsoft

Microsoft ATP: Mark community supported plugin

---

tools/Makefiles/Helpers.mk
tools/misspell.sh
tools/update-tools.sh

- Add `misspell` installation to `tools/update-tools.sh` script
- Run `misspell` on `make validate`
```
$ make validate
...
[*] Checking for typos with Misspell...
[SUCCESS] Passes Misspell check
```

Add misspell linting

---

checkpoint_sand_blast/.CHECKSUM
checkpoint_sand_blast/help.md
checkpoint_sand_blast/komand_checkpoint_sand_blast/actions/upload/schema.py
checkpoint_sand_blast/plugin.spec.yaml

Checkpoint Sand Blast - fixed description

Checkpoint Sand Blast - fixed description

---

jamf/help.md
jenkins/help.md
jira/help.md
joe_sandbox/help.md
jq/help.md
json_edit/help.md
kintone/help.md
kolide/help.md
komand/help.md
lastpass_enterprise/help.md
logstash/help.md

jamf
jenkins
jira
joe_sandbox
jq
json_edit
kintone
kolide
komand
lastpass_enterprise
logstash
-
2. Run the assessment tool: `icon-plugin run -A -R …

updates to help.md files

---

base64/help.md

- Adds a space to the end of help.md to trigger an autorelease on merge
No testing needed. …

Base64 Autorelease Test

---

aws_securityhub/.CHECKSUM
aws_securityhub/bin/icon_aws_securityhub
aws_securityhub/help.md
aws_securityhub/icon_aws_securityhub/triggers/sqs_feed/schema.py
aws_securityhub/plugin.spec.yaml
aws_securityhub/setup.py
barracuda_waf/help.md
misp/help.md
openvas/.CHECKSUM
openvas/bin/komand_openvas
openvas/help.md
openvas/komand_openvas/actions/create_port_list/schema.py
openvas/komand_openvas/actions/create_target/schema.py
openvas/plugin.spec.yaml
openvas/setup.py
vmray/help.md

- Mass update in enum delimiter for consistency and to pass InputOutputValidator

Separate enums by spaces for InputOutputValidator

---

github_enterprise/.CHECKSUM
github_enterprise/help.md
github_enterprise/tests/demote_github_enterprise.json
github_enterprise/tests/demote_github_enterprise_bad.json
github_enterprise/tests/issue_github_enterprise_all.json
github_enterprise/tests/issue_github_enterprise_bad.json
github_enterprise/tests/issue_github_enterprise_org_repo.json
github_enterprise/tests/issue_github_enterprise_repo.json
github_enterprise/tests/issue_github_enterprise_repo_asig.json
github_enterprise/tests/organization_github_enterprise.json
github_enterprise/tests/organization_github_enterprise_bad.json
github_enterprise/tests/promote_github_enterprise.json
github_enterprise/tests/suspend_github_enterprise.json
github_enterprise/tests/suspend_github_enterprise_bad.json
github_enterprise/tests/unsuspend_github_enterprise.json
github_enterprise/tests/unsuspend_github_enterprise_bad.json

- Update help.md requirements section
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin …

Update help.md requirements

---

freegeoip/help.md

- Add a space to the end of a line in freegeoip/help.md to trigger a file change for testing autorelease code.
No testing necessary.
2. Run the assessment tool: `icon-plugin run -A …

Plugin Autorelease Test 2

---

bmc_remedy_itsm/.CHECKSUM
bmc_remedy_itsm/help.md

- update help.md to improve requirements and troubleshooting …

DF-3266 BMC: update requirements and troubleshooting

---

aws_securityhub/help.md
cef/help.md
cherwell/help.md
cisco_cloudlock/help.md
craigslist/help.md
echotrail/help.md
eml/help.md
facebook_threat_exchange/plugin.spec.yaml
ftp/help.md
get_url/help.md
google_admin/help.md
ibm_resilient_incident/help.md
logstash/help.md
matplotlib/help.md
misp/help.md
mxtoolbox_dns/help.md
openvas/help.md
pagerduty/help.md
paloalto_wildfire/help.md
pastebin/help.md
phishtank/help.md
powershell/help.md
python_2_script/help.md
python_3_script/help.md
rest/help.md
sentinelone/help.md
splunk/help.md
tenable_nessus/help.md
threatstack/help.md
uniq/help.md

- Fix broken URLs in `help.md`

Help: Fix URL references

---

grep/.CHECKSUM
grep/bin/icon_grep
grep/setup.py

- Regenerate `grep` plugin
```
$ icon-plugin run -c info
INFO[0000] Running command:  docker run --rm -i rapid7/graphite:1.0.1 info
Name:        Graphite
Vendor:      rapid7
Version:     1.0.1
Description: Store, retrieve, and update metrics in Graphite
Actions (5):
└── metrics_expand (Expands metrics with matching paths)
└── metrics_find (Find metrics under a given path)
└── metrics_index (Walks the metrics tree and returns every metric found)
└── metrics_render (Render metrics data as a graph)
└── metrics_retrieve (Retrieve raw metrics data)
```

Grep: Updates

---

get_url/.CHECKSUM
get_url/help.md

This PR updates the help docs for a couple of typos and missing key features.

Get URL - Update Help

---

test/.dockerignore

- removes an unused test directory from the repository …

Remove test directory

---

rss/help.md

RSS | Update out of date links in help 

---

ipintel/.CHECKSUM
ipintel/help.md
ipintel/plugin.spec.yaml

- Designate the IPIntel plugin as obsolete. …

DF-3837: Mark IPIntel Plugin Obsolete

---

opendxl/.CHECKSUM
opendxl/bin/komand_opendxl
opendxl/help.md
opendxl/plugin.spec.yaml
opendxl/setup.py

Opendxl requirements updated

---

storage/.CHECKSUM
storage/bin/icon_storage
storage/help.md
storage/setup.py
sumologic/.CHECKSUM
sumologic/bin/komand_sumologic
sumologic/help.md
sumologic/setup.py
syslog_forwarder/.CHECKSUM
syslog_forwarder/bin/komand_syslog_forwarder
syslog_forwarder/help.md
syslog_forwarder/setup.py

- Hub updates for storage, sumologic, syslog_forwarder …

Hub updates

---

tsv/help.md
twitter/help.md
typo_squatter/help.md

- Hub Updates for twitter, tsv, typo_squatter …

Hub Updates for twitter, tsv, typo_squatter

---

threatstack/.CHECKSUM
threatstack/bin/komand_threatstack
threatstack/help.md
threatstack/setup.py

fix capitalization issue and regenerate
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json …

Threatstack: fix capitalization issue and regenerate

---

trello/.CHECKSUM
trello/bin/komand_trello
trello/help.md
trello/komand_trello/actions/deactivate_user/schema.py
trello/komand_trello/actions/member_list/schema.py
trello/komand_trello/actions/remove_member_from_board/schema.py
trello/komand_trello/actions/remove_member_from_org/schema.py
trello/plugin.spec.yaml
trello/setup.py

- Update spec titles and descriptions for AcronymValidator to pass
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single …

Update spec titles and descriptions

---

whois/.CHECKSUM
whois/Dockerfile
whois/bin/komand_whois
whois/help.md
whois/plugin.spec.yaml
whois/setup.py
whois/whois.conf

…whois
- Update whois.conf 
- Update Dockerfile to use new version of komand/python whois
2. Run the assessment tool: `icon-plugin run -A -R all -T …

Update whois.conf and Dockerfile to use new version of komand/python whois

---

basename/.CHECKSUM
basename/bin/komand_basename
basename/help.md
basename/setup.py

- Fixes a quotation error in Basename setup.py causing the plugin to fail to execute
2. Run the assessment tool: `icon-plugin run -A -R all -T …

Fix Basename Setup.py

---

sentry/help.md

- Fix DNS Configuration link that could render as a broken link on the Hub …

DF-3846: Fix links in Sentry Help

---

.gitignore

Allow wheels in git

---

.github/workflows/github_webhooks_status.yml
.github/workflows/main.yml

- Update the CI validation workflow to use Python properly as per GitHub recommendations.
2. Run the assessment tool: `icon-plugin run -A -R all -T …

Update CI Validation Workflow

---

awk/help.md

- Minor text fixes in Awk help.md
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A …

DF-3865: Typographical fixes in Awk help.md

---

threatminer/.CHECKSUM
threatminer/Dockerfile
threatminer/bin/komand_threatminer
threatminer/help.md
threatminer/komand_threatminer/actions/email_domain/schema.py
threatminer/komand_threatminer/actions/email_report/schema.py
threatminer/komand_threatminer/actions/import_hash_report/action.py
threatminer/komand_threatminer/actions/ip/schema.py
threatminer/komand_threatminer/connection/connection.py
threatminer/komand_threatminer/util/utils.py
threatminer/plugin.spec.yaml
threatminer/setup.py
threatminer/tests/av_report.json
threatminer/tests/av_sample.json
threatminer/tests/domain.json
threatminer/tests/domain_ext.json
threatminer/tests/email_domain.json
threatminer/tests/email_report.json
threatminer/tests/import_hash_report.json
threatminer/tests/import_hash_samples.json
threatminer/tests/ip.json
threatminer/tests/ip_ext.json
threatminer/tests/report.json
threatminer/tests/samples.json
threatminer/tests/search.json
threatminer/tests/ssdeep_report.json
threatminer/tests/ssdeep_sample.json
threatminer/tests/ssl_hosts.json
threatminer/tests/ssl_report.json

Update documentation | Cast import_hash_report status code to integer | Use python SDK V3 | Add Error handling for import_hash_report action | Add utils to support future changes of the plugin
-
1. Run …

Update Threatminer plugin

---

rest/.CHECKSUM
rest/Dockerfile
rest/bin/komand_rest
rest/help.md
rest/komand_rest/actions/get/action.py
rest/komand_rest/actions/get/schema.py
rest/komand_rest/connection/schema.py
rest/plugin.spec.yaml
rest/setup.py

Update docker
- Put non-object responses inside an object(python dictionary) so any type of response is considered to be an object from the JSON schema perspective.
1. Run `make validate` and make sure …

REST PLUGIN: Modify responses for Get method to satisfy json schema requirements

---

base64/Dockerfile

- Benign change to base64 Dockerfile to trigger an autorelease …

Autorelease test

---

base64/Dockerfile

- Benign change to Base64 to trigger autorelease …

Test Autorelease Webhook

---

rapid7_insightvm/.CHECKSUM
rapid7_insightvm/bin/komand_rapid7_insightvm
rapid7_insightvm/help.md
rapid7_insightvm/komand_rapid7_insightvm/actions/get_asset_group_assets/action.py
rapid7_insightvm/komand_rapid7_insightvm/actions/get_scan/schema.py
rapid7_insightvm/komand_rapid7_insightvm/actions/scan/schema.py
rapid7_insightvm/plugin.spec.yaml
rapid7_insightvm/setup.py

Co-Authored-By: Luke Milby <32271028+lmilby-r7@users.noreply.github.com>
Fixes the `file` type to include the `content` key
The `file` type in the plugin spec was missing a `content` key making it unable to be referenced from within the UI. Also fixes some linting issues
- Fix the `file` type
n/a
n/a …

Fix Generate Adhoc SQL Report action

---

rapid7_vulndb/.CHECKSUM
rapid7_vulndb/bin/komand_rapid7_vulndb
rapid7_vulndb/help.md
rapid7_vulndb/komand_rapid7_vulndb/util/extract.py
rapid7_vulndb/plugin.spec.yaml
rapid7_vulndb/setup.py
rapid7_vulndb/tests/get_content.json
rapid7_vulndb/tests/get_content_severity.json

- VulnDB API is returning `severity` as both an int or string depending on the request.
<details>
```
{
"body": {
"log": "rapid7/Rapid7 Vulnerability \u0026 Exploit Database:2.0.1. Step name: get_content\n",
"meta": {},
"output": {
"content_result": {
"alternate_ids": "CVE/2019-8835,URL/http://support.apple.com/kb/HT210793",
"content_type": "vulnerability",
"description": "\n    \u003cp\u003eMultiple memory corruption issues were addressed with improved memory handling.\u003c/p\u003e\n  ",
"published_at": "2019-12-12T00:00:00.000Z",
"references": "apple-itunes-upgrade-12_10_3",
"severity": "4",
"solutions": "apple-itunes-upgrade-12_10_3",
"title": "Apple iTunes security update for CVE-2019-8835"
}
},
"status": "ok"
},
"type": "action_event",
"version": "v1" …
```

vulndb: VulnDB API bug workaround

---

.gitignore

This PR remove .json from .gitignore. This allows us to check in test files.

removed json from gitignore

---

abuseipdb/help.md

AbuseIPDB: Missing JSON enclosure in help

---

foremost/.CHECKSUM
foremost/Dockerfile
foremost/bin/komand_foremost
foremost/help.md
foremost/komand_foremost/actions/extract/action.py
foremost/komand_foremost/connection/connection.py
foremost/plugin.spec.yaml
foremost/setup.py

Use input and output constants | Change docker image from `komand/python-3-plugin:2` to `komand/python-3-37-plugin:3` to reduce plugin image size | Use input and output constants | Added "f" strings | Changed `Exception` to `PluginException` | Change "/tmp" to tempfile.gettempdir()
-
* All actions/triggers shortcut `icon-plugin run -R …

#188 foremost amendments

---

trendmicro_deepsecurity/.CHECKSUM
trendmicro_deepsecurity/bin/icon_trendmicro_deepsecurity
trendmicro_deepsecurity/help.md
trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/deploy_rules/action.py
trendmicro_deepsecurity/icon_trendmicro_deepsecurity/actions/search_rules/action.py
trendmicro_deepsecurity/icon_trendmicro_deepsecurity/connection/connection.py
trendmicro_deepsecurity/icon_trendmicro_deepsecurity/connection/schema.py
trendmicro_deepsecurity/icon_trendmicro_deepsecurity/util/shared.py
trendmicro_deepsecurity/plugin.spec.yaml
trendmicro_deepsecurity/setup.py

Certificate verification was mandatory in the initial plugin.
Many customers use self-signed certificates in their environment. 
With this change, they have the ability to disable certificate verification.
[*] Running validators …

Add option to disable DSM certificate verification

---

carbon_black_response/help.md
cisco_umbrella_enforcement/help.md
cymon_v2/help.md
docker_engine/help.md
duo_admin/help.md
ifconfig_co/help.md
joe_sandbox/.CHECKSUM
joe_sandbox/bin/komand_joe_sandbox
joe_sandbox/help.md
joe_sandbox/plugin.spec.yaml
joe_sandbox/setup.py
mcafee_esm/help.md
mxtoolbox_dns/help.md
port_knocking/help.md
qualys_ssl/help.md
rapid7_insightops/help.md
rapid7_metasploit/help.md
rapid7_tcell/help.md
recorded_future/help.md
tenable_nessus/help.md
wazuh_ossec/help.md

- Fixes for remaining empty input messages missing `_` 's which breaks icon-plugin
- Add example inputs to Joe Sandbox plugin
```
$ grep -l 'This action does not contain any outputs.$' */help.md || printf "No more"
No more
$ grep -l 'This action does not contain any inputs.$' */help.md || printf "No more"
No more
```
```
$ make validate
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../tools/Makefiles/Colors.mk ../tools/Makefiles/Helpers.mk
--
[*] Running validators
You are using pip version 18.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[*] Executing …
```

Joe Sandbox: Example inputs

---

microsoft_atp_safe_links/.CHECKSUM
microsoft_atp_safe_links/bin/komand_microsoft_atp_safe_links
microsoft_atp_safe_links/help.md
microsoft_atp_safe_links/komand_microsoft_atp_safe_links/actions/decode/action.py
microsoft_atp_safe_links/plugin.spec.yaml
microsoft_atp_safe_links/setup.py

-
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T …

Fix ATP return bug

---

recorded_future/.CHECKSUM
recorded_future/bin/komand_recorded_future
recorded_future/help.md
recorded_future/komand_recorded_future/actions/lookup_IP_address/action.py
recorded_future/komand_recorded_future/actions/lookup_domain/action.py
recorded_future/komand_recorded_future/actions/lookup_hash/action.py
recorded_future/komand_recorded_future/actions/search_hashes/schema.py
recorded_future/plugin.spec.yaml
recorded_future/setup.py

* Fix NoneType has no len()
* Fix enums in search hashes
-
<details>
```
{
"entity": {
"id": "idn:example.com",
"name": "example.com",
"type": "InternetDomainName"
},
"timestamps": {
"firstSeen": "2011-07-25T13:11:51.000Z",
"lastSeen": …
```

[recorded_future] Fix NoneType has no len() | Fix enums in search hashes

---

urlscan/.CHECKSUM
urlscan/bin/komand_urlscan
urlscan/help.md
urlscan/komand_urlscan/actions/search/schema.py
urlscan/plugin.spec.yaml
urlscan/setup.py

add default input for search action

---

azure_ad_admin/.CHECKSUM
azure_ad_admin/bin/icon_azure_ad_admin
azure_ad_admin/help.md
azure_ad_admin/icon_azure_ad_admin/actions/add_user_to_groups_by_id/action.py
azure_ad_admin/icon_azure_ad_admin/actions/update_user_info/schema.py
azure_ad_admin/plugin.spec.yaml
azure_ad_admin/setup.py

Azure AD Admin: fix typo and regenerate

---

mimecast/.CHECKSUM
mimecast/bin/komand_mimecast
mimecast/help.md
mimecast/komand_mimecast/actions/get_ttp_url_logs/action.py
mimecast/komand_mimecast/actions/get_ttp_url_logs/schema.py
mimecast/komand_mimecast/util/util.py
mimecast/plugin.spec.yaml
mimecast/setup.py
mimecast/tests/get_ttp_url_logs_max_pages.json
mimecast/tests/get_ttp_url_logs_max_pages0.json
mimecast/tests/get_ttp_url_logs_max_pages4.json
mimecast/tests/get_ttp_url_logs_page_size.json
mimecast/tests/get_ttp_url_logs_url_filter.json

-
<details>
```
{
"body": {
"log": "rapid7/Mimecast:5.0.0. Step name: get_ttp_url_logs\n",
"status": "ok",
"meta": {},
"output": {
"click_logs": [
{
"userEmailAddress": "dhtestuser@rapid7.com",
"url": "https://www.dummy-mimecast-blacklist.com", …
```

[mimecast] Fix pagination for get ttp url logs

---

advanced_regex/.CHECKSUM
advanced_regex/bin/icon_advanced_regex
advanced_regex/help.md
advanced_regex/icon_advanced_regex/actions/replace/action.py
advanced_regex/icon_advanced_regex/actions/replace/schema.py
advanced_regex/plugin.spec.yaml
advanced_regex/setup.py
advanced_regex/tests/replace.json

- Update the replace action to not require a replace variable and isntead default to ''
2. Run the assessment tool: `icon-plugin run -A -R all -T …

Advanced_Regex: update plugin to make replace string non required in replace aciton

---

palo_alto_pan_os/.CHECKSUM
palo_alto_pan_os/help.md
palo_alto_pan_os/komand_palo_alto_pan_os/actions/commit/schema.py
palo_alto_pan_os/komand_palo_alto_pan_os/connection/schema.py
palo_alto_pan_os/plugin.spec.yaml

Just a 1 line change in the plugin.spec.yaml, the default value of 1 action has been updated.
icon-validate . -a Passes

Default commit action changed to ALL from COMMIT-ALL

---

ivanti_security_controls/.CHECKSUM
ivanti_security_controls/bin/icon_ivanti_security_controls
ivanti_security_controls/help.md
ivanti_security_controls/icon_ivanti_security_controls/util/api.py
ivanti_security_controls/plugin.spec.yaml
ivanti_security_controls/setup.py

- Bugfix for Get Agents actions
- Fetch next href start parameter
- Build parameters for next request instead of using href url since API does not return with parameters used in original request
- Add minimum Ivanti Security Controls version in help.md
* All actions/triggers shortcut `icon-plugin run -R all --debug --jq` (use PR format …

ivanit-modify-agent-href - use start parameter from next href instead of full next href url

---

ssh/.CHECKSUM
ssh/bin/komand_ssh
ssh/help.md
ssh/komand_ssh/connection/schema.py
ssh/plugin.spec.yaml
ssh/setup.py

SSH plugin connection input 'username' updated to string from credential_secret_key
^^^

Updated SSH plugin connection username input to a string type

---

markdown/.CHECKSUM
markdown/bin/komand_markdown
markdown/help.md
markdown/komand_markdown/actions/markdown_to_html/schema.py
markdown/komand_markdown/actions/markdown_to_pdf/schema.py
markdown/plugin.spec.yaml
markdown/setup.py

-
<details>
```
{
"body": {
"log": "rapid7/Markdown:3.0.0. Step name: markdown_to_html\n",
"meta": {},
"output": {
"html": "PGgxIGlkPSJyYXBpZDctaW5zaWdodGNvbm5lY3QiPlJhcGlkNyBJbnNpZ2h0Q29ubmVjdDwvaDE+Cg==",
"html_string": "\u003ch1 …
```

Markdown - Update plugin title and description

---

checkpoint_ngfw/.CHECKSUM
checkpoint_ngfw/help.md
checkpoint_ngfw/icon_checkpoint_ngfw/actions/add_access_rule/action.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/add_access_rule/schema.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/add_host/action.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/add_host/schema.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/add_host_to_network_group/action.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/add_host_to_network_group/schema.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/check_if_address_in_group/schema.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/install_policy/action.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/install_policy/schema.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/remove_access_rule/action.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/remove_access_rule/schema.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/remove_address_object_from_group/action.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/remove_address_object_from_group/schema.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/remove_host/action.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/remove_host/schema.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/set_threat_protection/action.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/set_threat_protection/schema.py
checkpoint_ngfw/icon_checkpoint_ngfw/connection/connection.py
checkpoint_ngfw/icon_checkpoint_ngfw/connection/schema.py
checkpoint_ngfw/plugin.spec.yaml

- Move the discard session input from individual actions to the connection …

SOAR-1273 Check Point - Move discard sessions input to connection

---

trendmicro_apex/.CHECKSUM
trendmicro_apex/bin/icon_trendmicro_apex
trendmicro_apex/plugin.spec.yaml
trendmicro_apex/setup.py

- Missed version bump for PR https://github.com/rapid7/insightconnect-plugins/pull/477

Trend Micro Apex - Missed version bump

---

urlscan/.CHECKSUM
urlscan/bin/komand_urlscan
urlscan/help.md
urlscan/komand_urlscan/actions/get_scan_results/action.py
urlscan/komand_urlscan/actions/get_scan_results/schema.py
urlscan/plugin.spec.yaml
urlscan/setup.py

Add missing outputs to Get Scan Results action
-
<details>
```
{
"body": {
"log": "rapid7/urlscan.io:2.1.6. Step name: get_scan_results\n",
"status": "ok",
"meta": {},
"output": {
"scan_results": {
"requests": [
{
"request": {
"requestId": …
```

Add missing outputs to Get Scan Results action

---

sentinelone/.CHECKSUM
sentinelone/Dockerfile
sentinelone/bin/komand_sentinelone
sentinelone/help.md
sentinelone/komand_sentinelone/connection/schema.py
sentinelone/plugin.spec.yaml
sentinelone/setup.py

Update to use the `komand/python-3-37-slim-plugin` Docker image to reduce plugin size
-
<details>
```
{
"body": {
"log": "Connect: Connecting...\nToken: *************378ad\nrapid7/SentinelOne:1.2.0. Step name: activities_list\nCalling endpoint: …
```

Docker image update SentinelOne

---

fortinet_fortigate/.CHECKSUM
fortinet_fortigate/bin/icon_fortinet_fortigate
fortinet_fortigate/help.md
fortinet_fortigate/icon_fortinet_fortigate/actions/check_if_address_in_group/action.py
fortinet_fortigate/icon_fortinet_fortigate/actions/check_if_address_in_group/schema.py
fortinet_fortigate/icon_fortinet_fortigate/actions/create_address_object/action.py
fortinet_fortigate/icon_fortinet_fortigate/actions/create_address_object/schema.py
fortinet_fortigate/plugin.spec.yaml
fortinet_fortigate/setup.py

- Update address search in Check Address Group for IP Address action
- Add RFC 1918 whitelist to Create Address Object action
<details>
```
{
"body": {
"log": "rapid7/Fortinet FortiGate:4.0.0. Step name: check_if_address_in_group\n",
"meta": …
```

[SOAR 1420, 1274] add RFC 1918 and search fuction

---

carbon_black_response/bin/komand_carbon_black_response
carbon_black_response/help.md
carbon_black_response/plugin.spec.yaml
carbon_black_response/requirements.txt
carbon_black_response/setup.py

* Pin to 1.6.2
* Version bump & line added to changelog
* Regenerated
-
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single …

Fix isolate bug in older versions of cbapi

---

checkpoint_ngfw/.CHECKSUM
checkpoint_ngfw/bin/icon_checkpoint_ngfw
checkpoint_ngfw/help.md
checkpoint_ngfw/icon_checkpoint_ngfw/actions/create_address_object/action.py
checkpoint_ngfw/icon_checkpoint_ngfw/actions/create_address_object/schema.py
checkpoint_ngfw/icon_checkpoint_ngfw/connection/connection.py
checkpoint_ngfw/icon_checkpoint_ngfw/util/utils.py
checkpoint_ngfw/plugin.spec.yaml
checkpoint_ngfw/setup.py

-
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T …

Check Point revisions

---

microsoft_teams/.CHECKSUM
microsoft_teams/bin/icon_microsoft_teams
microsoft_teams/help.md
microsoft_teams/icon_microsoft_teams/triggers/new_message_received/trigger.py
microsoft_teams/plugin.spec.yaml
microsoft_teams/setup.py
microsoft_teams/unit_test/test_new_message_received.py

This fixes an issue where the Teams trigger with a regex could break. 
If someone sent an image only message, the plugin would receive a message with no content. This caused a variable containing a regex to be overwritten with a null, thus causing the workflow to trigger on all subsequent messages. 
```
rmt-mbp-5357:microsoft_teams jmcadams$ icon-validate . …
```

[No Ticket] - Fix for Teams image only breaks trigger

---

sentinelone/.CHECKSUM
sentinelone/bin/komand_sentinelone
sentinelone/help.md
sentinelone/komand_sentinelone/connection/connection.py
sentinelone/komand_sentinelone/connection/schema.py
sentinelone/plugin.spec.yaml
sentinelone/setup.py

Update error message in Connection in SentinelOne
-
<details>
```
{
"body": {
"log": "Connect: Connecting...\nToken: *************d1cfd\nrapid7/SentinelOne:1.2.2. Step name: get_threat_summary\nStarting step\nGetting summary of threats from: …
```

Update error message in Connection in SentinelOne

---

okta/.CHECKSUM
okta/bin/komand_okta
okta/help.md
okta/komand_okta/actions/list_groups/action.py
okta/komand_okta/triggers/users_added_removed_from_group/trigger.py
okta/plugin.spec.yaml
okta/setup.py

-
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T …

SOAR-1478: Okta Trigger Fix

---

okta/.CHECKSUM
okta/bin/komand_okta
okta/help.md
okta/komand_okta/triggers/users_added_removed_from_group/trigger.py
okta/plugin.spec.yaml
okta/setup.py

- This PR addresses an issue where the Okta 'Monitor User Groups' trigger would detect user logins as a change to membership of a group.
2. Run the …

[No Ticket] Okta Trigger Fix, Pt 2

---

microsoft_teams/.CHECKSUM
microsoft_teams/bin/icon_microsoft_teams
microsoft_teams/help.md
microsoft_teams/icon_microsoft_teams/connection/connection.py
microsoft_teams/plugin.spec.yaml
microsoft_teams/setup.py

This PR fixes an issue where Teams would not refresh its auth token on long-running actions. 
```
rmt-mbp-5357:microsoft_teams jmcadams$ icon-validate . …
```

Teams fix auth token

---

cylance_protect/.CHECKSUM
cylance_protect/bin/icon_cylance_protect
cylance_protect/help.md
cylance_protect/icon_cylance_protect/connection/connection.py
cylance_protect/icon_cylance_protect/util/api.py
cylance_protect/plugin.spec.yaml
cylance_protect/setup.py

Update to fix connection test
-
<details>
```
{
"body": {
"log": "Connect: Connecting...\nrapid7/Blackberry CylancePROTECT:1.0.2. Step name: blacklist\n",
"meta": {},
"output": {
"success": true
},
"status": "ok"
},
"type": "action_event", …
```

Update to fix connection test

---

broadcom_symantec_endpoint_protection/.CHECKSUM
broadcom_symantec_endpoint_protection/bin/icon_broadcom_symantec_endpoint_protection
broadcom_symantec_endpoint_protection/help.md
broadcom_symantec_endpoint_protection/icon_broadcom_symantec_endpoint_protection/actions/get_agent_details/action.py
broadcom_symantec_endpoint_protection/icon_broadcom_symantec_endpoint_protection/actions/quarantine/action.py
broadcom_symantec_endpoint_protection/plugin.spec.yaml
broadcom_symantec_endpoint_protection/setup.py

- Fixes some issues with usability in workflows …

Symantec Endpoint Protection Usability Fixes

---

github/bin/komand_github
github/help.md
github/komand_github/actions/close_issue/action.py
github/plugin.spec.yaml
github/setup.py

Fix Github plugin action `close_issue`
- The `close_issue` action currently isn't working. The `.edit` api call requires **kwargs
Tested it on Komand
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. …

Fix Github plugin action "close_issue"

---

broadcom_symantec_endpoint_protection/.CHECKSUM
broadcom_symantec_endpoint_protection/bin/icon_broadcom_symantec_endpoint_protection
broadcom_symantec_endpoint_protection/help.md
broadcom_symantec_endpoint_protection/icon_broadcom_symantec_endpoint_protection/actions/blacklist/action.py
broadcom_symantec_endpoint_protection/icon_broadcom_symantec_endpoint_protection/actions/blacklist/schema.py
broadcom_symantec_endpoint_protection/plugin.spec.yaml
broadcom_symantec_endpoint_protection/setup.py

- SHA256 hashes are supported according to API documentation but are not supported in practice.
2. Run the assessment tool: `icon-plugin run -A -R …

Symantec Endpoint Protection: Don't allow SHA256 hashes

---

cylance_protect/.CHECKSUM
cylance_protect/bin/icon_cylance_protect
cylance_protect/help.md
cylance_protect/plugin.spec.yaml
cylance_protect/setup.py

- Two capital B's in BlackBerry
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A …

Update CylancePROTECT plugin branding

---

fortinet_fortigate/.CHECKSUM
fortinet_fortigate/bin/icon_fortinet_fortigate
fortinet_fortigate/help.md
fortinet_fortigate/icon_fortinet_fortigate/actions/check_if_address_in_group/action.py
fortinet_fortigate/plugin.spec.yaml
fortinet_fortigate/setup.py

- bug fix for check_if_address_in_group action. the / character was causing an error when addresses with it were looked up directly. Searching with params fixs this issue.
<details>
```
{
"body": {
"log": "rapid7/Fortinet FortiGate:4.0.1. Step …
```

bug fix for check_if_address_in_group action

---

base64/.CHECKSUM
base64/bin/komand_base64
base64/help.md
base64/komand_base64/actions/decode/action.py
base64/plugin.spec.yaml
base64/setup.py

Update PluginException message

---

fortinet_fortigate/.CHECKSUM
fortinet_fortigate/bin/icon_fortinet_fortigate
fortinet_fortigate/help.md
fortinet_fortigate/icon_fortinet_fortigate/util/util.py
fortinet_fortigate/plugin.spec.yaml
fortinet_fortigate/setup.py

- add error handling message to indicate that a 401 can be caused by the orchestrator ip not being in the trusted hosts list

[SOAR 1787] update error handling to help with trusted host issues

---

jira/.CHECKSUM
jira/bin/komand_jira
jira/help.md
jira/komand_jira/actions/comment_issue/action.py
jira/komand_jira/connection/connection.py
jira/plugin.spec.yaml
jira/setup.py

Jira: Logging fixes

---

sentinelone/.CHECKSUM
sentinelone/bin/komand_sentinelone
sentinelone/help.md
sentinelone/komand_sentinelone/triggers/get_threats/schema.py
sentinelone/komand_sentinelone/triggers/get_threats/trigger.py
sentinelone/plugin.spec.yaml
sentinelone/setup.py

Upgrade trigger input Agent is Active to default true
-
<details>
```
INFO[0000] Running command:  docker run --rm -i rapid7/sentinelone:1.4.1 --debug run < tests/get_threats.json
Connect: Connecting...
Starting new HTTPS connection (1): …
```

Sentinelone upgrade trigger input

---

jira/.CHECKSUM
jira/bin/komand_jira
jira/help.md
jira/plugin.spec.yaml
jira/setup.py

- Add docs_url with official guide

Jira: Add product documentation link for plugin

---

any_run/.CHECKSUM
any_run/bin/icon_any_run
any_run/help.md
any_run/icon_any_run/actions/run_analysis/action.py
any_run/icon_any_run/actions/run_analysis/schema.py
any_run/icon_any_run/util/api.py
any_run/plugin.spec.yaml
any_run/setup.py

- Allow User Agent in Any.Run 'Run Analysis' Action …

SOAR-1792: Allow User Agent in Any.Run 'Run Analysis' Action

---

basename/.CHECKSUM
basename/bin/komand_basename
basename/help.md
basename/komand_basename/actions/basename/action.py
basename/plugin.spec.yaml
basename/setup.py

Update Basename plugin
-
<details>
```
{
"body": {
"log": "rapid7/Basename:2.0.0. Step name: basename\n",
"meta": {},
"output": {
"basename": "robots.txt"
},
"status": "ok"
},
"type": "action_event",
"version": "v1"
}
```
<summary>
docker run …

Update Basename plugin

---

sentinelone/.CHECKSUM
sentinelone/bin/komand_sentinelone
sentinelone/help.md
sentinelone/komand_sentinelone/triggers/get_threats/trigger.py
sentinelone/plugin.spec.yaml
sentinelone/setup.py

Upgrade trigger Get Threats to only return threats trigger start
-
<details>
```
root@stretch:/insightconnect-plugins/sentinelone# icon-plugin run -R tests/get_threats.json
INFO[0000] Running command:  docker run --rm -i …
```

Upgrade trigger Get Threats to only return threats trigger start

---

rapid7_attackerkb/.CHECKSUM
rapid7_attackerkb/bin/icon_rapid7_attackerkb
rapid7_attackerkb/help.md
rapid7_attackerkb/icon_rapid7_attackerkb/actions/topic/schema.py
rapid7_attackerkb/icon_rapid7_attackerkb/actions/topics/schema.py
rapid7_attackerkb/plugin.spec.yaml
rapid7_attackerkb/setup.py

Rapid7 Attacker KB output change
-
<details>
```
{
"body": {
"log": "Connect: Connecting...\nrapid7/Rapid7 AttackerKB:1.0.1. Step name: assessment\n",
"meta": {},
"output": {
"data": {
"created": "2020-08-04T16:15:02.803493Z",
"document": "SANS …
```

Rapid7 Attacker KB output change

---

.github/workflows/github_webhooks_status.yml

- Temporarily Remove GitHub Webhook Status check from CI …

Temporarily Remove GitHub Webhook Status check from CI

---

rapid7_insightvm/.CHECKSUM
rapid7_insightvm/bin/komand_rapid7_insightvm
rapid7_insightvm/help.md
rapid7_insightvm/komand_rapid7_insightvm/actions/create_asset_group/schema.py
rapid7_insightvm/plugin.spec.yaml
rapid7_insightvm/setup.py

This PR makes the description required in the create asset group action. 
```
rmt-mbp-5357:rapid7_insightvm jmcadams$ icon-validate .
[*] Executing …
```

[SOAR-2441] - InisghtVM Make Description Required in Create Asset Group

---

microsoft_teams/.CHECKSUM
microsoft_teams/bin/icon_microsoft_teams
microsoft_teams/help.md
microsoft_teams/icon_microsoft_teams/triggers/new_message_received/schema.py
microsoft_teams/icon_microsoft_teams/triggers/new_message_received/trigger.py
microsoft_teams/plugin.spec.yaml
microsoft_teams/setup.py

Extract UUID in trigger new message Microsoft Teams
-
<details>
```
{
Time Now: 1598993713.1738656
Time Ago: 1598993593.8000004
Token is valid, not refreshing.
Starting new HTTPS connection (1): graph.microsoft.com:443 …
```

Extract UUID in trigger new message Microsoft Teams plugin

---

whois/.CHECKSUM
whois/bin/komand_whois
whois/help.md
whois/plugin.spec.yaml
whois/setup.py

- Update whois plugin to use latest runtime
- Define cloud_ready in space …

SOAR-2657: Update whois plugin to use latest runtime

---

azure_ad_admin/.CHECKSUM
azure_ad_admin/bin/icon_azure_ad_admin
azure_ad_admin/help.md
azure_ad_admin/icon_azure_ad_admin/actions/add_user_to_group/action.py
azure_ad_admin/icon_azure_ad_admin/actions/add_user_to_groups_by_id/action.py
azure_ad_admin/icon_azure_ad_admin/actions/get_user_info/action.py
azure_ad_admin/icon_azure_ad_admin/actions/remove_user_from_group/action.py
azure_ad_admin/icon_azure_ad_admin/util/get_user_info.py
azure_ad_admin/plugin.spec.yaml
azure_ad_admin/setup.py

The SSL error in Azure AD causes the request library to throw an exception. The code had expected a valid response with an error. This PR corrects that code. 
```
RMT-X270-4700:azure_ad_admin jmcadams$ icon-validate .
[*] …
```

[SOAR-2764] Azure AD fix ssl error retry code

---

dig/.CHECKSUM
dig/bin/komand_dig
dig/help.md
dig/plugin.spec.yaml
dig/setup.py

- Update whois plugin to use latest runtime
- Define cloud_ready in space …

Update dig for latest runtime and cloud_ready

---

azure_ad_admin/.CHECKSUM
azure_ad_admin/bin/icon_azure_ad_admin
azure_ad_admin/help.md
azure_ad_admin/icon_azure_ad_admin/actions/get_user_info/action.py
azure_ad_admin/plugin.spec.yaml
azure_ad_admin/setup.py

This adds retry code to a secondary get in Get User Info in Azure Admin AD
```
RMT-X270-4700:azure_ad_admin jmcadams$ icon-validate .
[*] Executing …
```

[SOAR-2764] Azure ad fix ssl try 3

---

microsoft_sql/.CHECKSUM
microsoft_sql/bin/icon_microsoft_sql
microsoft_sql/help.md
microsoft_sql/icon_microsoft_sql/actions/query/action.py
microsoft_sql/icon_microsoft_sql/connection/schema.py
microsoft_sql/plugin.spec.yaml
microsoft_sql/setup.py

Fix execute insert and update
-
<details>
```
{
"body": {
"log": "rapid7/Microsoft SQL:1.0.2. Step name: query\n",
"meta": {},
"output": {
"header": [],
"results": []
},
"status": "ok"
},
"type": "action_event",
"version": "v1"
}
```
<summary> …

Fix execute insert and update

---

rapid7_insightvm/.CHECKSUM
rapid7_insightvm/bin/komand_rapid7_insightvm
rapid7_insightvm/help.md
rapid7_insightvm/komand_rapid7_insightvm/actions/update_site_excluded_targets/action.py
rapid7_insightvm/komand_rapid7_insightvm/actions/update_site_included_targets/action.py
rapid7_insightvm/plugin.spec.yaml
rapid7_insightvm/setup.py
rapid7_insightvm/unit_test/test_update_site_excluded_targets.py
rapid7_insightvm/unit_test/test_update_site_included_targets.py

This PR fixes the update_site_excluded_targets and update_site_included_targets
```
RMT-X270-4700:rapid7_insightvm jmcadams$ ./run.sh -R tests/update_site_excluded_targets.json -j
Running: cat tests/update_site_excluded_targets.json | docker run --rm   -i rapid7/rapid7_insightvm:4.4.2  run | grep -- ^\{ | jq -r '.body | try(.log | split("\n") | .[]),.output'
rapid7/Rapid7 InsightVM:4.4.2. Step name: update_site_excluded_targets
Using https://ivm-console-test.vuln.lax.rapid7.com:3780/api/3/sites/1/excluded_targets ...
Starting new HTTPS connection (1): ivm-console-test.vuln.lax.rapid7.com:3780
https://ivm-console-test.vuln.lax.rapid7.com:3780 "PUT /api/3/sites/1/excluded_targets HTTP/1.1" 200 None
rapid7/Rapid7 InsightVM:4.4.2. Step name: update_site_excluded_targets
Using …
```

[SOAR-2802] - Fix InsightVM Update Site Included Targets

---

recorded_future/.CHECKSUM
recorded_future/bin/komand_recorded_future
recorded_future/help.md
recorded_future/komand_recorded_future/actions/lookup_alert/schema.py
recorded_future/plugin.spec.yaml
recorded_future/setup.py

This PR changes the output type of Lookup Alert from object to alert
```
rmt-mbp-5357:recorded_future jmcadams$ icon-validate .
[*] Executing …
```

[SOAR-3138] - Recorded future lookup alert object

---

storage/help.md
storage/plugin.spec.yaml

This PR marks the Storage plugin as obsolete.

[SOAR-3101] - Obsolete the Storage Plugin

---

rapid7_insightvm/.CHECKSUM
rapid7_insightvm/bin/komand_rapid7_insightvm
rapid7_insightvm/help.md
rapid7_insightvm/komand_rapid7_insightvm/actions/asset_search/action.py
rapid7_insightvm/komand_rapid7_insightvm/actions/asset_search/schema.py
rapid7_insightvm/komand_rapid7_insightvm/actions/get_asset_vulnerabilities/action.py
rapid7_insightvm/komand_rapid7_insightvm/actions/get_asset_vulnerabilities/schema.py
rapid7_insightvm/komand_rapid7_insightvm/util/resource_helper.py
rapid7_insightvm/plugin.spec.yaml
rapid7_insightvm/setup.py

- Fix output issue in Get Asset Vulnerabilities action
- Fix issue with RequestParams object set action
JPP dies on the output, but here it is in ICON
Ignore the AD stuff reusing an old test WF

[SOAR-3158] bug fix for Get Asset Vulnerabilities Action

---

microsoft_teams/.CHECKSUM
microsoft_teams/bin/icon_microsoft_teams
microsoft_teams/help.md
microsoft_teams/icon_microsoft_teams/actions/send_html_message/schema.py
microsoft_teams/icon_microsoft_teams/actions/send_message/schema.py
microsoft_teams/icon_microsoft_teams/actions/send_message_by_guid/schema.py
microsoft_teams/icon_microsoft_teams/triggers/new_message_received/schema.py
microsoft_teams/plugin.spec.yaml
microsoft_teams/setup.py

This PR fixes Microsoft Teams for the case where a message is received that is all HTML (like "<img src="">"). It makes words a non-required field
```
rmt-mbp-5357:microsoft_teams jmcadams$ icon-validate .
[*] Executing …
```

[No Ticket, Emergency Change] - Fix Microsoft Teams in case of blank or all html message 

---

microsoft_teams/.CHECKSUM
microsoft_teams/bin/icon_microsoft_teams
microsoft_teams/help.md
microsoft_teams/icon_microsoft_teams/triggers/new_message_received/trigger.py
microsoft_teams/plugin.spec.yaml
microsoft_teams/setup.py

-
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T …

Fix MS Teams trigger error

---

sentinelone/.CHECKSUM
sentinelone/bin/komand_sentinelone
sentinelone/help.md
sentinelone/komand_sentinelone/actions/quarantine/action.py
sentinelone/komand_sentinelone/actions/search_agents/action.py
sentinelone/komand_sentinelone/util/api.py
sentinelone/plugin.spec.yaml
sentinelone/setup.py

- Get Agent Details action was failing due to a change in an API function --> made a default parameter to fix this
- Whitelists in the Quarantine action did no accept IP addresses due to a nested list --> traverse that list and throw exception of necessary
<details>
<summary> <code>icon-plugin run -R tests/get_agent_details.json | jq '.' </code></summary>
```
{
"body": {
"log": "Connect: Connecting...\nToken: *************62f44\nrapid7/SentinelOne:4.0.1. Step name: get_agent_details\n",
"status": "ok",
"meta": {},
"output": {
"agent": {
"accountId": "433241117337583618",
"accountName": "SentinelOne",
"activeDirectory": {
"computerDistinguishedName": "None",
"computerMemberOf": [],
"lastUserDistinguishedName": "None",
"lastUserMemberOf": []
}, …
```

Fixes get_agent_details action and Quarantine whitelist in Sentinelone

---

servicenow/.CHECKSUM
servicenow/bin/icon_servicenow
servicenow/help.md
servicenow/plugin.spec.yaml
servicenow/setup.py

Updated docs_url in plugin spec for this plugin.
- Updated docs_url in plugin spec for this plugin.
<details>
```
[*] Validating plugin with all validators at .
[*] …
```

MC-144 - ServiceNow Plugin Documentation Update

---

zscaler/help.md

- Fixes a typo in the Zscaler help.md (Zscalar -> Zscaler) …

Fix Zscaler Typo

---

rapid7_insightidr/.CHECKSUM
rapid7_insightidr/bin/komand_rapid7_insightidr
rapid7_insightidr/help.md
rapid7_insightidr/komand_rapid7_insightidr/actions/query/schema.py
rapid7_insightidr/plugin.spec.yaml
rapid7_insightidr/setup.py

-
<details>
```
[*] Use ``make menu`` for available targets
[*] Including available Makefiles: ../tools/Makefiles/Helpers.mk ../tools/Makefiles/Colors.mk
--
[*] Running validators …
```

Change input ID description in Get Query Results action in InsightIDR plugin

---

servicenow/.CHECKSUM
servicenow/bin/icon_servicenow
servicenow/help.md
servicenow/icon_servicenow/triggers/incident_created/trigger.py
servicenow/plugin.spec.yaml
servicenow/setup.py

Fix interval parameter in ServiceNow trigger

---

rapid7_insightidr/.CHECKSUM
rapid7_insightidr/bin/komand_rapid7_insightidr
rapid7_insightidr/help.md
rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log/action.py
rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/action.py
rapid7_insightidr/plugin.spec.yaml
rapid7_insightidr/setup.py

This PR fixes "advanced query on log" and "advance query on log set" in the InsightIDR plugin
```
RMT-MBP-5357:rapid7_insightidr jmcadams$ icon-validate . …
```

[No Ticket - Emergency Change] - Fix advanced query2

---

rapid7_tcell/bin/komand_rapid7_tcell
rapid7_tcell/help.md
rapid7_tcell/komand_rapid7_tcell/util/api.py
rapid7_tcell/plugin.spec.yaml
rapid7_tcell/setup.py

- Updates the base_url of tCell
- Updates Authorization header to X-API-Key
- Adds link to docs in API key section
Tested via the UI by running `make export` from the plugin directory and uploading to InsightConnect. Successfully blocked an API with the new base URL and headers, whereas it was failing previously.
* All actions/triggers shortcut `icon-plugin run …

Updates tCell Base URL and Authorization Header

---

servicenow/.CHECKSUM
servicenow/bin/icon_servicenow
servicenow/help.md
servicenow/icon_servicenow/actions/create_incident/action.py
servicenow/icon_servicenow/actions/create_incident/schema.py
servicenow/icon_servicenow/actions/update_incident/action.py
servicenow/icon_servicenow/actions/update_incident/schema.py
servicenow/plugin.spec.yaml
servicenow/setup.py

Add JSON object containing the additional fields and values to create / update incident
-
<details>
```
{
"body": {
"log": "Connect: Connecting...\nrapid7/ServiceNow:5.0.1. Step name: create_incident\n",
"meta": {},
"output": { …
```

[MC-284] Added JSON object containing the additional fields and values to create / update incident

---

cisco_umbrella_investigate/.CHECKSUM
cisco_umbrella_investigate/bin/komand_cisco_umbrella_investigate
cisco_umbrella_investigate/help.md
cisco_umbrella_investigate/komand_cisco_umbrella_investigate/actions/sample/schema.py
cisco_umbrella_investigate/komand_cisco_umbrella_investigate/actions/samples/schema.py
cisco_umbrella_investigate/komand_cisco_umbrella_investigate/investigate/investigate.py
cisco_umbrella_investigate/plugin.spec.yaml
cisco_umbrella_investigate/setup.py

Add 'data' in PluginException in Cisco Umbrella Investigate plugin
-
<details>
```
{
"body": {
"log": "Connect: Connecting..\nrapid7/Cisco Umbrella Investigate:3.1.1. Step name: categorization\n",
"meta": {},
"output": {
"categories": …
```

Add 'data' in PluginException in Cisco Umbrella Investigate plugin

---

rapid7_insightidr/help.md

This adds a log entry to the Rapid7 Insight IDR log.

[No ticket, doc change only] - Fix idr history

---

CONTRIBUTING.md
README.md
tools/update-tools.sh

Updating contribution documentation to reflect newest changes:
- Pre-commit & Black

Update Contribution Documentation

---

.github/workflows/black.yml

- Quick update to utilize pyproject.toml for black configuration …

Use pyproject.toml for Black

---

.github/workflows/black.yml

The Black linting tool has a known issue that produces different results between runs due to colliding behavior fixing trailing commas and parentheses. The issue is tracked here: https://github.com/psf/black/issues/1629
We will monitor this issue until a fix has been merged and included in a new release of Black. For now, we will temporarily disable the Black GitHub action.
- Temporarily disable Black linting GitHub action.
No testing required.
* All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format …

Disable Black

---

elasticsearch/.CHECKSUM
elasticsearch/bin/komand_elasticsearch
elasticsearch/help.md
elasticsearch/plugin.spec.yaml
elasticsearch/setup.py

Updated all the example inputs and outputs.
-
<details>
``` …
```

MC-295 - ElasticSearch - Update example Inputs and Outputs

---

elastalert/plugin.spec.yaml
foremost/plugin.spec.yaml
qradar/plugin.spec.yaml

- Hide old plugins that have not been tested in a while from Ext Lib

Hide plugins that shouldn't be used at this time

---

cybereason/help.md

- Add disclaimer for file search action taking up to three days to help.md
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. …

Add disclaimer for file search duration for Cyberreason

---

url_encoder/.CHECKSUM
url_encoder/bin/icon_url_encoder
url_encoder/help.md
url_encoder/icon_url_encoder/actions/encode/action.py
url_encoder/plugin.spec.yaml
url_encoder/setup.py

- The plugin cannot retrieve the "Encode All" variable because it was set as `ENCODE_ALL` but retrieved as `encode_all`. This PR puts the retrieval line in all-caps.
1. Run `make validate` and …

SOAR-4698: Patch input schema misspelling

---

rest/.CHECKSUM
rest/bin/komand_rest
rest/help.md
rest/plugin.spec.yaml
rest/setup.py

MC-338 - HTTP Requests - Update Documentation References

---

jira/.CHECKSUM
jira/bin/komand_jira
jira/help.md
jira/komand_jira/connection/schema.py
jira/plugin.spec.yaml
jira/setup.py

Updated help requirements to reflect what's needed to authenticate to on-prem Jira server.
-

MC-305 - Jira - Update Help Requirements

---

jira/.CHECKSUM
jira/Dockerfile
jira/bin/komand_jira
jira/help.md
jira/komand_jira/actions/assign_issue/action.py
jira/komand_jira/actions/attach_issue/action.py
jira/komand_jira/actions/comment_issue/action.py
jira/komand_jira/actions/create_user/action.py
jira/komand_jira/actions/delete_user/action.py
jira/komand_jira/actions/edit_issue/action.py
jira/komand_jira/actions/find_issues/action.py
jira/komand_jira/actions/find_users/action.py
jira/komand_jira/actions/get_comments/action.py
jira/komand_jira/actions/get_issue/action.py
jira/komand_jira/actions/label_issue/action.py
jira/komand_jira/actions/transition_issue/action.py
jira/plugin.spec.yaml
jira/setup.py

- Fixes Jira compile issue
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run …

Fix Jira Compile Issue

---

rapid7_vulndb/plugin.spec.yaml

- Set `cloud_ready: true` to ensure all future released of the plugin are enabled for cloud use
- No functional changes
2. Run the …

Define vulndb plugin as cloud_ready

---

.github/workflows/statuspage.yml

- This change adds a new GitHub Action workflow check to assert that InsightConnect is operational according to https://status.rapid7.com prior to releasing plugins.
This action was tested by running and debugging the workflow in a separate branch.
You must validate …

SOAR-5031: Check InsightConnect status GitHub Action

---

.github/workflows/github_webhooks_status.yml
.github/workflows/statuspage.yml

- This PR moves the Github webhooks status check GHA workflow from the github-status-checker Python module to a simple Bash script. It adapts the script from the Rapid7 InsightConnect status check GHA workflow by modifying the API endpoint and the `jq` filter for Webhooks.
- This PR also re-indents the .yml files for both Github Webhooks status and Rapid7 InsightConnect status.
This PR was tested by running the Bash script locally.
* …

SOAR-5207: Move Github Webhooks status check

---

.github/workflows/github_webhooks_status.yml
.github/workflows/statuspage.yml

-This PR adds a cron schedule to the InsightConnect status checker to protect against the case that a successful check upon a PR push becomes out-of-date upon release. The InsightConnect status checker will now run on push and also every 15 minutes to keep the PR's status check fresh.
Cron tested in GitHub Actions.
* All actions/triggers shortcut `icon-plugin …

SOAR-5031: Run InsightConnect status check every 15 minutes

---

README.md

- Add mention of Discuss community for community to reach out prior to intalliance email
2. Run the assessment tool: `icon-plugin run -A …

[NOTICKET] Discuss Community linked in readme

---

ifconfig_co/help.md

This removes a live IP from the examples in the help.md in the if_config_go plugin
None - Doc only change

[No Ticket] if_config_co remove IP

---

red_canary/help.md

This PR removes a live IP from the red canary plugin
None - Doc only change

[No Ticket] - Red Canary Sanitized

---

greynoise/help.md
greynoise/icon_greynoise/connection/schema.py
greynoise/plugin.spec.yaml

- Removes the "server" parameter from the schema, as it was no longer needed (Fixed #911 )
2. Run the assessment tool: `icon-plugin run -A …

GreyNoise - Fixes 911 - missing connection parameter

---

cisco_umbrella_investigate/.CHECKSUM
cisco_umbrella_investigate/bin/komand_cisco_umbrella_investigate
cisco_umbrella_investigate/help.md
cisco_umbrella_investigate/komand_cisco_umbrella_investigate/actions/security/schema.py
cisco_umbrella_investigate/plugin.spec.yaml
cisco_umbrella_investigate/setup.py

- Fixes an invalid character in one of the descriptions that was causing validation failure
2. Run the assessment tool: `icon-plugin run …

Fix Cisco Umbrella Investigate Description

---

active_directory_ldap/.CHECKSUM
active_directory_ldap/bin/komand_active_directory_ldap
active_directory_ldap/help.md
active_directory_ldap/komand_active_directory_ldap/connection/connection.py
active_directory_ldap/plugin.spec.yaml
active_directory_ldap/setup.py

Add default prefix in connection.py in Active Directory LDAP
Add default prefix (ldap:// and ldaps://) in connection.py in Active Directory LDAP
Ticket MC-499
<details>
```
{
"body": {
"log": "HOST:ldaps://172.17.0.1\nConnecting to 172.17.0.1:10636\nFailed to …
```

[MC-499] Add default prefix in connection.py in Active Directory LDAP

---

urlscan/.CHECKSUM
urlscan/bin/komand_urlscan
urlscan/help.md
urlscan/plugin.spec.yaml
urlscan/setup.py

Major version bump for urlscan.io plugin
Major version bump to ensure awareness of a breaking change related to the addition of the `was_scan_skipped` output in Submit URL for Scan action in the previous version
Ticket MC-516
<details>
```
[*] Validating plugin with …
```

[MC-516] Major version bump for urlscan.io plugin

---

rapid7_insightvm_cloud/.CHECKSUM
rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
rapid7_insightvm_cloud/help.md
rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/start_scan/action.py
rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/start_scan/schema.py
rapid7_insightvm_cloud/plugin.spec.yaml
rapid7_insightvm_cloud/setup.py

Added the list of scanned asset IDs as an output of the start scan action
Tests run and passed

Cloud IVM Plugin Update Start Scan Output

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py

- This PR adds a requirement to the Insight Agent plugin to say that the user needs to have administrator access to InsightIDR to use this plugin.
Plugin has been validated locally.
1. Run `make validate` and make sure …

SOAR-5689: Admin requirement for Insight Agent plugin

---

.github/pull_request_template.md

- Add checkbox for unit tests to PR template …

Add unit tests to PR template checklist

---

plugins/easyvista/.CHECKSUM
plugins/easyvista/bin/icon_easyvista
plugins/easyvista/help.md
plugins/easyvista/icon_easyvista/connection/connection.py
plugins/easyvista/plugin.spec.yaml
plugins/easyvista/setup.py

Fix EasyVista connection test - Jira Ticket - https://issues.corp.rapid7.com/browse/MC-590
- Removed unsupported key words,
- Fixed the connection test
* All actions/triggers shortcut `icon-plugin run -T all …

[MC-590] EasyVista - Fix connection test

---

.gitignore

Able to add .json files into the payloads folder of unit_tests without manually updating the .gitignore.
No functional changes, but tested to make sure this works, and it does.

SOAR-6152 GitIgnore Update

---

prospector.yaml

Quick thing to add more ignores, including too many arguments, and dangerous default.

Add a few things to prospector lint ignore

---

plugins/sql/.CHECKSUM
plugins/sql/komand_sql/actions/query/action.py
plugins/sql/komand_sql/connection/connection.py
plugins/sql/plugin.spec.yaml

[MC-597] SQL plugin issue with closing connections

---

prospector.yaml

- Ignores "too many arguments" PyLint rule

Ignore too many arguments rule in PyLint

---

plugins/jira/.CHECKSUM
plugins/jira/plugin.spec.yaml

- Jira plugin is not cloud-ready. So remove the attribute. …

[no ticket] - jira plugin is not cloud ready

---

prospector.yaml

- This PR adds the `raise-missing-from` Pylint warning to the ignore list for the Prospector GHA workflow. We don't really care about the use of `raise Exception from e` as it does not affect functionality.
JIRA: https://issues.corp.rapid7.com/browse/SOAR-6792 …

SOAR-6792: Ignore raise-missing-from Pylint warning

---

.github/workflows/autoupdate.yml

Adds a GitHub Action to keep PRs up-to-date with their base branch.

Add autoupdate Github Action

---

.github/workflows/autoupdate.yml

Disable Autoupdate GitHub Action

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/plugin.spec.yaml

- Regenerates the plugin to synchronize the help.md with the plugin spec.
- This PR does not bump the version and will therefore fail the version validator. We may ignore this. …

[MC-669][MC-695][MC-696] Proofpoint Tap - Regenerate plugin support

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

Added `docs_url` for Rapid7 InsightIDR plugin.
https://issues.corp.rapid7.com/browse/MC-712
- Added `docs_url` for Rapid7 InsightIDR plugin.
* All actions/triggers shortcut `icon-plugin run -T all --debug --jq` …

[MC-712] Added `docs_url` for InsightIDR plugin

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/bin/icon_microsoft_teams
plugins/microsoft_teams/help.md
plugins/microsoft_teams/plugin.spec.yaml
plugins/microsoft_teams/setup.py

Add troubleshooting message to Teams
- Update the Teams plugin with troubleshooting information from Robert Helm on Discuss, specifically around how Teams will use the oldest team if there are two teams with the same name. https://discuss.rapid7.com/t/issuing-commands-from-teams-unsuccessful/6707/5?u=mike_rinehart …

[SOAR-7005] Update Teams Plugin with Troubleshooting from Discuss

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/komand_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

- Updates the help documentation to include troubleshooting information for installing third-party modules.
- Adds g++ for pandas support

Update Python 3 Script documentation & install g++

---

plugins/devo/.CHECKSUM
plugins/devo/bin/icon_devo
plugins/devo/help.md
plugins/devo/icon_devo/triggers/get_new_alerts/schema.py
plugins/devo/icon_devo/triggers/get_new_alerts/trigger.py
plugins/devo/plugin.spec.yaml
plugins/devo/setup.py

* configurable interval
* set interval default to 10 seconds
- …

[SOAR-7961] Configurable interval for devo  (#1059)

---

plugins/automox/.CHECKSUM
plugins/automox/help.md
plugins/automox/icon_automox/actions/create_group/schema.py
plugins/automox/icon_automox/actions/run_command/schema.py
plugins/automox/icon_automox/actions/update_group/schema.py
plugins/automox/plugin.spec.yaml

- Update create and update group action title and descriptions for greater end user clarity
- Update run command description for input for greater end user clarity
* All actions/triggers shortcut `icon-plugin …

Automox Plugin Enhancements: Description and Title changes for greater end user clarity

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/get_attachments_for_an_incident/action.py
plugins/servicenow/icon_servicenow/actions/get_attachments_for_an_incident/schema.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py
plugins/servicenow/unit_test/test_get_attachments_for_an_incident.py

[MC-751] - ServiceNow Get Attachments (#1054)

---

plugins/automox/.CHECKSUM
plugins/automox/icon_automox/actions/action_on_vulnerability_sync_batch/action.py
plugins/automox/icon_automox/actions/action_on_vulnerability_sync_task/action.py
plugins/automox/icon_automox/actions/create_group/action.py
plugins/automox/icon_automox/actions/delete_device/action.py
plugins/automox/icon_automox/actions/delete_group/action.py
plugins/automox/icon_automox/actions/get_device_by_hostname/action.py
plugins/automox/icon_automox/actions/get_device_by_ip/action.py
plugins/automox/icon_automox/actions/get_device_software/action.py
plugins/automox/icon_automox/actions/get_vulnerability_sync_batch/action.py
plugins/automox/icon_automox/actions/list_devices/action.py
plugins/automox/icon_automox/actions/list_groups/action.py
plugins/automox/icon_automox/actions/list_organization_users/action.py
plugins/automox/icon_automox/actions/list_organizations/action.py
plugins/automox/icon_automox/actions/list_policies/action.py
plugins/automox/icon_automox/actions/list_vulnerability_sync_batches/action.py
plugins/automox/icon_automox/actions/list_vulnerability_sync_tasks/action.py
plugins/automox/icon_automox/actions/run_command/action.py
plugins/automox/icon_automox/actions/update_device/action.py
plugins/automox/icon_automox/actions/update_group/action.py
plugins/automox/icon_automox/actions/upload_vulnerability_sync_file/action.py
plugins/automox/icon_automox/connection/connection.py
plugins/automox/icon_automox/triggers/get_events/trigger.py
plugins/automox/icon_automox/util/api_client.py

1. Update the files to support Black standards
- …

Automox - Reformat for the files to support standards

---

plugins/palo_alto_pan_os/.CHECKSUM
plugins/palo_alto_pan_os/bin/komand_palo_alto_pan_os
plugins/palo_alto_pan_os/help.md
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_address_object_to_group/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_external_dynamic_list/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_to_policy/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/check_if_address_object_in_group/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/commit/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/delete/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/edit/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/get/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/get_addresses_from_group/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/get_policy/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/op/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/remove_address_object_from_group/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/remove_from_policy/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/retrieve_logs/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/set/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/set_address_object/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/set_security_policy_rule/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/show/schema.py
plugins/palo_alto_pan_os/plugin.spec.yaml
plugins/palo_alto_pan_os/setup.py

Add information to every action is it work with Panorama or direct firewall connection
- Add information to every action is it work with Panorama or direct firewall connection
- MC-689 …

Update palo alto pan os help

---

plugins/palo_alto_pan_os/.CHECKSUM
plugins/palo_alto_pan_os/bin/komand_palo_alto_pan_os
plugins/palo_alto_pan_os/help.md
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_address_object_to_group/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_external_dynamic_list/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/add_to_policy/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/check_if_address_object_in_group/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/commit/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/delete/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/edit/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/get/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/get_addresses_from_group/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/get_policy/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/op/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/remove_address_object_from_group/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/remove_from_policy/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/retrieve_logs/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/set/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/set_address_object/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/set_security_policy_rule/schema.py
plugins/palo_alto_pan_os/komand_palo_alto_pan_os/actions/show/schema.py
plugins/palo_alto_pan_os/plugin.spec.yaml
plugins/palo_alto_pan_os/setup.py

* [MC-689] Add information to every action is it work with Panorama or direct firewall connection
* [MC-689] Remove support header from help
-
* All actions/triggers shortcut `icon-plugin run -T all --debug …

Update palo alto pan os help (#1064)

---

plugins/devo/.CHECKSUM
plugins/devo/bin/icon_devo
plugins/devo/help.md
plugins/devo/icon_devo/triggers/get_new_alerts/schema.py
plugins/devo/icon_devo/triggers/get_new_alerts/trigger.py
plugins/devo/plugin.spec.yaml
plugins/devo/setup.py

- Resolving problem with duplicate alerts …

[SOAR-7961] Fix duplicate alerts for devo

---

plugins/devo/.CHECKSUM
plugins/devo/bin/icon_devo
plugins/devo/help.md
plugins/devo/icon_devo/triggers/get_new_alerts/schema.py
plugins/devo/icon_devo/triggers/get_new_alerts/trigger.py
plugins/devo/plugin.spec.yaml
plugins/devo/setup.py

* changed sending new alerts
* add references update
* typo in variable
* bump version
* Update plugins/devo/help.md
- …

[SOAR-7961] Fix duplicate alerts for devo (#1082)

---

plugins/devo/help.md

Devo Plugin 3.0.0 - Update help.md (#1094)

---

.github/workflows/black.yml
plugins/haveibeenpwned/icon_haveibeenpwned/util/util.py
plugins/subnet/komand_subnet/actions/calculate/action.py

- This PR pins the version of the Black linting tool to the release 22.1.0 and formats two files that this release of Black wants to change.
* All actions/triggers shortcut `icon-plugin run -T all --debug --jq` …

[NO TICKET] Black linter version pin

---

.github/workflows/black.yml
plugins/haveibeenpwned/icon_haveibeenpwned/util/util.py
plugins/subnet/komand_subnet/actions/calculate/action.py

Lintformatfix

---

plugins/rapid7_intsights/.CHECKSUM
plugins/rapid7_intsights/bin/icon_rapid7_intsights
plugins/rapid7_intsights/help.md
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_complete_alert_by_id/schema.py
plugins/rapid7_intsights/icon_rapid7_intsights/util/api.py
plugins/rapid7_intsights/plugin.spec.yaml
plugins/rapid7_intsights/setup.py
plugins/rapid7_intsights/unit_test/payloads/get_complete_alert_by_id.json.resp
plugins/rapid7_intsights/unit_test/test_connection.py
plugins/rapid7_intsights/unit_test/test_get_complete_alert_by_id.py

- Add assets custom type
- Fix missing URL bug in DarkWeb Webmail alerts
- Fix response status code handling
* Single …

[MC-865] Add new assets type in rapid7_intsights plugin

---

plugins/opsgenie/.CHECKSUM
plugins/opsgenie/bin/icon_opsgenie
plugins/opsgenie/help.md
plugins/opsgenie/icon_opsgenie/actions/close_alert/action.py
plugins/opsgenie/icon_opsgenie/actions/close_alert/schema.py
plugins/opsgenie/icon_opsgenie/actions/create_alert/action.py
plugins/opsgenie/icon_opsgenie/actions/create_alert/schema.py
plugins/opsgenie/icon_opsgenie/actions/get_alert/action.py
plugins/opsgenie/icon_opsgenie/actions/get_alert/schema.py
plugins/opsgenie/icon_opsgenie/actions/get_on_calls/action.py
plugins/opsgenie/icon_opsgenie/actions/get_on_calls/schema.py
plugins/opsgenie/icon_opsgenie/connection/schema.py
plugins/opsgenie/icon_opsgenie/util/api.py
plugins/opsgenie/plugin.spec.yaml
plugins/opsgenie/requirements.txt
plugins/opsgenie/setup.py
plugins/opsgenie/unit_test/responses/get_alert.json.resp
plugins/opsgenie/unit_test/test_close_alert.py
plugins/opsgenie/unit_test/test_create_alert.py
plugins/opsgenie/unit_test/test_get_alert.py
plugins/opsgenie/unit_test/test_get_on_calls.py

- Changed description for responders  field in `create alert` action   …

Opsgenie yaml fix

---

plugins/rapid7_intsights/.CHECKSUM
plugins/rapid7_intsights/bin/icon_rapid7_intsights
plugins/rapid7_intsights/help.md
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_complete_alert_by_id/schema.py
plugins/rapid7_intsights/icon_rapid7_intsights/util/api.py
plugins/rapid7_intsights/plugin.spec.yaml
plugins/rapid7_intsights/setup.py
plugins/rapid7_intsights/unit_test/payloads/get_complete_alert_by_id.json.resp
plugins/rapid7_intsights/unit_test/test_connection.py
plugins/rapid7_intsights/unit_test/test_get_complete_alert_by_id.py

Fix DarkWeb Webmail crash - no URL
Fix response status code handling (401 means invalid API_KEY)
-
* Single …

Rapid7IntSights-MC-865 Add new assets type (#1084)

---

plugins/devo/.CHECKSUM
plugins/devo/bin/icon_devo
plugins/devo/help.md
plugins/devo/icon_devo/actions/query_logs/action.py
plugins/devo/icon_devo/triggers/get_new_alerts/trigger.py
plugins/devo/icon_devo/util/api.py
plugins/devo/plugin.spec.yaml
plugins/devo/setup.py

- Eliminated duplicated alerts  
- Added method to elapsed request time. Running trigger sometimes lose single alert, because request time spent a lot time, we added trigger interval plus elapsed request time in request
* Single action/trigger `icon-plugin run -T tests/example.json …

Soar 7961 Devo Plugin - fix duplicated alerts, fix lost alert

---

plugins/devo/.CHECKSUM
plugins/devo/bin/icon_devo
plugins/devo/help.md
plugins/devo/icon_devo/actions/query_logs/action.py
plugins/devo/icon_devo/triggers/get_new_alerts/trigger.py
plugins/devo/icon_devo/util/api.py
plugins/devo/plugin.spec.yaml
plugins/devo/setup.py

* devo - 7961 - Changed datetime now, eliminated duplicate alerts, added decorator for mesure request time
* devo - 7961 - changed version plugin
* devo - 7961 - Added log for version changes, fix validators
* devo - 7961 - Fixed logging validator
- …

Soar 7961 Devo Plugin - fix duplicated alerts, fix lost alert (#1113)

---

plugins/abuseipdb/.CHECKSUM
plugins/abuseipdb/bin/komand_abuseipdb
plugins/abuseipdb/help.md
plugins/abuseipdb/komand_abuseipdb/actions/check_ip/action.py
plugins/abuseipdb/komand_abuseipdb/actions/check_ip/schema.py
plugins/abuseipdb/plugin.spec.yaml
plugins/abuseipdb/setup.py

SOAR-6671: Disable AbuseIPDB cloud_ready flag & rename 'found' to 'isMalicious'

---

plugins/typo_squatter/.CHECKSUM
plugins/typo_squatter/help.md
plugins/typo_squatter/plugin.spec.yaml

-
JIRA: https://issues.corp.rapid7.com/browse/MC-702 …

[MC-702] Fix Typo Squatter plugin (#1039)

---

plugins/extractit/requirements.txt

- Our plugins depend on the plugin SDK. The plugin SDK [depends](https://github.com/rapid7/komand-plugin-sdk-python/blob/master/setup.py#L21) on Flask. Flask [depends](https://github.com/pallets/flask/blob/main/setup.py#L9) on itsdangerous. itsdangerous had a minor version bump that [removed](https://itsdangerous.palletsprojects.com/en/2.1.x/changes/#version-2-1-0) a package that Flask depends on. This makes Flask fail to import anywhere that it is depended on, causing literally all of our unit tests to fail.
- The temporary solution is to [version pin](https://github.com/pallets/flask/issues/4455#issuecomment-1044223329) itsdangerous anywhere we have SDK runtime failures. The permanent solution is to [version …

SOAR-7681 Version pin itsdangerous dependency

---

plugins/abuseipdb/.CHECKSUM
plugins/abuseipdb/bin/komand_abuseipdb
plugins/abuseipdb/help.md
plugins/abuseipdb/komand_abuseipdb/actions/check_ip/action.py
plugins/abuseipdb/komand_abuseipdb/actions/check_ip/schema.py
plugins/abuseipdb/plugin.spec.yaml
plugins/abuseipdb/setup.py

- Updated to v5.0.8
- Changed description for output Found …

Soar 8322 new phraseology

---

plugins/abuseipdb/.CHECKSUM
plugins/abuseipdb/bin/komand_abuseipdb
plugins/abuseipdb/help.md
plugins/abuseipdb/komand_abuseipdb/actions/check_ip/schema.py
plugins/abuseipdb/plugin.spec.yaml
plugins/abuseipdb/setup.py

- Updated cloud_Ready to false
- Update version to v5.0.8
- Changed description for output 'found'
* Single …

Changed cloud_Ready to false | Update description for 'found'

---

.github/workflows/unit_test.yml

Remove komand module from unit test runner GHA (#1143)

---

plugins/rapid7_intsights/.CHECKSUM
plugins/rapid7_intsights/bin/icon_rapid7_intsights
plugins/rapid7_intsights/help.md
plugins/rapid7_intsights/icon_rapid7_intsights/triggers/new_alert/trigger.py
plugins/rapid7_intsights/plugin.spec.yaml
plugins/rapid7_intsights/setup.py
plugins/rapid7_intsights/unit_test/test_new_alert.py

- Fix issue where New Alert trigger sends empty list when there are no new alerts …

[MC-939] Fix New Alert trigger in Rapid7 IntSights plugin

---

plugins/rapid7_intsights/.CHECKSUM
plugins/rapid7_intsights/bin/icon_rapid7_intsights
plugins/rapid7_intsights/help.md
plugins/rapid7_intsights/icon_rapid7_intsights/triggers/new_alert/trigger.py
plugins/rapid7_intsights/plugin.spec.yaml
plugins/rapid7_intsights/setup.py
plugins/rapid7_intsights/unit_test/test_new_alert.py

[MC-939] Rapid7IntSights_Fix New Alert trigger (#1127)

---

plugins/extractit/icon_extractit/actions/ioc_extractor/action.py
plugins/extractit/icon_extractit/util/extractor.py
plugins/extractit/requirements.txt

-Changes url extractor behavior for encoded urls. Previously, encoded urls would only extract everything up to the top level domain correctly, but would not extract the rest of the url correctly due to it being decoded. 
This change keeps encoded urls encoded during the extraction process so we avoid this. This can be specified with the keep_original_urls input boolean, available in the URL extract action.
If you are an InsightConnect customer or have access to an InsightConnect instance, the …

SOAR-7681 encoded url fix for ExtractIt (#1118)

---

plugins/rest/.CHECKSUM
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/komand_rest/actions/patch/action.py
plugins/rest/komand_rest/util/util.py
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py
plugins/rest/unit_test/mockconnection.py
plugins/rest/unit_test/test_delete.py
plugins/rest/unit_test/test_get.py
plugins/rest/unit_test/test_patch.py
plugins/rest/unit_test/test_post.py
plugins/rest/unit_test/test_put.py
plugins/rest/unit_test/test_utils.py

rest - 8441 - Fix issue with JSON data parser for PATCH request (#1133)

---

plugins/cisco_umbrella_destinations/.CHECKSUM
plugins/cisco_umbrella_destinations/help.md
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dlGetAll/action.py
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dlGetAll/schema.py
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/util/api.py
plugins/cisco_umbrella_destinations/plugin.spec.yaml

- Changed dlGetAll action to output an array of objects
- Added new helper function in api.py …

[SOAR-8598] - Cisco Destinations GetAll Fix

---

.github/workflows/prospector.yml

Fixvalidators for master and develop

---

.github/workflows/prospector.yml

- This PR fixes the syntax of the bash script that runs the Prospector linting tools. The if-statement compared the current branch to `"*-release"` which literally interprets the asterisk, instead of `*-release` which interprets it as a catch-all regex. …

SOAR-8293: Fix bash if statement regex

---

.github/workflows/prospector.yml

Remove quotes from bash if statement regex (#1158)

---

plugins/cisco_umbrella_destinations/.CHECKSUM
plugins/cisco_umbrella_destinations/bin/icon_cisco_umbrella_destinations
plugins/cisco_umbrella_destinations/help.md
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dAdd/action.py
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dDelete/action.py
plugins/cisco_umbrella_destinations/plugin.spec.yaml
plugins/cisco_umbrella_destinations/setup.py
plugins/cisco_umbrella_destinations/unit_test/test_dAdd.py
plugins/cisco_umbrella_destinations/unit_test/test_dDelete.py

* Updated dAdd to return only data
* Updated dAdd & dDelete & unit tests
* Version bump to 2.0.0
* Updated supported_versions date
- …

Cisco Umbrella Destinations - Soar 8723 cisco defects (#1160)

---

plugins/servicenow/help.md

* [MC-866] ServiceNow Update Documentation
* [MC-866] Reverted the version upgrade.
- …

MC-941 - ServiceNow - Update Documentation  (#1124)

---

plugins/cisco_umbrella_destinations/.CHECKSUM
plugins/cisco_umbrella_destinations/bin/icon_cisco_umbrella_destinations
plugins/cisco_umbrella_destinations/help.md
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dGet/schema.py
plugins/cisco_umbrella_destinations/plugin.spec.yaml
plugins/cisco_umbrella_destinations/setup.py

- Updated typeOf to type for output in dGet action …

[SOAR-8752] - Cisco Umbrella - Fix TypeOf

---

plugins/cisco_umbrella_destinations/.CHECKSUM
plugins/cisco_umbrella_destinations/bin/icon_cisco_umbrella_destinations
plugins/cisco_umbrella_destinations/help.md
plugins/cisco_umbrella_destinations/icon_cisco_umbrella_destinations/actions/dGet/schema.py
plugins/cisco_umbrella_destinations/plugin.spec.yaml
plugins/cisco_umbrella_destinations/setup.py

* Changed typeOf -> type in destinationsEntity type
- …

Updated typeOf to type (#1169)

---

.github/workflows/black.yml
.github/workflows/main.yml
.github/workflows/prospector.yml
.github/workflows/unit_test.yml

-Bump all python versions in Github actions workflows from 3.7 to 3.8 …

[SOAR-8647] Update Github Actions workflows to python 3.8

---

plugins/netskope/.CHECKSUM
plugins/netskope/help.md
plugins/netskope/icon_netskope/actions/apply_pending_url_list_changes/schema.py
plugins/netskope/icon_netskope/actions/create_new_url_list/schema.py
plugins/netskope/icon_netskope/actions/delete_url_list_by_id/schema.py
plugins/netskope/icon_netskope/actions/get_all_url_list/action.py
plugins/netskope/icon_netskope/actions/get_all_url_list/schema.py
plugins/netskope/icon_netskope/actions/get_single_user_confidence_index/schema.py
plugins/netskope/icon_netskope/actions/get_url_list_by_id/schema.py
plugins/netskope/icon_netskope/actions/patch_url_list_by_id/action.py
plugins/netskope/icon_netskope/actions/patch_url_list_by_id/schema.py
plugins/netskope/icon_netskope/actions/replace_url_list_by_id/schema.py
plugins/netskope/icon_netskope/actions/update_file_hash_list/action.py
plugins/netskope/icon_netskope/actions/upload_json_config/schema.py
plugins/netskope/icon_netskope/util/api.py
plugins/netskope/plugin.spec.yaml
plugins/netskope/unit_test/mock.py
plugins/netskope/unit_test/responses/test_upload_json_config_ok.json.resp
plugins/netskope/unit_test/test_apply_pending_url_list_changes.py
plugins/netskope/unit_test/test_delete_url_list_by_id.py
plugins/netskope/unit_test/test_get_all_url_list.py
plugins/netskope/unit_test/test_get_url_list_by_id.py
plugins/netskope/unit_test/test_patch_url_list_by_id.py
plugins/netskope/unit_test/test_replace_url_list_by_id.py
plugins/netskope/unit_test/test_update_file_hash_list.py
plugins/netskope/unit_test/test_upload_json_config.py

- Changed Get All URL lists action - add "any" option
- Removed json_version from all the outputs
- Removed required fileds from Update URL list by ID action
- Fixed Update File Hash List action
- Fixed Upload JSON Configuration File action …

[SOAR-8793][SOAR-8795][SOAR-8806] Netskope Fixes

---

plugins/get_url/.CHECKSUM
plugins/get_url/bin/komand_get_url
plugins/get_url/help.md
plugins/get_url/plugin.spec.yaml
plugins/get_url/setup.py

1. Update help.md to include the changes
2. Update the plugin version to 2.0.1 as it is not released yet
-
* Single …

[SOAR-8869] Get_URL Plugin set the version to 2.0.1

---

plugins/rapid7_vulndb/.CHECKSUM
plugins/rapid7_vulndb/bin/komand_rapid7_vulndb
plugins/rapid7_vulndb/help.md
plugins/rapid7_vulndb/komand_rapid7_vulndb/util/extract.py
plugins/rapid7_vulndb/komand_rapid7_vulndb/util/util.py
plugins/rapid7_vulndb/plugin.spec.yaml
plugins/rapid7_vulndb/setup.py
plugins/rapid7_vulndb/unit_test/mock.py
plugins/rapid7_vulndb/unit_test/payloads/get_content.json.resp
plugins/rapid7_vulndb/unit_test/payloads/get_content_bad.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_metasploit.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_metasploit_page_0.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_nexpose.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_nexpose_page_0.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_no_results.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_page_0.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_page_1.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_result.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_3.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_4.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_5.json.resp
plugins/rapid7_vulndb/unit_test/payloads/search_db_test_identifier_6.json.resp
plugins/rapid7_vulndb/unit_test/test_get_content.py
plugins/rapid7_vulndb/unit_test/test_search_db.py
plugins/rapid7_vulndb/unit_test/util.py

* Fix 404 error handling
* Add 404 and 504 error handling | Add retry | Add Unit tests
* Add Unit tests
* Refactor punctuation | Remove duplicate help.md headers
* Fix lint errors | Fix static code analysis errors
* Fix lint errors
* Fix mock response selection
* Refactor retry of extraction
* Add version to help.md
- …

[SOAR-7564] Rapid7 VulnDB Error Handling Improvements (#1150)

---

plugins/fireeye_hx/icon_fireeye_hx/actions/check_host_quarantine_status/action.py
plugins/fireeye_hx/unit_test/test_check_host_quarantine_status.py

- Add Check Quarantine Status action
* …

[MC-651] Add Check Quarantine Status action in FireEye HX plugin

---

.github/workflows/black.yml

- Bump the version of Black to 22.3.0, which resolves errors we have been experiencing in the Lint GitHub Action workflow.
- JIRA: https://issues.corp.rapid7.com/browse/SOAR-8951 …

SOAR-8951: Update Black workflow

---

.github/workflows/black.yml
.github/workflows/main.yml
.github/workflows/prospector.yml
.github/workflows/unit_test.yml

- Update the Python version used in all of the GitHub Action workflows in this repository from 3.7 to 3.8
- JIRA: https://issues.corp.rapid7.com/browse/SOAR-8647
- Update the Black version used in the Lint workflow from 22.1.0 to 22.3.0 
- JIRA: https://issues.corp.rapid7.com/browse/SOAR-8951
- Release these changes to the master branch …

[SOAR-8647, SOAR-8951] Update workflows version pins

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/put_incident_attachment/action.py
plugins/servicenow/icon_servicenow/util/request_helper.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

MC-954 Decode b64 data in put_attachment_to_incident (#1173)

---

plugins/microsoft_log_analytics/.CHECKSUM
plugins/microsoft_log_analytics/help.md
plugins/microsoft_log_analytics/icon_microsoft_log_analytics/triggers/search/schema.py
plugins/microsoft_log_analytics/plugin.spec.yaml

- Changed default value for interval input to 900s (15 minutes)
- Updated help.md file with a query that allows to retrieve data within specified interval time i.e. "| where TimeGenerate > ago(900s)"
* All …

[SOAR-8945] Microsoft Log Analytics Search Trigger

---

plugins/csv/.CHECKSUM
plugins/csv/bin/komand_csv
plugins/csv/help.md
plugins/csv/komand_csv/actions/filter_bytes/action.py
plugins/csv/komand_csv/actions/filter_string/action.py
plugins/csv/komand_csv/actions/to_json/action.py
plugins/csv/komand_csv/util/utils.py
plugins/csv/plugin.spec.yaml
plugins/csv/setup.py
plugins/csv/unit_test/test_filter_bytes.py
plugins/csv/unit_test/test_filter_string.py
plugins/csv/unit_test/test_json_to_csv_bytes.py
plugins/csv/unit_test/test_json_to_csv_string.py
plugins/csv/unit_test/test_to_json.py

- Fix bug with extra space character in json keys in `To JSON` action
- Fix bugs with parsing cells with quotes and comma in `To JSON`, `Filter Bytes` and `Filter String` actions
- Add unit tests for `To JSON`, `Filter Bytes` and `Filter String` actions
Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation)
and [writing](https://docs.rapid7.com/insightconnect/unit-test-primer) plugin unit tests
If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests
should be done:
and [Python …

[MC-995] CSV - Fix bug with extra space in dict keys in to json action

---

plugins/csv/.CHECKSUM
plugins/csv/bin/komand_csv
plugins/csv/help.md
plugins/csv/komand_csv/actions/filter_bytes/action.py
plugins/csv/komand_csv/actions/filter_string/action.py
plugins/csv/komand_csv/actions/to_json/action.py
plugins/csv/komand_csv/util/utils.py
plugins/csv/plugin.spec.yaml
plugins/csv/setup.py
plugins/csv/unit_test/test_filter_bytes.py
plugins/csv/unit_test/test_filter_string.py
plugins/csv/unit_test/test_json_to_csv_bytes.py
plugins/csv/unit_test/test_json_to_csv_string.py
plugins/csv/unit_test/test_to_json.py

Fix bugs with parsing cells with quotes and comma in to_json, filter_bytes and filter_string actions
Add unit tests for to_json, filter_bytes and filter_string actions
- …

MC-995 Fix bug with extra space in dict keys in to json action (#1190)

---

plugins/rapid7_insightappsec/.CHECKSUM
plugins/rapid7_insightappsec/bin/komand_rapid7_insightappsec
plugins/rapid7_insightappsec/help.md
plugins/rapid7_insightappsec/plugin.spec.yaml
plugins/rapid7_insightappsec/setup.py

[MC-792] Rapid7_insightappsec. Update title for action Submit scan.

---

plugins/rapid7_insightappsec/.CHECKSUM
plugins/rapid7_insightappsec/bin/komand_rapid7_insightappsec
plugins/rapid7_insightappsec/help.md
plugins/rapid7_insightappsec/plugin.spec.yaml
plugins/rapid7_insightappsec/setup.py

- Fix typo in InsightAppSec plugin action Submit Scan. …

[MC-792] Update title of InsightAppSec Submit Scan action (#1184)

---

plugins/netskope/.CHECKSUM
plugins/netskope/bin/icon_netskope
plugins/netskope/help.md
plugins/netskope/icon_netskope/actions/patch_url_list_by_id/action.py
plugins/netskope/icon_netskope/actions/patch_url_list_by_id/schema.py
plugins/netskope/plugin.spec.yaml
plugins/netskope/setup.py

- Update the Update URL List By ID action to handle non-required field 'name' being empty. Previously, if left empty, the action would fail.
- Update the Update URL List By ID action to successfully update URL list by setting 'type' input to required. If 'type' input was not provided previously, the passed URLs would not be appended to or replace the original URL list. …

SOAR-9079: Netskope patch update (#1223)

---

plugins/microsoft_log_analytics/.CHECKSUM
plugins/microsoft_log_analytics/bin/icon_microsoft_log_analytics
plugins/microsoft_log_analytics/help.md
plugins/microsoft_log_analytics/icon_microsoft_log_analytics/util/api.py
plugins/microsoft_log_analytics/icon_microsoft_log_analytics/util/tools.py
plugins/microsoft_log_analytics/plugin.spec.yaml
plugins/microsoft_log_analytics/setup.py
plugins/microsoft_log_analytics/unit_test/__init__.py
plugins/microsoft_log_analytics/unit_test/test_connection.py
plugins/microsoft_log_analytics/unit_test/test_create_or_update_saved_search.py
plugins/microsoft_log_analytics/unit_test/test_delete_saved_search.py
plugins/microsoft_log_analytics/unit_test/test_get_log_data.py
plugins/microsoft_log_analytics/unit_test/test_get_saved_search.py
plugins/microsoft_log_analytics/unit_test/test_list_all_searches.py
plugins/microsoft_log_analytics/unit_test/test_search.py
plugins/microsoft_log_analytics/unit_test/test_send_log_data.py

- Changed log message for status code of 404 …

[SOAR-9306] Microsoft Log Analytics - Changed log message for status code of 404

---

plugins/microsoft_log_analytics/.CHECKSUM
plugins/microsoft_log_analytics/bin/icon_microsoft_log_analytics
plugins/microsoft_log_analytics/help.md
plugins/microsoft_log_analytics/icon_microsoft_log_analytics/util/api.py
plugins/microsoft_log_analytics/icon_microsoft_log_analytics/util/tools.py
plugins/microsoft_log_analytics/plugin.spec.yaml
plugins/microsoft_log_analytics/setup.py
plugins/microsoft_log_analytics/unit_test/__init__.py
plugins/microsoft_log_analytics/unit_test/test_connection.py
plugins/microsoft_log_analytics/unit_test/test_create_or_update_saved_search.py
plugins/microsoft_log_analytics/unit_test/test_delete_saved_search.py
plugins/microsoft_log_analytics/unit_test/test_get_log_data.py
plugins/microsoft_log_analytics/unit_test/test_get_saved_search.py
plugins/microsoft_log_analytics/unit_test/test_list_all_searches.py
plugins/microsoft_log_analytics/unit_test/test_search.py
plugins/microsoft_log_analytics/unit_test/test_send_log_data.py

Microsoft Log Analytics - 9306 - changed log message for 404 status code
- Fix error handling while submit URL which is in blacklist of URLScan API | Update SDK to version 4 …

[SOAR-9306] Microsoft Log Analytics patch update (#1239)

---

.github/workflows/unit_test.yml

Add new step to the workflow displaying the unittest coverage.

[SOAR-9152] Generate unittest coverage data in a workflow

---

.github/workflows/unit_test.yml

[SOAR-9152] Generate unittest coverage data in a workflow (#1232)

---

plugins/extractit/.CHECKSUM
plugins/extractit/bin/icon_extractit
plugins/extractit/help.md
plugins/extractit/icon_extractit/actions/date_extractor/schema.py
plugins/extractit/icon_extractit/actions/extract_all/schema.py
plugins/extractit/plugin.spec.yaml
plugins/extractit/setup.py

- Remove duplicate date formats from inputs …

extractit 3.0.3 release (#1268)

---

plugins/palo_alto_mine_meld/help.md

[MC-1035] Update documentation for Palo Alto MineMeld plugin

---

plugins/palo_alto_mine_meld/help.md

[MC-1035] Update documentation (#1227)

---

plugins/recorded_future/.CHECKSUM
plugins/recorded_future/bin/komand_recorded_future
plugins/recorded_future/help.md
plugins/recorded_future/plugin.spec.yaml
plugins/recorded_future/setup.py
plugins/recorded_future/unit_test/util.py

- Remove unwanted strings from Recorded Future unit tests
- JIRA: https://issues.corp.rapid7.com/browse/SOAR-9732
* …

SOAR-9732: Recorded Future security patch

---

plugins/sql/.CHECKSUM
plugins/sql/bin/komand_sql
plugins/sql/help.md
plugins/sql/komand_sql/actions/query/action.py
plugins/sql/komand_sql/connection/connection.py
plugins/sql/komand_sql/util/util.py
plugins/sql/plugin.spec.yaml
plugins/sql/setup.py
plugins/sql/unit_test/__init__.py
plugins/sql/unit_test/test_connection.py

- Fixed .get method keyword argument error …

[SOAR-9386 ] SQL - Fix .get method

---

plugins/sql/.CHECKSUM
plugins/sql/bin/komand_sql
plugins/sql/help.md
plugins/sql/komand_sql/actions/query/action.py
plugins/sql/komand_sql/connection/connection.py
plugins/sql/komand_sql/util/util.py
plugins/sql/plugin.spec.yaml
plugins/sql/setup.py
plugins/sql/unit_test/__init__.py
plugins/sql/unit_test/test_connection.py

SQL - 9386 - Fix get method (#1300)

---

plugins/aws_ec2/icon_aws_ec2/util/common.py
plugins/aws_ec2/requirements.txt
plugins/aws_ec2/unit_test/payloads/output_handle_pagination.json
plugins/aws_ec2/unit_test/payloads/output_schema.json
plugins/aws_ec2/unit_test/test_AwsAction.py
plugins/aws_ec2/unit_test/test_action_helper.py
plugins/aws_ec2/unit_test/test_connection.py
plugins/aws_ec2/unit_test/test_pagination_helper.py

- Create unit tests for AWS EC2 plugin
2. Run the assessment tool: `icon-plugin run -A -R all -T all`. For single action validation: `icon-plugin run -A -R tests/my_action.json -T tests/my_action.json`
3. …

[SOAR-9507] AWS EC2 - Add unit tests

---

.github/workflows/unit_test.yml

- Add a test coverage threshold check in github workflows

[SOAR-9830] Check coverage threshold inside a GHA action

---

.github/workflows/unit_test.yml

[SOAR-9830] Check coverage threshold inside a GHA action (#1323)

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/asset_vulnerability_solution/schema.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/get_asset/action.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/get_asset/schema.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/get_asset_software/schema.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/get_asset_vulnerabilities/schema.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/requirements.txt
plugins/rapid7_insightvm/setup.py
plugins/rapid7_insightvm/unit_test/expected/asset_vulnerability_solution.json.exp
plugins/rapid7_insightvm/unit_test/payloads/asset_vulnerability_solution.json.resp
plugins/rapid7_insightvm/unit_test/payloads/asset_vulnerability_solution_invalid_asset_id.json.resp
plugins/rapid7_insightvm/unit_test/payloads/asset_vulnerability_solution_invalid_vulnerability_id.json.resp
plugins/rapid7_insightvm/unit_test/payloads/get_asset_software.json.resp
plugins/rapid7_insightvm/unit_test/payloads/get_asset_software_invalid_id.json.resp
plugins/rapid7_insightvm/unit_test/payloads/get_asset_vulnerabilities.json.resp
plugins/rapid7_insightvm/unit_test/payloads/get_asset_vulnerabilities_invalid_id.json.resp
plugins/rapid7_insightvm/unit_test/payloads/get_asset_vulnerabilities_with_risk_score.json.resp
plugins/rapid7_insightvm/unit_test/test_asset_vulnerability_solution.py
plugins/rapid7_insightvm/unit_test/test_async_requests.py
plugins/rapid7_insightvm/unit_test/test_get_asset.py
plugins/rapid7_insightvm/unit_test/test_get_asset_software.py
plugins/rapid7_insightvm/unit_test/test_get_asset_vulnerabilities.py
plugins/rapid7_insightvm/unit_test/util.py

Proposed Changes
Fix parameters type, input examples, description
Get Asset Vulnerability Solutions
Get Asset Vulnerabilities
Get Asset Software
Get Asset
Create Unit tests for:
Get Asset Vulnerability Solutions
Get Asset Vulnerabilities
Get Asset Software
Description
PR Requirements
Testing
Unit Tests
Unit tests written for any new or updated code
In-Product Tests …

Mc 1017 insight vm incorrect types

---

plugins/azure_ad_admin/.CHECKSUM
plugins/azure_ad_admin/bin/icon_azure_ad_admin
plugins/azure_ad_admin/help.md
plugins/azure_ad_admin/icon_azure_ad_admin/actions/get_user_info/schema.py
plugins/azure_ad_admin/plugin.spec.yaml
plugins/azure_ad_admin/setup.py
plugins/azure_ad_admin/unit_test/mock.py
plugins/azure_ad_admin/unit_test/test_create_user.py
plugins/azure_ad_admin/unit_test/test_get_user_info.py

- Fix issue with incorrect data validation in Get User Info action …

[SOAR-9823] Azure AD Admin plugin fix validation data 

---

plugins/azure_ad_admin/.CHECKSUM
plugins/azure_ad_admin/bin/icon_azure_ad_admin
plugins/azure_ad_admin/help.md
plugins/azure_ad_admin/icon_azure_ad_admin/actions/get_user_info/schema.py
plugins/azure_ad_admin/plugin.spec.yaml
plugins/azure_ad_admin/setup.py
plugins/azure_ad_admin/unit_test/mock.py
plugins/azure_ad_admin/unit_test/test_create_user.py
plugins/azure_ad_admin/unit_test/test_get_user_info.py

SOAR-9823 fix issue with incorrect data validation (#1322)

---

plugins/rapid7_intsights/.CHECKSUM
plugins/rapid7_intsights/bin/icon_rapid7_intsights
plugins/rapid7_intsights/help.md
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_complete_alert_by_id/action.py
plugins/rapid7_intsights/icon_rapid7_intsights/triggers/new_alert/schema.py
plugins/rapid7_intsights/icon_rapid7_intsights/triggers/new_alert/trigger.py
plugins/rapid7_intsights/icon_rapid7_intsights/util/api.py
plugins/rapid7_intsights/plugin.spec.yaml
plugins/rapid7_intsights/requirements.txt
plugins/rapid7_intsights/setup.py
plugins/rapid7_intsights/unit_test/test_new_alert.py

* Fixed is_closed & is_flagged filter tag
* Fix for honouring boolean values
* Get_Complete_Alert is_closed fix
* Enum Fix
* Refactored trigger.py
* Update help.md
* Unit test draft
* Added parameterized for trigger unit test
* Update help.md
* Updated version to 3.2.0
* 100% coverage unit tests
* Updated unit test
* Update new input desc and help.md update log
* Helpmd Sync
* Update help.md example for trigger
-
If you are an InsightConnect customer or have access to an InsightConnect …

[SOAR-9284] IntSights Trigger Fix (#1331)

---

prospector.yaml

- Enabled max-complexity of code for maccabe with value of 10 …

[SOAR-9903] Prospector - Enable max-complexity for maccabe

---

plugins/rapid7_insightidr/help.md

Insight IDR Changelog

---

plugins/abuseipdb/.CHECKSUM
plugins/abuseipdb/Makefile
plugins/abuseipdb/bin/komand_abuseipdb
plugins/abuseipdb/help.md
plugins/abuseipdb/komand_abuseipdb/connection/connection.py
plugins/abuseipdb/plugin.spec.yaml
plugins/abuseipdb/setup.py
plugins/carbon_black_defense/unit_tests/test_find_event.py

- Failed connection tests are returning a 200 status code in Insight Connect. This should be updated to return the proper status code corresponding to a failure.
* All actions/triggers shortcut `icon-plugin run …

[SOAR-9920] AbuseIPDB Connect Test Error Handling

---

plugins/abuseipdb/.CHECKSUM
plugins/abuseipdb/Makefile
plugins/abuseipdb/bin/komand_abuseipdb
plugins/abuseipdb/help.md
plugins/abuseipdb/komand_abuseipdb/connection/connection.py
plugins/abuseipdb/plugin.spec.yaml
plugins/abuseipdb/setup.py

* Update error handling connection test
* Fix formatting
* Fix formatting | Replace one character variable names
* Reverse change
- …

[SOAR-9920] AbuseIPDB Connect Test Error Handling (#1360)

---

plugins/azure_ad_admin/.CHECKSUM
plugins/azure_ad_admin/bin/icon_azure_ad_admin
plugins/azure_ad_admin/help.md
plugins/azure_ad_admin/plugin.spec.yaml
plugins/azure_ad_admin/setup.py

- Missing permission for `risk_detection` added …

[SOAR-9917] Add missing permission for Azure Ad Admin plugin

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/komand_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/komand_python_3_script/actions/run/action.py
plugins/python_3_script/komand_python_3_script/actions/run/schema.py
plugins/python_3_script/komand_python_3_script/connection/connection.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

- Release Python 3 Script plugin from https://github.com/rapid7/insightconnect-plugins/pull/1373/
- This PR does not include PowerShell, that will be [released separately](https://github.com/rapid7/insightconnect-plugins/pull/1375). …

Python 3 Script major update

---

plugins/dynamodb/.CHECKSUM
plugins/dynamodb/bin/komand_dynamodb
plugins/dynamodb/help.md
plugins/dynamodb/komand_dynamodb/util/extra_schemas/scan.py
plugins/dynamodb/plugin.spec.yaml
plugins/dynamodb/setup.py
plugins/dynamodb/unit_test/test_action_scan.py
plugins/dynamodb/unit_test/test_validation.py

- Fix validation schema for exclusive key parameter in scan action

[SOAR-10714] - DynamoDB - fix input number should be a string

---

plugins/type_converter/.CHECKSUM
plugins/type_converter/bin/icon_type_converter
plugins/type_converter/help.md
plugins/type_converter/icon_type_converter/actions/array_to_string/action.py
plugins/type_converter/icon_type_converter/actions/boolean_to_integer/action.py
plugins/type_converter/icon_type_converter/actions/boolean_to_string/action.py
plugins/type_converter/icon_type_converter/actions/integer_to_boolean/action.py
plugins/type_converter/icon_type_converter/actions/integer_to_number/action.py
plugins/type_converter/icon_type_converter/actions/integer_to_string/action.py
plugins/type_converter/icon_type_converter/actions/number_to_integer/action.py
plugins/type_converter/icon_type_converter/actions/object_to_string/action.py
plugins/type_converter/icon_type_converter/actions/string_to_boolean/action.py
plugins/type_converter/icon_type_converter/actions/string_to_float/action.py
plugins/type_converter/icon_type_converter/actions/string_to_integer/action.py
plugins/type_converter/icon_type_converter/actions/string_to_list/action.py
plugins/type_converter/icon_type_converter/actions/string_to_object/action.py
plugins/type_converter/plugin.spec.yaml
plugins/type_converter/setup.py

- Fixed error handling for string_to_int & string_to_float such that the errors are displayed client-side.
- Update 'e' variable to 'error' across all actions for PluginException. …

[SOAR-10497] - TypeConverter error handling

---

plugins/type_converter/.CHECKSUM
plugins/type_converter/bin/icon_type_converter
plugins/type_converter/help.md
plugins/type_converter/icon_type_converter/actions/array_to_string/action.py
plugins/type_converter/icon_type_converter/actions/boolean_to_integer/action.py
plugins/type_converter/icon_type_converter/actions/boolean_to_string/action.py
plugins/type_converter/icon_type_converter/actions/integer_to_boolean/action.py
plugins/type_converter/icon_type_converter/actions/integer_to_number/action.py
plugins/type_converter/icon_type_converter/actions/integer_to_string/action.py
plugins/type_converter/icon_type_converter/actions/number_to_integer/action.py
plugins/type_converter/icon_type_converter/actions/object_to_string/action.py
plugins/type_converter/icon_type_converter/actions/string_to_boolean/action.py
plugins/type_converter/icon_type_converter/actions/string_to_float/action.py
plugins/type_converter/icon_type_converter/actions/string_to_integer/action.py
plugins/type_converter/icon_type_converter/actions/string_to_list/action.py
plugins/type_converter/icon_type_converter/actions/string_to_object/action.py
plugins/type_converter/plugin.spec.yaml
plugins/type_converter/setup.py

* Updated error handling for 2 actions
* Updated help.md | Validators fix
* Update help.md again
* Updated e to error for all actions
* Updated to boolean actions with better error handling
* Undoing int_to_bool change
* Undo string to bool behaviour
- …

[SOAR-10497] - TypeConverter error handling (#1372)

---

plugins/azure_ad_admin/.CHECKSUM
plugins/azure_ad_admin/bin/icon_azure_ad_admin
plugins/azure_ad_admin/help.md
plugins/azure_ad_admin/icon_azure_ad_admin/connection/connection.py
plugins/azure_ad_admin/plugin.spec.yaml
plugins/azure_ad_admin/setup.py

Azure AD Admin release

---

plugins/csv/.CHECKSUM
plugins/csv/help.md
plugins/csv/plugin.spec.yaml
plugins/extractit/help.md

- Updated Input/output examples in help.md file to make sure the example input actually returns the example output.
* …

[SOAR-10500] CSV Update help.md

---

plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/connection/connection.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/util/api.py

- Fix Connection Test failures occurring in staging due to test method not returning a value …

InsightVM Cloud Connection Test Fix

---

plugins/csv/.CHECKSUM
plugins/csv/help.md
plugins/csv/plugin.spec.yaml

* updated CSV help.md input/output Examples
* help.md updated
- …

[SOAR-10500] CSV Update help.md (#1366)

---

plugins/string/help.md

Example of to lowercase action output not correct …

String Plugin help example fix

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py

[SOAR-9669] Insight Agent - Cloud enabled

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py

Rapid7 Insight Agent - 9669 - Cloud enabled Release

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/actions/get_managed_url/schema.py
plugins/mimecast/komand_mimecast/connection/schema.py
plugins/mimecast/komand_mimecast/util/constants.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py

Mimecast - 11027 - fix authentication release

---

plugins/abuseipdb/.CHECKSUM
plugins/abuseipdb/bin/komand_abuseipdb
plugins/abuseipdb/help.md
plugins/abuseipdb/plugin.spec.yaml
plugins/abuseipdb/setup.py

- Cloud enabled for Abuse IPDB
* All …

[SOAR-9667] AbuseIPDB - Cloud Enabled

---

plugins/urlscan/.CHECKSUM
plugins/urlscan/bin/komand_urlscan
plugins/urlscan/help.md
plugins/urlscan/plugin.spec.yaml
plugins/urlscan/setup.py

[SOAR-9660] Upgrade Urlscan Plugin to run on cloud

---

plugins/abuseipdb/.CHECKSUM
plugins/abuseipdb/bin/komand_abuseipdb
plugins/abuseipdb/help.md
plugins/abuseipdb/plugin.spec.yaml
plugins/abuseipdb/setup.py

- Release branch for AbuseIPDB 5.1.0 - Cloud enabled …

Abuse IPDB 5.1.0 Release

---

plugins/ipstack/.CHECKSUM
plugins/ipstack/bin/icon_ipstack
plugins/ipstack/help.md
plugins/ipstack/icon_ipstack/connection/connection.py
plugins/ipstack/plugin.spec.yaml
plugins/ipstack/setup.py

- Cloud enabled for IPStack
- Updated connection to include a connection test
* Single action/trigger `icon-plugin run …

[SOAR-9664] IPStack - Cloud Enabled

---

plugins/ipstack/icon_ipstack/connection/connection.py

- Quick fix for the connection test so it works with cloud orchestrator …

IPStack connection test fix

---

plugins/ipstack/icon_ipstack/connection/connection.py

Deleted all test, returned true

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/get_all_saved_queries/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/query/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/connection/connection.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/endpoints.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/mock.py
plugins/rapid7_insightidr/unit_test/util.py

- Fix issue with `Get Query Results` and `Get All Saved Queries actions` …

[SOAR-10641] Insight IDR - Fix issue with Get Query Results and Get All Saved Queries actions Release

---

plugins/ipstack/icon_ipstack/connection/connection.py

IPStack changed connection test to true

---

plugins/jira/.CHECKSUM
plugins/jira/Dockerfile
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/util/util.py
plugins/jira/plugin.spec.yaml
plugins/jira/requirements.txt
plugins/jira/setup.py

- Update docker version to using Debian OS. Resolving issue with failed Jenkins build.
- Fix errors with attribute error
* All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format at …

[SOAR-9775][SOAR-10287] Jira Plugin change docker image version, fix errors

---

plugins/jira/komand_jira/util/util.py

- During the tests Jira Plugin on staging I realized I made an error in the code and I had a problem with project permission. 
* All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use PR format …

[SOAR-10287] Jira fix look up project

---

plugins/jira/.CHECKSUM
plugins/jira/Dockerfile
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/util/util.py
plugins/jira/plugin.spec.yaml
plugins/jira/requirements.txt
plugins/jira/setup.py

- Release branch for Jira 6.2.1 
* All …

Jira 6.2.1 release

---

plugins/urlscan/.CHECKSUM
plugins/urlscan/bin/komand_urlscan
plugins/urlscan/help.md
plugins/urlscan/plugin.spec.yaml
plugins/urlscan/setup.py

Urlscan 4.1.0 release

---

plugins/palo_alto_cortex_xdr/.CHECKSUM
plugins/palo_alto_cortex_xdr/help.md
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/actions/get_xql_query_results/schema.py
plugins/palo_alto_cortex_xdr/icon_palo_alto_cortex_xdr/triggers/get_query_results/schema.py
plugins/palo_alto_cortex_xdr/plugin.spec.yaml

- Changed description for `Get XQL Query Results` action, `Get Query Results` trigger
- Added example output field to `Get Query Results` trigger
- Changed the query examples for `Get XQL Query Results`, and `Get Query Results` in order not to brake the `help.md` table
* Single …

[SOAR-10513] Palo Alto Cortex XDR - Fixed descriptions, examples

---

plugins/manage_engine_service_desk/.CHECKSUM
plugins/manage_engine_service_desk/bin/icon_manage_engine_service_desk
plugins/manage_engine_service_desk/help.md
plugins/manage_engine_service_desk/icon_manage_engine_service_desk/util/helpers.py
plugins/manage_engine_service_desk/plugin.spec.yaml
plugins/manage_engine_service_desk/setup.py
plugins/manage_engine_service_desk/unit_test/test_add_request.py
plugins/manage_engine_service_desk/unit_test/test_add_request_note.py
plugins/manage_engine_service_desk/unit_test/test_add_resolution.py
plugins/manage_engine_service_desk/unit_test/test_assign_request.py
plugins/manage_engine_service_desk/unit_test/test_close_request.py
plugins/manage_engine_service_desk/unit_test/test_delete_request.py
plugins/manage_engine_service_desk/unit_test/test_delete_request_note.py
plugins/manage_engine_service_desk/unit_test/test_edit_request.py
plugins/manage_engine_service_desk/unit_test/test_edit_request_note.py
plugins/manage_engine_service_desk/unit_test/test_get_list_request.py
plugins/manage_engine_service_desk/unit_test/test_get_list_request_notes.py
plugins/manage_engine_service_desk/unit_test/test_get_request.py
plugins/manage_engine_service_desk/unit_test/test_get_resolution.py
plugins/manage_engine_service_desk/unit_test/test_helpers.py
plugins/manage_engine_service_desk/unit_test/test_pickup_request.py

- Fix int conversion bug in 2 actions
* …

[MC-1328] Manage Engine int conversion bug

---

plugins/microsoft_teams/icon_microsoft_teams/connection/connection.py

Update the connection test to return true when working.
* All …

Soar 7618 Teams Connection

---

plugins/markdown/.CHECKSUM
plugins/markdown/bin/komand_markdown
plugins/markdown/help.md
plugins/markdown/komand_markdown/actions/html_to_markdown/action.py
plugins/markdown/komand_markdown/actions/markdown_to_html/action.py
plugins/markdown/komand_markdown/actions/markdown_to_pdf/action.py
plugins/markdown/komand_markdown/actions/markdown_to_txt/action.py
plugins/markdown/plugin.spec.yaml
plugins/markdown/requirements.txt
plugins/markdown/setup.py
plugins/markdown/unit_test/test_html_to_markdown.py
plugins/markdown/unit_test/test_markdown_to_html.py
plugins/markdown/unit_test/test_markdown_to_pdf.py
plugins/markdown/unit_test/test_markdown_to_txt.py

- Update `markdown_to_txt` action to have more accurate error messaging.
- Refactor other actions to have consistency in the code …

[SOAR-11246] Markdown Error Messaging

---

plugins/markdown/help.md
plugins/markdown/komand_markdown/actions/markdown_to_html/action.py
plugins/markdown/komand_markdown/actions/markdown_to_pdf/action.py

- Added review changes from release branch to merge with develop to ensure consistency. …

Release review changes

---

plugins/microsoft_teams/icon_microsoft_teams/connection/connection.py

Previous version would not reach the return properly. Moved the if and try back around to fix this. …

SOAR-7618 Microsoft Teams Connection Test Redo

---

plugins/manage_engine_service_desk/.CHECKSUM
plugins/manage_engine_service_desk/bin/icon_manage_engine_service_desk
plugins/manage_engine_service_desk/help.md
plugins/manage_engine_service_desk/icon_manage_engine_service_desk/util/helpers.py
plugins/manage_engine_service_desk/plugin.spec.yaml
plugins/manage_engine_service_desk/setup.py
plugins/manage_engine_service_desk/unit_test/test_add_request.py
plugins/manage_engine_service_desk/unit_test/test_add_request_note.py
plugins/manage_engine_service_desk/unit_test/test_add_resolution.py
plugins/manage_engine_service_desk/unit_test/test_assign_request.py
plugins/manage_engine_service_desk/unit_test/test_close_request.py
plugins/manage_engine_service_desk/unit_test/test_delete_request.py
plugins/manage_engine_service_desk/unit_test/test_delete_request_note.py
plugins/manage_engine_service_desk/unit_test/test_edit_request.py
plugins/manage_engine_service_desk/unit_test/test_edit_request_note.py
plugins/manage_engine_service_desk/unit_test/test_get_list_request.py
plugins/manage_engine_service_desk/unit_test/test_get_list_request_notes.py
plugins/manage_engine_service_desk/unit_test/test_get_request.py
plugins/manage_engine_service_desk/unit_test/test_get_resolution.py
plugins/manage_engine_service_desk/unit_test/test_helpers.py
plugins/manage_engine_service_desk/unit_test/test_pickup_request.py

* MC-1328 Fix int conversion bug
* MC-1328 Update plugin version
* MC-1328 Fix unit test
- …

[MC-1328] Manage Engine int conversion bug (#1458)

---

plugins/rapid7_insightvm/komand_rapid7_insightvm/triggers/new_scans/trigger.py

[SOAR-11442] insightvm

---

plugins/extractit/.CHECKSUM
plugins/extractit/bin/icon_extractit
plugins/extractit/help.md
plugins/extractit/icon_extractit/util/extractor.py
plugins/extractit/plugin.spec.yaml
plugins/extractit/setup.py
plugins/extractit/unit_test/test_url_extractor.py

- Extract URL fails when 'keep original urls' is set to false and multiple urls containing the same linked url are passed as input. …

[SOAR-11501] ExtractIt

---

plugins/markdown/.CHECKSUM
plugins/markdown/bin/komand_markdown
plugins/markdown/help.md
plugins/markdown/komand_markdown/actions/html_to_markdown/action.py
plugins/markdown/komand_markdown/actions/markdown_to_html/action.py
plugins/markdown/komand_markdown/actions/markdown_to_pdf/action.py
plugins/markdown/komand_markdown/actions/markdown_to_txt/action.py
plugins/markdown/plugin.spec.yaml
plugins/markdown/requirements.txt
plugins/markdown/setup.py
plugins/markdown/unit_test/test_html_to_markdown.py
plugins/markdown/unit_test/test_markdown_to_html.py
plugins/markdown/unit_test/test_markdown_to_pdf.py
plugins/markdown/unit_test/test_markdown_to_txt.py

* Improved error messaging in markdown_to_txt
* Refactored html to markdown
* Refactored html & markdown
* Removed empty variable in markdown_to_txt
* Update version and help.md
* Update help.md
* Added unit test for markdown_to_txt
* Unit test templates
* Unit test filler
* Reformatted to_txt with parameterized
* 3/4 unit tests finished
* Tests finished minus to pdf
* Reformatting
* Fix static code check
* Longshot to fix the pandoc error
* Second longshot to fix the pandoc error
* Finished up on unit tests
* Tided up markdowntopdf test
* Bug fix for markdown to txt
* Updated help md for bug fix
* Plugin validator fix
-
Review our documentation on …

Markdown 3.1.2 Release

---

plugins/extractit/.CHECKSUM
plugins/extractit/bin/icon_extractit
plugins/extractit/help.md
plugins/extractit/icon_extractit/util/extractor.py
plugins/extractit/plugin.spec.yaml
plugins/extractit/setup.py
plugins/extractit/unit_test/test_url_extractor.py

* Fix remove extracted urls from links | version update | update test method for test_url_extractor.py
* Regenerate
* Regenerate
* Regenerate
- Extract URL fails when 'keep original urls' is set to false and multiple urls containing the same linked url are passed as input.
* Single …

[SOAR-11501] ExtractIt 3.0.6 Release (#1468)

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

- The change here is simply to fix the spelling of an enum for the `advanced_query_on_log_set` action to ensure the strings match when performing a search so that the enum is not skipped over when the action is run.
* Single action/trigger `icon-plugin run -T tests/example.json --debug …

[SOAR-9030] - IDR Enum Bug fix

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/create_incident/action.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

- Fix issue when additional_fields field is empty in Create Incident action
* Single action/trigger `icon-plugin run …

[SOAR-11558] ServiceNow - Fix issue when additional_fields field is empty in Create Incident action RELEASE (#1471)

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/advanced_query_on_log_set/schema.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py

* Fix enum for action in advanced query on log set
* Updated changelog
- …

[SOAR-9030] - IDR Enum Bug fix (#1460)

---

plugins/aws_ec2/.CHECKSUM
plugins/aws_ec2/bin/icon_aws_ec2
plugins/aws_ec2/help.md
plugins/aws_ec2/icon_aws_ec2/actions/authorize_security_group_egress/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/authorize_security_group_ingress/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/describe_instances/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/describe_security_groups/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/revoke_security_group_egress/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/revoke_security_group_ingress/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/update_security_group_rule_descriptions_egress/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/update_security_group_rule_descriptions_ingress/schema.py
plugins/aws_ec2/icon_aws_ec2/connection/connection.py
plugins/aws_ec2/icon_aws_ec2/connection/schema.py
plugins/aws_ec2/icon_aws_ec2/util/common.py
plugins/aws_ec2/plugin.spec.yaml
plugins/aws_ec2/requirements.txt
plugins/aws_ec2/setup.py
plugins/aws_ec2/unit_test/test_connection.py

- Assume role in connection
- Assume role in action …

Soar 10893 ec2 assume role

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/help.md
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/setup.py

- Refresh to fix JSON marshalling issue on unexpected API response for Force Password Reset action
* Single …

[PLGN-10] Active Directory LDAP Refresh

---

plugins/python_3_script/Dockerfile

- Changed user in Dockerfile to root
* …

Python 3 Script - Changed user in Dockerfile to root

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/icon_python_3_script/actions/run/action.py
plugins/python_3_script/icon_python_3_script/connection/connection.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py
plugins/python_3_script/unit_test/test_run.py
plugins/python_3_script/unit_test/util.py

- Fix issue with installing python modules
- Fix indentation issue …

[PLGN-28, PLGN-32] Python 3 Script Release

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/bin/icon_microsoft_teams
plugins/microsoft_teams/help.md
plugins/microsoft_teams/icon_microsoft_teams/actions/add_channel_to_team/action.py
plugins/microsoft_teams/icon_microsoft_teams/actions/add_channel_to_team/schema.py
plugins/microsoft_teams/icon_microsoft_teams/util/teams_utils.py
plugins/microsoft_teams/plugin.spec.yaml
plugins/microsoft_teams/setup.py
plugins/microsoft_teams/unit_test/payloads/add_channel_to_team.json.resp
plugins/microsoft_teams/unit_test/test_add_channel_to_team.py
plugins/microsoft_teams/unit_test/util.py

- Added ability to create private channels …

[PLGN-25] Microsoft Teams - Add Channel to Team: Added ability to create private channels

---

plugins/aws_ec2/.CHECKSUM
plugins/aws_ec2/bin/icon_aws_ec2
plugins/aws_ec2/help.md
plugins/aws_ec2/icon_aws_ec2/actions/authorize_security_group_egress/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/authorize_security_group_ingress/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/describe_instances/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/describe_security_groups/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/revoke_security_group_egress/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/revoke_security_group_ingress/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/update_security_group_rule_descriptions_egress/schema.py
plugins/aws_ec2/icon_aws_ec2/actions/update_security_group_rule_descriptions_ingress/schema.py
plugins/aws_ec2/icon_aws_ec2/connection/connection.py
plugins/aws_ec2/icon_aws_ec2/connection/schema.py
plugins/aws_ec2/icon_aws_ec2/util/common.py
plugins/aws_ec2/plugin.spec.yaml
plugins/aws_ec2/requirements.txt
plugins/aws_ec2/setup.py
plugins/aws_ec2/unit_test/test_connection.py

- [SOAR-10893] AWS EC2 - Assue Role

AWS EC2 - 1.2.0 - release

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/help.md
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/setup.py

* Refresh
* Refresh
- Refresh to prevent JSON marshalling error being raised upon receiving unexpected API response
* …

[PLGN-10] Active Directory LDAP Refresh Release(#1478)

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/bin/komand_sentinelone
plugins/sentinelone/help.md
plugins/sentinelone/komand_sentinelone/actions/mark_as_benign/schema.py
plugins/sentinelone/komand_sentinelone/actions/update_analyst_verdict/action.py
plugins/sentinelone/komand_sentinelone/actions/update_analyst_verdict/schema.py
plugins/sentinelone/komand_sentinelone/actions/update_incident_status/action.py
plugins/sentinelone/komand_sentinelone/actions/update_incident_status/schema.py
plugins/sentinelone/komand_sentinelone/connection/connection.py
plugins/sentinelone/plugin.spec.yaml
plugins/sentinelone/setup.py
plugins/sentinelone/unit_test/payloads/alerts_non_existing.json.resp
plugins/sentinelone/unit_test/test_update_analyst_verdict.py
plugins/sentinelone/unit_test/test_update_incident_status.py
plugins/sentinelone/unit_test/util.py

SentinelOne change log update

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/help.md
plugins/microsoft_teams/icon_microsoft_teams/actions/add_channel_to_team/schema.py
plugins/microsoft_teams/plugin.spec.yaml

- Set default channel type to `Standard` …

Microsoft Teams - 25 - Set default channel type to Standard

---

plugins/microsoft_teams/help.md

- Updated changelog in help.md file
* All …

Microsoft Teams - Updated changelog in help.md

---

plugins/freshdesk/.CHECKSUM
plugins/freshdesk/Dockerfile
plugins/freshdesk/icon_freshdesk/util/helpers.py
plugins/freshdesk/plugin.spec.yaml
plugins/freshdesk/unit_test/test_helpers.py

[MC-1327] FreshDesk - add cloud ready flag

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/icon_python_3_script/actions/run/action.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py
plugins/python_3_script/unit_test/test_run.py

- Run: Updated indentation fix for input action …

Release Python 3 Script - Updated indentation fix (#1494)

---

.github/workflows/unit_test.yml

- Added required packages to run unittests (Github Actions) …

[PLGN-56] Github Actions - Added required packages to run unittests

---

plugins/threatcrowd/.CHECKSUM
plugins/threatcrowd/bin/icon_threatcrowd
plugins/threatcrowd/help.md
plugins/threatcrowd/plugin.spec.yaml
plugins/threatcrowd/setup.py

- Updated the plugin version to `3.1.0`
* …

[PLGN-16] Threatcrowd - Updated the plugin version

---

.github/workflows/unit_test.yml

- Removed failing package
* All …

Github Actions - Removed failing package

---

plugins/whois/.CHECKSUM
plugins/whois/Dockerfile
plugins/whois/bin/komand_whois
plugins/whois/help.md
plugins/whois/plugin.spec.yaml
plugins/whois/setup.py
plugins/whois/whois.conf

- Add .monster and .nl tld
* All …

[PLGN-31] whois new tlds

---

.github/workflows/unit_test.yml

- Removed failing `python-dev` package
* …

Release Github Actions - Removed failing package (#1508)

---

.github/workflows/prospector.yml

- Removed pylint from prospector due to the package issue …

Github Actions - Removed pylint from prospector due to the package issue

---

.github/workflows/prospector.yml

- Removed `pylint` from prospector due to the package issue …

Release Github Actions - Removed pylint from prospector due to the package issue (#1515)

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/help.md
plugins/microsoft_teams/icon_microsoft_teams/actions/add_member_to_channel/action.py
plugins/microsoft_teams/icon_microsoft_teams/actions/add_member_to_channel/schema.py
plugins/microsoft_teams/icon_microsoft_teams/util/azure_ad_utils.py
plugins/microsoft_teams/plugin.spec.yaml
plugins/microsoft_teams/unit_test/test_add_member_to_channel.py

Added the ability to choose a role (member or owner) to the action "add member to channel" …

Plgn-66 Update Microsoft Teams Action Add Member to Channel 

---

plugins/threatcrowd/.CHECKSUM
plugins/threatcrowd/plugin.spec.yaml

- Changed status to obsolete
* All …

[PLGN-78] - Disable the threat crowd plugin

---

plugins/jira/.CHECKSUM
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/connection/connection.py
plugins/jira/komand_jira/connection/schema.py
plugins/jira/plugin.spec.yaml
plugins/jira/requirements.txt
plugins/jira/setup.py
plugins/jira/unit_test/test_connection.py
plugins/jira/unit_test/test_transition_issue.py

- Add PAT authentication for the on-prem Jira

[PLGN-80] Jira - add PAT authentication

---

plugins/urlscan/.CHECKSUM
plugins/urlscan/bin/komand_urlscan
plugins/urlscan/help.md
plugins/urlscan/komand_urlscan/actions/search/action.py
plugins/urlscan/plugin.spec.yaml
plugins/urlscan/setup.py

- Fixed the issue where a user adding `https://` breaks the search.  …

[PLGN-69] URLScan bug fix

---

plugins/urlscan/.CHECKSUM
plugins/urlscan/bin/komand_urlscan
plugins/urlscan/help.md
plugins/urlscan/komand_urlscan/actions/search/action.py
plugins/urlscan/plugin.spec.yaml
plugins/urlscan/setup.py

* Fixed it
* Refactored it
* Wee small comment change
* Updated comment
* Changed fix to raise exception
* Updated changelog
* Updated exception messaging
* Changed error handling and updated docs
* Update changelog
* Updated error handling and references in help.md
* Refactored code
* refactored …

URLScan 4.1.1 release

---

plugins/rapid7_intsights/.CHECKSUM
plugins/rapid7_intsights/help.md
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_iocs_by_filter/schema.py
plugins/rapid7_intsights/plugin.spec.yaml
plugins/rapid7_intsights/unit_test/payloads/get_iocs_by_filter.json.resp
plugins/rapid7_intsights/unit_test/test_get_iocs_by_filter.py

- Remove Sources from IOC Content output for action Get IOCs By Filter …

[PLGN-67] Rapid7 Intsights Quick Fix

---

plugins/rapid7_intsights/.CHECKSUM
plugins/rapid7_intsights/bin/icon_rapid7_intsights
plugins/rapid7_intsights/help.md
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_indicator_by_value/action.py
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_indicator_by_value/schema.py
plugins/rapid7_intsights/icon_rapid7_intsights/actions/get_iocs_by_filter/schema.py
plugins/rapid7_intsights/plugin.spec.yaml
plugins/rapid7_intsights/setup.py
plugins/rapid7_intsights/unit_test/payloads/get_iocs_by_filter.json.resp
plugins/rapid7_intsights/unit_test/payloads/iocs_ioc-by-value.json.resp
plugins/rapid7_intsights/unit_test/test_get_indicator_by_value.py
plugins/rapid7_intsights/unit_test/test_get_iocs_by_filter.py

- Mismatched response values from API documentation vs reality leading to incorrect action outputs
* Single …

[PLGN-26] rapid7 intsights quicker fix

---

plugins/sentinelone/.CHECKSUM
plugins/sentinelone/bin/komand_sentinelone
plugins/sentinelone/help.md
plugins/sentinelone/komand_sentinelone/connection/connection.py
plugins/sentinelone/komand_sentinelone/connection/schema.py
plugins/sentinelone/komand_sentinelone/util/constants.py
plugins/sentinelone/plugin.spec.yaml
plugins/sentinelone/setup.py
plugins/sentinelone/unit_test/test_activities_list.py
plugins/sentinelone/unit_test/util.py

* [PLGN-14][PLGN-7][PLGN-24] Azure Ad Admin Plugin new action change user password, fix issue with validation schema (#1500)
* PLGN-14 change validation schema for get user info action
* PLGN-7 change password action
* Microsoft Teams - 57 - New Message Received: Fixed issue where font-size value appeared in the urls, and domains output fields (#1511)
* [PLGN-71] Add Service role for SentinelOne. Remove basic authentication
* Fixed incorrect merge
* Fixed incorrect merge
* Added several updates to ensure validator checks pass (unrelated to service role updates)
* Updated to use constant for service role string
* Refactored to use type instead of role for clarity
* Updated formatting
* Updated timestamps for validator
Co-authored-by: llaszuk-r7 …

SentinelOne 8.0.0 release 

---

plugins/threatcrowd/.CHECKSUM
plugins/threatcrowd/bin/icon_threatcrowd
plugins/threatcrowd/plugin.spec.yaml
plugins/threatcrowd/setup.py

- made obsolete
- update version number
* …

[PLGN] - 94 - Disable threat crowd

---

plugins/aws_ec2/.CHECKSUM
plugins/aws_ec2/bin/icon_aws_ec2
plugins/aws_ec2/help.md
plugins/aws_ec2/plugin.spec.yaml
plugins/aws_ec2/setup.py

[PLGN-62] AWS EC2 related code change-log update

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/icon_python_3_script/actions/run/action.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

Python 3 Script - Logging fix

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/icon_python_3_script/actions/run/action.py
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py

Python 3 Script - Fix logging issue

---

plugins/threatcrowd/.CHECKSUM
plugins/threatcrowd/bin/icon_threatcrowd
plugins/threatcrowd/help.md
plugins/threatcrowd/plugin.spec.yaml
plugins/threatcrowd/setup.py

- make obsolete
- increase version number to 4.0.0 …

[PLGN-78] - Disable the threat crowd plugin + Bump version number

---

plugins/microsoft_teams/.CHECKSUM
plugins/microsoft_teams/bin/icon_microsoft_teams
plugins/microsoft_teams/help.md
plugins/microsoft_teams/icon_microsoft_teams/triggers/new_message_received/trigger.py
plugins/microsoft_teams/plugin.spec.yaml
plugins/microsoft_teams/setup.py
plugins/microsoft_teams/unit_test/test_new_message_received.py

- URLs with case-sensitive characters after the domain are transformed to lower case and in some instances are no longer valid. Update to remove transformation to lower case.
- Also update to improve domain handling, returning the domain only and not the path and query params as well.
* …

[SOAR-10512] Microsoft Teams

---

plugins/rest/.CHECKSUM
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/komand_rest/actions/delete/action.py
plugins/rest/komand_rest/actions/delete/schema.py
plugins/rest/komand_rest/actions/get/action.py
plugins/rest/komand_rest/actions/get/schema.py
plugins/rest/komand_rest/actions/patch/action.py
plugins/rest/komand_rest/actions/post/action.py
plugins/rest/komand_rest/actions/post/schema.py
plugins/rest/komand_rest/actions/put/action.py
plugins/rest/komand_rest/actions/put/schema.py
plugins/rest/komand_rest/util/util.py
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py

* Added body as an array
* Refactored actions
* Get and Post done
* Updated help.md
* Regen
* Update help.md
* Change type to isinstance
* Update helpmd
* Regen
* Update get in help.md
* Hashes
* Restored removed part
* Updated help.md
* fixed 2 lines in help.md
- …

Rest 5.2.0 Release

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/get_asset/schema.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/vuln_search/schema.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml

Vulnerability Search action was returning the wrong information for the type given, so created new matching type. …

Plgn-60 InsightVM Cloud New Action Vuln Search Update

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py

- Fix incorrect behavior for unquarantine when the agent ID is wrong …

Insight Agent - Fix incorrect behavior for unquarantine when the agent ID is wrong

---

plugins/jira/help.md
plugins/jira/komand_jira/connection/connection.py

- Connection test implemented for PAT based connections …

[PLGN-124] Jira - Failed PAT Connection Test

---

plugins/jira/.CHECKSUM
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/triggers/monitor_issues/schema.py
plugins/jira/komand_jira/triggers/monitor_issues/trigger.py
plugins/jira/komand_jira/triggers/new_issue/schema.py
plugins/jira/komand_jira/triggers/new_issue/trigger.py
plugins/jira/komand_jira/util/util.py
plugins/jira/plugin.spec.yaml
plugins/jira/setup.py
plugins/jira/unit_test/test_create_issue.py
plugins/jira/unit_test/test_monitor_issues.py
plugins/jira/unit_test/test_new_issue.py
plugins/jira/unit_test/util.py

- Add ability to return Issue fields in Triggers …

[PLGN-115] Jira - Fields not returned by Triggers

---

plugins/jira/.CHECKSUM
plugins/jira/bin/komand_jira
plugins/jira/help.md
plugins/jira/komand_jira/actions/create_issue/action.py
plugins/jira/komand_jira/connection/connection.py
plugins/jira/komand_jira/triggers/monitor_issues/schema.py
plugins/jira/komand_jira/triggers/monitor_issues/trigger.py
plugins/jira/komand_jira/triggers/new_issue/schema.py
plugins/jira/komand_jira/triggers/new_issue/trigger.py
plugins/jira/komand_jira/util/util.py
plugins/jira/plugin.spec.yaml
plugins/jira/setup.py
plugins/jira/unit_test/test_create_issue.py
plugins/jira/unit_test/test_monitor_issues.py
plugins/jira/unit_test/test_new_issue.py
plugins/jira/unit_test/util.py

- Fix PAT Connection Test Failure | Fix Fields not returned by Triggers | Fix Create Issue …

Jira 6.4.0 Release

---

plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/vuln_search/action.py
plugins/rapid7_insightvm_cloud/unit_test/test_vuln_search.py

A few small changes that were brought up in the release PR regarding test comments and a check for negative value inputs …

[PLGN-60] InsightVM-Cloud Vuln Search Action Small fixes

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/create_investigation/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/update_investigation/action.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/test_create_investigation.py
plugins/rapid7_insightidr/unit_test/test_update_investigation.py

- Fix issue with Create Investigation, Update Investigation actions when email field is not empty
* Single …

Insight IDR - Fix issue with Create Investigation, Update Investigation actions when email field is not empty

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/create_investigation/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/update_investigation/action.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/test_create_investigation.py
plugins/rapid7_insightidr/unit_test/test_update_investigation.py

- Fix issue with Create Investigation, Update Investigation actions when email field is not empty
* Single …

Release Insight IDR - Fix issue with Create Investigation, Update Investigation actions when email field is not empty

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/bin/icon_servicenow
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/search_incident/action.py
plugins/servicenow/icon_servicenow/actions/search_incident_attachment/action.py
plugins/servicenow/icon_servicenow/util/request_helper.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/setup.py

- `Search Incident`, `Search Incident Attachment`: Fix issue where the action were failing on bigger results
* Single …

ServiceNow - `Search Incident`, `Search Incident Attachment`: Fix issue where the action were failing on bigger results

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/create_incident/schema.py
plugins/servicenow/icon_servicenow/actions/update_incident/action.py
plugins/servicenow/icon_servicenow/actions/update_incident/schema.py
plugins/servicenow/plugin.spec.yaml

Modify the update incident action to ensure that fields that are not provided are not reset to defaults.
Also corrected a typo in spelling of incident for create incident action.
**NOTE**: I'm planning to merge this to production with @igorski-r7  updates at https://github.com/rapid7/insightconnect-plugins/pull/1597, hence I've gone with the same version number. …

[PLGN-134] ServiceNow Update Incident defaults

---

plugins/sentinelone/requirements.txt

Matser fix

---

plugins/sentinelone/requirements.txt

Master fix (#1614)

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/update_shared_credential/schema.py
plugins/rapid7_insightvm/plugin.spec.yaml

Insight vm console required enums fix

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/update_shared_credential/schema.py
plugins/rapid7_insightvm/plugin.spec.yaml

- Added Default Values to ENUM's
* All …

added default values for enum (#1620)

---

plugins/samanage/.CHECKSUM
plugins/samanage/Dockerfile
plugins/samanage/help.md
plugins/samanage/komand_samanage/actions/assign_incident/schema.py
plugins/samanage/komand_samanage/actions/attach_incident/schema.py
plugins/samanage/komand_samanage/actions/change_incident_state/schema.py
plugins/samanage/komand_samanage/actions/create_incident/schema.py
plugins/samanage/komand_samanage/actions/create_user/schema.py
plugins/samanage/komand_samanage/actions/get_incident/schema.py
plugins/samanage/komand_samanage/actions/list_incidents/schema.py
plugins/samanage/komand_samanage/actions/list_users/schema.py
plugins/samanage/komand_samanage/actions/tag_incident/schema.py
plugins/samanage/komand_samanage/triggers/new_incidents/schema.py
plugins/samanage/komand_samanage/util/api.py
plugins/samanage/plugin.spec.yaml

Noticed during testing that id fields can be strings or integers and therefore the output coming back was frequently incorrect. Added additional code to convert any integer id fields to strings for consistency. 
Also needed to update Dockerfile to allow attach incident to work (curl command).
Tested with generated samples. 
Unit tests will be treated in separate PR.

[PLGN-133] Samanage/Solarwinds updates

---

plugins/opsgenie/.CHECKSUM
plugins/opsgenie/bin/icon_opsgenie
plugins/opsgenie/help.md
plugins/opsgenie/icon_opsgenie/util/api.py
plugins/opsgenie/plugin.spec.yaml
plugins/opsgenie/setup.py

PLGN-84 Opsgenie Create Alert 404 issue 

---

plugins/powershell/.CHECKSUM
plugins/powershell/bin/icon_powershell
plugins/powershell/bin/komand_powershell
plugins/powershell/help.md
plugins/powershell/icon_powershell/util/util.py
plugins/powershell/plugin.spec.yaml
plugins/powershell/requirements.txt
plugins/powershell/setup.py
plugins/powershell/unit_test/test_util.py

* Change quotes to double
* Regen and add parameterized to requirements
* requirements
* Updated unit test
* black formatting
* Fixed unit test
* Black formatting
* Regen
* restore original help.md
* updated md
* new checksum
* original help md
* orig checksum
* checksum + helpmd
* md
* md
* md
* update bin file v
* Proper fix
* Changed quotes back
* reverted unit test change
-
If you are an InsightConnect customer or have access to an InsightConnect instance, the following in-product tests …

[PLGN-58] - PowerShell password bug fix (#1621)

---

plugins/opsgenie/.CHECKSUM
plugins/opsgenie/bin/icon_opsgenie
plugins/opsgenie/help.md
plugins/opsgenie/icon_opsgenie/util/api.py
plugins/opsgenie/plugin.spec.yaml
plugins/opsgenie/setup.py

[PLGN-84] Opsgenie 1.1.1 release

---

plugins/palo_alto_mine_meld/.CHECKSUM
plugins/palo_alto_mine_meld/bin/icon_palo_alto_mine_meld
plugins/palo_alto_mine_meld/help.md
plugins/palo_alto_mine_meld/icon_palo_alto_mine_meld/actions/update_external_dynamic_list/action.py
plugins/palo_alto_mine_meld/plugin.spec.yaml
plugins/palo_alto_mine_meld/setup.py
plugins/palo_alto_mine_meld/unit_test/test_update_external_dynamic_list.py

- Added extra validators to enable users to input CIDR IP addresses …

[PLGN-156] Mine Meld - Added validation for CIDR IP addresses

---

plugins/nmap/.CHECKSUM
plugins/nmap/bin/komand_nmap
plugins/nmap/help.md
plugins/nmap/komand_nmap/actions/scan/schema.py
plugins/nmap/plugin.spec.yaml
plugins/nmap/setup.py

- Changed type of tcp results from `[]tcp` to `tcp` (array to object) …

[PLGN-151] nmap - TCP results bug fix

---

plugins/zendesk/help.md
plugins/zendesk/icon_zendesk/actions/create_ticket/action.py
plugins/zendesk/icon_zendesk/connection/connection.py
plugins/zendesk/icon_zendesk/util/exceptions.py
plugins/zendesk/requirements.txt
plugins/zendesk/unit_test/test_create_ticket.py

- Fixed issue with create ticket action
* …

[SOAR-8392] Zendesk - Fixed issue with create ticket action

---

plugins/nmap/.CHECKSUM
plugins/nmap/bin/komand_nmap
plugins/nmap/help.md
plugins/nmap/komand_nmap/actions/scan/schema.py
plugins/nmap/plugin.spec.yaml
plugins/nmap/setup.py

* Bug fix for validation error on tcp results
* Update checksum
* restore help md
- …

[PLGN-151] nmap - TCP results bug fix (#1636)

---

plugins/palo_alto_mine_meld/.CHECKSUM
plugins/palo_alto_mine_meld/bin/icon_palo_alto_mine_meld
plugins/palo_alto_mine_meld/help.md
plugins/palo_alto_mine_meld/icon_palo_alto_mine_meld/actions/update_external_dynamic_list/action.py
plugins/palo_alto_mine_meld/plugin.spec.yaml
plugins/palo_alto_mine_meld/setup.py
plugins/palo_alto_mine_meld/unit_test/test_update_external_dynamic_list.py

* Added extra validators
* Update unit test
- …

[PLGN-156] Mine Meld - Added validation for CIDR IP addresses (#1637)

---

.github/workflows/prospector.yml

- Updated the version of `prospector` and enabled `pylint` …

Prospector - Updated version and pylint enabled

---

.github/workflows/prospector.yml

- Updated version and enabled pylint
* …

Prospector - Updated version and enabled pylint

---

plugins/rest/.CHECKSUM
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/komand_rest/actions/delete/action.py
plugins/rest/komand_rest/actions/delete/schema.py
plugins/rest/komand_rest/actions/get/action.py
plugins/rest/komand_rest/actions/get/schema.py
plugins/rest/komand_rest/actions/patch/action.py
plugins/rest/komand_rest/actions/patch/schema.py
plugins/rest/komand_rest/actions/post/action.py
plugins/rest/komand_rest/actions/post/schema.py
plugins/rest/komand_rest/actions/put/action.py
plugins/rest/komand_rest/actions/put/schema.py
plugins/rest/komand_rest/util/util.py
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py
plugins/rest/unit_test/test_patch.py

- Changed input `body_as_an_array` (Array of objects) input to `body_any` (string) across all actions.
- Renamed `body` input to `body_object`.
- General refactoring in all actions and `util.py`.
- Major version increase due to backwards incompatibility.  …

[PLGN-137] HTTP Requests - Handle string inputs for body

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/asset_search/action.py
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/asset_search/schema.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py
plugins/rapid7_insightvm_cloud/unit_test/test_asset_search.py

- Add new filter fields to asset search action 
- Refactor asset search action …

[PLGN-143] InsightVM Cloud - Asset Search action

---

plugins/rest/.CHECKSUM
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/komand_rest/actions/delete/action.py
plugins/rest/komand_rest/actions/delete/schema.py
plugins/rest/komand_rest/actions/get/action.py
plugins/rest/komand_rest/actions/get/schema.py
plugins/rest/komand_rest/actions/patch/action.py
plugins/rest/komand_rest/actions/patch/schema.py
plugins/rest/komand_rest/actions/post/action.py
plugins/rest/komand_rest/actions/post/schema.py
plugins/rest/komand_rest/actions/put/action.py
plugins/rest/komand_rest/actions/put/schema.py
plugins/rest/komand_rest/util/util.py
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py
plugins/rest/unit_test/test_patch.py

* Initial commit
* Update help md
* Updated unit tests & names in spec
* Update help md violation
* Update examples
- …

[PLGN-137] HTTP Requests - Handle string inputs for body (#1654)

---

plugins/cisco_umbrella_reporting/.CHECKSUM
plugins/cisco_umbrella_reporting/bin/icon_cisco_umbrella_reporting
plugins/cisco_umbrella_reporting/help.md
plugins/cisco_umbrella_reporting/plugin.spec.yaml
plugins/cisco_umbrella_reporting/requirements.txt
plugins/cisco_umbrella_reporting/setup.py
plugins/cisco_umbrella_reporting/unit_test/mock.py
plugins/cisco_umbrella_reporting/unit_test/responses/get_domain_visits.json.resp
plugins/cisco_umbrella_reporting/unit_test/test_get_domain_visits.py

* Updated docs with links
* Updated version
* Unit test framework
* Unit tests functional
* Black
* Add parameterized to requirements
-
* All actions/triggers shortcut `icon-plugin run -T all --debug --jq` (use …

[PLGN-164] Cisco Umbrella Reporting - Release

---

plugins/cisco_umbrella_destinations/.CHECKSUM
plugins/cisco_umbrella_destinations/bin/icon_cisco_umbrella_destinations
plugins/cisco_umbrella_destinations/help.md
plugins/cisco_umbrella_destinations/plugin.spec.yaml
plugins/cisco_umbrella_destinations/setup.py

- Update help.md to include reference to management of Legacy API Keys for Cisco Umbrella to provide clarity due to use of incorrect type of API Keys
* All actions/triggers shortcut `icon-plugin run -T all …

[PLGN-162] cisco umbrella destinations

---

plugins/samanage/komand_samanage/util/api.py

Noticed during testing of the SSL verify updates that there was an issue with substituting parameters into the curl command.

[PLGN-176] SSL verify fix curl command

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/vuln_search/schema.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py
plugins/rapid7_insightvm_cloud/unit_test/expected_responses/vuln_search.json.resp
plugins/rapid7_insightvm_cloud/unit_test/payloads/vuln_search.json.resp

- Vulnerability Search: fix schema validation problem for exploits field …

[PLGN-181] InsightVM Cloud - change schema validation for exploits field

---

plugins/rapid7_insightvm_cloud/.CHECKSUM
plugins/rapid7_insightvm_cloud/bin/icon_rapid7_insightvm_cloud
plugins/rapid7_insightvm_cloud/help.md
plugins/rapid7_insightvm_cloud/icon_rapid7_insightvm_cloud/actions/vuln_search/schema.py
plugins/rapid7_insightvm_cloud/plugin.spec.yaml
plugins/rapid7_insightvm_cloud/setup.py
plugins/rapid7_insightvm_cloud/unit_test/expected_responses/vuln_search.json.resp
plugins/rapid7_insightvm_cloud/unit_test/payloads/vuln_search.json.resp

- Vulnerability Search: fix schema validation problem for exploits field …

[PLGN-181] InsightVM Cloud 4.0.0  - release

---

plugins/cisco_umbrella_reporting/.CHECKSUM
plugins/cisco_umbrella_reporting/help.md
plugins/cisco_umbrella_reporting/icon_cisco_umbrella_reporting/actions/get_domain_visits/action.py
plugins/cisco_umbrella_reporting/icon_cisco_umbrella_reporting/actions/get_domain_visits/schema.py
plugins/cisco_umbrella_reporting/plugin.spec.yaml

- Refactored the input parameters
* All …

[PLGN-180] Cisco Umbrella Reporting - Refactored the input parameters

---

plugins/zoom/.CHECKSUM

[zoom] remove venv dependencies from checksum

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/setup.py

- Quick Fix: Version update to 6.0.0
* …

[PLGN-194] Version Update

---

plugins/cybereason/.CHECKSUM
plugins/cybereason/help.md
plugins/cybereason/plugin.spec.yaml

- Added example outputs for all outputs to avoid failing faulty validator.
- One of the validators still fail because of an issue with the help_example_validator. There is a jira ticket made to fix this issue here: https://issues.corp.rapid7.com/browse/SOAR-13940 …

Cybereason validator fix

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/quarantine_multiple/action.py
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/quarantine_multiple/schema.py
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/unit_test/parameters/quarantine_multiple_failure.json.resp
plugins/rapid7_insight_agent/unit_test/parameters/quarantine_multiple_success.json.resp
plugins/rapid7_insight_agent/unit_test/responses/quarantine_multiple.resp
plugins/rapid7_insight_agent/unit_test/responses/quarantine_multiple_failure.resp
plugins/rapid7_insight_agent/unit_test/test_quarantine_multiple.py
plugins/rapid7_insight_agent/unit_test/util.py

- Changing the requirements of insight agent to take an array of asset IDs and quarantine directly rather than taking an array of hostnames and then converting to ID
* All actions/triggers shortcut `icon-plugin …

Removed convert hostname to id

---

plugins/cybereason/.CHECKSUM
plugins/cybereason/bin/icon_cybereason
plugins/cybereason/help.md
plugins/cybereason/icon_cybereason/actions/get_sensor/schema.py
plugins/cybereason/plugin.spec.yaml
plugins/cybereason/setup.py

The plugin action get sensor works individually, however the output the api gives does not match the plugin spec yaml file so we cannot pass the output as an input in insight connect.
Validator is failing because the help_output_validator is faulty. there is a ticket made to fix it.
**Files Refactored:**
- Output for plugin in plugin spec file and files effected by regenerating
**Testing**
- Insight Connect Test

Cybereason output fix

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/quarantine_multiple/action.py
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/quarantine_multiple/schema.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/unit_test/parameters/quarantine_multiple_failure.json.resp
plugins/rapid7_insight_agent/unit_test/parameters/quarantine_multiple_success.json.resp

- Add a new boolean output for quarantine multiple to indicate if there have been any unsuccessful operations.
* …

New boolean output to indicate failure

---

plugins/cybereason/help.md

Small cybereason fix

---

plugins/cybereason/.CHECKSUM
plugins/cybereason/bin/icon_cybereason
plugins/cybereason/help.md
plugins/cybereason/icon_cybereason/actions/get_sensor/schema.py
plugins/cybereason/plugin.spec.yaml
plugins/cybereason/setup.py

- Updated Outputs in plugin spec yaml. 
Screenshot of working workflow: …

Cybereason 3.0.0 release

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/help.md
plugins/active_directory_ldap/komand_active_directory_ldap/actions/disable_users/action.py
plugins/active_directory_ldap/komand_active_directory_ldap/actions/disable_users/schema.py
plugins/active_directory_ldap/komand_active_directory_ldap/actions/enable_users/action.py
plugins/active_directory_ldap/komand_active_directory_ldap/actions/enable_users/schema.py
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/setup.py
plugins/active_directory_ldap/unit_test/test_action_disable_users.py
plugins/active_directory_ldap/unit_test/test_action_enable_users.py

- [PLGN-227](https://issues.corp.rapid7.com/browse/PLGN-227)
- Update Enable Users / Disable Users output to include All Operations Successful
* All actions/triggers shortcut `icon-plugin run -T all --debug …

[PLGN-227] Active Directory LDAP

---

plugins/fortinet_fortigate/help.md
plugins/fortinet_fortigate/icon_fortinet_fortigate/actions/check_if_address_in_group/action.py

- Fix bug in Check if Address in Group which found that IPV6 Group did not exist. IPV6 Group is required input but not always necessary to complete action.
* All actions/triggers shortcut `icon-plugin run -T all …

[PLGN-160] Fix bug Check if Address In Group

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/requirements.txt
plugins/python_3_script/setup.py

* Update Pyyaml to version 6.0.0
* Update example input Add links
* test input example
* test input example
* test input example
* Fix json input
- pyyaml currently at 3.12, needs updated to 6.0 to avoid Arbitrary code execution vulnerability …

[SOAR-9864] Python 3 Script (#1743)

---

plugins/sophos_xg_firewall/.CHECKSUM
plugins/sophos_xg_firewall/bin/komand_sophos_xg_firewall
plugins/sophos_xg_firewall/help.md
plugins/sophos_xg_firewall/komand_sophos_xg_firewall/connection/schema.py
plugins/sophos_xg_firewall/plugin.spec.yaml
plugins/sophos_xg_firewall/requirements.txt
plugins/sophos_xg_firewall/setup.py

Update the requests module version to avoid (snyk highlighted) vulnerability in older package.

[SOAR-9695] Sophos XG Firewall update requests package (#1738)

---

plugins/fortinet_fortigate/.CHECKSUM
plugins/fortinet_fortigate/bin/icon_fortinet_fortigate
plugins/fortinet_fortigate/help.md
plugins/fortinet_fortigate/icon_fortinet_fortigate/actions/check_if_address_in_group/action.py
plugins/fortinet_fortigate/icon_fortinet_fortigate/connection/connection.py
plugins/fortinet_fortigate/plugin.spec.yaml
plugins/fortinet_fortigate/setup.py

- Support newest version of Fortinet Fortigate V7
- Fix error relating to Check if Address in Group where action fails if IPV6 Group isn't found
* All actions/triggers shortcut `icon-plugin run -T all --debug …

Fortinet fortigate 6.0.1 release

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/quarantine_multiple/schema.py
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/unit_test/test_quarantine_multiple.py

Restored convert hostnames to ID functionality

---

plugins/zoom/.CHECKSUM
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/connection/connection.py
plugins/zoom/icon_zoom/connection/schema.py
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/icon_zoom/util/api.py
plugins/zoom/icon_zoom/util/event.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_api.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

SOAR-14186,13971: Zoom 4.0.0 Release

---

plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/actions/create_user/action.py
plugins/zoom/icon_zoom/actions/delete_user/action.py
plugins/zoom/icon_zoom/actions/get_user/action.py
plugins/zoom/icon_zoom/connection/connection.py
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/icon_zoom/triggers/user_activity_event/trigger.py
plugins/zoom/icon_zoom/util/api.py
plugins/zoom/icon_zoom/util/util.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/mock.py
plugins/zoom/unit_test/test_api.py
plugins/zoom/unit_test/test_create_user.py
plugins/zoom/unit_test/test_get_user.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

- Moves responsibility of raising authentication-related PluginExceptions to plugin code, outside of the API layer.
- Returns (normalized) Zoom status codes within task state. …

SOAR-14124: Zoom status code in state

---

plugins/recorded_future/.CHECKSUM
plugins/recorded_future/Dockerfile
plugins/recorded_future/bin/komand_recorded_future
plugins/recorded_future/help.md
plugins/recorded_future/plugin.spec.yaml
plugins/recorded_future/requirements.txt
plugins/recorded_future/setup.py

* Update pyyaml to 6.0.0
* Update output examples
* Update output examples
* Update output examples
- Update pyyaml
* …

[SOAR-9685] Recorded Future 6.0.1 Release

---

plugins/grr/.CHECKSUM
plugins/grr/bin/icon_grr
plugins/grr/help.md
plugins/grr/icon_grr/actions/hunting/schema.py
plugins/grr/plugin.spec.yaml
plugins/grr/requirements.txt
plugins/grr/setup.py

* updated requests version
* regen
-
* …

GRR-3.0.0-release

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/create_vulnerability/action.py
plugins/servicenow/icon_servicenow/actions/create_vulnerability/schema.py
plugins/servicenow/icon_servicenow/actions/update_vulnerability/action.py
plugins/servicenow/icon_servicenow/actions/update_vulnerability/schema.py
plugins/servicenow/icon_servicenow/connection/connection.py
plugins/servicenow/icon_servicenow/triggers/vulnerability_updated/schema.py
plugins/servicenow/icon_servicenow/triggers/vulnerability_updated/trigger.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/unit_test/test_create_vulnerability.py
plugins/servicenow/unit_test/test_delete_vulnerability.py
plugins/servicenow/unit_test/test_get_vulnerability.py
plugins/servicenow/unit_test/test_update_vulnerability.py
plugins/servicenow/unit_test/util.py

- Updated the vulnerability source from Application Vulnerability Item to Vulnerability Item …

[PLGN-222] Servicenow - Updated the vulnerability source from Application Vulnerability Item to Vulnerability Item

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/create_vulnerability/action.py
plugins/servicenow/icon_servicenow/actions/create_vulnerability/schema.py
plugins/servicenow/icon_servicenow/actions/update_vulnerability/action.py
plugins/servicenow/icon_servicenow/actions/update_vulnerability/schema.py
plugins/servicenow/icon_servicenow/triggers/vulnerability_updated/schema.py
plugins/servicenow/icon_servicenow/util/constants.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/unit_test/test_create_vulnerability.py
plugins/servicenow/unit_test/test_update_vulnerability.py

- Updated the input fields for `Create Vulnerability` and `Update Vulnerability` …

[PLGN-222] Servicenow - Updated the input fields for `Create Vulnerability` and `Update Vulnerability`

---

plugins/thehive/.CHECKSUM
plugins/thehive/help.md
plugins/thehive/komand_thehive/actions/create_case/schema.py
plugins/thehive/komand_thehive/connection/connection.py
plugins/thehive/komand_thehive/connection/schema.py
plugins/thehive/plugin.spec.yaml

theHive - More testing fixes

---

plugins/komand/.CHECKSUM
plugins/komand/help.md
plugins/komand/plugin.spec.yaml

- Make plugin obsolete as it is no longer supported …

[SOAR-9912] Komand Obsolete

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/quarantine_multiple/action.py
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/quarantine_multiple/schema.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py
plugins/rapid7_insight_agent/unit_test/parameters/quarantine_multiple_failure.json.resp
plugins/rapid7_insight_agent/unit_test/parameters/quarantine_multiple_success.json.resp

- Quarantine Multiple output updated to failed: list, completed: list …

[PLGN-255] Rapid7 Insight Agent - Update output Quarantine Multiple

---

plugins/active_directory_ldap/.CHECKSUM
plugins/active_directory_ldap/bin/komand_active_directory_ldap
plugins/active_directory_ldap/help.md
plugins/active_directory_ldap/komand_active_directory_ldap/actions/disable_users/action.py
plugins/active_directory_ldap/komand_active_directory_ldap/actions/disable_users/schema.py
plugins/active_directory_ldap/komand_active_directory_ldap/actions/enable_users/action.py
plugins/active_directory_ldap/komand_active_directory_ldap/actions/enable_users/schema.py
plugins/active_directory_ldap/komand_active_directory_ldap/util/utils.py
plugins/active_directory_ldap/plugin.spec.yaml
plugins/active_directory_ldap/setup.py
plugins/active_directory_ldap/unit_test/test_action_disable_users.py
plugins/active_directory_ldap/unit_test/test_action_enable_users.py

- Change output of Enable Users and Disable Users to completed: array, failed: array …

[PLGN-256] Active Directory LDAP - Disable/Enable Users output update

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/setup.py
plugins/python_3_script/unit_test/test_run.py
plugins/python_3_script/unit_test/util.py

- Updated the SDK version to include output credential masking …

[PLGN-230] Python 3 Script - Updated the SDK version to include output credential masking

---

plugins/python_3_script/help.md
plugins/python_3_script/requirements.txt

- Updated all dependencies to the newest versions …

[PLGN-230] Python 3 Script - Updated all dependencies to the newest versions

---

plugins/powershell/.CHECKSUM
plugins/powershell/Dockerfile
plugins/powershell/bin/icon_powershell
plugins/powershell/help.md
plugins/powershell/plugin.spec.yaml
plugins/powershell/requirements.txt
plugins/powershell/setup.py
plugins/powershell/unit_test/test_execute_script.py
plugins/powershell/unit_test/test_powershell_string.py

- Update the SDK to include output masking …

[PLGN-230] Powershell - Update the SDK to include output masking

---

plugins/python_3_script/.CHECKSUM
plugins/python_3_script/Dockerfile
plugins/python_3_script/bin/icon_python_3_script
plugins/python_3_script/help.md
plugins/python_3_script/plugin.spec.yaml
plugins/python_3_script/requirements.txt
plugins/python_3_script/setup.py
plugins/python_3_script/unit_test/test_run.py
plugins/python_3_script/unit_test/util.py

- Updated the SDK version to include output masking …

Release Python 3 Script - Updated the SDK version

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/bin/icon_rapid7_insight_agent
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/quarantine_multiple/action.py
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/actions/quarantine_multiple/schema.py
plugins/rapid7_insight_agent/icon_rapid7_insight_agent/util/graphql_api/api_connection.py
plugins/rapid7_insight_agent/plugin.spec.yaml
plugins/rapid7_insight_agent/setup.py
plugins/rapid7_insight_agent/unit_test/parameters/quarantine_multiple_failure.json.resp
plugins/rapid7_insight_agent/unit_test/parameters/quarantine_multiple_success.json.resp
plugins/rapid7_insight_agent/unit_test/responses/unquarantine.resp
plugins/rapid7_insight_agent/unit_test/responses/unquarantine_check.resp
plugins/rapid7_insight_agent/unit_test/test_check_agent_status.py
plugins/rapid7_insight_agent/unit_test/test_get_agent_details.py
plugins/rapid7_insight_agent/unit_test/test_quarantine.py
plugins/rapid7_insight_agent/unit_test/test_quarantine_multiple.py
plugins/rapid7_insight_agent/unit_test/util.py

- Update Quarantine Multiple output completed: list[str], failed: list[{hostname: str, error: str}]
- Update error handling Quarantine Multiple on hostname not found
- Improve efficiency of quarantine multiple
* …

[PLGN-255] Insight Agent 2.0.0 Release

---

plugins/okta/.CHECKSUM
plugins/okta/plugin.spec.yaml

- Add the connection_version field in the plugin spec …

[MC-1452] Add connection_version field in plugin spec in Okta plugin

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_add_group_member.py
plugins/mimecast/unit_test/test_create_blocked_sender_policy.py
plugins/mimecast/unit_test/test_create_managed_url.py
plugins/mimecast/unit_test/test_decode_url.py
plugins/mimecast/unit_test/test_delete_blocked_sender_policy.py
plugins/mimecast/unit_test/test_delete_group_member.py
plugins/mimecast/unit_test/test_delete_managed_url.py
plugins/mimecast/unit_test/test_find_groups.py
plugins/mimecast/unit_test/test_get_audit_event.py
plugins/mimecast/unit_test/test_get_managed_url.py
plugins/mimecast/unit_test/test_get_ttp_url_logs.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/test_permit_or_block_sender.py
plugins/mimecast/unit_test/test_response_status_code_handling.py
plugins/mimecast/unit_test/test_track_messages.py

- add connection version 
* All …

[PLGN-272] Mimecast add connection version

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_add_group_member.py
plugins/mimecast/unit_test/test_create_blocked_sender_policy.py
plugins/mimecast/unit_test/test_create_managed_url.py
plugins/mimecast/unit_test/test_decode_url.py
plugins/mimecast/unit_test/test_delete_blocked_sender_policy.py
plugins/mimecast/unit_test/test_delete_group_member.py
plugins/mimecast/unit_test/test_delete_managed_url.py
plugins/mimecast/unit_test/test_find_groups.py
plugins/mimecast/unit_test/test_get_audit_event.py
plugins/mimecast/unit_test/test_get_managed_url.py
plugins/mimecast/unit_test/test_get_ttp_url_logs.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/test_permit_or_block_sender.py
plugins/mimecast/unit_test/test_response_status_code_handling.py
plugins/mimecast/unit_test/test_track_messages.py

- add connection version
* All …

[PLGN-272] Mimecast 5.2.1 - release

---

plugins/servicenow/.CHECKSUM
plugins/servicenow/help.md
plugins/servicenow/icon_servicenow/actions/create_vulnerability/action.py
plugins/servicenow/icon_servicenow/actions/create_vulnerability/schema.py
plugins/servicenow/icon_servicenow/actions/update_vulnerability/schema.py
plugins/servicenow/icon_servicenow/connection/connection.py
plugins/servicenow/icon_servicenow/triggers/vulnerability_updated/schema.py
plugins/servicenow/icon_servicenow/triggers/vulnerability_updated/trigger.py
plugins/servicenow/plugin.spec.yaml
plugins/servicenow/requirements.txt
plugins/servicenow/unit_test/test_create_change_request.py
plugins/servicenow/unit_test/test_create_vulnerability.py
plugins/servicenow/unit_test/test_delete_vulnerability.py
plugins/servicenow/unit_test/test_get_attachments_for_an_incident.py
plugins/servicenow/unit_test/test_get_incident_attachment.py
plugins/servicenow/unit_test/test_get_vulnerability.py
plugins/servicenow/unit_test/test_update_vulnerability.py
plugins/servicenow/unit_test/util.py

- Updated the trigger `Vulnerability Updated` …

[PLGN-222] Servicenow - Updated the trigger `Vulnerability Updated`

---

plugins/rest/.CHECKSUM
plugins/rest/bin/komand_rest
plugins/rest/help.md
plugins/rest/komand_rest/actions/delete/schema.py
plugins/rest/komand_rest/actions/get/schema.py
plugins/rest/komand_rest/actions/patch/schema.py
plugins/rest/komand_rest/actions/post/schema.py
plugins/rest/komand_rest/actions/put/schema.py
plugins/rest/komand_rest/util/util.py
plugins/rest/plugin.spec.yaml
plugins/rest/setup.py
plugins/rest/unit_test/expected/put.json.resp
plugins/rest/unit_test/expected/put_error.json.resp
plugins/rest/unit_test/payloads/connection_test.json.resp
plugins/rest/unit_test/payloads/put_404_false_failure.json.resp
plugins/rest/unit_test/payloads/put_error.json.resp
plugins/rest/unit_test/payloads/put_json_body.json.resp
plugins/rest/unit_test/payloads/put_json_body_x_www_form_urlencoded.json.resp
plugins/rest/unit_test/payloads/put_json_empty_body.json.resp
plugins/rest/unit_test/payloads/put_json_non_latin.json.resp
plugins/rest/unit_test/payloads/put_plain_text.json.resp
plugins/rest/unit_test/test_put.py
plugins/rest/unit_test/util.py

* Update encoding handling
* Update encoding handling
* Update Put Unit Tests
* Reformat and regen
* Validate help.md
* Update help.md examples | Add test file
* Update descriptions / Unit Tests
* Update plugins/rest/unit_test/test_put.py
* New line
---------
- …

[PLGN-265] Rest 6.0.1 Release

---

plugins/mimecast/komand_mimecast/util/api.py

- solve problems with status code for Task Get SIEM logs …

[PLGN-281] Mimecast status code issues v2 

---

plugins/vmray/komand_vmray/actions/get_analysis/action.py
plugins/vmray/komand_vmray/actions/get_samples/action.py

- Update output to handle single value returns …

Vmray list fix

---

plugins/vmray/.CHECKSUM
plugins/vmray/komand_vmray/actions/get_analysis/schema.py
plugins/vmray/plugin.spec.yaml

VMRay add title

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/komand_mimecast/util/constants.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/util.py

- Solve problems with status code for Task Get SIEM logs
- Request limit set to 1 minute in Monitor SIEM Logs
* Single …

Mimecast 5.2.2 release

---

plugins/armorblox/.CHECKSUM
plugins/armorblox/help.md
plugins/armorblox/icon_armorblox/actions/get_remediation_action/action.py
plugins/armorblox/icon_armorblox/connection/connection.py
plugins/armorblox/icon_armorblox/triggers/get_incidents/schema.py
plugins/armorblox/icon_armorblox/triggers/get_incidents/trigger.py
plugins/armorblox/icon_armorblox/util/api.py
plugins/armorblox/requirements.txt
plugins/armorblox/unit_test/test_connection.py
plugins/armorblox/unit_test/test_get_remediation_action.py
plugins/armorblox/unit_test/util.py

- run black linter
- fix other validators
- fix unit tests …

[SOAR-14684] Armorblox run black linter

---

plugins/zoom/.CHECKSUM
plugins/zoom/help.md
plugins/zoom/icon_zoom/actions/get_user/schema.py

Zoom Validator Fixes

---

.github/pull_request_template.md

- Update this template so its worded towards new tooling. …

[SOAR-14742] Update PR template

---

.github/pull_request_template.md

* Updated to use new tooling
* Updated sdk version number in doc
- …

[SOAR-14742] Update PR template (#1868)

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/util.py

- handle rate limiting
- update SDK …

[PLGN-294] Mimecast rate limiting, update SDK

---

plugins/zoom/Dockerfile
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/tasks/monitor_sign_in_out_activity/task.py
plugins/zoom/icon_zoom/util/api.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py
plugins/zoom/unit_test/test_monitor_sign_in_out_activity.py

- Updates Zoom to support external pagination (has_more_pages)
- Updates Zoom task to return status code in output as well as error messaging
- Bump SDK to v5
- Update error messaging when incorrect scope is in place
All tests working locally

SOAR-14707 - Add External Pagination Support for Zoom Task

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/scan/action.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/scan/schema.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py
plugins/rapid7_insightvm/unit_test/expected/scan_with_override_blackout_as_false.json.exp
plugins/rapid7_insightvm/unit_test/expected/scan_with_override_blackout_as_true.json.exp
plugins/rapid7_insightvm/unit_test/inputs/scan_invalid_site_id.json.inp
plugins/rapid7_insightvm/unit_test/inputs/scan_with_host.json.inp
plugins/rapid7_insightvm/unit_test/inputs/scan_with_override_blackout_as_false.json.inp
plugins/rapid7_insightvm/unit_test/inputs/scan_with_override_blackout_as_true.json.inp
plugins/rapid7_insightvm/unit_test/payloads/scan1.json.resp
plugins/rapid7_insightvm/unit_test/payloads/scan2.json.resp
plugins/rapid7_insightvm/unit_test/payloads/scan_invalid_site_id.json.resp
plugins/rapid7_insightvm/unit_test/test_scan.py
plugins/rapid7_insightvm/unit_test/util.py

- Add new input in Scan action
- Refactor code in Scan action
- Add unit tests for Scan action
* Single …

[MC-1498] Add new input in Scan action in InsightVM plugin

---

plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/unit_test/expected/monitor_logs.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_2.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_3.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_bad_request.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_server_error.json.exp
plugins/duo_admin/unit_test/inputs/monitor_logs_next_page.json.inp
plugins/duo_admin/unit_test/inputs/monitor_logs_with_state.json.inp
plugins/duo_admin/unit_test/test_monitor_logs.py

- update SDK to the latest
* All …

[PLGN-307] Duo Admin SDK update

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py
plugins/proofpoint_tap/unit_test/expected/monitor_events_bad_request.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_duplicated_event.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_first_run.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_next_page.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_server_error.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_subsequent_run.json.exp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_bad_request.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_duplicated_event.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_last_page.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_next_page.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_server_error.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_subsequent_run.json.inp
plugins/proofpoint_tap/unit_test/test_monitor_events.py
plugins/proofpoint_tap/unit_test/test_parse_tap_alert.py

- update to the latest plugin SDK  …

[PLGN-310] Proofpoint update SDK

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/komand_okta/tasks/monitor_logs/task.py
plugins/okta/komand_okta/util/exceptions.py
plugins/okta/setup.py
plugins/okta/unit_test/expected/get_logs.json.exp
plugins/okta/unit_test/expected/get_logs_next_page.json.exp
plugins/okta/unit_test/inputs/monitor_logs_next_page.json.inp
plugins/okta/unit_test/test_monitor_logs.py

- Update to latest plugin SDK
* …

[PLGN-308] Okta sdk update, handling exceptions 

---

plugins/rapid7_insightvm/.CHECKSUM
plugins/rapid7_insightvm/bin/komand_rapid7_insightvm
plugins/rapid7_insightvm/help.md
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/scan/action.py
plugins/rapid7_insightvm/komand_rapid7_insightvm/actions/scan/schema.py
plugins/rapid7_insightvm/plugin.spec.yaml
plugins/rapid7_insightvm/setup.py
plugins/rapid7_insightvm/unit_test/expected/scan_with_override_blackout_as_false.json.exp
plugins/rapid7_insightvm/unit_test/expected/scan_with_override_blackout_as_true.json.exp
plugins/rapid7_insightvm/unit_test/inputs/scan_invalid_site_id.json.inp
plugins/rapid7_insightvm/unit_test/inputs/scan_with_host.json.inp
plugins/rapid7_insightvm/unit_test/inputs/scan_with_override_blackout_as_false.json.inp
plugins/rapid7_insightvm/unit_test/inputs/scan_with_override_blackout_as_true.json.inp
plugins/rapid7_insightvm/unit_test/payloads/scan1.json.resp
plugins/rapid7_insightvm/unit_test/payloads/scan2.json.resp
plugins/rapid7_insightvm/unit_test/payloads/scan_invalid_site_id.json.resp
plugins/rapid7_insightvm/unit_test/test_scan.py
plugins/rapid7_insightvm/unit_test/util.py

Release PR for InsightVM scan action plugin update

[MC-1498] Add new input in Scan action in InsightVM plugin (#1884)

---

plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/komand_duo_admin/util/api.py
plugins/duo_admin/setup.py

- remove rate limiting from task  …

[PLGN-307] Duo Admin remove rate limiting 

---

plugins/mimecast/komand_mimecast/util/api.py

- Handle error message for secret key …

[PLGN-294] Mimecast - Handle error message for secret key

---

plugins/mimecast/.CHECKSUM
plugins/mimecast/bin/komand_mimecast
plugins/mimecast/help.md
plugins/mimecast/komand_mimecast/tasks/monitor_siem_logs/task.py
plugins/mimecast/komand_mimecast/util/api.py
plugins/mimecast/plugin.spec.yaml
plugins/mimecast/setup.py
plugins/mimecast/unit_test/test_monitor_siem_logs.py
plugins/mimecast/unit_test/test_response_status_code_handling.py
plugins/mimecast/unit_test/util.py

- update to the latest sdk 
- handled all exceptions
- improve cause messages
- handled rate limiting error messaging 
- move status code from state to output 
* All actions/triggers shortcut `insight-plugin …

Mimecast 5.3.0 release

---

plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/komand_salesforce/util/api.py

- disable rate limiting for the Monitor Users task …

[MC-1441] Disable rate limiting for Monitor Users task in Salesforce plugin

---

plugins/duo_admin/bin/komand_duo_admin
plugins/duo_admin/help.md
plugins/duo_admin/komand_duo_admin/tasks/monitor_logs/task.py
plugins/duo_admin/komand_duo_admin/util/api.py
plugins/duo_admin/plugin.spec.yaml
plugins/duo_admin/setup.py
plugins/duo_admin/unit_test/expected/monitor_logs.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_2.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_3.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_bad_request.json.exp
plugins/duo_admin/unit_test/expected/monitor_logs_server_error.json.exp
plugins/duo_admin/unit_test/inputs/monitor_logs_next_page.json.inp
plugins/duo_admin/unit_test/inputs/monitor_logs_with_state.json.inp
plugins/duo_admin/unit_test/test_monitor_logs.py

- update to the latest sdk
- handled all exceptions
- improve cause messages
- handled rate limiting error messaging
- move status code from state to output
* All actions/triggers shortcut `insight-plugin run …

Duo 4.1.0 release

---

plugins/proofpoint_tap/.CHECKSUM
plugins/proofpoint_tap/bin/komand_proofpoint_tap
plugins/proofpoint_tap/help.md
plugins/proofpoint_tap/komand_proofpoint_tap/tasks/monitor_events/task.py
plugins/proofpoint_tap/komand_proofpoint_tap/util/api.py
plugins/proofpoint_tap/plugin.spec.yaml
plugins/proofpoint_tap/setup.py
plugins/proofpoint_tap/unit_test/expected/monitor_events_bad_request.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_duplicated_event.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_first_run.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_next_page.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_server_error.json.exp
plugins/proofpoint_tap/unit_test/expected/monitor_events_subsequent_run.json.exp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_bad_request.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_duplicated_event.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_last_page.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_next_page.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_server_error.json.inp
plugins/proofpoint_tap/unit_test/inputs/monitor_events_subsequent_run.json.inp
plugins/proofpoint_tap/unit_test/test_fetch_forensics.py
plugins/proofpoint_tap/unit_test/test_monitor_events.py
plugins/proofpoint_tap/unit_test/test_parse_tap_alert.py

- update to the latest sdk
- handled all exceptions
- improve cause messages
- handled rate limiting error messaging
- move status code from state to output
* All actions/triggers shortcut `insight-plugin run …

Proofpoint 4.1.0 release

---

.github/workflows/unit_test_coverage.yml

* test github action
* accidently delted github action before
* add datetime unit tests
* working version
* added artifact plus refactor
* added comments
* remove datetime unit tests
* add back zoom init
* run on workflow_dispatch
* cd into unit tests directly to avoid import errros
* fixed path issue
* g
* fix path
* removed testing commands
* version bumps and comment
* added secrets
* rename_coverage
* rename
-
If you are an InsightConnect customer or have access to an InsightConnect …

[SOAR-14686] - Gather test coverage for plugins (#1913)

---

.github/workflows/unit_test_coverage.yml

- Fix to GHA issue where plugins with no unit tests returned 100% coverage.
https://issues.corp.rapid7.com/browse/SOAR-14686
* All actions/triggers shortcut `insight-plugin run -T all --debug --jq` (use PR …

[SOAR]-14686 - Gather test coverage for plugins Update

---

.github/workflows/unit_test_coverage.yml

* fixed 100 percent issue
* removed workingDir var
- Fix Issue where plugins with no unit tests returned 100% coverage.
**Before**:
**After**:
```
active_directory_ldap, 96%
advanced_regex, 0%
microsoft_atp_safe_links, 0%
base64, 83%
string, 76%
ssh, 0%
basename, 0%
subnet, 99%
microsoft_teams, 72%
csv, 99%
python_3_script, 83%
type_converter, 82%
rapid7_insight_agent, 89%
datetime, 0%
rapid7_insightidr, 89%
whois, 46%
dig, 
rapid7_insightvm, 74%
rapid7_intsights, 98%
extractit, 97%
rapid7_vulndb, 96%
rapid7_insightappsec, 81%
hashit, 0%
rest, 93%
``` …

[SOAR]-14686 - Gather test coverage for plugins Update (#1936)

---

plugins/rapid7_insight_agent/.CHECKSUM
plugins/rapid7_insight_agent/Dockerfile
plugins/rapid7_insight_agent/help.md
plugins/rapid7_insight_agent/plugin.spec.yaml

[PLGN-219] insight agent sdk 5

---

plugins/azure_ad_admin/.CHECKSUM
plugins/azure_ad_admin/bin/icon_azure_ad_admin
plugins/azure_ad_admin/help.md
plugins/azure_ad_admin/plugin.spec.yaml
plugins/azure_ad_admin/setup.py

- Update requirements in help.md …

[MC-1503] Update requirements in help.md in Azure AD Admin plugin

---

plugins/azure_ad_admin/.CHECKSUM
plugins/azure_ad_admin/bin/icon_azure_ad_admin
plugins/azure_ad_admin/help.md
plugins/azure_ad_admin/plugin.spec.yaml
plugins/azure_ad_admin/setup.py

Update to help.md file for required setup.

[PLGN-357] Update requirements in help.md in Azure AD Admin plugin

---

.github/workflows/unit_test_coverage.yml

- export python path of unit test folder but run coverage from main plugin folder to avoid import errors.
Ticket:
https://issues.corp.rapid7.com/browse/SOAR-15420 …

Coverage unittest fix2

---

.github/workflows/unit_test_coverage.yml

* fixed import issues and add init files
* remove plugin changes | removed TODO from comment in gha
- Changed Python Path for unit test to avoid import errors
* All actions/triggers shortcut `insight-plugin …

Coverage GHA Release - InsightConnect

---

plugins/freshservice/.CHECKSUM
plugins/freshservice/help.md
plugins/freshservice/icon_freshservice/actions/list_all_agents/schema.py
plugins/freshservice/plugin.spec.yaml

- `List All Agents`: Fixed issue related to departament IDs field …

[PLGN-291] Freshservice - `List All Agents`: Fixed issue related to departament IDs field

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py

[PLGN-380] Salesforce plugin - add extra logs

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py

Salesforce plugin 2.0.1 - release

---

plugins/zoom/.CHECKSUM
plugins/zoom/bin/icon_zoom
plugins/zoom/plugin.spec.yaml

after testing the changes made in https://github.com/rapid7/insightconnect-plugins/pull/1982, it was found that there was a place in the code where the version was not bumped correctly, this version number has been bumped as well as adding the connection_version:4 to the plugin spec file and updating the checksums to match 
running the docker container the new version is correctly printed out  …

SOAR-15612-Making version is bumped in all places after changes

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/util.py

- query improvment
- handle exception related with grant type …

plgn-380 query improvment, handle exception grant type

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/tasks/monitor_users/task.py
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py
plugins/salesforce/unit_test/util.py

- query improvement
- handle exception related to grant type …

Salesforce plugin 2.0.2 - release

---

plugins/salesforce/.CHECKSUM
plugins/salesforce/bin/komand_salesforce
plugins/salesforce/help.md
plugins/salesforce/komand_salesforce/util/api.py
plugins/salesforce/plugin.spec.yaml
plugins/salesforce/setup.py

- Implemented token auto-refresh on expiration for continuous sessions …

[PLGN-380] Salesforce - auto-refresh token on expiration 

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/get_a_saved_query/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/endpoints.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/mock.py

to update the endpoint that get_a_saved_query reaches out to as its currently not working, after updates made in  https://issues.corp.rapid7.com/browse/SOAR-10641  made a change for the endpoint to get all queryies was updated but not the endpoint to get a single query
- to now pass in a region instead of base url to the endpoints class to allow for the new endpoint to be correctly built
- bump to the version number
-  some extra examples were added to the spec and help.md file to ensure that the validator passes
testing running the docker image and making the call via postman to ensure the call can complete
running of integration tests (note the failing one is due to an invalid …

PLGN-392-update the endpoint that get_a_saved_query reaches out to

---

plugins/rapid7_insightidr/requirements.txt

- after noticed in the following pr https://github.com/rapid7/insightconnect-plugins/pull/1890 it looks like there was a vulnerability in aiohttp==3.7.4.post0 and there is none in aiohttp==3.8.5 so bumping up the version to avoid this vulnerability
testing on local machine in a docker container, this package only seems to be used with the `AdvancedQueryOnLogSet` action  the action still works as well as the integration tests are passing
```
Feature: Rapid7 insightIdr - Advanced Query on Log Set Validation # features/advanced_query_on_log_set.feature:1
Scenario: Validate Rapid7 InsightIDR Advanced Query on Log Set for valid input  # features/advanced_query_on_log_set.feature:3 …
```

PLGN-392-bump requiremnets for aiohttp in rapid7_insightidr

---

plugins/zoom/.CHECKSUM
plugins/zoom/bin/icon_zoom
plugins/zoom/help.md
plugins/zoom/icon_zoom/actions/get_user/schema.py
plugins/zoom/plugin.spec.yaml
plugins/zoom/setup.py

release pr for the following:
when the insight-plugin refresh command was last run for the zoom integration it had introduced a regression into the code. this error was caused by the required fields in the icon_zoom/actions/get_user/schema.py for the user object to be nested incorrectly into the object and require itself as required field. I have manually updated this issue as well as manually calculated and updated the hash values for this file
Following PRs included:
- #1982 
- #1983 
testing was carried on the staging server as part of #1982  
Review our documentation on [generating](https://docs.rapid7.com/insightconnect/unit-test-generation) and [writing](https://docs.rapid7.com/insightconnect/unit-test-pr …

Zoom 4.1.2 release

---

plugins/rapid7_insightidr/.CHECKSUM
plugins/rapid7_insightidr/bin/komand_rapid7_insightidr
plugins/rapid7_insightidr/help.md
plugins/rapid7_insightidr/komand_rapid7_insightidr/actions/get_a_saved_query/action.py
plugins/rapid7_insightidr/komand_rapid7_insightidr/util/endpoints.py
plugins/rapid7_insightidr/plugin.spec.yaml
plugins/rapid7_insightidr/requirements.txt
plugins/rapid7_insightidr/setup.py
plugins/rapid7_insightidr/unit_test/mock.py

release pr for the following change:
to update the endpoint that get_a_saved_query reaches out to as its currently not working, after updates made in https://issues.corp.rapid7.com/browse/SOAR-10641 made a change for the endpoint to get all queries was updated but not the endpoint to get a single query
Following PRs included:
- #1986 
testing was carried out using staging workflows as part of #1986  …

Rapid7 Insightidr 5.0.1 release

---

plugins/okta/.CHECKSUM
plugins/okta/bin/komand_okta
plugins/okta/help.md
plugins/okta/plugin.spec.yaml
plugins/okta/setup.py

Small change after https://github.com/rapid7/insightconnect-plugins/pull/2000 to bump the version number correctly.

[Plgn-411] Bump version of plugin correctly
